import type { NextConfig } from "next";

/** Image hosts: CDN wildcards cover most med spa site assets; named domains for top providers. */
const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "**.cdninstagram.com" },
      { protocol: "https", hostname: "**.squarespace.com" },
      { protocol: "http", hostname: "**.squarespace.com" },
      { protocol: "https", hostname: "**.squarespace-cdn.com" },
      { protocol: "https", hostname: "**.wp.com" },
      { protocol: "https", hostname: "**.wixstatic.com" },
      { protocol: "https", hostname: "**.cloudfront.net" },
      { protocol: "https", hostname: "**.cdn-website.com" },
      { protocol: "https", hostname: "**.websitepro-cdn.com" },
      { protocol: "https", hostname: "**.website-files.com" },
      { protocol: "https", hostname: "cdn.prod.website-files.com" },
      { protocol: "https", hostname: "**.amazonaws.com" },
      { protocol: "https", hostname: "**.shopify.com" },
      { protocol: "https", hostname: "assets.cdn.filesafe.space" },
      { protocol: "https", hostname: "img1.wsimg.com" },
      { protocol: "https", hostname: "datocms-assets.com" },
      { protocol: "https", hostname: "content.app-sources.com" },
      { protocol: "https", hostname: "i0.wp.com" },
      { protocol: "https", hostname: "olympiaaesthetics.com" },
      { protocol: "https", hostname: "livingyoungcenter.com" },
      { protocol: "https", hostname: "lueuraesthetics360.com" },
      { protocol: "https", hostname: "liviamedspa.com" },
      { protocol: "https", hostname: "arvivaesthetics.com" },
      { protocol: "https", hostname: "4everyoungantiaging.com" },
      { protocol: "https", hostname: "www.miamiskinspa.com" },
      { protocol: "https", hostname: "www.thesurfacelevel.com" },
      { protocol: "https", hostname: "brickellcosmetic.com" },
      { protocol: "https", hostname: "novaskinmedspa.com" },
      { protocol: "https", hostname: "cdn.aventuramedspa.com" },
      { protocol: "https", hostname: "www.fbmedspa.com" },
      { protocol: "https", hostname: "www.glowstpete.com" },
      { protocol: "https", hostname: "www.elan-aesthetics.com" },
      { protocol: "https", hostname: "visojuve.com" },
      { protocol: "https", hostname: "viomedspa.com" },
      { protocol: "https", hostname: "elase.com" },
      { protocol: "https", hostname: "viivwellnesshaus.com" },
      { protocol: "https", hostname: "mwellcenter.com" },
      { protocol: "https", hostname: "stpetewellnessmedspa.com" },
      { protocol: "https", hostname: "redbamboomedispa.com" },
      { protocol: "https", hostname: "bevelup.com" },
      { protocol: "https", hostname: "hermannaesthetics.com" },
      { protocol: "https", hostname: "aventuramedspa.com" },
      { protocol: "https", hostname: "contourclinique.com" },
      { protocol: "https", hostname: "inertiatampa.com" },
      { protocol: "https", hostname: "perfectlybarelaser.com" },
      { protocol: "https", hostname: "padgettmedical.com" },
      { protocol: "https", hostname: "phdermatology.com" },
      { protocol: "https", hostname: "luxinjectables.com" },
      { protocol: "https", hostname: "venusmedspa.com" },
    ],
  },
};

export default nextConfig;
