import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "**.cdninstagram.com" },
      { protocol: "https", hostname: "**.squarespace.com" },
      { protocol: "http", hostname: "**.squarespace.com" },
      { protocol: "https", hostname: "**.squarespace-cdn.com" },
      { protocol: "https", hostname: "**.wp.com" },
      { protocol: "https", hostname: "**.wixstatic.com" },
      { protocol: "https", hostname: "**.cloudfront.net" },
      { protocol: "https", hostname: "**.cdn-website.com" },
      { protocol: "https", hostname: "**.websitepro-cdn.com" },
      { protocol: "https", hostname: "**.website-files.com" },
      { protocol: "https", hostname: "**.amazonaws.com" },
      { protocol: "https", hostname: "**.shopify.com" },
      { protocol: "https", hostname: "plenitudemedspa.com" },
      { protocol: "https", hostname: "www.miamiskinspa.com" },
      { protocol: "https", hostname: "www.thesurfacelevel.com" },
      { protocol: "https", hostname: "brickellcosmetic.com" },
      { protocol: "https", hostname: "skinneymedspa.com" },
      { protocol: "https", hostname: "novaskinmedspa.com" },
      { protocol: "https", hostname: "cdn.aventuramedspa.com" },
      { protocol: "https", hostname: "www.fbmedspa.com" },
      { protocol: "https", hostname: "assets.cdn.filesafe.space" },
      { protocol: "https", hostname: "img1.wsimg.com" },
      { protocol: "https", hostname: "olympiaaesthetics.com" },
      { protocol: "https", hostname: "livingyoungcenter.com" },
      { protocol: "https", hostname: "moraitisplasticsurgery.com" },
      { protocol: "https", hostname: "lueuraesthetics360.com" },
      { protocol: "https", hostname: "medspabellaclearwater.com" },
      { protocol: "https", hostname: "aurivitamedspa.com" },
      { protocol: "https", hostname: "tonicityhealth.com" },
      { protocol: "https", hostname: "drksmedspa.com" },
      { protocol: "https", hostname: "dunedinwellspa.com" },
      { protocol: "https", hostname: "iconciergemedspa.com" },
      { protocol: "https", hostname: "liviamedspa.com" },
      { protocol: "https", hostname: "www.tremedspa.com" },
      { protocol: "https", hostname: "taowellnessmedspa.com" },
      { protocol: "https", hostname: "erasablemedspa.com" },
      { protocol: "https", hostname: "arvivaesthetics.com" },
      { protocol: "https", hostname: "4everyoungantiaging.com" },
      { protocol: "https", hostname: "windermeremedicalspa.com" },
      { protocol: "https", hostname: "rejuvinorlando.com" },
      { protocol: "https", hostname: "www.thenurmedspa.com" },
      { protocol: "https", hostname: "luxemedspaaesthetics.com" },
      { protocol: "https", hostname: "jaxaestheticscenter.com" },
      { protocol: "https", hostname: "focusaestheticsjax.com" },
      { protocol: "https", hostname: "conciergecosmeticsandaesthetics.com" },
      { protocol: "https", hostname: "www.macflorida.com" },
      { protocol: "https", hostname: "cmamedicine.com" },
      { protocol: "https", hostname: "insideoutmedspa.com" },
    ],
  },
};

export default nextConfig;
