import { productImages } from "./product-images";
import type { Product } from "./types";

const AMAZON = "Amazon Associates";

function amazon(asin: string): string {
  return `https://www.amazon.com/dp/${asin}`;
}

/** Luxury derm-brand products with Amazon affiliate links (tag applied at runtime). */
export const amazonAffiliateProducts: Product[] = [
  {
    slug: "eltamd-uv-clear",
    name: "UV Clear Broad-Spectrum SPF 46",
    brand: "EltaMD",
    category: "SPF",
    trustScore: 92,
    productTags: ["fragrance-free", "paraben-free", "dermatologist-tested"],
    description:
      "Oil-free sunscreen loved by med spas for post-procedure protection. Niacinamide helps calm sensitive skin.",
    rating: 4.5,
    reviewCount: 69094,
    image: productImages["eltamd-uv-clear"],
    ingredients: ["Zinc Oxide", "Niacinamide", "Hyaluronic Acid"],
    origin: "US",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B002MSN3QQ"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "eltamd-uv-daily-hydration-tinted",
    name: "UV Daily Hydration+ Tinted Face Sunscreen",
    brand: "EltaMD",
    category: "SPF",
    trustScore: 91,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Tinted daily SPF with transparent zinc oxide and hyaluronic acid. Hydrates while protecting dry, combination, and normal skin.",
    rating: 4.7,
    reviewCount: 218,
    image: productImages["eltamd-uv-daily-hydration-tinted"],
    ingredients: ["Zinc Oxide", "Hyaluronic Acid", "Iron Oxides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0GXLFWPSS"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-anthelios",
    name: "Anthelios Melt-In Milk Sunscreen SPF 60",
    brand: "La Roche-Posay",
    category: "SPF",
    trustScore: 93,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Fast-absorbing body and face sunscreen milk favored by derms for high UVA/UVB protection without a greasy finish.",
    rating: 4.8,
    reviewCount: 12400,
    image: productImages["la-roche-posay-anthelios"],
    ingredients: ["Avobenzone", "Homosalate", "Octisalate", "Niacinamide"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07HFHWNPH"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-anthelios-niacinamide",
    name: "Anthelios UV Protection + Niacinamide",
    brand: "La Roche-Posay",
    category: "SPF",
    trustScore: 92,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Lightweight, fast-absorbing sunscreen with niacinamide to help even tone while protecting against daily UV exposure.",
    rating: 4.7,
    reviewCount: 890,
    image: productImages["la-roche-posay-anthelios-niacinamide"],
    ingredients: ["Niacinamide", "Avobenzone", "Glycerin"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FJYPJLYC"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-toleriane-hydrating",
    name: "Toleriane Double Repair Face Moisturizer",
    brand: "La Roche-Posay",
    category: "Moisturizer",
    trustScore: 90,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Hyaluronic-acid moisturizer with ceramides and niacinamide for sensitive skin barrier repair — a med spa aftercare staple.",
    rating: 4.7,
    reviewCount: 15600,
    image: productImages["la-roche-posay-toleriane-hydrating"],
    ingredients: ["Ceramide NP", "Niacinamide", "Hyaluronic Acid"],
    origin: "FR",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B075VX4QVM"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-pure-vitamin-c",
    name: "Pure Vitamin C Face Serum",
    brand: "La Roche-Posay",
    category: "Serum",
    trustScore: 88,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "10% pure vitamin C serum for radiance and fine-line smoothing — pharmacy-grade brightening at a accessible price point.",
    rating: 4.6,
    reviewCount: 4200,
    image: productImages["la-roche-posay-pure-vitamin-c"],
    ingredients: ["Ascorbic Acid", "Salicylic Acid", "Neurosensine"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07PM79MSC"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinceuticals-discoloration-defense",
    name: "Discoloration Defense Serum",
    brand: "SkinCeuticals",
    category: "Serum",
    trustScore: 89,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Multi-pathway brightening serum with tranexamic acid and niacinamide — used post-laser to target stubborn hyperpigmentation.",
    rating: 4.6,
    reviewCount: 640,
    image: productImages["skinceuticals-discoloration-defense"],
    ingredients: ["Tranexamic Acid", "Niacinamide", "Kojic Acid", "Hepes"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B005IXGA6C"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-eryfotona-actinica",
    name: "Eryfotona Actinica Daily Mineral SPF 50+",
    brand: "ISDIN",
    category: "SPF",
    trustScore: 94,
    productTags: ["dermatologist-tested", "reef-safe"],
    description:
      "Lightweight mineral sunscreen with DNA repair enzymes — dermatologist-recommended for daily photoprotection and actinic care.",
    rating: 4.7,
    reviewCount: 2100,
    image: productImages["isdin-eryfotona-actinica"],
    ingredients: ["Zinc Oxide", "DNA Repairsomes", "Vitamin E"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0DWXXJ9Q1"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-eryfotona-ageless",
    name: "Eryfotona Ageless Tinted Mineral SPF 50+",
    brand: "ISDIN",
    category: "SPF",
    trustScore: 93,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Tinted mineral SPF with peptides and DNA Repairsomes for mature skin — anti-aging sun protection in one step.",
    rating: 4.6,
    reviewCount: 980,
    image: productImages["isdin-eryfotona-ageless"],
    ingredients: ["Zinc Oxide", "Peptides", "DNA Repairsomes"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0CV85FYPJ"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-mineral-powder-spf",
    name: "Isdinceutics Mineral Brush On Powder SPF 50",
    brand: "ISDIN",
    category: "SPF",
    trustScore: 90,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "On-the-go mineral powder SPF for touch-ups over makeup — pollution protection for urban lifestyles.",
    rating: 4.5,
    reviewCount: 760,
    image: productImages["isdin-mineral-powder-spf"],
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Mica"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07R2CSP6P"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-essential-cleansing",
    name: "Isdinceutics Essential Cleansing Oil",
    brand: "ISDIN",
    category: "Cleanser",
    trustScore: 88,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Oil cleanser with natural-origin oils to dissolve sunscreen and makeup without stripping — ideal pre-facial prep.",
    rating: 4.6,
    reviewCount: 540,
    image: productImages["isdin-essential-cleansing"],
    ingredients: ["Sunflower Oil", "Squalane", "Grape Seed Oil"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B09JQ325R5"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-micellar-solution",
    name: "Micellar Solution 400ml",
    brand: "ISDIN",
    category: "Cleanser",
    trustScore: 87,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Gentle micellar water for sensitive skin — removes impurities without rinsing, common in European derm protocols.",
    rating: 4.5,
    reviewCount: 1100,
    image: productImages["isdin-micellar-solution"],
    ingredients: ["Micelles", "Glycerin", "Panthenol"],
    origin: "EU",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B0771RDWY3"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-hydratint-spf",
    name: "HydraTint Pro Mineral Broad Spectrum SPF 36",
    brand: "ALASTIN Skincare",
    category: "SPF",
    trustScore: 93,
    productTags: ["fragrance-free", "dermatologist-tested", "reef-safe"],
    description:
      "Tinted mineral moisturizer with SPF — post-procedure friendly and popular after laser and microneedling series.",
    rating: 4.7,
    reviewCount: 890,
    image: productImages["alastin-hydratint-spf"],
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Peptides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0GK86VSC7"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-c-radical-serum",
    name: "C-RADICAL Defense Antioxidant Serum",
    brand: "ALASTIN Skincare",
    category: "Serum",
    trustScore: 91,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Illuminating antioxidant serum designed to defend against environmental stressors and support post-treatment recovery.",
    rating: 4.6,
    reviewCount: 320,
    image: productImages["alastin-c-radical-serum"],
    ingredients: ["Vitamin C", "Antioxidants", "Peptides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G42XZCXP"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-restorative-skin-complex",
    name: "Restorative Skin Complex with TriHex Technology",
    brand: "ALASTIN Skincare",
    category: "Serum",
    trustScore: 95,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Flagship anti-aging treatment with TriHex Technology — clears damaged collagen and supports new, healthy extracellular matrix.",
    rating: 4.8,
    reviewCount: 1100,
    image: productImages["alastin-restorative-skin-complex"],
    ingredients: ["TriHex Peptides", "Niacinamide", "Antioxidants"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G42F3X4T"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-gentle-cleanser",
    name: "Gentle Cleanser",
    brand: "ALASTIN Skincare",
    category: "Cleanser",
    trustScore: 89,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Non-foaming gentle cleanser safe for post-procedure skin — removes debris without disrupting the skin barrier.",
    rating: 4.6,
    reviewCount: 480,
    image: productImages["alastin-gentle-cleanser"],
    ingredients: ["Glycerin", "Panthenol", "Aloe Vera"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0B6717SNJ"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-regenerating-skin-nectar",
    name: "Regenerating Skin Nectar with TriHex Technology",
    brand: "ALASTIN Skincare",
    category: "Serum",
    trustScore: 94,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Concentrated treatment nectar for compromised or healing skin — frequently recommended after ablative and non-ablative lasers.",
    rating: 4.8,
    reviewCount: 720,
    image: productImages["alastin-regenerating-skin-nectar"],
    ingredients: ["TriHex Peptides", "Hyaluronic Acid", "Antioxidants"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07L9F177Y"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-tns-advanced-serum",
    name: "TNS Advanced+ Serum",
    brand: "SkinMedica",
    category: "Serum",
    trustScore: 92,
    productTags: ["dermatologist-tested"],
    description:
      "Growth-factor serum for comprehensive anti-aging — gold standard at physician-led med spas nationwide.",
    rating: 4.7,
    reviewCount: 2400,
    image: productImages["skinmedica-tns-advanced-serum"],
    ingredients: ["Growth Factors", "Peptides", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FT8V14XK"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-collagen-support",
    name: "Collagen Support Complex",
    brand: "SkinMedica",
    category: "Serum",
    trustScore: 90,
    productTags: ["dermatologist-tested"],
    description:
      "Age-defying collagen support with hyaluronic acid — complements in-office injectables and laser resurfacing plans.",
    rating: 4.6,
    reviewCount: 380,
    image: productImages["skinmedica-collagen-support"],
    ingredients: ["Collagen Amino Acids", "Hyaluronic Acid", "Peptides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FTK9M5FS"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-dermal-repair-cream",
    name: "Dermal Repair Cream",
    brand: "SkinMedica",
    category: "Moisturizer",
    trustScore: 91,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Rich repair cream with vitamins C and E for dry, compromised, or post-procedure skin needing intensive moisture.",
    rating: 4.7,
    reviewCount: 920,
    image: productImages["skinmedica-dermal-repair-cream"],
    ingredients: ["Vitamin C", "Vitamin E", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G1B26P5D"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-instant-bright-eye",
    name: "Instant Bright Eye Cream",
    brand: "SkinMedica",
    category: "Eye Care",
    trustScore: 88,
    productTags: ["dermatologist-tested"],
    description:
      "Brightening eye cream targeting dark circles and puffiness — pairs well with tear-trough and under-eye treatment plans.",
    rating: 4.5,
    reviewCount: 560,
    image: productImages["skinmedica-instant-bright-eye"],
    ingredients: ["Peptides", "Niacinamide", "Caffeine"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G19JCFTF"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-neck-correct-cream",
    name: "Neck Correct Cream",
    brand: "SkinMedica",
    category: "Moisturizer",
    trustScore: 89,
    productTags: ["dermatologist-tested"],
    description:
      "Targeted neck and décolleté cream for crepiness and laxity — extends facial treatment results below the jawline.",
    rating: 4.6,
    reviewCount: 410,
    image: productImages["skinmedica-neck-correct-cream"],
    ingredients: ["Peptides", "Antioxidants", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G19BSX47"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-essential-spf-tinted",
    name: "Essential Defense Mineral Shield SPF 35 (Tinted)",
    brand: "SkinMedica",
    category: "SPF",
    trustScore: 90,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Lightweight tinted mineral sunscreen for combination skin — daily photoprotection after in-office treatments.",
    rating: 4.6,
    reviewCount: 680,
    image: productImages["skinmedica-essential-spf-tinted"],
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Green Tea Extract"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G19LB6NL"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-essential-spf-clear",
    name: "Essential Defense Mineral Shield SPF 35 (Clear)",
    brand: "SkinMedica",
    category: "SPF",
    trustScore: 90,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Clear-finish mineral SPF for all skin tones — non-comedogenic daily protection recommended by aesthetic physicians.",
    rating: 4.6,
    reviewCount: 620,
    image: productImages["skinmedica-essential-spf-clear"],
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Green Tea Extract"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FT8VW19Z"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-cleansing",
    name: "Cleansing Complex",
    brand: "iS Clinical",
    category: "Cleanser",
    trustScore: 90,
    productTags: ["paraben-free", "dermatologist-tested"],
    description:
      "3-in-1 gentle deep-pore cleanser, face wash, and makeup remover. Resurfaces without stripping — a staple in luxury facial protocols.",
    rating: 4.7,
    reviewCount: 3200,
    image: productImages["is-clinical-cleansing"],
    ingredients: ["Willow Bark", "Sugar Cane Extract", "Chamomile"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0026TOCK2"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-pro-heal-serum",
    name: "Pro-Heal Serum Advance+",
    brand: "iS Clinical",
    category: "Serum",
    trustScore: 92,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Antioxidant-rich serum with vitamins C, E, and A for redness, inflammation, and post-procedure recovery — ideal after laser and IPL.",
    rating: 4.6,
    reviewCount: 480,
    image: productImages["is-clinical-pro-heal-serum"],
    ingredients: ["Vitamin C", "Vitamin E", "Vitamin A", "Olive Leaf Extract"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0093NPNO8"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-genexc-eye-gel",
    name: "GeneXC Firming Eye Gel",
    brand: "iS Clinical",
    category: "Eye Care",
    trustScore: 89,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Anti-aging brightening under-eye gel that reduces puffiness while hydrating and firming delicate skin.",
    rating: 4.5,
    reviewCount: 210,
    image: productImages["is-clinical-genexc-eye-gel"],
    ingredients: ["Peptides", "Hyaluronic Acid", "Antioxidants"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0GXDS8YKR"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-youth-eye-complex",
    name: "Youth Eye Complex",
    brand: "iS Clinical",
    category: "Eye Care",
    trustScore: 90,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Anti-aging brightening under-eye cream that reduces puffiness with hydrating, firming peptides for mature skin.",
    rating: 4.6,
    reviewCount: 340,
    image: productImages["is-clinical-youth-eye-complex"],
    ingredients: ["Copper Tripeptide", "Hyaluronic Acid", "Vitamin C"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B00ANEUTKY"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-lip-polish",
    name: "Lip Polish",
    brand: "iS Clinical",
    category: "Treatment",
    trustScore: 87,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Gentle lip scrub and exfoliator that polishes dry, chapped lips — common prep step before injectable lip treatments.",
    rating: 4.5,
    reviewCount: 520,
    image: productImages["is-clinical-lip-polish"],
    ingredients: ["Sugar Crystals", "Vitamin E", "Coconut Oil"],
    origin: "US",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B07RQ6RXKY"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-liprotect-spf35",
    name: "Liprotect SPF 35",
    brand: "iS Clinical",
    category: "SPF",
    trustScore: 88,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Hydrating SPF lip balm with vitamin E and coconut oil — protects and heals dry, chapped lips after procedures.",
    rating: 4.6,
    reviewCount: 380,
    image: productImages["is-clinical-liprotect-spf35"],
    ingredients: ["Vitamin E", "Coconut Oil", "Zinc Oxide"],
    origin: "US",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B08WR8QWFF"),
    affiliatePartner: AMAZON,
  },
];
