import { productImages } from "./product-images";
import type { Product } from "./types";

const AMAZON = "Amazon Associates";
const IMG_SPF = "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop";
const IMG_SERUM = "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=600&fit=crop";
const IMG_MOIST = "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop";
const IMG_CLEANSE = "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop";

function amazon(asin: string): string {
  return `https://www.amazon.com/dp/${asin}`;
}

/** Luxury derm-brand products with Amazon affiliate links (tag applied at runtime). */
export const amazonAffiliateProducts: Product[] = [
  {
    slug: "eltamd-uv-clear",
    name: "UV Clear Broad-Spectrum SPF 46",
    brand: "EltaMD",
    category: "SPF",
    trustScore: 92,
    productTags: ["fragrance-free", "paraben-free", "dermatologist-tested"],
    description:
      "Oil-free sunscreen loved by med spas for post-procedure protection. Niacinamide helps calm sensitive skin.",
    rating: 4.5,
    reviewCount: 69094,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Niacinamide", "Hyaluronic Acid"],
    origin: "US",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B002MSN3QQ"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "eltamd-uv-daily-hydration-tinted",
    name: "UV Daily Hydration+ Tinted Face Sunscreen",
    brand: "EltaMD",
    category: "SPF",
    trustScore: 91,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Tinted daily SPF with transparent zinc oxide and hyaluronic acid. Hydrates while protecting dry, combination, and normal skin.",
    rating: 4.7,
    reviewCount: 218,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Hyaluronic Acid", "Iron Oxides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0GXLFWPSS"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-anthelios",
    name: "Anthelios Melt-In Milk Sunscreen SPF 60",
    brand: "La Roche-Posay",
    category: "SPF",
    trustScore: 93,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Fast-absorbing body and face sunscreen milk favored by derms for high UVA/UVB protection without a greasy finish.",
    rating: 4.8,
    reviewCount: 12400,
    image: IMG_SPF,
    ingredients: ["Avobenzone", "Homosalate", "Octisalate", "Niacinamide"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07HFHWNPH"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-anthelios-niacinamide",
    name: "Anthelios UV Protection + Niacinamide",
    brand: "La Roche-Posay",
    category: "SPF",
    trustScore: 92,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Lightweight, fast-absorbing sunscreen with niacinamide to help even tone while protecting against daily UV exposure.",
    rating: 4.7,
    reviewCount: 890,
    image: IMG_SPF,
    ingredients: ["Niacinamide", "Avobenzone", "Glycerin"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FJYPJLYC"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-toleriane-hydrating",
    name: "Toleriane Double Repair UV SPF 30 Moisturizer",
    brand: "La Roche-Posay",
    category: "Moisturizer",
    trustScore: 90,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Daily face moisturizer with broad-spectrum SPF 30, ceramides, niacinamide, and glycerin — barrier repair and sun protection in one step for sensitive skin.",
    rating: 4.7,
    reviewCount: 15600,
    image: productImages["la-roche-posay-toleriane-hydrating"]!,
    ingredients: ["Ceramide NP", "Niacinamide", "Glycerin", "SPF 30"],
    origin: "FR",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B01NCWV3KM"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-pure-vitamin-c",
    name: "Pure Vitamin C Face Serum",
    brand: "La Roche-Posay",
    category: "Serum",
    trustScore: 88,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "10% pure vitamin C serum for radiance and fine-line smoothing — pharmacy-grade brightening at a accessible price point.",
    rating: 4.6,
    reviewCount: 4200,
    image: IMG_SERUM,
    ingredients: ["Ascorbic Acid", "Salicylic Acid", "Neurosensine"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07PM79MSC"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinceuticals-discoloration-defense",
    name: "Discoloration Defense Serum",
    brand: "SkinCeuticals",
    category: "Serum",
    trustScore: 89,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Multi-pathway brightening serum with tranexamic acid and niacinamide — used post-laser to target stubborn hyperpigmentation.",
    rating: 4.6,
    reviewCount: 640,
    image: IMG_SERUM,
    ingredients: ["Tranexamic Acid", "Niacinamide", "Kojic Acid", "Hepes"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B005IXGA6C"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-eryfotona-actinica",
    name: "Eryfotona Actinica Daily Mineral SPF 50+",
    brand: "ISDIN",
    category: "SPF",
    trustScore: 94,
    productTags: ["dermatologist-tested", "reef-safe"],
    description:
      "Lightweight mineral sunscreen with DNA repair enzymes — dermatologist-recommended for daily photoprotection and actinic care.",
    rating: 4.7,
    reviewCount: 2100,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "DNA Repairsomes", "Vitamin E"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0DWXXJ9Q1"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-eryfotona-ageless",
    name: "Eryfotona Ageless Tinted Mineral SPF 50+",
    brand: "ISDIN",
    category: "SPF",
    trustScore: 93,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Tinted mineral SPF with peptides and DNA Repairsomes for mature skin — anti-aging sun protection in one step.",
    rating: 4.6,
    reviewCount: 980,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Peptides", "DNA Repairsomes"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0CV85FYPJ"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-mineral-powder-spf",
    name: "Isdinceutics Mineral Brush On Powder SPF 50",
    brand: "ISDIN",
    category: "SPF",
    trustScore: 90,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "On-the-go mineral powder SPF for touch-ups over makeup — pollution protection for urban lifestyles.",
    rating: 4.5,
    reviewCount: 760,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Mica"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07R2CSP6P"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-essential-cleansing",
    name: "Isdinceutics Essential Cleansing Oil",
    brand: "ISDIN",
    category: "Cleanser",
    trustScore: 88,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Oil cleanser with natural-origin oils to dissolve sunscreen and makeup without stripping — ideal pre-facial prep.",
    rating: 4.6,
    reviewCount: 540,
    image: IMG_CLEANSE,
    ingredients: ["Sunflower Oil", "Squalane", "Grape Seed Oil"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B09JQ325R5"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-micellar-solution",
    name: "Micellar Solution 400ml",
    brand: "ISDIN",
    category: "Cleanser",
    trustScore: 87,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Gentle micellar water for sensitive skin — removes impurities without rinsing, common in European derm protocols.",
    rating: 4.5,
    reviewCount: 1100,
    image: IMG_CLEANSE,
    ingredients: ["Micelles", "Glycerin", "Panthenol"],
    origin: "EU",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B0771RDWY3"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-hydratint-spf",
    name: "HydraTint Pro Mineral Broad Spectrum SPF 36",
    brand: "ALASTIN Skincare",
    category: "SPF",
    trustScore: 93,
    productTags: ["fragrance-free", "dermatologist-tested", "reef-safe"],
    description:
      "Tinted mineral moisturizer with SPF — post-procedure friendly and popular after laser and microneedling series.",
    rating: 4.7,
    reviewCount: 890,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Peptides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0GK86VSC7"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-c-radical-serum",
    name: "C-RADICAL Defense Antioxidant Serum",
    brand: "ALASTIN Skincare",
    category: "Serum",
    trustScore: 91,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Illuminating antioxidant serum designed to defend against environmental stressors and support post-treatment recovery.",
    rating: 4.6,
    reviewCount: 320,
    image: IMG_SERUM,
    ingredients: ["Vitamin C", "Antioxidants", "Peptides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G42XZCXP"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-restorative-skin-complex",
    name: "Restorative Skin Complex with TriHex Technology",
    brand: "ALASTIN Skincare",
    category: "Serum",
    trustScore: 95,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Flagship anti-aging treatment with TriHex Technology — clears damaged collagen and supports new, healthy extracellular matrix.",
    rating: 4.8,
    reviewCount: 1100,
    image: IMG_SERUM,
    ingredients: ["TriHex Peptides", "Niacinamide", "Antioxidants"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G42F3X4T"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-gentle-cleanser",
    name: "Gentle Cleanser",
    brand: "ALASTIN Skincare",
    category: "Cleanser",
    trustScore: 89,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Non-foaming gentle cleanser safe for post-procedure skin — removes debris without disrupting the skin barrier.",
    rating: 4.6,
    reviewCount: 480,
    image: IMG_CLEANSE,
    ingredients: ["Glycerin", "Panthenol", "Aloe Vera"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0B6717SNJ"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-regenerating-skin-nectar",
    name: "Regenerating Skin Nectar with TriHex Technology",
    brand: "ALASTIN Skincare",
    category: "Serum",
    trustScore: 94,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Concentrated treatment nectar for compromised or healing skin — frequently recommended after ablative and non-ablative lasers.",
    rating: 4.8,
    reviewCount: 720,
    image: IMG_SERUM,
    ingredients: ["TriHex Peptides", "Hyaluronic Acid", "Antioxidants"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07L9F177Y"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-tns-advanced-serum",
    name: "TNS Advanced+ Serum",
    brand: "SkinMedica",
    category: "Serum",
    trustScore: 92,
    productTags: ["dermatologist-tested"],
    description:
      "Growth-factor serum for comprehensive anti-aging — gold standard at physician-led med spas nationwide.",
    rating: 4.7,
    reviewCount: 2400,
    image: IMG_SERUM,
    ingredients: ["Growth Factors", "Peptides", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FT8V14XK"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-ha5",
    name: "HA5 Hydra Collagen Hydrator",
    brand: "SkinMedica",
    category: "Moisturizer",
    trustScore: 87,
    productTags: ["dermatologist-tested"],
    description:
      "Next-generation HA⁵ complex with vegan collagen and five forms of hyaluronic acid for deep hydration and visibly plumper skin after injectables and lasers.",
    rating: 4.8,
    reviewCount: 700,
    image: productImages["skinmedica-ha5"]!,
    ingredients: ["Hyaluronic Acid", "Vegan Collagen", "Peptides", "Vitis Flower Stem Extract"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FTK9M5FS"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-dermal-repair-cream",
    name: "Dermal Repair Cream",
    brand: "SkinMedica",
    category: "Moisturizer",
    trustScore: 91,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Rich repair cream with vitamins C and E for dry, compromised, or post-procedure skin needing intensive moisture.",
    rating: 4.7,
    reviewCount: 920,
    image: IMG_MOIST,
    ingredients: ["Vitamin C", "Vitamin E", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G1B26P5D"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-instant-bright-eye",
    name: "Instant Bright Eye Cream",
    brand: "SkinMedica",
    category: "Eye Care",
    trustScore: 88,
    productTags: ["dermatologist-tested"],
    description:
      "Brightening eye cream targeting dark circles and puffiness — pairs well with tear-trough and under-eye treatment plans.",
    rating: 4.5,
    reviewCount: 560,
    image: IMG_MOIST,
    ingredients: ["Peptides", "Niacinamide", "Caffeine"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G19JCFTF"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-neck-correct-cream",
    name: "Neck Correct Cream",
    brand: "SkinMedica",
    category: "Moisturizer",
    trustScore: 89,
    productTags: ["dermatologist-tested"],
    description:
      "Targeted neck and décolleté cream for crepiness and laxity — extends facial treatment results below the jawline.",
    rating: 4.6,
    reviewCount: 410,
    image: IMG_MOIST,
    ingredients: ["Peptides", "Antioxidants", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G19BSX47"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-essential-spf-tinted",
    name: "Essential Defense Mineral Shield SPF 35 (Tinted)",
    brand: "SkinMedica",
    category: "SPF",
    trustScore: 90,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Lightweight tinted mineral sunscreen for combination skin — daily photoprotection after in-office treatments.",
    rating: 4.6,
    reviewCount: 680,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Green Tea Extract"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G19LB6NL"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-essential-spf-clear",
    name: "Essential Defense Mineral Shield SPF 35 (Clear)",
    brand: "SkinMedica",
    category: "SPF",
    trustScore: 90,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Clear-finish mineral SPF for all skin tones — non-comedogenic daily protection recommended by aesthetic physicians.",
    rating: 4.6,
    reviewCount: 620,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Green Tea Extract"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FT8VW19Z"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-cleansing",
    name: "Cleansing Complex",
    brand: "iS Clinical",
    category: "Cleanser",
    trustScore: 90,
    productTags: ["paraben-free", "dermatologist-tested"],
    description:
      "3-in-1 gentle deep-pore cleanser, face wash, and makeup remover. Resurfaces without stripping — a staple in luxury facial protocols.",
    rating: 4.7,
    reviewCount: 3200,
    image: IMG_CLEANSE,
    ingredients: ["Willow Bark", "Sugar Cane Extract", "Chamomile"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0026TOCK2"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-pro-heal-serum",
    name: "Pro-Heal Serum Advance+",
    brand: "iS Clinical",
    category: "Serum",
    trustScore: 92,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Antioxidant-rich serum with vitamins C, E, and A for redness, inflammation, and post-procedure recovery — ideal after laser and IPL.",
    rating: 4.6,
    reviewCount: 480,
    image: IMG_SERUM,
    ingredients: ["Vitamin C", "Vitamin E", "Vitamin A", "Olive Leaf Extract"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0093NPNO8"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-genexc-eye-gel",
    name: "GeneXC Firming Eye Gel",
    brand: "iS Clinical",
    category: "Eye Care",
    trustScore: 89,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Anti-aging brightening under-eye gel that reduces puffiness while hydrating and firming delicate skin.",
    rating: 4.5,
    reviewCount: 210,
    image: IMG_MOIST,
    ingredients: ["Peptides", "Hyaluronic Acid", "Antioxidants"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0GXDS8YKR"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-youth-eye-complex",
    name: "Youth Eye Complex",
    brand: "iS Clinical",
    category: "Eye Care",
    trustScore: 90,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Anti-aging brightening under-eye cream that reduces puffiness with hydrating, firming peptides for mature skin.",
    rating: 4.6,
    reviewCount: 340,
    image: IMG_MOIST,
    ingredients: ["Copper Tripeptide", "Hyaluronic Acid", "Vitamin C"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B00ANEUTKY"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-lip-polish",
    name: "Lip Polish",
    brand: "iS Clinical",
    category: "Treatment",
    trustScore: 87,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Gentle lip scrub and exfoliator that polishes dry, chapped lips — common prep step before injectable lip treatments.",
    rating: 4.5,
    reviewCount: 520,
    image: IMG_CLEANSE,
    ingredients: ["Sugar Crystals", "Vitamin E", "Coconut Oil"],
    origin: "US",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B07RQ6RXKY"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "is-clinical-liprotect-spf35",
    name: "Liprotect SPF 35",
    brand: "iS Clinical",
    category: "SPF",
    trustScore: 88,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Hydrating SPF lip balm with vitamin E and coconut oil — protects and heals dry, chapped lips after procedures.",
    rating: 4.6,
    reviewCount: 380,
    image: IMG_SPF,
    ingredients: ["Vitamin E", "Coconut Oil", "Zinc Oxide"],
    origin: "US",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B08WR8QWFF"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "caudalie-vinoperfect-serum",
    name: "Vinoperfect Brightening Dark Spot Serum",
    brand: "Caudalie",
    category: "Serum",
    trustScore: 91,
    productTags: ["cruelty-free", "dermatologist-tested", "fragrance-free"],
    description:
      "Viniferine-powered brightening serum — a vitamin C alternative clinically shown to visibly even dark spots and dullness for a radiant complexion.",
    rating: 4.6,
    reviewCount: 3200,
    image: productImages["caudalie-vinoperfect-serum"]!,
    ingredients: ["Viniferine", "Niacinamide", "Olive Squalane", "Glycerin"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0CX5B5VTX"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "caudalie-resveratrol-lift-essentials",
    name: "Resveratrol-Lift Essentials Gift Set",
    brand: "Caudalie",
    category: "Treatment",
    trustScore: 89,
    productTags: ["cruelty-free", "dermatologist-tested"],
    description:
      "Anti-aging lift-and-firm set with full-size Resveratrol-Lift serum plus travel-size day and night creams — a complete firming protocol from Bordeaux vine science.",
    rating: 4.7,
    reviewCount: 890,
    image: productImages["caudalie-resveratrol-lift-essentials"]!,
    ingredients: ["Resveratrol", "Hyaluronic Acid", "Peptides", "Grape Seed Oil"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B08H1SZCV2"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "caudalie-beauty-elixir",
    name: "Beauty Elixir Face Mist",
    brand: "Caudalie",
    category: "Treatment",
    trustScore: 88,
    productTags: ["cruelty-free", "dermatologist-tested"],
    description:
      "Iconic grape-infused facial mist that tightens pores, boosts radiance, and sets makeup — a spa-room staple for instant glow and refresh.",
    rating: 4.5,
    reviewCount: 12400,
    image: productImages["caudalie-beauty-elixir"]!,
    ingredients: ["Grape Extract", "Rosemary", "Benzoin", "Bitter Orange Blossom"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0006BDMIU"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "caudalie-vinoperfect-moisturizer",
    name: "Vinoperfect Instant Brightening Moisturizer with Niacinamide",
    brand: "Caudalie",
    category: "Moisturizer",
    trustScore: 90,
    productTags: ["cruelty-free", "dermatologist-tested", "fragrance-free"],
    description:
      "Refillable brightening moisturizer with niacinamide and viniferine to hydrate while targeting dark spots — pairs with the Vinoperfect serum in med spa brightening protocols.",
    rating: 4.6,
    reviewCount: 2100,
    image: productImages["caudalie-vinoperfect-moisturizer"]!,
    ingredients: ["Niacinamide", "Viniferine", "Hyaluronic Acid", "Shea Butter"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B085K7TTYY"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-lipikar-ap-max",
    name: "Lipikar AP+MAX Triple Repair Moisturizing Cream",
    brand: "La Roche-Posay",
    category: "Moisturizer",
    trustScore: 91,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Intensive triple-repair body and face cream with shea butter and niacinamide for very dry, rough, and sensitive skin — dermatologist-trusted barrier recovery.",
    rating: 4.7,
    reviewCount: 9800,
    image: productImages["la-roche-posay-lipikar-ap-max"]!,
    ingredients: ["Shea Butter", "Niacinamide", "Ceramides", "Glycerin"],
    origin: "FR",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B003QXZWYW"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-hyalu-b5-suractivated",
    name: "Hyalu B5 Suractivated Anti-Aging Face & Neck Cream",
    brand: "La Roche-Posay",
    category: "Moisturizer",
    trustScore: 90,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Firming anti-wrinkle moisturizer with three types of hyaluronic acid for 72-hour hydration — strengthens skin on face and neck for visible wrinkle reduction.",
    rating: 4.6,
    reviewCount: 420,
    image: productImages["la-roche-posay-hyalu-b5-suractivated"]!,
    ingredients: ["Hyaluronic Acid", "Vitamin B5", "Madecassoside", "Glycerin"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0F226HQVW"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "revision-nectifirm",
    name: "Nectifirm Neck Cream (1.7 oz)",
    brand: "Revision Skincare",
    category: "Treatment",
    trustScore: 93,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Clinically proven neck and jawline cream that firms, lifts, and smooths while brightening skin and reducing early signs of aging — the signature Revision treatment for the décolletage.",
    rating: 4.6,
    reviewCount: 1800,
    image: productImages["revision-nectifirm"]!,
    ingredients: ["Peptides", "Antioxidants", "Plant Extracts", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0010P6D28"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "revision-dermprotect",
    name: "DermProtect Barrier Defense Intensive Moisturizer",
    brand: "Revision Skincare",
    category: "Moisturizer",
    trustScore: 91,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Intensive barrier-repair moisturizer for dry, sensitive, and mature skin — hydrates and strengthens the skin barrier after lasers, peels, and retinol protocols.",
    rating: 4.7,
    reviewCount: 240,
    image: productImages["revision-dermprotect"]!,
    ingredients: ["Ceramides", "Hyaluronic Acid", "Niacinamide", "Glycerin"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0DT4YDM9Y"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "revision-retinol",
    name: "Retinol Complete 1.0",
    brand: "Revision Skincare",
    category: "Retinol",
    trustScore: 90,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Clinical-strength retinol serum that brightens, smooths texture, and reduces fine lines while boosting hydration to combat retinol dryness — a med spa anti-aging staple.",
    rating: 4.7,
    reviewCount: 890,
    image: productImages["revision-retinol"]!,
    ingredients: ["Retinol", "Bakuchiol", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B071WXKTJ8"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "revision-firming-night",
    name: "Firming Night Treatment",
    brand: "Revision Skincare",
    category: "Moisturizer",
    trustScore: 89,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Hydrating anti-aging night cream with peptides for dry and sensitive skin — supports overnight firming and recovery between in-office treatment sessions.",
    rating: 4.6,
    reviewCount: 520,
    image: productImages["revision-firming-night"]!,
    ingredients: ["Peptides", "Hyaluronic Acid", "Antioxidants", "Glycerin"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B003TY8UEC"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "revision-replenisher",
    name: "YouthFull Lip Replenisher",
    brand: "Revision Skincare",
    category: "Lip Care",
    trustScore: 88,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Moisturizing lip plumper with hyaluronic acid that volumizes, plumps, and smooths lips — ideal for post-filler lip care and daily anti-aging.",
    rating: 4.5,
    reviewCount: 310,
    image: productImages["revision-replenisher"]!,
    ingredients: ["Hyaluronic Acid", "Peptides", "Antioxidants"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0DFMZV6WG"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "revision-night-cream",
    name: "D·E·J Night Face Cream",
    brand: "Revision Skincare",
    category: "Moisturizer",
    trustScore: 92,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Antioxidant-rich anti-aging night moisturizer with retinol and bakuchiol — supports collagen and elastin renewal while you sleep.",
    rating: 4.7,
    reviewCount: 640,
    image: productImages["revision-night-cream"]!,
    ingredients: ["Retinol", "Bakuchiol", "Antioxidants", "Peptides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07HS34913"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "revision-intellishade-truphysical",
    name: "Intellishade TruPhysical SPF 45",
    brand: "Revision Skincare",
    category: "SPF",
    trustScore: 94,
    productTags: ["dermatologist-tested", "fragrance-free", "reef-safe"],
    description:
      "100% mineral tinted sunscreen with SPF 45, vitamin C, and anti-aging moisturizers — daily photoprotection for sensitive skin after procedures.",
    rating: 4.6,
    reviewCount: 1100,
    image: productImages["revision-intellishade-truphysical"]!,
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Vitamin C", "Peptides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07B4DZGRR"),
    affiliatePartner: AMAZON,
  },

  // ---------------------------------------------------------------------------
  // International skincare — Korean (KR), French (FR), Italian (IT).
  // Real Amazon ASINs. Price omitted (Amazon fluctuates); rating/reviewCount 0
  // (not fabricated) so no rating shows and no aggregateRating schema is emitted.
  // ---------------------------------------------------------------------------

  // --- Korean (K-beauty) ---
  {
    slug: "beauty-of-joseon-relief-sun",
    name: "Relief Sun: Rice + Probiotics SPF50+",
    brand: "Beauty of Joseon",
    category: "SPF",
    trustScore: 90,
    productTags: ["cruelty-free"],
    description:
      "Cult Korean chemical sunscreen with a lightweight, no-white-cast finish. Rice extract and probiotics soothe and hydrate under makeup.",
    rating: 0,
    reviewCount: 0,
    image: IMG_SPF,
    ingredients: ["Rice Extract", "Probiotics", "Niacinamide"],
    origin: "KR",
    recommended: true,
    affiliateUrl: amazon("B0C2BYV394"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "cosrx-advanced-snail-96-mucin-essence",
    name: "Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    category: "Serum",
    trustScore: 90,
    productTags: ["cruelty-free"],
    description:
      "96% snail secretion filtrate essence that plumps, repairs, and hydrates dull, tired skin. A K-beauty holy grail for barrier support.",
    rating: 0,
    reviewCount: 0,
    image: IMG_SERUM,
    ingredients: ["Snail Secretion Filtrate", "Hyaluronic Acid", "Panthenol"],
    origin: "KR",
    recommended: true,
    affiliateUrl: amazon("B00PBX3L7K"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "anua-heartleaf-77-soothing-toner",
    name: "Heartleaf 77% Soothing Toner",
    brand: "Anua",
    category: "Toner",
    trustScore: 89,
    productTags: ["vegan", "cruelty-free", "fragrance-free"],
    description:
      "Lightweight calming toner with 77% heartleaf extract to soothe redness, balance pH, and prep skin for the rest of your routine.",
    rating: 0,
    reviewCount: 0,
    image: IMG_SERUM,
    ingredients: ["Houttuynia Cordata (Heartleaf) Extract", "Hyaluronic Acid", "Panthenol"],
    origin: "KR",
    affiliateUrl: amazon("B08CMS8P67"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "laneige-water-sleeping-mask",
    name: "Water Sleeping Mask",
    brand: "Laneige",
    category: "Sleeping Mask",
    trustScore: 88,
    productTags: [],
    description:
      "Overnight gel mask that seals in deep hydration while you sleep for brighter, plumper skin by morning.",
    rating: 0,
    reviewCount: 0,
    image: IMG_MOIST,
    ingredients: ["Squalane", "Hyaluronic Acid", "Niacinamide"],
    origin: "KR",
    affiliateUrl: amazon("B07XFLXW3S"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "beauty-of-joseon-glow-serum",
    name: "Glow Serum: Propolis + Niacinamide",
    brand: "Beauty of Joseon",
    category: "Serum",
    trustScore: 89,
    productTags: ["cruelty-free"],
    description:
      "Hydrating glow serum with 60% propolis and 2% niacinamide to brighten, even tone, and add a healthy sheen.",
    rating: 0,
    reviewCount: 0,
    image: IMG_SERUM,
    ingredients: ["Propolis Extract", "Niacinamide"],
    origin: "KR",
    affiliateUrl: amazon("B0BX8YWFH1"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "medicube-zero-pore-pad-2-0",
    name: "Zero Pore Pad 2.0",
    brand: "Medicube",
    category: "Exfoliant",
    trustScore: 87,
    productTags: ["cruelty-free"],
    description:
      "Dual-textured toner pads with AHA, BHA, and PHA to exfoliate, refine pores, and smooth texture between treatments.",
    rating: 0,
    reviewCount: 0,
    image: IMG_CLEANSE,
    ingredients: ["Lactic Acid (AHA)", "Salicylic Acid (BHA)", "PHA"],
    origin: "KR",
    affiliateUrl: amazon("B09V7Z4TJG"),
    affiliatePartner: AMAZON,
  },

  // --- French (pharmacy) ---
  {
    slug: "la-roche-posay-cicaplast-baume-b5",
    name: "Cicaplast Baume B5 Soothing Balm",
    brand: "La Roche-Posay",
    category: "Balm",
    trustScore: 93,
    productTags: ["fragrance-free", "paraben-free"],
    description:
      "Multi-purpose repairing balm with panthenol and madecassoside — a med-spa favorite for post-procedure recovery and dry, irritated skin.",
    rating: 0,
    reviewCount: 0,
    image: IMG_MOIST,
    ingredients: ["Panthenol", "Madecassoside", "Shea Butter"],
    origin: "FR",
    recommended: true,
    affiliateUrl: amazon("B072MK7BN2"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "embryolisse-lait-creme-concentre",
    name: "Lait-Crème Concentré",
    brand: "Embryolisse",
    category: "Moisturizer",
    trustScore: 90,
    productTags: ["paraben-free"],
    description:
      "The French backstage classic since 1950 — a rich moisturizer, primer, and makeup remover in one, with shea butter and aloe vera.",
    rating: 0,
    reviewCount: 0,
    image: IMG_MOIST,
    ingredients: ["Shea Butter", "Aloe Vera", "Soy Proteins"],
    origin: "FR",
    recommended: true,
    affiliateUrl: amazon("B007PM1A82"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "bioderma-sensibio-h2o",
    name: "Sensibio H2O Micellar Water",
    brand: "Bioderma",
    category: "Cleanser",
    trustScore: 92,
    productTags: ["fragrance-free"],
    description:
      "The original micellar water — gently removes makeup and impurities from sensitive skin with no rinse and no residue.",
    rating: 0,
    reviewCount: 0,
    image: IMG_CLEANSE,
    ingredients: ["Micelles", "Cucumber Extract", "Glycerin"],
    origin: "FR",
    recommended: true,
    affiliateUrl: amazon("B002XZLAWM"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "avene-thermal-spring-water",
    name: "Thermal Spring Water Facial Mist",
    brand: "Avène",
    category: "Facial Mist",
    trustScore: 89,
    productTags: ["fragrance-free", "paraben-free"],
    description:
      "Soothing thermal spring water mist to calm, cool, and comfort sensitive or post-treatment skin.",
    rating: 0,
    reviewCount: 0,
    image: IMG_CLEANSE,
    ingredients: ["Avène Thermal Spring Water"],
    origin: "FR",
    affiliateUrl: amazon("B002D48QUC"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "nuxe-huile-prodigieuse-dry-oil",
    name: "Huile Prodigieuse Multi-Purpose Dry Oil",
    brand: "Nuxe",
    category: "Face Oil",
    trustScore: 88,
    productTags: [],
    description:
      "Iconic French dry oil with botanical oils that nourish face, body, and hair with a fast-absorbing, radiant finish.",
    rating: 0,
    reviewCount: 0,
    image: IMG_SERUM,
    ingredients: ["Botanical Oils", "Vitamin E"],
    origin: "FR",
    affiliateUrl: amazon("B000BO52TE"),
    affiliatePartner: AMAZON,
  },

  // --- Italian ---
  {
    slug: "collistar-rigenera-anti-wrinkle-cream",
    name: "Rigenera Smoothing Anti-Wrinkle Cream",
    brand: "Collistar",
    category: "Moisturizer",
    trustScore: 87,
    productTags: [],
    description:
      "Italian anti-wrinkle cream with hyaluronic acid and biomimetic peptides to smooth and rebioregenerate the skin.",
    rating: 0,
    reviewCount: 0,
    image: IMG_MOIST,
    ingredients: ["Hyaluronic Acid", "Biomimetic Peptides"],
    origin: "IT",
    recommended: true,
    affiliateUrl: amazon("B09SLM2F1N"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "collistar-lift-hd-eye-lip-contour",
    name: "Lift HD+ Lifting Eye and Lip Contour Cream",
    brand: "Collistar",
    category: "Eye Care",
    trustScore: 86,
    productTags: [],
    description:
      "Targeted Italian contour cream with the Lift HD+ complex to firm and smooth the delicate eye and lip areas.",
    rating: 0,
    reviewCount: 0,
    image: IMG_MOIST,
    ingredients: ["Peptides", "Hyaluronic Acid"],
    origin: "IT",
    affiliateUrl: amazon("B0BVKFCYP9"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "collistar-rigenera-anti-wrinkle-concentrate",
    name: "Rigenera Smoothing Anti-Wrinkle Concentrate",
    brand: "Collistar",
    category: "Serum",
    trustScore: 86,
    productTags: [],
    description:
      "Intensive Italian face concentrate with hyaluronic acid and peptides to target wrinkles and boost skin renewal.",
    rating: 0,
    reviewCount: 0,
    image: IMG_SERUM,
    ingredients: ["Hyaluronic Acid", "Peptides"],
    origin: "IT",
    affiliateUrl: amazon("B09SLKPHZX"),
    affiliatePartner: AMAZON,
  },
];
