import type { Product } from "./types";

const AMAZON = "Amazon Associates";
const IMG_SPF = "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop";
const IMG_SERUM = "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=600&fit=crop";
const IMG_MOIST = "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop";
const IMG_CLEANSE = "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop";

function amazon(asin: string): string {
  return `https://www.amazon.com/dp/${asin}`;
}

/** Luxury derm-brand products with Amazon affiliate links (tag applied at runtime). */
export const amazonAffiliateProducts: Product[] = [
  {
    slug: "eltamd-uv-clear",
    name: "UV Clear Broad-Spectrum SPF 46",
    brand: "EltaMD",
    category: "SPF",
    trustScore: 92,
    productTags: ["fragrance-free", "paraben-free", "dermatologist-tested"],
    description:
      "Oil-free sunscreen loved by med spas for post-procedure protection. Niacinamide helps calm sensitive skin.",
    rating: 4.5,
    reviewCount: 69094,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Niacinamide", "Hyaluronic Acid"],
    origin: "US",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B002MSN3QQ"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "eltamd-uv-daily-hydration-tinted",
    name: "UV Daily Hydration+ Tinted Face Sunscreen",
    brand: "EltaMD",
    category: "SPF",
    trustScore: 91,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Tinted daily SPF with transparent zinc oxide and hyaluronic acid. Hydrates while protecting dry, combination, and normal skin.",
    rating: 4.7,
    reviewCount: 218,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Hyaluronic Acid", "Iron Oxides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0GXLFWPSS"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-anthelios",
    name: "Anthelios Melt-In Milk Sunscreen SPF 60",
    brand: "La Roche-Posay",
    category: "SPF",
    trustScore: 93,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Fast-absorbing body and face sunscreen milk favored by derms for high UVA/UVB protection without a greasy finish.",
    rating: 4.8,
    reviewCount: 12400,
    image: IMG_SPF,
    ingredients: ["Avobenzone", "Homosalate", "Octisalate", "Niacinamide"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07HFHWNPH"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-anthelios-niacinamide",
    name: "Anthelios UV Protection + Niacinamide",
    brand: "La Roche-Posay",
    category: "SPF",
    trustScore: 92,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Lightweight, fast-absorbing sunscreen with niacinamide to help even tone while protecting against daily UV exposure.",
    rating: 4.7,
    reviewCount: 890,
    image: IMG_SPF,
    ingredients: ["Niacinamide", "Avobenzone", "Glycerin"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FJYPJLYC"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-toleriane-hydrating",
    name: "Toleriane Double Repair Face Moisturizer",
    brand: "La Roche-Posay",
    category: "Moisturizer",
    trustScore: 90,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Hyaluronic-acid moisturizer with ceramides and niacinamide for sensitive skin barrier repair — a med spa aftercare staple.",
    rating: 4.7,
    reviewCount: 15600,
    image: IMG_MOIST,
    ingredients: ["Ceramide NP", "Niacinamide", "Hyaluronic Acid"],
    origin: "FR",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B075VX4QVM"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "la-roche-posay-pure-vitamin-c",
    name: "Pure Vitamin C Face Serum",
    brand: "La Roche-Posay",
    category: "Serum",
    trustScore: 88,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "10% pure vitamin C serum for radiance and fine-line smoothing — pharmacy-grade brightening at a accessible price point.",
    rating: 4.6,
    reviewCount: 4200,
    image: IMG_SERUM,
    ingredients: ["Ascorbic Acid", "Salicylic Acid", "Neurosensine"],
    origin: "FR",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07PM79MSC"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinceuticals-discoloration-defense",
    name: "Discoloration Defense Serum",
    brand: "SkinCeuticals",
    category: "Serum",
    trustScore: 89,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Multi-pathway brightening serum with tranexamic acid and niacinamide — used post-laser to target stubborn hyperpigmentation.",
    rating: 4.6,
    reviewCount: 640,
    image: IMG_SERUM,
    ingredients: ["Tranexamic Acid", "Niacinamide", "Kojic Acid", "Hepes"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B005IXGA6C"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-eryfotona-actinica",
    name: "Eryfotona Actinica Daily Mineral SPF 50+",
    brand: "ISDIN",
    category: "SPF",
    trustScore: 94,
    productTags: ["dermatologist-tested", "reef-safe"],
    description:
      "Lightweight mineral sunscreen with DNA repair enzymes — dermatologist-recommended for daily photoprotection and actinic care.",
    rating: 4.7,
    reviewCount: 2100,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "DNA Repairsomes", "Vitamin E"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0DWXXJ9Q1"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-eryfotona-ageless",
    name: "Eryfotona Ageless Tinted Mineral SPF 50+",
    brand: "ISDIN",
    category: "SPF",
    trustScore: 93,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Tinted mineral SPF with peptides and DNA Repairsomes for mature skin — anti-aging sun protection in one step.",
    rating: 4.6,
    reviewCount: 980,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Peptides", "DNA Repairsomes"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0CV85FYPJ"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-mineral-powder-spf",
    name: "Isdinceutics Mineral Brush On Powder SPF 50",
    brand: "ISDIN",
    category: "SPF",
    trustScore: 90,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "On-the-go mineral powder SPF for touch-ups over makeup — pollution protection for urban lifestyles.",
    rating: 4.5,
    reviewCount: 760,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Mica"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07R2CSP6P"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-essential-cleansing",
    name: "Isdinceutics Essential Cleansing Oil",
    brand: "ISDIN",
    category: "Cleanser",
    trustScore: 88,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Oil cleanser with natural-origin oils to dissolve sunscreen and makeup without stripping — ideal pre-facial prep.",
    rating: 4.6,
    reviewCount: 540,
    image: IMG_CLEANSE,
    ingredients: ["Sunflower Oil", "Squalane", "Grape Seed Oil"],
    origin: "EU",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B09JQ325R5"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "isdin-micellar-solution",
    name: "Micellar Solution 400ml",
    brand: "ISDIN",
    category: "Cleanser",
    trustScore: 87,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Gentle micellar water for sensitive skin — removes impurities without rinsing, common in European derm protocols.",
    rating: 4.5,
    reviewCount: 1100,
    image: IMG_CLEANSE,
    ingredients: ["Micelles", "Glycerin", "Panthenol"],
    origin: "EU",
    premium: false,
    recommended: true,
    affiliateUrl: amazon("B0771RDWY3"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-hydratint-spf",
    name: "HydraTint Pro Mineral Broad Spectrum SPF 36",
    brand: "ALASTIN Skincare",
    category: "SPF",
    trustScore: 93,
    productTags: ["fragrance-free", "dermatologist-tested", "reef-safe"],
    description:
      "Tinted mineral moisturizer with SPF — post-procedure friendly and popular after laser and microneedling series.",
    rating: 4.7,
    reviewCount: 890,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Peptides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0GK86VSC7"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-c-radical-serum",
    name: "C-RADICAL Defense Antioxidant Serum",
    brand: "ALASTIN Skincare",
    category: "Serum",
    trustScore: 91,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Illuminating antioxidant serum designed to defend against environmental stressors and support post-treatment recovery.",
    rating: 4.6,
    reviewCount: 320,
    image: IMG_SERUM,
    ingredients: ["Vitamin C", "Antioxidants", "Peptides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G42XZCXP"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-restorative-skin-complex",
    name: "Restorative Skin Complex with TriHex Technology",
    brand: "ALASTIN Skincare",
    category: "Serum",
    trustScore: 95,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Flagship anti-aging treatment with TriHex Technology — clears damaged collagen and supports new, healthy extracellular matrix.",
    rating: 4.8,
    reviewCount: 1100,
    image: IMG_SERUM,
    ingredients: ["TriHex Peptides", "Niacinamide", "Antioxidants"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G42F3X4T"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-gentle-cleanser",
    name: "Gentle Cleanser",
    brand: "ALASTIN Skincare",
    category: "Cleanser",
    trustScore: 89,
    productTags: ["fragrance-free", "dermatologist-tested"],
    description:
      "Non-foaming gentle cleanser safe for post-procedure skin — removes debris without disrupting the skin barrier.",
    rating: 4.6,
    reviewCount: 480,
    image: IMG_CLEANSE,
    ingredients: ["Glycerin", "Panthenol", "Aloe Vera"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0B6717SNJ"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "alastin-regenerating-skin-nectar",
    name: "Regenerating Skin Nectar with TriHex Technology",
    brand: "ALASTIN Skincare",
    category: "Serum",
    trustScore: 94,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Concentrated treatment nectar for compromised or healing skin — frequently recommended after ablative and non-ablative lasers.",
    rating: 4.8,
    reviewCount: 720,
    image: IMG_SERUM,
    ingredients: ["TriHex Peptides", "Hyaluronic Acid", "Antioxidants"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B07L9F177Y"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-tns-advanced-serum",
    name: "TNS Advanced+ Serum",
    brand: "SkinMedica",
    category: "Serum",
    trustScore: 92,
    productTags: ["dermatologist-tested"],
    description:
      "Growth-factor serum for comprehensive anti-aging — gold standard at physician-led med spas nationwide.",
    rating: 4.7,
    reviewCount: 2400,
    image: IMG_SERUM,
    ingredients: ["Growth Factors", "Peptides", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FT8V14XK"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-collagen-support",
    name: "Collagen Support Complex",
    brand: "SkinMedica",
    category: "Serum",
    trustScore: 90,
    productTags: ["dermatologist-tested"],
    description:
      "Age-defying collagen support with hyaluronic acid — complements in-office injectables and laser resurfacing plans.",
    rating: 4.6,
    reviewCount: 380,
    image: IMG_SERUM,
    ingredients: ["Collagen Amino Acids", "Hyaluronic Acid", "Peptides"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FTK9M5FS"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-dermal-repair-cream",
    name: "Dermal Repair Cream",
    brand: "SkinMedica",
    category: "Moisturizer",
    trustScore: 91,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Rich repair cream with vitamins C and E for dry, compromised, or post-procedure skin needing intensive moisture.",
    rating: 4.7,
    reviewCount: 920,
    image: IMG_MOIST,
    ingredients: ["Vitamin C", "Vitamin E", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G1B26P5D"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-instant-bright-eye",
    name: "Instant Bright Eye Cream",
    brand: "SkinMedica",
    category: "Eye Care",
    trustScore: 88,
    productTags: ["dermatologist-tested"],
    description:
      "Brightening eye cream targeting dark circles and puffiness — pairs well with tear-trough and under-eye treatment plans.",
    rating: 4.5,
    reviewCount: 560,
    image: IMG_MOIST,
    ingredients: ["Peptides", "Niacinamide", "Caffeine"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G19JCFTF"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-neck-correct-cream",
    name: "Neck Correct Cream",
    brand: "SkinMedica",
    category: "Moisturizer",
    trustScore: 89,
    productTags: ["dermatologist-tested"],
    description:
      "Targeted neck and décolleté cream for crepiness and laxity — extends facial treatment results below the jawline.",
    rating: 4.6,
    reviewCount: 410,
    image: IMG_MOIST,
    ingredients: ["Peptides", "Antioxidants", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G19BSX47"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-essential-spf-tinted",
    name: "Essential Defense Mineral Shield SPF 35 (Tinted)",
    brand: "SkinMedica",
    category: "SPF",
    trustScore: 90,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Lightweight tinted mineral sunscreen for combination skin — daily photoprotection after in-office treatments.",
    rating: 4.6,
    reviewCount: 680,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Green Tea Extract"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0G19LB6NL"),
    affiliatePartner: AMAZON,
  },
  {
    slug: "skinmedica-essential-spf-clear",
    name: "Essential Defense Mineral Shield SPF 35 (Clear)",
    brand: "SkinMedica",
    category: "SPF",
    trustScore: 90,
    productTags: ["dermatologist-tested", "fragrance-free"],
    description:
      "Clear-finish mineral SPF for all skin tones — non-comedogenic daily protection recommended by aesthetic physicians.",
    rating: 4.6,
    reviewCount: 620,
    image: IMG_SPF,
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Green Tea Extract"],
    origin: "US",
    premium: true,
    recommended: true,
    affiliateUrl: amazon("B0FT8VW19Z"),
    affiliatePartner: AMAZON,
  },
];
