import type { Product, Review, Spa, Treatment } from "./types";

const IMAGES = [
  "https://images.unsplash.com/photo-1519494020892-80afc2743508?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1540555700478-4be289bebecc?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1515377905703-c4788e51ad09?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&h=600&fit=crop",
  "https://images.unsplash.com/photo-1596178065880-2314bdb1f869?w=800&h=600&fit=crop",
];

const GALLERY = [
  "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1515377905703-c4788e51ad09?w=600&h=400&fit=crop",
  "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=400&fit=crop",
];

export const products: Product[] = [
  {
    slug: "eltamd-uv-clear",
    name: "UV Clear Broad-Spectrum SPF 46",
    brand: "EltaMD",
    category: "SPF",
    trustScore: 92,
    productTags: ["fragrance-free", "paraben-free", "dermatologist-tested"],
    description:
      "Oil-free sunscreen loved by med spas for post-procedure protection. Niacinamide helps calm sensitive skin.",
    rating: 4.8,
    reviewCount: 342,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop",
    ingredients: ["Zinc Oxide", "Niacinamide", "Hyaluronic Acid"],
  },
  {
    slug: "skinceuticals-ce-ferulic",
    name: "C E Ferulic",
    brand: "SkinCeuticals",
    category: "Serum",
    trustScore: 88,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Gold-standard antioxidant serum used before and after laser treatments at top Miami med spas.",
    rating: 4.7,
    reviewCount: 891,
    image: "https://images.unsplash.com/photo-1620916561694-4d134e883ab7?w=600&h=600&fit=crop",
    ingredients: ["Vitamin C", "Vitamin E", "Ferulic Acid"],
  },
  {
    slug: "epicutis-arctigenin",
    name: "Arctigenin Brightening Treatment",
    brand: "Epicutis",
    category: "Serum",
    trustScore: 94,
    productTags: ["fragrance-free", "paraben-free", "vegan", "cruelty-free"],
    description:
      "Premium post-procedure serum popular at luxury Miami facials. Ideal for sensitive and post-treatment skin.",
    rating: 4.9,
    reviewCount: 128,
    image: "https://images.unsplash.com/photo-1570194065650-d99fb4b74108?w=600&h=600&fit=crop",
    ingredients: ["Arctigenin", "Squalane", "Ferulic Acid", "Chia Seed Oil"],
  },
  {
    slug: "is-clinical-cleansing",
    name: "Cleansing Complex",
    brand: "iS Clinical",
    category: "Cleanser",
    trustScore: 86,
    productTags: ["paraben-free", "dermatologist-tested"],
    description:
      "Gentle resurfacing cleanser used in luxury facial protocols across South Florida.",
    rating: 4.6,
    reviewCount: 456,
    image: "https://images.unsplash.com/photo-1608248543801-ba43f4474263?w=600&h=600&fit=crop",
    ingredients: ["Willow Bark", "Sugar Cane Extract", "Chamomile"],
  },
  {
    slug: "revision-retinol",
    name: "Retinol Complete 1.0",
    brand: "Revision Skincare",
    category: "Retinol",
    trustScore: 90,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description: "Clinical retinol used in anti-aging protocols at premier Miami med spas.",
    rating: 4.7,
    reviewCount: 312,
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&h=600&fit=crop",
    ingredients: ["Retinol", "Bakuchiol", "Hyaluronic Acid"],
  },
  {
    slug: "skinmedica-ha5",
    name: "HA5 Rejuvenating Hydrator",
    brand: "SkinMedica",
    category: "Moisturizer",
    trustScore: 87,
    productTags: ["dermatologist-tested"],
    description: "Five-type hyaluronic acid complex for deep hydration after injectables and lasers.",
    rating: 4.8,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop",
    ingredients: ["Hyaluronic Acid", "Peptides", "Vitamin E"],
  },
];

type SpaSeed = Omit<Spa, "gallery"> & { gallery?: string[] };

function seedSpa(data: SpaSeed, index: number): Spa {
  return {
    ...data,
    image: data.image || IMAGES[index % IMAGES.length],
    gallery: data.gallery || GALLERY,
  };
}

const spaSeeds: SpaSeed[] = [
  {
    slug: "aether-aesthetics-coral-gables",
    name: "Aether Aesthetics",
    neighborhood: "Coral Gables",
    city: "Miami",
    tagline: "Natural injectables. Transparent protocols.",
    description:
      "Board-supervised boutique med spa specializing in natural-looking injectables. Every product used in treatment is disclosed before your appointment.",
    rating: 4.9,
    reviewCount: 187,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Elena Morales, MD",
    licenseId: "ME-98421",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "aetheraesthetics_mia",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin", "is-clinical-cleansing"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
  },
  {
    slug: "lumiere-medspa-brickell",
    name: "Lumière Medspa",
    neighborhood: "Brickell",
    city: "Miami",
    tagline: "Luxury laser. Expert recovery.",
    description:
      "High-end laser and skin rejuvenation for Miami professionals. Results-driven treatments with published provider credentials.",
    rating: 4.8,
    reviewCount: 334,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. James Chen, MD",
    licenseId: "ME-87234",
    yearsOpen: 9,
    treatments: ["laser", "facial", "microneedling", "body-contouring"],
    priceRange: "$$$$",
    instagram: "lumiere_medspa_brickell",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
  },
  {
    slug: "salt-glow-miami-beach",
    name: "Salt & Glow",
    neighborhood: "Miami Beach",
    city: "Miami Beach",
    tagline: "Coastal luxury skincare.",
    description:
      "Facial-forward med spa blending clinical treatments with premium skincare. Perfect for first-time med spa visitors.",
    rating: 4.7,
    reviewCount: 262,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Sofia Reyes, NP (MSN)",
    licenseId: "ME-76102",
    yearsOpen: 4,
    treatments: ["facial", "microneedling", "botox"],
    priceRange: "$$",
    instagram: "saltandglow_miami",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Beach-adjacent location"],
  },
  {
    slug: "forme-aesthetics-wynwood",
    name: "Forme Aesthetics",
    neighborhood: "Wynwood",
    city: "Miami",
    tagline: "Artistry meets accountability.",
    description:
      "Modern injectables studio with transparent pricing and published provider credentials. Known for natural lip and jawline work.",
    rating: 4.6,
    reviewCount: 298,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Marcus Webb, MD",
    licenseId: "ME-91045",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "body-contouring"],
    priceRange: "$$$",
    instagram: "forme_aesthetics",
    productSlugs: ["skinceuticals-ce-ferulic"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
  },
  {
    slug: "maison-skin-design-district",
    name: "Maison Skin Lab",
    neighborhood: "Design District",
    city: "Miami",
    tagline: "Where luxury meets precision.",
    description: "Ultra-premium med spa serving Miami's Design District clientele. Specializing in bespoke treatment plans.",
    rating: 4.9,
    reviewCount: 156,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Isabelle Fontaine, MD",
    licenseId: "ME-88201",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$$$",
    instagram: "maison_skin_lab",
    productSlugs: ["skinceuticals-ce-ferulic", "revision-retinol", "skinmedica-ha5"],
    highlights: ["Bespoke treatment plans", "Private suites", "Celebrity clientele"],
  },
  {
    slug: "injector-studio-brickell",
    name: "The Injector Studio",
    neighborhood: "Brickell",
    city: "Miami",
    tagline: "Injectables-only excellence.",
    description: "Focused exclusively on Botox and fillers with board-certified injectors. High volume, natural results.",
    rating: 4.7,
    reviewCount: 412,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Rachel Kim, MD",
    licenseId: "ME-89334",
    yearsOpen: 8,
    treatments: ["botox", "fillers"],
    priceRange: "$$$",
    instagram: "injector_studio_mia",
    productSlugs: ["eltamd-uv-clear"],
    highlights: ["Injectables specialists", "Same-day appointments", "Transparent pricing"],
  },
  {
    slug: "coastal-aesthetics-south-beach",
    name: "Coastal Aesthetics",
    neighborhood: "South Beach",
    city: "Miami Beach",
    tagline: "South Beach's trusted med spa.",
    description: "Full-service aesthetics clinic steps from Ocean Drive. Popular with locals and visitors alike.",
    rating: 4.5,
    reviewCount: 523,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Antonio Vega, MD",
    licenseId: "ME-77201",
    yearsOpen: 11,
    treatments: ["botox", "fillers", "laser", "body-contouring"],
    priceRange: "$$$",
    instagram: "coastal_aesthetics_sb",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-ce-ferulic"],
    highlights: ["Walk-in consultations", "Multilingual staff", "Tourist-friendly booking"],
  },
  {
    slug: "grove-wellness-coconut-grove",
    name: "Grove Wellness Spa",
    neighborhood: "Coconut Grove",
    city: "Miami",
    tagline: "Relaxed luxury in the Grove.",
    description: "Boutique med spa in Coconut Grove offering facials, injectables, and body treatments in a serene setting.",
    rating: 4.8,
    reviewCount: 145,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Patricia Dunn, MD",
    licenseId: "ME-85432",
    yearsOpen: 5,
    treatments: ["facial", "botox", "microneedling"],
    priceRange: "$$$",
    instagram: "grove_wellness_spa",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing"],
    highlights: ["Serene setting", "Holistic consultations", "Grove village location"],
  },
  {
    slug: "aventura-med-aesthetics",
    name: "Aventura Med Aesthetics",
    neighborhood: "Aventura",
    city: "Aventura",
    tagline: "North Miami's premier destination.",
    description: "Large-format med spa serving Aventura and Sunny Isles. Full menu from injectables to body contouring.",
    rating: 4.6,
    reviewCount: 389,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Michael Roth, MD",
    licenseId: "ME-90123",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "laser", "body-contouring", "facial"],
    priceRange: "$$$",
    instagram: "aventura_med_aesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "skinmedica-ha5", "revision-retinol"],
    highlights: ["Full treatment menu", "Free parking", "Extended hours"],
  },
  {
    slug: "doral-beauty-institute",
    name: "Doral Beauty Institute",
    neighborhood: "Doral",
    city: "Doral",
    tagline: "West Miami's aesthetic hub.",
    description: "Modern med spa in Doral offering competitive pricing on injectables and advanced laser treatments.",
    rating: 4.5,
    reviewCount: 267,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Luis Hernandez, MD",
    licenseId: "ME-88765",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "laser", "microneedling"],
    priceRange: "$$",
    instagram: "doral_beauty_institute",
    productSlugs: ["eltamd-uv-clear", "is-clinical-cleansing"],
    highlights: ["Competitive pricing", "Spanish/English staff", "Laser hair removal"],
  },
  {
    slug: "pinecrest-plastic-spa",
    name: "Pinecrest Aesthetic Studio",
    neighborhood: "Pinecrest",
    city: "Miami",
    tagline: "Suburban sophistication.",
    description: "Upscale med spa in Pinecrest favored by South Miami families. Emphasis on subtle, age-appropriate results.",
    rating: 4.9,
    reviewCount: 178,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Susan Walsh, MD",
    licenseId: "ME-91234",
    yearsOpen: 12,
    treatments: ["botox", "fillers", "facial", "laser"],
    priceRange: "$$$$",
    instagram: "pinecrest_aesthetic",
    productSlugs: ["revision-retinol", "skinmedica-ha5", "epicutis-arctigenin"],
    highlights: ["Age-appropriate results", "Family-friendly scheduling", "Plastic surgeon-led"],
  },
  {
    slug: "bal-harbour-skin-clinic",
    name: "Bal Harbour Skin Clinic",
    neighborhood: "Bal Harbour",
    city: "Bal Harbour",
    tagline: "Ultra-luxury. Ultra-discreet.",
    description: "Exclusive med spa at Bal Harbour Shops. Discretion and white-glove service for high-profile clients.",
    rating: 4.9,
    reviewCount: 89,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Victoria Ashford, MD",
    licenseId: "ME-94567",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    priceRange: "$$$$",
    instagram: "balharbour_skin",
    productSlugs: ["skinceuticals-ce-ferulic", "epicutis-arctigenin", "revision-retinol"],
    highlights: ["Private entrance", "VIP scheduling", "Concierge service"],
  },
  {
    slug: "key-biscayne-med-spa",
    name: "Key Biscayne Med Spa",
    neighborhood: "Key Biscayne",
    city: "Key Biscayne",
    tagline: "Island luxury aesthetics.",
    description: "Boutique island med spa serving Key Biscayne residents. Intimate setting with personalized care.",
    rating: 4.8,
    reviewCount: 112,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Robert Ellis, MD",
    licenseId: "ME-87890",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial"],
    priceRange: "$$$$",
    instagram: "keybiscayne_medspa",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["Island location", "Personalized care", "Member loyalty program"],
  },
  {
    slug: "south-miami-aesthetics",
    name: "South Miami Aesthetics",
    neighborhood: "South Miami",
    city: "Miami",
    tagline: "Your neighborhood med spa.",
    description: "Community-focused med spa on US-1 in South Miami. Trusted by locals for over a decade.",
    rating: 4.6,
    reviewCount: 445,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Karen Mitchell, MD",
    licenseId: "ME-82345",
    yearsOpen: 13,
    treatments: ["botox", "fillers", "laser", "facial", "body-contouring"],
    priceRange: "$$",
    instagram: "southmiami_aesthetics",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["Established reputation", "Flexible payment plans", "Loyalty rewards"],
  },
  {
    slug: "kendall-rejuvenation",
    name: "Kendall Rejuvenation Center",
    neighborhood: "Kendall",
    city: "Miami",
    tagline: "Results you can trust.",
    description: "High-volume med spa in Kendall offering accessible pricing on Botox, fillers, and laser treatments.",
    rating: 4.4,
    reviewCount: 678,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Carlos Mendez, MD",
    licenseId: "ME-85678",
    yearsOpen: 9,
    treatments: ["botox", "fillers", "laser", "microneedling", "body-contouring"],
    priceRange: "$$",
    instagram: "kendall_rejuvenation",
    productSlugs: ["eltamd-uv-clear", "skinmedica-ha5"],
    highlights: ["Accessible pricing", "High patient volume", "Extended weekend hours"],
  },
  {
    slug: "edgewater-laser-skin",
    name: "Edgewater Laser & Skin",
    neighborhood: "Edgewater",
    city: "Miami",
    tagline: "Laser experts on the bay.",
    description: "Laser-focused med spa in Edgewater with bay views. Specialists in pigmentation, scars, and skin tightening.",
    rating: 4.7,
    reviewCount: 234,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Amy Chang, MD",
    licenseId: "ME-89012",
    yearsOpen: 5,
    treatments: ["laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "edgewater_laser_skin",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Laser specialists", "Bay views", "Free skin analysis"],
  },
  {
    slug: "midtown-miami-medspa",
    name: "Midtown Med Spa",
    neighborhood: "Midtown",
    city: "Miami",
    tagline: "Urban beauty, clinical precision.",
    description: "Trendy Midtown location popular with young professionals. Strong on preventive Botox and lip fillers.",
    rating: 4.5,
    reviewCount: 312,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Nicole Park, MD",
    licenseId: "ME-86789",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial"],
    priceRange: "$$$",
    instagram: "midtown_medspa_mia",
    productSlugs: ["revision-retinol", "eltamd-uv-clear"],
    highlights: ["Preventive Botox", "After-work hours", "Social media savvy team"],
  },
  {
    slug: "sunny-isles-aesthetics",
    name: "Sunny Isles Aesthetics",
    neighborhood: "Sunny Isles",
    city: "Sunny Isles Beach",
    tagline: "International standards, local care.",
    description: "Multilingual med spa serving Sunny Isles and Aventura's international community. Full aesthetics menu.",
    rating: 4.6,
    reviewCount: 289,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Ivan Petrov, MD",
    licenseId: "ME-90456",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "body-contouring", "facial"],
    priceRange: "$$$",
    instagram: "sunnyisles_aesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "skinmedica-ha5"],
    highlights: ["Multilingual staff", "International clientele", "Body contouring specialists"],
  },
  {
    slug: "north-miami-beauty-lab",
    name: "North Miami Beauty Lab",
    neighborhood: "North Miami",
    city: "North Miami",
    tagline: "Innovation meets aesthetics.",
    description: "Tech-forward med spa in North Miami offering the latest in injectables and skin rejuvenation.",
    rating: 4.5,
    reviewCount: 198,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jasmine Brooks, MD",
    licenseId: "ME-88123",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "microneedling", "facial"],
    priceRange: "$$",
    instagram: "northmiami_beautylab",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing"],
    highlights: ["Latest technology", "New patient specials", "Online booking"],
  },
  {
    slug: "coral-way-skin-studio",
    name: "Coral Way Skin Studio",
    neighborhood: "Coral Way",
    city: "Miami",
    tagline: "Classic Miami beauty.",
    description: "Established med spa on Coral Way serving central Miami. Known for excellent facials and injectables.",
    rating: 4.7,
    reviewCount: 356,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Maria Santos, MD",
    licenseId: "ME-84567",
    yearsOpen: 10,
    treatments: ["facial", "botox", "fillers", "microneedling"],
    priceRange: "$$",
    instagram: "coralway_skin",
    productSlugs: ["is-clinical-cleansing", "epicutis-arctigenin", "eltamd-uv-clear"],
    highlights: ["Award-winning facials", "Central location", "Established 2014"],
  },
  {
    slug: "homestead-wellness-medspa",
    name: "Homestead Wellness Med Spa",
    neighborhood: "Homestead",
    city: "Homestead",
    tagline: "South Dade's med spa.",
    description: "Serving South Miami-Dade with accessible med spa services. Botox, fillers, and laser hair removal.",
    rating: 4.4,
    reviewCount: 167,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jorge Rivera, MD",
    licenseId: "ME-91200",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser"],
    priceRange: "$",
    instagram: "homestead_wellness",
    productSlugs: ["eltamd-uv-clear"],
    highlights: ["South Dade location", "Affordable pricing", "Laser hair removal"],
  },
  {
    slug: "cutler-bay-aesthetics",
    name: "Cutler Bay Aesthetics",
    neighborhood: "Cutler Bay",
    city: "Cutler Bay",
    tagline: "Quality care, south of the city.",
    description: "Full-service med spa in Cutler Bay. Popular with families and professionals in South Miami-Dade.",
    rating: 4.5,
    reviewCount: 223,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Angela Torres, NP (MSN)",
    licenseId: "ME-89876",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "body-contouring"],
    priceRange: "$$",
    instagram: "cutlerbay_aesthetics",
    productSlugs: ["is-clinical-cleansing", "skinmedica-ha5"],
    highlights: ["Family-friendly", "Free consultations", "Body contouring"],
  },
  {
    slug: "miami-shores-aesthetics",
    name: "Miami Shores Aesthetics",
    neighborhood: "Miami Shores",
    city: "Miami Shores",
    tagline: "Quiet luxury, north of downtown.",
    description: "Intimate med spa in Miami Shores village. Personalized attention in a relaxed neighborhood setting.",
    rating: 4.8,
    reviewCount: 134,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Helen Price, MD",
    licenseId: "ME-87321",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "miamishores_aesthetics",
    productSlugs: ["epicutis-arctigenin", "revision-retinol"],
    highlights: ["Village setting", "Small-batch attention", "Referral-only reputation"],
  },
  {
    slug: "fisher-island-aesthetics",
    name: "Fisher Island Aesthetics",
    neighborhood: "Fisher Island",
    city: "Miami Beach",
    tagline: "Exclusive island treatments.",
    description: "Private med spa on Fisher Island serving residents and members. By-appointment only.",
    rating: 4.9,
    reviewCount: 67,
    verified: true,
    premierPartner: true,
    medicalDirector: "Dr. Charles Whitmore, MD",
    licenseId: "ME-95678",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$$$",
    instagram: "fisherisland_aesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "epicutis-arctigenin", "revision-retinol"],
    highlights: ["Members only", "Island location", "House calls available"],
  },
];

export const spas: Spa[] = spaSeeds.map((seed, i) => seedSpa(seed, i));

export const neighborhoods = [...new Set(spas.map((s) => s.neighborhood))].sort();

export const reviews: Review[] = [
  {
    id: "r1",
    author: "Camila R.",
    rating: 5,
    text: "They emailed me every product before my facial — zero surprises. Exactly the transparency I wanted.",
    date: "2026-05-12",
    verified: true,
    treatment: "Luxury Facial",
    productSlug: "epicutis-arctigenin",
  },
  {
    id: "r2",
    author: "Jennifer L.",
    rating: 5,
    text: "Finally a platform where I could see which SPF my spa actually uses. EltaMD post-laser was perfect.",
    date: "2026-04-28",
    verified: true,
    treatment: "Laser Resurfacing",
    productSlug: "eltamd-uv-clear",
  },
  {
    id: "r3",
    author: "Alex M.",
    rating: 4,
    text: "Loved the natural lip filler at Forme. Spa confirmed my booking within 2 hours.",
    date: "2026-03-15",
    verified: true,
    treatment: "Lip Filler",
  },
  {
    id: "r4",
    author: "Diana K.",
    rating: 5,
    text: "The trust score on Epicutis helped me compare spas. Salt & Glow was the perfect match.",
    date: "2026-05-01",
    verified: true,
    productSlug: "epicutis-arctigenin",
  },
  {
    id: "r5",
    author: "Marcus T.",
    rating: 5,
    text: "Used Verity Premium for priority booking at Bal Harbour Skin Clinic. Worth every penny.",
    date: "2026-05-20",
    verified: true,
    treatment: "Botox",
  },
];

export function getSpa(slug: string) {
  return spas.find((s) => s.slug === slug);
}

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getSpaReviews(spaSlug: string) {
  const spa = getSpa(spaSlug);
  if (!spa) return [];
  const productSet = new Set(spa.productSlugs);
  return reviews.filter(
    (r) => r.treatment || (r.productSlug && productSet.has(r.productSlug))
  );
}

export function getProductReviews(productSlug: string) {
  return reviews.filter((r) => r.productSlug === productSlug);
}

export function getSpasForProduct(productSlug: string) {
  return spas.filter((s) => s.productSlugs.includes(productSlug));
}

export function getProductsForSpa(spaSlug: string) {
  const spa = getSpa(spaSlug);
  if (!spa) return [];
  return products.filter((p) => spa.productSlugs.includes(p.slug));
}

export function getSpasByNeighborhood(neighborhood: string) {
  if (!neighborhood || neighborhood === "All") return spas;
  return spas.filter((s) => s.neighborhood === neighborhood);
}
