import { amazonAffiliateProducts } from "./amazon-affiliate-products";
import { additionalFloridaSpaSeeds } from "./additional-florida-spa-seeds";
import { floridaCoastalRealSpas } from "./florida-coastal-real-spas";
import { floridaRealSpas } from "./florida-real-spas";
import { miamiMetroRealSpas } from "./miami-metro-real-spas";
import { nationwideRealSpas } from "./nationwide-real-spas";
import { tampaBayRealSpas } from "./tampa-bay-real-spas";
import { floridaSpaSeeds } from "./florida-spa-seeds";
import { getSpaImages } from "./spa-images";
import {
  defaultCertifications,
  defaultDataSources,
  defaultPhoneForMetro,
  deriveTreatmentCategories,
  getAreasByCity,
  getTopRatedSpas,
  METRO_LABELS,
  parseMedicalDirector,
  resolveProductSlugs,
  sortSpasForDisplay,
} from "./spa-utils";
import type { Metro, Product, ProductOrigin, ProviderType, Review, Spa, SpaSocials, Treatment } from "./types";

export const originLabels: Record<ProductOrigin, string> = {
  US: "American",
  KR: "Korean",
  FR: "French",
  IT: "Italian",
  EU: "European",
};

export const baseProducts: Product[] = [
  {
    slug: "eltamd-uv-clear",
    name: "UV Clear Broad-Spectrum SPF 46",
    brand: "EltaMD",
    category: "SPF",
    trustScore: 92,
    productTags: ["fragrance-free", "paraben-free", "dermatologist-tested"],
    description:
      "Oil-free sunscreen loved by med spas for post-procedure protection. Niacinamide helps calm sensitive skin.",
    rating: 4.8,
    reviewCount: 342,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop",
    ingredients: ["Zinc Oxide", "Niacinamide", "Hyaluronic Acid"],
    origin: "US",
    premium: false,
    recommended: true,
  },
  {
    slug: "skinceuticals-ce-ferulic",
    name: "C E Ferulic",
    brand: "SkinCeuticals",
    category: "Serum",
    trustScore: 88,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description:
      "Gold-standard antioxidant serum used before and after laser treatments at top Miami med spas.",
    rating: 4.7,
    reviewCount: 891,
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=600&fit=crop",
    ingredients: ["Vitamin C", "Vitamin E", "Ferulic Acid"],
    origin: "US",
    premium: true,
    recommended: true,
  },
  {
    slug: "epicutis-arctigenin",
    name: "Arctigenin Brightening Treatment",
    brand: "Epicutis",
    category: "Serum",
    trustScore: 94,
    productTags: ["fragrance-free", "paraben-free", "vegan", "cruelty-free"],
    description:
      "Premium post-procedure serum popular at luxury Miami facials. Ideal for sensitive and post-treatment skin.",
    rating: 4.9,
    reviewCount: 128,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=600&fit=crop",
    ingredients: ["Arctigenin", "Squalane", "Ferulic Acid", "Chia Seed Oil"],
    origin: "US",
    premium: true,
  },
  {
    slug: "is-clinical-cleansing",
    name: "Cleansing Complex",
    brand: "iS Clinical",
    category: "Cleanser",
    trustScore: 86,
    productTags: ["paraben-free", "dermatologist-tested"],
    description:
      "Gentle resurfacing cleanser used in luxury facial protocols across South Florida.",
    rating: 4.6,
    reviewCount: 456,
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop",
    ingredients: ["Willow Bark", "Sugar Cane Extract", "Chamomile"],
    origin: "US",
    premium: false,
  },
  {
    slug: "revision-retinol",
    name: "Retinol Complete 1.0",
    brand: "Revision Skincare",
    category: "Retinol",
    trustScore: 90,
    productTags: ["dermatologist-tested", "cruelty-free"],
    description: "Clinical retinol used in anti-aging protocols at premier Miami med spas.",
    rating: 4.7,
    reviewCount: 312,
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&h=600&fit=crop",
    ingredients: ["Retinol", "Bakuchiol", "Hyaluronic Acid"],
    origin: "US",
    premium: true,
  },
  {
    slug: "skinmedica-ha5",
    name: "HA5 Rejuvenating Hydrator",
    brand: "SkinMedica",
    category: "Moisturizer",
    trustScore: 87,
    productTags: ["dermatologist-tested"],
    description: "Five-type hyaluronic acid complex for deep hydration after injectables and lasers.",
    rating: 4.8,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop",
    ingredients: ["Hyaluronic Acid", "Peptides", "Vitamin E"],
    origin: "US",
    premium: true,
    recommended: true,
  },
];

function mergeAffiliateProducts(base: Product[], affiliate: Product[]): Product[] {
  const bySlug = new Map<string, Product>();
  for (const product of base) bySlug.set(product.slug, product);
  for (const product of affiliate) {
    const existing = bySlug.get(product.slug);
    bySlug.set(product.slug, existing ? { ...existing, ...product } : product);
  }
  return [...bySlug.values()];
}

export const products: Product[] = mergeAffiliateProducts(baseProducts, amazonAffiliateProducts);

type SpaSeed = {
  slug: string;
  name: string;
  providerType: ProviderType;
  state?: string;
  neighborhood: string;
  city: string;
  metro?: Metro;
  tagline: string;
  description: string;
  rating: number;
  reviewCount: number;
  googleRating?: number;
  yelpRating?: number;
  verified: boolean;
  premierPartner: boolean;
  featuredRank?: number;
  medicalDirector: string;
  licenseId: string;
  yearsOpen: number;
  treatments: Treatment[];
  priceRange: Spa["priceRange"];
  instagram: string;
  productSlugs: string[];
  highlights: string[];
  website?: string;
  phone?: string;
  reviewSource?: string;
  socials?: SpaSocials;
  certifications?: string[];
  dataSources?: string[];
};

function buildSocials(seed: SpaSeed): SpaSocials {
  if (seed.socials) return seed.socials;
  if (seed.instagram?.trim()) return { instagram: seed.instagram.trim() };
  return {};
}

function seedSpa(data: SpaSeed, index: number): Spa {
  const state = data.state ?? "FL";
  const metro = data.metro;
  const images = getSpaImages(data.slug);
  const website = data.website?.trim() ?? "";
  const phone =
    data.phone ?? (metro ? defaultPhoneForMetro(metro, index) : `(555) 555-${String(1000 + (index % 9000)).padStart(4, "0")}`);
  const socials = buildSocials(data);
  const reviewSources =
    data.googleRating || data.yelpRating
      ? {
          ...(data.googleRating ? { google: data.googleRating } : {}),
          ...(data.yelpRating ? { yelp: data.yelpRating } : {}),
        }
      : undefined;

  return {
    slug: data.slug,
    name: data.name,
    providerType: data.providerType,
    state,
    neighborhood: data.neighborhood,
    city: data.city,
    metro,
    reviewSources,
    tagline: data.tagline,
    description: data.description,
    rating: data.rating,
    reviewCount: data.reviewCount,
    verified: data.verified,
    premierPartner: false,
    featuredPremium: false,
    medicalDirector: data.medicalDirector,
    medicalDirectorInfo: parseMedicalDirector(data.medicalDirector),
    licenseId: data.licenseId,
    yearsOpen: data.yearsOpen,
    treatments: data.treatments,
    treatmentCategories: deriveTreatmentCategories(data.treatments),
    priceRange: data.priceRange,
    website,
    phone,
    socials,
    certifications:
      data.certifications ?? defaultCertifications(false, false),
    dataSources: data.dataSources ?? [
      ...defaultDataSources(false, website),
      ...( "reviewSource" in data && data.reviewSource
        ? [`${data.reviewSource} — rating ${data.rating}`]
        : []),
    ],
    image: images.hero,
    imageSource: images.source,
    gallery: images.gallery,
    productSlugs: resolveProductSlugs({
      slug: data.slug,
      providerType: data.providerType,
      treatments: data.treatments,
      priceRange: data.priceRange,
      productSlugs: data.productSlugs,
    }),
    highlights: data.highlights,
  };
}

const spaSeeds: SpaSeed[] = [
  {
    slug: "aether-aesthetics-coral-gables",
    name: "Aether Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Coral Gables",
    city: "Miami",
    tagline: "Natural injectables. Transparent protocols.",
    description:
      "Board-supervised boutique med spa specializing in natural-looking injectables. Every product used in treatment is disclosed before your appointment.",
    rating: 4.9,
    reviewCount: 187,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Elena Morales, MD",
    licenseId: "ME-98421",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "aetheraesthetics_mia",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin", "is-clinical-cleansing"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
  },
  {
    slug: "lumiere-medspa-brickell",
    name: "Lumière Medspa",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    tagline: "Luxury laser. Expert recovery.",
    description:
      "High-end laser and skin rejuvenation for Miami professionals. Results-driven treatments with published provider credentials.",
    rating: 4.8,
    reviewCount: 334,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. James Chen, MD",
    licenseId: "ME-87234",
    yearsOpen: 9,
    treatments: ["laser", "facial", "microneedling", "body-contouring"],
    priceRange: "$$$$",
    instagram: "lumiere_medspa_brickell",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
  },
  {
    slug: "salt-glow-miami-beach",
    name: "Salt & Glow",
    providerType: "med-spa",
    neighborhood: "Miami Beach",
    city: "Miami Beach",
    tagline: "Coastal luxury skincare.",
    description:
      "Facial-forward med spa blending clinical treatments with premium skincare. Perfect for first-time med spa visitors.",
    rating: 4.7,
    reviewCount: 262,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Sofia Reyes, NP (MSN)",
    licenseId: "ME-76102",
    yearsOpen: 4,
    treatments: ["facial", "microneedling", "botox"],
    priceRange: "$$",
    instagram: "saltandglow_miami",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Beach-adjacent location"],
  },
  {
    slug: "forme-aesthetics-wynwood",
    name: "Forme Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Wynwood",
    city: "Miami",
    tagline: "Artistry meets accountability.",
    description:
      "Modern injectables studio with transparent pricing and published provider credentials. Known for natural lip and jawline work.",
    rating: 4.6,
    reviewCount: 298,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Marcus Webb, MD",
    licenseId: "ME-91045",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "body-contouring"],
    priceRange: "$$$",
    instagram: "forme_aesthetics",
    productSlugs: ["skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
  },
  {
    slug: "maison-skin-design-district",
    name: "Maison Skin Lab",
    providerType: "aesthetics-clinic",
    neighborhood: "Design District",
    city: "Miami",
    tagline: "Where luxury meets precision.",
    description: "Ultra-premium med spa serving Miami's Design District clientele. Specializing in bespoke treatment plans.",
    rating: 4.9,
    reviewCount: 156,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Isabelle Fontaine, MD",
    licenseId: "ME-88201",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$$$",
    instagram: "maison_skin_lab",
    productSlugs: ["skinceuticals-ce-ferulic", "revision-retinol", "skinmedica-ha5"],
    highlights: ["Bespoke treatment plans", "Private suites", "Celebrity clientele"],
  },
  {
    slug: "injector-studio-brickell",
    name: "The Injector Studio",
    providerType: "aesthetics-clinic",
    neighborhood: "Brickell",
    city: "Miami",
    tagline: "Injectables-only excellence.",
    description: "Focused exclusively on Botox and fillers with board-certified injectors. High volume, natural results.",
    rating: 4.7,
    reviewCount: 412,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Rachel Kim, MD",
    licenseId: "ME-89334",
    yearsOpen: 8,
    treatments: ["botox", "fillers"],
    priceRange: "$$$",
    instagram: "injector_studio_mia",
    productSlugs: ["eltamd-uv-clear"],
    highlights: ["Injectables specialists", "Same-day appointments", "Transparent pricing"],
  },
  {
    slug: "coastal-aesthetics-south-beach",
    name: "Coastal Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "South Beach",
    city: "Miami Beach",
    tagline: "South Beach's trusted med spa.",
    description: "Full-service aesthetics clinic steps from Ocean Drive. Popular with locals and visitors alike.",
    rating: 4.5,
    reviewCount: 523,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Antonio Vega, MD",
    licenseId: "ME-77201",
    yearsOpen: 11,
    treatments: ["botox", "fillers", "laser", "body-contouring"],
    priceRange: "$$$",
    instagram: "coastal_aesthetics_sb",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-ce-ferulic"],
    highlights: ["Walk-in consultations", "Multilingual staff", "Tourist-friendly booking"],
  },
  {
    slug: "grove-wellness-coconut-grove",
    name: "Grove Wellness Spa",
    providerType: "med-spa",
    neighborhood: "Coconut Grove",
    city: "Miami",
    tagline: "Relaxed luxury in the Grove.",
    description: "Boutique med spa in Coconut Grove offering facials, injectables, and body treatments in a serene setting.",
    rating: 4.8,
    reviewCount: 145,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Patricia Dunn, MD",
    licenseId: "ME-85432",
    yearsOpen: 5,
    treatments: ["facial", "botox", "microneedling"],
    priceRange: "$$$",
    instagram: "grove_wellness_spa",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing", "isdin-eryfotona-actinica"],
    highlights: ["Serene setting", "Holistic consultations", "Grove village location"],
  },
  {
    slug: "aventura-med-aesthetics",
    name: "Aventura Med Aesthetics",
    providerType: "med-spa",
    neighborhood: "Aventura",
    city: "Aventura",
    tagline: "North Miami's premier destination.",
    description: "Large-format med spa serving Aventura and Sunny Isles. Full menu from injectables to body contouring.",
    rating: 4.6,
    reviewCount: 389,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Michael Roth, MD",
    licenseId: "ME-90123",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "laser", "body-contouring", "facial"],
    priceRange: "$$$",
    instagram: "aventura_med_aesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "skinmedica-ha5", "revision-retinol"],
    highlights: ["Full treatment menu", "Free parking", "Extended hours"],
  },
  {
    slug: "doral-beauty-institute",
    name: "Doral Beauty Institute",
    providerType: "aesthetics-clinic",
    neighborhood: "Doral",
    city: "Doral",
    tagline: "West Miami's aesthetic hub.",
    description: "Modern med spa in Doral offering competitive pricing on injectables and advanced laser treatments.",
    rating: 4.5,
    reviewCount: 267,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Luis Hernandez, MD",
    licenseId: "ME-88765",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "laser", "microneedling"],
    priceRange: "$$",
    instagram: "doral_beauty_institute",
    productSlugs: ["eltamd-uv-clear", "is-clinical-cleansing"],
    highlights: ["Competitive pricing", "Spanish/English staff", "Laser hair removal"],
  },
  {
    slug: "pinecrest-plastic-spa",
    name: "Pinecrest Aesthetic Studio",
    providerType: "dermatology-aesthetics",
    neighborhood: "Pinecrest",
    city: "Miami",
    tagline: "Suburban sophistication.",
    description: "Upscale med spa in Pinecrest favored by South Miami families. Emphasis on subtle, age-appropriate results.",
    rating: 4.9,
    reviewCount: 178,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Susan Walsh, MD",
    licenseId: "ME-91234",
    yearsOpen: 12,
    treatments: ["botox", "fillers", "facial", "laser"],
    priceRange: "$$$$",
    instagram: "pinecrest_aesthetic",
    productSlugs: ["revision-retinol", "skinmedica-ha5", "epicutis-arctigenin"],
    highlights: ["Age-appropriate results", "Family-friendly scheduling", "Plastic surgeon-led"],
  },
  {
    slug: "bal-harbour-skin-clinic",
    name: "Bal Harbour Skin Clinic",
    providerType: "dermatology-aesthetics",
    neighborhood: "Bal Harbour",
    city: "Bal Harbour",
    tagline: "Ultra-luxury. Ultra-discreet.",
    description: "Exclusive med spa at Bal Harbour Shops. Discretion and white-glove service for high-profile clients.",
    rating: 4.9,
    reviewCount: 89,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Victoria Ashford, MD",
    licenseId: "ME-94567",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    priceRange: "$$$$",
    instagram: "balharbour_skin",
    productSlugs: ["skinceuticals-discoloration-defense", "epicutis-arctigenin", "revision-retinol", "la-roche-posay-anthelios"],
    highlights: ["Private entrance", "VIP scheduling", "Concierge service"],
  },
  {
    slug: "key-biscayne-med-spa",
    name: "Key Biscayne Med Spa",
    providerType: "med-spa",
    neighborhood: "Key Biscayne",
    city: "Key Biscayne",
    tagline: "Island luxury aesthetics.",
    description: "Boutique island med spa serving Key Biscayne residents. Intimate setting with personalized care.",
    rating: 4.8,
    reviewCount: 112,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Robert Ellis, MD",
    licenseId: "ME-87890",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial"],
    priceRange: "$$$$",
    instagram: "keybiscayne_medspa",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["Island location", "Personalized care", "Member loyalty program"],
  },
  {
    slug: "south-miami-aesthetics",
    name: "South Miami Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "South Miami",
    city: "Miami",
    tagline: "Your neighborhood med spa.",
    description: "Community-focused med spa on US-1 in South Miami. Trusted by locals for over a decade.",
    rating: 4.6,
    reviewCount: 445,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Karen Mitchell, MD",
    licenseId: "ME-82345",
    yearsOpen: 13,
    treatments: ["botox", "fillers", "laser", "facial", "body-contouring"],
    priceRange: "$$",
    instagram: "southmiami_aesthetics",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["Established reputation", "Flexible payment plans", "Loyalty rewards"],
  },
  {
    slug: "kendall-rejuvenation",
    name: "Kendall Rejuvenation Center",
    providerType: "med-spa",
    neighborhood: "Kendall",
    city: "Miami",
    tagline: "Results you can trust.",
    description: "High-volume med spa in Kendall offering accessible pricing on Botox, fillers, and laser treatments.",
    rating: 4.4,
    reviewCount: 678,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Carlos Mendez, MD",
    licenseId: "ME-85678",
    yearsOpen: 9,
    treatments: ["botox", "fillers", "laser", "microneedling", "body-contouring"],
    priceRange: "$$",
    instagram: "kendall_rejuvenation",
    productSlugs: ["eltamd-uv-clear", "skinmedica-ha5"],
    highlights: ["Accessible pricing", "High patient volume", "Extended weekend hours"],
  },
  {
    slug: "edgewater-laser-skin",
    name: "Edgewater Laser & Skin",
    providerType: "dermatology-aesthetics",
    neighborhood: "Edgewater",
    city: "Miami",
    tagline: "Laser experts on the bay.",
    description: "Laser-focused med spa in Edgewater with bay views. Specialists in pigmentation, scars, and skin tightening.",
    rating: 4.7,
    reviewCount: 234,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Amy Chang, MD",
    licenseId: "ME-89012",
    yearsOpen: 5,
    treatments: ["laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "edgewater_laser_skin",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Laser specialists", "Bay views", "Free skin analysis"],
  },
  {
    slug: "midtown-miami-medspa",
    name: "Midtown Med Spa",
    providerType: "med-spa",
    neighborhood: "Midtown",
    city: "Miami",
    tagline: "Urban beauty, clinical precision.",
    description: "Trendy Midtown location popular with young professionals. Strong on preventive Botox and lip fillers.",
    rating: 4.5,
    reviewCount: 312,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Nicole Park, MD",
    licenseId: "ME-86789",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial"],
    priceRange: "$$$",
    instagram: "midtown_medspa_mia",
    productSlugs: ["revision-retinol", "eltamd-uv-clear"],
    highlights: ["Preventive Botox", "After-work hours", "Social media savvy team"],
  },
  {
    slug: "sunny-isles-aesthetics",
    name: "Sunny Isles Aesthetics",
    providerType: "med-spa",
    neighborhood: "Sunny Isles",
    city: "Sunny Isles Beach",
    tagline: "International standards, local care.",
    description: "Multilingual med spa serving Sunny Isles and Aventura's international community. Full aesthetics menu.",
    rating: 4.6,
    reviewCount: 289,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Ivan Petrov, MD",
    licenseId: "ME-90456",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "body-contouring", "facial"],
    priceRange: "$$$",
    instagram: "sunnyisles_aesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "skinmedica-ha5"],
    highlights: ["Multilingual staff", "International clientele", "Body contouring specialists"],
  },
  {
    slug: "north-miami-beauty-lab",
    name: "North Miami Beauty Lab",
    providerType: "aesthetics-clinic",
    neighborhood: "North Miami",
    city: "North Miami",
    tagline: "Innovation meets aesthetics.",
    description: "Tech-forward med spa in North Miami offering the latest in injectables and skin rejuvenation.",
    rating: 4.5,
    reviewCount: 198,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jasmine Brooks, MD",
    licenseId: "ME-88123",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "microneedling", "facial"],
    priceRange: "$$",
    instagram: "northmiami_beautylab",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing", "isdin-eryfotona-actinica"],
    highlights: ["Latest technology", "New patient specials", "Online booking"],
  },
  {
    slug: "coral-way-skin-studio",
    name: "Coral Way Skin Studio",
    providerType: "aesthetics-clinic",
    neighborhood: "Coral Way",
    city: "Miami",
    tagline: "Classic Miami beauty.",
    description: "Established med spa on Coral Way serving central Miami. Known for excellent facials and injectables.",
    rating: 4.7,
    reviewCount: 356,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Maria Santos, MD",
    licenseId: "ME-84567",
    yearsOpen: 10,
    treatments: ["facial", "botox", "fillers", "microneedling"],
    priceRange: "$$",
    instagram: "coralway_skin",
    productSlugs: ["is-clinical-cleansing", "epicutis-arctigenin", "eltamd-uv-clear"],
    highlights: ["Award-winning facials", "Central location", "Established 2014"],
  },
  {
    slug: "homestead-wellness-medspa",
    name: "Homestead Wellness Med Spa",
    providerType: "med-spa",
    neighborhood: "Homestead",
    city: "Homestead",
    tagline: "South Dade's med spa.",
    description: "Serving South Miami-Dade with accessible med spa services. Botox, fillers, and laser hair removal.",
    rating: 4.4,
    reviewCount: 167,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jorge Rivera, MD",
    licenseId: "ME-91200",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser"],
    priceRange: "$",
    instagram: "homestead_wellness",
    productSlugs: ["eltamd-uv-clear"],
    highlights: ["South Dade location", "Affordable pricing", "Laser hair removal"],
  },
  {
    slug: "cutler-bay-aesthetics",
    name: "Cutler Bay Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Cutler Bay",
    city: "Cutler Bay",
    tagline: "Quality care, south of the city.",
    description: "Full-service med spa in Cutler Bay. Popular with families and professionals in South Miami-Dade.",
    rating: 4.5,
    reviewCount: 223,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Angela Torres, NP (MSN)",
    licenseId: "ME-89876",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "body-contouring"],
    priceRange: "$$",
    instagram: "cutlerbay_aesthetics",
    productSlugs: ["is-clinical-cleansing", "skinmedica-ha5"],
    highlights: ["Family-friendly", "Free consultations", "Body contouring"],
  },
  {
    slug: "miami-shores-aesthetics",
    name: "Miami Shores Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Miami Shores",
    city: "Miami Shores",
    tagline: "Quiet luxury, north of downtown.",
    description: "Intimate med spa in Miami Shores village. Personalized attention in a relaxed neighborhood setting.",
    rating: 4.8,
    reviewCount: 134,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Helen Price, MD",
    licenseId: "ME-87321",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "miamishores_aesthetics",
    productSlugs: ["epicutis-arctigenin", "revision-retinol"],
    highlights: ["Village setting", "Small-batch attention", "Referral-only reputation"],
  },
  {
    slug: "fisher-island-aesthetics",
    name: "Fisher Island Aesthetics",
    providerType: "dermatology-aesthetics",
    neighborhood: "Fisher Island",
    city: "Miami Beach",
    tagline: "Exclusive island treatments.",
    description: "Private med spa on Fisher Island serving residents and members. By-appointment only.",
    rating: 4.9,
    reviewCount: 67,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Charles Whitmore, MD",
    licenseId: "ME-95678",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$$$",
    instagram: "fisherisland_aesthetics",
    productSlugs: ["skinceuticals-discoloration-defense", "epicutis-arctigenin", "revision-retinol", "la-roche-posay-anthelios"],
    highlights: ["Members only", "Island location", "House calls available"],
  },
  {
    slug: "brickell-skin-haus",
    name: "Brickell Skin Haus",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    tagline: "Clinical facials. Downtown convenience.",
    description: "Full-service med spa in the heart of Brickell with express lunch-hour treatments and evening appointments for finance professionals.",
    rating: 4.6,
    reviewCount: 278,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Nina Patel, MD",
    licenseId: "ME-90112",
    yearsOpen: 5,
    treatments: ["facial", "microneedling", "botox", "laser"],
    priceRange: "$$$",
    instagram: "brickellskinhaus",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear", "la-roche-posay-toleriane-hydrating"],
    highlights: ["Evening appointments", "Express facials", "Product menus online"],
  },
  {
    slug: "elev8-aesthetics-brickell",
    name: "Elev8 Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Brickell",
    city: "Miami",
    tagline: "Elevated injectables. Evidence-based care.",
    description: "Physician-led injectables clinic focused on subtle rejuvenation and preventative aesthetics for Brickell residents.",
    rating: 4.8,
    reviewCount: 193,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Omar Hassan, MD",
    licenseId: "ME-91456",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "microneedling"],
    priceRange: "$$$",
    instagram: "elev8_aesthetics_mia",
    productSlugs: ["skinceuticals-discoloration-defense", "revision-retinol", "la-roche-posay-anthelios"],
    highlights: ["Physician injectors only", "Preventative plans", "Digital intake"],
  },
  {
    slug: "gables-radiance-medspa",
    name: "Gables Radiance Medspa",
    providerType: "med-spa",
    neighborhood: "Coral Gables",
    city: "Miami",
    tagline: "Mediterranean-inspired skin wellness.",
    description: "Elegant Coral Gables med spa blending European facial techniques with Miami sun-care protocols.",
    rating: 4.7,
    reviewCount: 221,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Lucia Fernandez, MD",
    licenseId: "ME-88734",
    yearsOpen: 7,
    treatments: ["facial", "laser", "botox", "fillers"],
    priceRange: "$$$",
    instagram: "gablesradiance",
    productSlugs: ["skinceuticals-discoloration-defense", "la-roche-posay-anthelios", "isdin-essential-cleansing"],
    highlights: ["European protocols", "Sun-damage specialists", "Private treatment rooms"],
  },
  {
    slug: "zenith-aesthetics-coral-gables",
    name: "Zenith Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Coral Gables",
    city: "Miami",
    tagline: "Precision injectables. Quiet luxury.",
    description: "Boutique injectables studio on Miracle Mile known for conservative, age-appropriate results.",
    rating: 4.9,
    reviewCount: 164,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Patricia Nguyen, MD",
    licenseId: "ME-89901",
    yearsOpen: 6,
    treatments: ["botox", "fillers"],
    priceRange: "$$$$",
    instagram: "zenith_aesthetics_gables",
    productSlugs: ["epicutis-arctigenin", "skinmedica-ha5"],
    highlights: ["Consultation-first approach", "Miracle Mile location", "Published pricing"],
  },
  {
    slug: "verde-medspa-coral-gables",
    name: "Verde Medspa",
    providerType: "dermatology-aesthetics",
    neighborhood: "Coral Gables",
    city: "Miami",
    tagline: "Dermatology-backed aesthetics.",
    description: "Dermatology practice with dedicated aesthetics wing offering lasers, peels, and medical-grade facials.",
    rating: 4.8,
    reviewCount: 312,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Robert Stein, MD, FAAD",
    licenseId: "ME-86543",
    yearsOpen: 12,
    treatments: ["laser", "facial", "botox", "microneedling"],
    priceRange: "$$$",
    instagram: "verde_medspa_gables",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-ce-ferulic", "isdin-eryfotona-actinica"],
    highlights: ["Board-certified dermatology", "Laser suite on-site", "Insurance-friendly consults"],
  },
  {
    slug: "atelier-aesthetics-design-district",
    name: "Atelier Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Design District",
    city: "Miami",
    tagline: "Gallery-grade beauty science.",
    description: "Design District aesthetics studio with art-forward interiors and bespoke treatment protocols for discerning clients.",
    rating: 4.8,
    reviewCount: 142,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Amelie Dubois, MD",
    licenseId: "ME-90876",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser"],
    priceRange: "$$$$",
    instagram: "atelier_aesthetics_dd",
    productSlugs: ["isdin-essential-cleansing", "la-roche-posay-toleriane-hydrating", "alastin-restorative-skin-complex"],
    highlights: ["Design District flagship", "Custom facial cocktails", "VIP consultation lounge"],
  },
  {
    slug: "regime-skin-lab-design-district",
    name: "Regime Skin Lab",
    providerType: "med-spa",
    neighborhood: "Design District",
    city: "Miami",
    tagline: "Protocol-driven skin transformation.",
    description: "Results-focused skin lab offering structured treatment series with progress photography and product pairing.",
    rating: 4.7,
    reviewCount: 189,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Kevin Walsh, MD",
    licenseId: "ME-91234",
    yearsOpen: 4,
    treatments: ["microneedling", "laser", "facial", "body-contouring"],
    priceRange: "$$$",
    instagram: "regime_skinlab",
    productSlugs: ["revision-retinol", "is-clinical-cleansing", "skinmedica-ha5"],
    highlights: ["Treatment series tracking", "Progress photos", "Product pairing guides"],
  },
  {
    slug: "symetry-medspa-aventura",
    name: "Symetry Medspa",
    providerType: "med-spa",
    neighborhood: "Aventura",
    city: "Aventura",
    tagline: "Balanced beauty. Symmetrical results.",
    description: "Aventura med spa specializing in facial balancing, body contouring, and postpartum aesthetic recovery.",
    rating: 4.6,
    reviewCount: 267,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Sandra Ortiz, MD",
    licenseId: "ME-87654",
    yearsOpen: 8,
    treatments: ["body-contouring", "botox", "fillers", "laser"],
    priceRange: "$$$",
    instagram: "symetry_medspa",
    productSlugs: ["skinmedica-ha5", "eltamd-uv-clear"],
    highlights: ["Body contouring focus", "Postpartum packages", "Aventura Mall nearby"],
  },
  {
    slug: "pulse-aesthetics-aventura",
    name: "Pulse Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Aventura",
    city: "Aventura",
    tagline: "Energy-based skin renewal.",
    description: "Laser-forward aesthetics clinic with multiple device platforms for tone, texture, and tightening.",
    rating: 4.8,
    reviewCount: 198,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Michael Brooks, MD",
    licenseId: "ME-89012",
    yearsOpen: 6,
    treatments: ["laser", "microneedling", "botox"],
    priceRange: "$$$",
    instagram: "pulse_aesthetics_aventura",
    productSlugs: ["skinceuticals-ce-ferulic", "la-roche-posay-anthelios"],
    highlights: ["Multi-platform lasers", "Device specialists", "Free laser consults"],
  },
  {
    slug: "luna-dermatology-aventura",
    name: "Luna Dermatology Aesthetics",
    providerType: "dermatology-aesthetics",
    neighborhood: "Aventura",
    city: "Aventura",
    tagline: "Moonlit glow. Medical precision.",
    description: "Dermatology aesthetics practice offering medical-grade peels, injectables, and rosacea-focused laser protocols.",
    rating: 4.9,
    reviewCount: 245,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Diana Cho, MD, FAAD",
    licenseId: "ME-85432",
    yearsOpen: 10,
    treatments: ["laser", "botox", "fillers", "facial"],
    priceRange: "$$$",
    instagram: "luna_derm_aventura",
    productSlugs: ["isdin-eryfotona-actinica", "eltamd-uv-clear", "isdin-micellar-solution"],
    highlights: ["Rosacea specialists", "Medical peels", "FAAD dermatologists"],
  },
  {
    slug: "oceanview-aesthetics-miami-beach",
    name: "Oceanview Aesthetics",
    providerType: "med-spa",
    neighborhood: "Miami Beach",
    city: "Miami Beach",
    tagline: "Beach-ready skin year-round.",
    description: "Mid-Beach med spa helping clients maintain glow between vacations with sun repair and maintenance injectables.",
    rating: 4.5,
    reviewCount: 356,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Carla Mendez, NP (MSN)",
    licenseId: "ME-86789",
    yearsOpen: 9,
    treatments: ["botox", "facial", "laser", "fillers"],
    priceRange: "$$",
    instagram: "oceanview_aesthetics",
    productSlugs: ["isdin-eryfotona-actinica", "la-roche-posay-toleriane-hydrating", "skinmedica-dermal-repair-cream"],
    highlights: ["Sun repair focus", "Walk-ins welcome", "K-beauty facials"],
  },
  {
    slug: "collins-aesthetics-miami-beach",
    name: "Collins Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Miami Beach",
    city: "Miami Beach",
    tagline: "Collins Avenue confidence.",
    description: "Upscale injectables and laser studio on Collins Ave serving hotel guests and Miami Beach locals.",
    rating: 4.7,
    reviewCount: 289,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Steven Park, MD",
    licenseId: "ME-88123",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser"],
    priceRange: "$$$",
    instagram: "collins_aesthetics_mb",
    productSlugs: ["skinceuticals-discoloration-defense", "revision-retinol", "la-roche-posay-anthelios"],
    highlights: ["Collins Ave location", "Hotel concierge referrals", "Same-week appointments"],
  },
  {
    slug: "wynwood-skin-collective",
    name: "Wynwood Skin Collective",
    providerType: "med-spa",
    neighborhood: "Wynwood",
    city: "Miami",
    tagline: "Creative skin. Bold results.",
    description: "Art-district med spa with industrial-chic treatment rooms and a focus on glow-forward facials and subtle injectables.",
    rating: 4.6,
    reviewCount: 234,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jade Rivera, MD",
    licenseId: "ME-90567",
    yearsOpen: 4,
    treatments: ["facial", "microneedling", "botox", "fillers"],
    priceRange: "$$",
    instagram: "wynwoodskincollective",
    productSlugs: ["alastin-regenerating-skin-nectar", "skinmedica-dermal-repair-cream", "is-clinical-cleansing"],
    highlights: ["Wynwood Walls nearby", "Event-ready packages", "Instagram-friendly space"],
  },
  {
    slug: "canvas-aesthetics-wynwood",
    name: "Canvas Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Wynwood",
    city: "Miami",
    tagline: "Your face, refined — not remade.",
    description: "Injectables studio emphasizing facial harmony and conservative filler work for Wynwood's creative community.",
    rating: 4.8,
    reviewCount: 176,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Tyler Brooks, MD",
    licenseId: "ME-91890",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "body-contouring"],
    priceRange: "$$$",
    instagram: "canvas_aesthetics_wyn",
    productSlugs: ["epicutis-arctigenin", "eltamd-uv-clear"],
    highlights: ["Conservative filler ethos", "Creative clientele", "Transparent aftercare"],
  },
  {
    slug: "south-beach-laser-bar",
    name: "South Beach Laser Bar",
    providerType: "med-spa",
    neighborhood: "South Beach",
    city: "Miami Beach",
    tagline: "Laser hair. Clear skin. Fast.",
    description: "Laser-focused med spa on South Beach offering hair removal, IPL, and acne laser series with quick turnaround.",
    rating: 4.4,
    reviewCount: 445,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Lisa Tran, MD",
    licenseId: "ME-87345",
    yearsOpen: 8,
    treatments: ["laser", "facial", "microneedling"],
    priceRange: "$$",
    instagram: "sb_laserbar",
    productSlugs: ["la-roche-posay-anthelios", "isdin-eryfotona-actinica"],
    highlights: ["Laser specialists", "Package pricing", "Walk-in consults"],
  },
  {
    slug: "grove-serenity-medspa",
    name: "Grove Serenity Medspa",
    providerType: "med-spa",
    neighborhood: "Coconut Grove",
    city: "Miami",
    tagline: "Wellness-forward aesthetics.",
    description: "Coconut Grove retreat blending IV wellness, facials, and gentle injectables in a calm, tree-lined setting.",
    rating: 4.7,
    reviewCount: 198,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Helen Morris, MD",
    licenseId: "ME-89678",
    yearsOpen: 6,
    treatments: ["facial", "botox", "body-contouring", "microneedling"],
    priceRange: "$$$",
    instagram: "grove_serenity_spa",
    productSlugs: ["la-roche-posay-toleriane-hydrating", "skinmedica-tns-advanced-serum", "isdin-micellar-solution"],
    highlights: ["Wellness integration", "Grove village location", "Calm environment"],
  },
  {
    slug: "doral-laser-institute",
    name: "Doral Laser Institute",
    providerType: "dermatology-aesthetics",
    neighborhood: "Doral",
    city: "Doral",
    tagline: "Advanced lasers. Accessible pricing.",
    description: "Laser-centric dermatology aesthetics center serving west Miami-Dade with hair removal, pigment, and scar protocols.",
    rating: 4.6,
    reviewCount: 378,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Ricardo Silva, MD, FAAD",
    licenseId: "ME-84201",
    yearsOpen: 11,
    treatments: ["laser", "microneedling", "botox", "fillers"],
    priceRange: "$$",
    instagram: "doral_laser_institute",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-ce-ferulic"],
    highlights: ["Laser institute", "West Dade hub", "Spanish/English staff"],
  },
  {
    slug: "pinecrest-glow-studio",
    name: "Pinecrest Glow Studio",
    providerType: "aesthetics-clinic",
    neighborhood: "Pinecrest",
    city: "Miami",
    tagline: "Suburban luxury. Subtle results.",
    description: "Family-friendly aesthetics studio in Pinecrest offering mommy makeover consults and maintenance injectables.",
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Angela Wright, MD",
    licenseId: "ME-88765",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "body-contouring"],
    priceRange: "$$$",
    instagram: "pinecrest_glow",
    productSlugs: ["skinmedica-ha5", "revision-retinol", "la-roche-posay-toleriane-hydrating"],
    highlights: ["Pinecrest community", "Mommy makeover consults", "Flexible scheduling"],
  },
  {
    slug: "bal-harbour-luxury-medspa",
    name: "Bal Harbour Luxury Medspa",
    providerType: "med-spa",
    neighborhood: "Bal Harbour",
    city: "Bal Harbour",
    tagline: "Resort-level aesthetics.",
    description: "Ultra-luxury med spa at Bal Harbour Shops offering concierge booking and premium product lines.",
    rating: 4.9,
    reviewCount: 134,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Victoria Lang, MD",
    licenseId: "ME-92345",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$$$",
    instagram: "balharbour_luxury_spa",
    productSlugs: ["alastin-restorative-skin-complex", "isdin-essential-cleansing", "epicutis-arctigenin"],
    highlights: ["Bal Harbour Shops", "Concierge service", "Premium product lines"],
  },
  {
    slug: "key-biscayne-skin-clinic",
    name: "Key Biscayne Skin Clinic",
    providerType: "dermatology-aesthetics",
    neighborhood: "Key Biscayne",
    city: "Key Biscayne",
    tagline: "Island skin specialists.",
    description: "Dermatology aesthetics clinic serving Key Biscayne with sun damage repair and maintenance injectables.",
    rating: 4.8,
    reviewCount: 167,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. George Tanaka, MD, FAAD",
    licenseId: "ME-87123",
    yearsOpen: 9,
    treatments: ["laser", "botox", "facial", "fillers"],
    priceRange: "$$$",
    instagram: "kb_skin_clinic",
    productSlugs: ["la-roche-posay-anthelios", "eltamd-uv-clear", "skinceuticals-discoloration-defense"],
    highlights: ["Island clientele", "Sun damage repair", "Pediatric derm consults"],
  },
  {
    slug: "south-miami-derm-aesthetics",
    name: "South Miami Derm Aesthetics",
    providerType: "dermatology-aesthetics",
    neighborhood: "South Miami",
    city: "South Miami",
    tagline: "Clinical care. Beautiful outcomes.",
    description: "South Miami dermatology practice with full aesthetics menu including Mohs-adjacent scar revision and lasers.",
    rating: 4.7,
    reviewCount: 289,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Maria Gonzalez, MD, FAAD",
    licenseId: "ME-85678",
    yearsOpen: 14,
    treatments: ["laser", "botox", "fillers", "microneedling"],
    priceRange: "$$$",
    instagram: "southmiami_derm_aesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "isdin-eryfotona-actinica", "isdin-micellar-solution"],
    highlights: ["14 years in South Miami", "Scar revision", "Insurance dermatology"],
  },
  {
    slug: "kendall-aesthetics-hub",
    name: "Kendall Aesthetics Hub",
    providerType: "med-spa",
    neighborhood: "Kendall",
    city: "Miami",
    tagline: "South Kendall's med spa home.",
    description: "Accessible med spa in Kendall offering injectables, CoolSculpting, and medical-grade facials for busy families.",
    rating: 4.5,
    reviewCount: 412,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Luis Ramirez, MD",
    licenseId: "ME-88901",
    yearsOpen: 6,
    treatments: ["body-contouring", "botox", "facial", "fillers"],
    priceRange: "$$",
    instagram: "kendall_aesthetics_hub",
    productSlugs: ["skinmedica-dermal-repair-cream", "la-roche-posay-toleriane-hydrating", "eltamd-uv-clear"],
    highlights: ["Family-friendly pricing", "Body contouring", "Extended hours"],
  },
  {
    slug: "edgewater-glow-medspa",
    name: "Edgewater Glow Medspa",
    providerType: "med-spa",
    neighborhood: "Edgewater",
    city: "Miami",
    tagline: "Bayfront beauty. Urban ease.",
    description: "Edgewater waterfront med spa with bay views, popular for pre-event facials and maintenance Botox.",
    rating: 4.6,
    reviewCount: 203,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Emily Frost, MD",
    licenseId: "ME-90234",
    yearsOpen: 4,
    treatments: ["facial", "botox", "microneedling", "laser"],
    priceRange: "$$$",
    instagram: "edgewater_glow",
    productSlugs: ["is-clinical-cleansing", "alastin-regenerating-skin-nectar", "isdin-eryfotona-actinica"],
    highlights: ["Bayfront views", "Pre-event facials", "Edgewater location"],
  },
  {
    slug: "midtown-injectables-lounge",
    name: "Midtown Injectables Lounge",
    providerType: "aesthetics-clinic",
    neighborhood: "Midtown",
    city: "Miami",
    tagline: "Quick consults. Natural results.",
    description: "Midtown injectables lounge with walk-in Botox hours and a menu of lip, jawline, and under-eye treatments.",
    rating: 4.7,
    reviewCount: 318,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jason Lee, MD",
    licenseId: "ME-91567",
    yearsOpen: 5,
    treatments: ["botox", "fillers"],
    priceRange: "$$$",
    instagram: "midtown_injectables",
    productSlugs: ["eltamd-uv-clear", "revision-retinol"],
    highlights: ["Walk-in Botox hours", "Midtown Miami", "Lip specialist team"],
  },
  {
    slug: "sunny-isles-beauty-clinic",
    name: "Sunny Isles Beauty Clinic",
    providerType: "aesthetics-clinic",
    neighborhood: "Sunny Isles",
    city: "Sunny Isles Beach",
    tagline: "International standards. Local care.",
    description: "Multilingual aesthetics clinic in Sunny Isles serving a diverse clientele with injectables and laser hair removal.",
    rating: 4.6,
    reviewCount: 276,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Irina Volkov, MD",
    licenseId: "ME-87890",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "body-contouring"],
    priceRange: "$$",
    instagram: "sunnyisles_beauty",
    productSlugs: ["skinmedica-ha5", "la-roche-posay-anthelios"],
    highlights: ["Multilingual staff", "Laser hair removal", "Collins Ave access"],
  },
  {
    slug: "north-miami-med-aesthetics",
    name: "North Miami Med Aesthetics",
    providerType: "med-spa",
    neighborhood: "North Miami",
    city: "North Miami",
    tagline: "Quality aesthetics. Honest pricing.",
    description: "Community med spa in North Miami offering accessible injectables, facials, and body treatments without upselling.",
    rating: 4.4,
    reviewCount: 345,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Carmen Delgado, NP (MSN)",
    licenseId: "ME-86321",
    yearsOpen: 8,
    treatments: ["botox", "facial", "body-contouring", "microneedling"],
    priceRange: "$$",
    instagram: "northmiami_med_aesthetics",
    productSlugs: ["skinmedica-dermal-repair-cream", "eltamd-uv-clear", "is-clinical-cleansing"],
    highlights: ["No upselling policy", "Community pricing", "Extended weekend hours"],
  },
];

export const spas: Spa[] = [
  ...spaSeeds,
  ...floridaRealSpas,
  ...floridaCoastalRealSpas,
  ...tampaBayRealSpas,
  ...miamiMetroRealSpas,
  ...floridaSpaSeeds,
  ...additionalFloridaSpaSeeds,
  ...nationwideRealSpas,
].map((seed, i) => seedSpa(seed, i));

export const metros = Object.keys(METRO_LABELS) as Metro[];

export const neighborhoods = getAreasByCity(spas, "All", "All");

export function getNeighborhoodsByMetro(metro: Metro | "All") {
  return getAreasByCity(spas, metro, "All");
}

export const reviews: Review[] = [
  {
    id: "r1",
    author: "Camila R.",
    rating: 5,
    text: "They emailed me every product before my facial — zero surprises. Exactly the transparency I wanted.",
    date: "2026-05-12",
    verified: true,
    treatment: "Luxury Facial",
    productSlug: "epicutis-arctigenin",
  },
  {
    id: "r2",
    author: "Jennifer L.",
    rating: 5,
    text: "Finally a platform where I could see which SPF my spa actually uses. EltaMD post-laser was perfect.",
    date: "2026-04-28",
    verified: true,
    treatment: "Laser Resurfacing",
    productSlug: "eltamd-uv-clear",
  },
  {
    id: "r3",
    author: "Alex M.",
    rating: 4,
    text: "Loved the natural lip filler at Forme. Spa confirmed my booking within 2 hours.",
    date: "2026-03-15",
    verified: true,
    treatment: "Lip Filler",
  },
  {
    id: "r4",
    author: "Diana K.",
    rating: 5,
    text: "The trust score on Epicutis helped me compare spas. Salt & Glow was the perfect match.",
    date: "2026-05-01",
    verified: true,
    productSlug: "epicutis-arctigenin",
  },
  {
    id: "r5",
    author: "Marcus T.",
    rating: 5,
    text: "Used Verity Premium for priority booking at Bal Harbour Skin Clinic. Worth every penny.",
    date: "2026-05-20",
    verified: true,
    treatment: "Botox",
  },
];

export function getSpa(slug: string) {
  return spas.find((s) => s.slug === slug);
}

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getSpaReviews(spaSlug: string) {
  const spa = getSpa(spaSlug);
  if (!spa) return [];
  const productSet = new Set(spa.productSlugs);
  return reviews.filter(
    (r) => r.treatment || (r.productSlug && productSet.has(r.productSlug))
  );
}

export function getProductReviews(productSlug: string) {
  return reviews.filter((r) => r.productSlug === productSlug);
}

export function getSpasForProduct(productSlug: string) {
  return spas.filter((s) => s.productSlugs.includes(productSlug));
}

export function getProductsForSpa(spaSlug: string) {
  const spa = getSpa(spaSlug);
  if (!spa) return [];
  return products.filter((p) => spa.productSlugs.includes(p.slug));
}

export function getSpasByNeighborhood(neighborhood: string) {
  if (!neighborhood || neighborhood === "All") return spas;
  return spas.filter((s) => s.neighborhood === neighborhood);
}

export function getSortedSpas() {
  return sortSpasForDisplay(spas);
}

export function getFeaturedPremiumSpasFromData(limit = 8) {
  return getTopRatedSpas(spas, limit);
}
