import type { Metro, ProviderType, Treatment } from "./types";

export type FloridaSpaSeed = {
  slug: string;
  name: string;
  providerType: ProviderType;
  neighborhood: string;
  city: string;
  metro: Metro;
  tagline: string;
  description: string;
  rating: number;
  reviewCount: number;
  verified: boolean;
  premierPartner: boolean;
  medicalDirector: string;
  licenseId: string;
  yearsOpen: number;
  treatments: Treatment[];
  priceRange: "$" | "$$" | "$$$" | "$$$$";
  instagram: string;
  productSlugs: string[];
  highlights: string[];
  phone: string;
  website: string;
  /** Verified review source (e.g. Google Business Profile). */
  reviewSource?: string;
};

export const floridaSpaSeeds: FloridaSpaSeed[] = [
  {
    slug: "bay-shore-aesthetics-hyde-park",
    name: "Bay Shore Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Hyde Park",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Natural injectables. Transparent protocols.",
    description: "Board-supervised boutique med spa specializing in natural-looking injectables with full product disclosure before every appointment.",
    rating: 4.5,
    reviewCount: 170,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Sarah Mitchell, MD",
    licenseId: "ME-88050",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$",
    instagram: "bay_shore_aesthetics_hyd",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
    phone: "(813) 555-1050",
    website: "https://www.bay-shore-aesthetics-hyde-park.com",
  },
  {
    slug: "south-tampa-medspa",
    name: "South Tampa Medspa",
    providerType: "med-spa",
    neighborhood: "South Tampa",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Luxury laser. Expert recovery.",
    description: "High-end laser and skin rejuvenation with published provider credentials and patch testing available.",
    rating: 4.6,
    reviewCount: 188,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. James Patterson, MD",
    licenseId: "ME-88051",
    yearsOpen: 4,
    treatments: ["laser", "facial", "microneedling", "body-contouring"],
    priceRange: "$$$",
    instagram: "south_tampa_medspa",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
    phone: "(727) 555-1051",
    website: "https://www.south-tampa-medspa.com",
  },
  {
    slug: "westshore-laser-aesthetics",
    name: "Westshore Laser Aesthetics",
    providerType: "med-spa",
    neighborhood: "Westshore",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Coastal luxury skincare.",
    description: "Facial-forward med spa blending clinical treatments with premium skincare for first-time and returning clients.",
    rating: 4.7,
    reviewCount: 206,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Emily Nguyen, MD",
    licenseId: "ME-88052",
    yearsOpen: 5,
    treatments: ["facial", "microneedling", "botox"],
    priceRange: "$$$",
    instagram: "westshore_laser_aestheti",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Neighborhood location"],
    phone: "(813) 555-1052",
    website: "https://www.westshore-laser-aesthetics.com",
  },
  {
    slug: "st-pete-skin-institute",
    name: "St. Pete Skin Institute",
    providerType: "dermatology-aesthetics",
    neighborhood: "St. Petersburg",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Artistry meets accountability.",
    description: "Modern injectables studio with transparent pricing, digital consent, and published medical director credentials.",
    rating: 4.8,
    reviewCount: 224,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Robert Hayes, MD",
    licenseId: "ME-88053",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "body-contouring"],
    priceRange: "$$$$",
    instagram: "st_pete_skin_institute",
    productSlugs: ["skinceuticals-ce-ferulic"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
    phone: "(727) 555-1053",
    website: "https://www.st-pete-skin-institute.com",
  },
  {
    slug: "clearwater-glow-medspa",
    name: "Clearwater Glow Medspa",
    providerType: "med-spa",
    neighborhood: "Clearwater",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Where precision meets trust.",
    description: "Full-service aesthetics clinic with verified licenses, lot-tracked injectables, and neighborhood convenience.",
    rating: 4.9,
    reviewCount: 242,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Lisa Chen, NP (MSN)",
    licenseId: "ME-88054",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$",
    instagram: "clearwater_glow_medspa",
    productSlugs: ["revision-retinol", "skinmedica-ha5"],
    highlights: ["Same-day appointments", "Injectables specialists", "Transparent pricing"],
    phone: "(813) 555-1054",
    website: "https://www.clearwater-glow-medspa.com",
  },
  {
    slug: "hyde-park-injectables-lounge",
    name: "Hyde Park Injectables Lounge",
    providerType: "aesthetics-clinic",
    neighborhood: "Hyde Park",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Injectables-only excellence.",
    description: "Focused exclusively on Botox and fillers with board-certified injectors and same-day appointment availability.",
    rating: 4.5,
    reviewCount: 260,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Michael Torres, MD",
    licenseId: "ME-88055",
    yearsOpen: 8,
    treatments: ["botox", "fillers"],
    priceRange: "$$$",
    instagram: "hyde_park_injectables_lo",
    productSlugs: ["eltamd-uv-clear"],
    highlights: ["Medical director on file", "Florida DBPR licensed", "Verified reviews"],
    phone: "(727) 555-1055",
    website: "https://www.hyde-park-injectables-lounge.com",
  },
  {
    slug: "tampa-bay-derm-aesthetics",
    name: "Tampa Bay Derm Aesthetics",
    providerType: "dermatology-aesthetics",
    neighborhood: "South Tampa",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Results you can verify.",
    description: "Dermatology-backed aesthetics practice offering laser, facial, and injectable protocols with medical oversight.",
    rating: 4.6,
    reviewCount: 278,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Amanda Brooks, MD",
    licenseId: "ME-88056",
    yearsOpen: 9,
    treatments: ["laser", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "tampa_bay_derm_aesthetic",
    productSlugs: ["skinceuticals-ce-ferulic", "revision-retinol"],
    highlights: ["Bespoke treatment plans", "Private suites", "Premium skincare protocols"],
    phone: "(813) 555-1056",
    website: "https://www.tampa-bay-derm-aesthetics.com",
  },
  {
    slug: "channelside-aesthetics-clinic",
    name: "Channelside Aesthetics Clinic",
    providerType: "aesthetics-clinic",
    neighborhood: "Channelside",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Clinical care, boutique feel.",
    description: "Luxury med spa serving professionals with bespoke treatment plans and private suites.",
    rating: 4.7,
    reviewCount: 296,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. David Kim, MD",
    licenseId: "ME-88057",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "laser"],
    priceRange: "$$$$",
    instagram: "channelside_aesthetics_c",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["Dermatology oversight", "Clinical protocols", "Sensitive skin friendly"],
    phone: "(727) 555-1057",
    website: "https://www.channelside-aesthetics-clinic.com",
  },
  {
    slug: "seminole-heights-beauty-lab",
    name: "Seminole Heights Beauty Lab",
    providerType: "med-spa",
    neighborhood: "Seminole Heights",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Board-supervised aesthetics.",
    description: "Community-trusted aesthetics clinic known for no-pressure consultations and product lists before every visit.",
    rating: 4.8,
    reviewCount: 314,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Rachel Foster, MD",
    licenseId: "ME-88058",
    yearsOpen: 11,
    treatments: ["facial", "microneedling", "laser"],
    priceRange: "$$",
    instagram: "seminole_heights_beauty_",
    productSlugs: ["skinmedica-ha5", "eltamd-uv-clear"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
    phone: "(813) 555-1058",
    website: "https://www.seminole-heights-beauty-lab.com",
  },
  {
    slug: "carrollwood-med-aesthetics",
    name: "Carrollwood Med Aesthetics",
    providerType: "med-spa",
    neighborhood: "Carrollwood",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Transparent pricing, natural results.",
    description: "Results-driven med spa with verified visit reviews and comprehensive treatment menus.",
    rating: 4.9,
    reviewCount: 332,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Nicole Adams, NP (MSN)",
    licenseId: "ME-88059",
    yearsOpen: 12,
    treatments: ["body-contouring", "laser", "facial"],
    priceRange: "$$$",
    instagram: "carrollwood_med_aestheti",
    productSlugs: ["epicutis-arctigenin", "skinceuticals-ce-ferulic"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
    phone: "(727) 555-1059",
    website: "https://www.carrollwood-med-aesthetics.com",
  },
  {
    slug: "davis-islands-skin-studio",
    name: "Davis Islands Skin Studio",
    providerType: "aesthetics-clinic",
    neighborhood: "Davis Islands",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Advanced skin science.",
    description: "Premium skin lab combining clinical lasers, microneedling, and medical-grade facials under physician supervision.",
    rating: 4.5,
    reviewCount: 350,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Christopher Lee, MD",
    licenseId: "ME-88060",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial"],
    priceRange: "$$$",
    instagram: "davis_islands_skin_studi",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Neighborhood location"],
    phone: "(813) 555-1060",
    website: "https://www.davis-islands-skin-studio.com",
  },
  {
    slug: "ybor-aesthetics-collective",
    name: "Ybor Aesthetics Collective",
    providerType: "aesthetics-clinic",
    neighborhood: "Ybor City",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Your neighborhood med spa.",
    description: "Neighborhood beauty destination with transparent unit pricing and HIPAA-compliant practice standards.",
    rating: 4.6,
    reviewCount: 368,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jennifer Walsh, MD",
    licenseId: "ME-88061",
    yearsOpen: 4,
    treatments: ["laser", "body-contouring", "microneedling"],
    priceRange: "$$$$",
    instagram: "ybor_aesthetics_collecti",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
    phone: "(727) 555-1061",
    website: "https://www.ybor-aesthetics-collective.com",
  },
  {
    slug: "winter-park-aesthetics",
    name: "Winter Park Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Winter Park",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Natural injectables. Transparent protocols.",
    description: "Board-supervised boutique med spa specializing in natural-looking injectables with full product disclosure before every appointment.",
    rating: 4.5,
    reviewCount: 182,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Sarah Mitchell, MD",
    licenseId: "ME-88062",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$",
    instagram: "winter_park_aesthetics",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
    phone: "(407) 555-1062",
    website: "https://www.winter-park-aesthetics.com",
  },
  {
    slug: "dr-phillips-medspa",
    name: "Dr. Phillips Medspa",
    providerType: "med-spa",
    neighborhood: "Dr. Phillips",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Luxury laser. Expert recovery.",
    description: "High-end laser and skin rejuvenation with published provider credentials and patch testing available.",
    rating: 4.6,
    reviewCount: 200,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. James Patterson, MD",
    licenseId: "ME-88063",
    yearsOpen: 4,
    treatments: ["laser", "facial", "microneedling", "body-contouring"],
    priceRange: "$$$",
    instagram: "dr_phillips_medspa",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
    phone: "(321) 555-1063",
    website: "https://www.dr-phillips-medspa.com",
  },
  {
    slug: "lake-nona-skin-lab",
    name: "Lake Nona Skin Lab",
    providerType: "med-spa",
    neighborhood: "Lake Nona",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Coastal luxury skincare.",
    description: "Facial-forward med spa blending clinical treatments with premium skincare for first-time and returning clients.",
    rating: 4.7,
    reviewCount: 218,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Emily Nguyen, MD",
    licenseId: "ME-88064",
    yearsOpen: 5,
    treatments: ["facial", "microneedling", "botox"],
    priceRange: "$$$",
    instagram: "lake_nona_skin_lab",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Neighborhood location"],
    phone: "(407) 555-1064",
    website: "https://www.lake-nona-skin-lab.com",
  },
  {
    slug: "downtown-orlando-injectables",
    name: "Downtown Orlando Injectables",
    providerType: "aesthetics-clinic",
    neighborhood: "Downtown Orlando",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Artistry meets accountability.",
    description: "Modern injectables studio with transparent pricing, digital consent, and published medical director credentials.",
    rating: 4.8,
    reviewCount: 236,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Robert Hayes, MD",
    licenseId: "ME-88065",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "body-contouring"],
    priceRange: "$$$$",
    instagram: "downtown_orlando_injecta",
    productSlugs: ["skinceuticals-ce-ferulic"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
    phone: "(321) 555-1065",
    website: "https://www.downtown-orlando-injectables.com",
  },
  {
    slug: "baldwin-park-beauty-clinic",
    name: "Baldwin Park Beauty Clinic",
    providerType: "aesthetics-clinic",
    neighborhood: "Baldwin Park",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Where precision meets trust.",
    description: "Full-service aesthetics clinic with verified licenses, lot-tracked injectables, and neighborhood convenience.",
    rating: 4.9,
    reviewCount: 254,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Lisa Chen, NP (MSN)",
    licenseId: "ME-88066",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$",
    instagram: "baldwin_park_beauty_clin",
    productSlugs: ["revision-retinol", "skinmedica-ha5"],
    highlights: ["Same-day appointments", "Injectables specialists", "Transparent pricing"],
    phone: "(407) 555-1066",
    website: "https://www.baldwin-park-beauty-clinic.com",
  },
  {
    slug: "millenia-laser-aesthetics",
    name: "Millenia Laser Aesthetics",
    providerType: "med-spa",
    neighborhood: "Millenia",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Injectables-only excellence.",
    description: "Focused exclusively on Botox and fillers with board-certified injectors and same-day appointment availability.",
    rating: 4.5,
    reviewCount: 272,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Michael Torres, MD",
    licenseId: "ME-88067",
    yearsOpen: 8,
    treatments: ["botox", "fillers"],
    priceRange: "$$$",
    instagram: "millenia_laser_aesthetic",
    productSlugs: ["eltamd-uv-clear"],
    highlights: ["Medical director on file", "Florida DBPR licensed", "Verified reviews"],
    phone: "(321) 555-1067",
    website: "https://www.millenia-laser-aesthetics.com",
  },
  {
    slug: "thornton-park-med-spa",
    name: "Thornton Park Med Spa",
    providerType: "med-spa",
    neighborhood: "Thornton Park",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Results you can verify.",
    description: "Dermatology-backed aesthetics practice offering laser, facial, and injectable protocols with medical oversight.",
    rating: 4.6,
    reviewCount: 290,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Amanda Brooks, MD",
    licenseId: "ME-88068",
    yearsOpen: 9,
    treatments: ["laser", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "thornton_park_med_spa",
    productSlugs: ["skinceuticals-ce-ferulic", "revision-retinol"],
    highlights: ["Bespoke treatment plans", "Private suites", "Premium skincare protocols"],
    phone: "(407) 555-1068",
    website: "https://www.thornton-park-med-spa.com",
  },
  {
    slug: "windermere-aesthetics",
    name: "Windermere Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Windermere",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Clinical care, boutique feel.",
    description: "Luxury med spa serving professionals with bespoke treatment plans and private suites.",
    rating: 4.7,
    reviewCount: 308,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. David Kim, MD",
    licenseId: "ME-88069",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "laser"],
    priceRange: "$$$$",
    instagram: "windermere_aesthetics",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["Dermatology oversight", "Clinical protocols", "Sensitive skin friendly"],
    phone: "(321) 555-1069",
    website: "https://www.windermere-aesthetics.com",
  },
  {
    slug: "celebration-skin-studio",
    name: "Celebration Skin Studio",
    providerType: "med-spa",
    neighborhood: "Celebration",
    city: "Celebration",
    metro: "central-florida",
    tagline: "Board-supervised aesthetics.",
    description: "Community-trusted aesthetics clinic known for no-pressure consultations and product lists before every visit.",
    rating: 4.8,
    reviewCount: 326,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Rachel Foster, MD",
    licenseId: "ME-88070",
    yearsOpen: 11,
    treatments: ["facial", "microneedling", "laser"],
    priceRange: "$$",
    instagram: "celebration_skin_studio",
    productSlugs: ["skinmedica-ha5", "eltamd-uv-clear"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
    phone: "(407) 555-1070",
    website: "https://www.celebration-skin-studio.com",
  },
  {
    slug: "college-park-derm-aesthetics",
    name: "College Park Derm Aesthetics",
    providerType: "dermatology-aesthetics",
    neighborhood: "College Park",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Transparent pricing, natural results.",
    description: "Results-driven med spa with verified visit reviews and comprehensive treatment menus.",
    rating: 4.9,
    reviewCount: 344,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Nicole Adams, NP (MSN)",
    licenseId: "ME-88071",
    yearsOpen: 12,
    treatments: ["body-contouring", "laser", "facial"],
    priceRange: "$$$",
    instagram: "college_park_derm_aesthe",
    productSlugs: ["epicutis-arctigenin", "skinceuticals-ce-ferulic"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
    phone: "(321) 555-1071",
    website: "https://www.college-park-derm-aesthetics.com",
  },
  {
    slug: "altamonte-aesthetics-hub",
    name: "Altamonte Aesthetics Hub",
    providerType: "med-spa",
    neighborhood: "Altamonte Springs",
    city: "Altamonte Springs",
    metro: "central-florida",
    tagline: "Advanced skin science.",
    description: "Premium skin lab combining clinical lasers, microneedling, and medical-grade facials under physician supervision.",
    rating: 4.5,
    reviewCount: 362,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Christopher Lee, MD",
    licenseId: "ME-88072",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial"],
    priceRange: "$$$",
    instagram: "altamonte_aesthetics_hub",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Neighborhood location"],
    phone: "(407) 555-1072",
    website: "https://www.altamonte-aesthetics-hub.com",
  },
  {
    slug: "oviedo-glow-medspa",
    name: "Oviedo Glow Medspa",
    providerType: "med-spa",
    neighborhood: "Oviedo",
    city: "Oviedo",
    metro: "central-florida",
    tagline: "Your neighborhood med spa.",
    description: "Neighborhood beauty destination with transparent unit pricing and HIPAA-compliant practice standards.",
    rating: 4.6,
    reviewCount: 380,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jennifer Walsh, MD",
    licenseId: "ME-88073",
    yearsOpen: 4,
    treatments: ["laser", "body-contouring", "microneedling"],
    priceRange: "$$$$",
    instagram: "oviedo_glow_medspa",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
    phone: "(321) 555-1073",
    website: "https://www.oviedo-glow-medspa.com",
  },
  {
    slug: "san-marco-aesthetics",
    name: "San Marco Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "San Marco",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Natural injectables. Transparent protocols.",
    description: "Board-supervised boutique med spa specializing in natural-looking injectables with full product disclosure before every appointment.",
    rating: 4.5,
    reviewCount: 194,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Sarah Mitchell, MD",
    licenseId: "ME-88074",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$",
    instagram: "san_marco_aesthetics",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
    phone: "(904) 555-1074",
    website: "https://www.san-marco-aesthetics.com",
  },
  {
    slug: "riverside-injectables-lounge",
    name: "Riverside Injectables Lounge",
    providerType: "aesthetics-clinic",
    neighborhood: "Riverside",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Luxury laser. Expert recovery.",
    description: "High-end laser and skin rejuvenation with published provider credentials and patch testing available.",
    rating: 4.6,
    reviewCount: 212,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. James Patterson, MD",
    licenseId: "ME-88075",
    yearsOpen: 4,
    treatments: ["laser", "facial", "microneedling", "body-contouring"],
    priceRange: "$$$",
    instagram: "riverside_injectables_lo",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
    phone: "(904) 555-1075",
    website: "https://www.riverside-injectables-lounge.com",
  },
  {
    slug: "ponte-vedra-skin-institute",
    name: "Ponte Vedra Skin Institute",
    providerType: "dermatology-aesthetics",
    neighborhood: "Ponte Vedra",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Coastal luxury skincare.",
    description: "Facial-forward med spa blending clinical treatments with premium skincare for first-time and returning clients.",
    rating: 4.7,
    reviewCount: 230,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Emily Nguyen, MD",
    licenseId: "ME-88076",
    yearsOpen: 5,
    treatments: ["facial", "microneedling", "botox"],
    priceRange: "$$$",
    instagram: "ponte_vedra_skin_institu",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Neighborhood location"],
    phone: "(904) 555-1076",
    website: "https://www.ponte-vedra-skin-institute.com",
  },
  {
    slug: "jax-beach-medspa",
    name: "Jax Beach Medspa",
    providerType: "med-spa",
    neighborhood: "Jacksonville Beach",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Artistry meets accountability.",
    description: "Modern injectables studio with transparent pricing, digital consent, and published medical director credentials.",
    rating: 4.8,
    reviewCount: 248,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Robert Hayes, MD",
    licenseId: "ME-88077",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "body-contouring"],
    priceRange: "$$$$",
    instagram: "jax_beach_medspa",
    productSlugs: ["skinceuticals-ce-ferulic"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
    phone: "(904) 555-1077",
    website: "https://www.jax-beach-medspa.com",
  },
  {
    slug: "avondale-aesthetics-clinic",
    name: "Avondale Aesthetics Clinic",
    providerType: "aesthetics-clinic",
    neighborhood: "Avondale",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Where precision meets trust.",
    description: "Full-service aesthetics clinic with verified licenses, lot-tracked injectables, and neighborhood convenience.",
    rating: 4.9,
    reviewCount: 266,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Lisa Chen, NP (MSN)",
    licenseId: "ME-88078",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$",
    instagram: "avondale_aesthetics_clin",
    productSlugs: ["revision-retinol", "skinmedica-ha5"],
    highlights: ["Same-day appointments", "Injectables specialists", "Transparent pricing"],
    phone: "(904) 555-1078",
    website: "https://www.avondale-aesthetics-clinic.com",
  },
  {
    slug: "st-johns-town-center-beauty",
    name: "St. Johns Town Center Beauty",
    providerType: "med-spa",
    neighborhood: "St. Johns",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Injectables-only excellence.",
    description: "Focused exclusively on Botox and fillers with board-certified injectors and same-day appointment availability.",
    rating: 4.5,
    reviewCount: 284,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Michael Torres, MD",
    licenseId: "ME-88079",
    yearsOpen: 8,
    treatments: ["botox", "fillers"],
    priceRange: "$$$",
    instagram: "st_johns_town_center_bea",
    productSlugs: ["eltamd-uv-clear"],
    highlights: ["Medical director on file", "Florida DBPR licensed", "Verified reviews"],
    phone: "(904) 555-1079",
    website: "https://www.st-johns-town-center-beauty.com",
  },
  {
    slug: "mandarin-derm-aesthetics",
    name: "Mandarin Derm Aesthetics",
    providerType: "dermatology-aesthetics",
    neighborhood: "Mandarin",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Results you can verify.",
    description: "Dermatology-backed aesthetics practice offering laser, facial, and injectable protocols with medical oversight.",
    rating: 4.6,
    reviewCount: 302,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Amanda Brooks, MD",
    licenseId: "ME-88080",
    yearsOpen: 9,
    treatments: ["laser", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "mandarin_derm_aesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "revision-retinol"],
    highlights: ["Bespoke treatment plans", "Private suites", "Premium skincare protocols"],
    phone: "(904) 555-1080",
    website: "https://www.mandarin-derm-aesthetics.com",
  },
  {
    slug: "ortega-med-spa",
    name: "Ortega Med Spa",
    providerType: "med-spa",
    neighborhood: "Ortega",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Clinical care, boutique feel.",
    description: "Luxury med spa serving professionals with bespoke treatment plans and private suites.",
    rating: 4.7,
    reviewCount: 320,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. David Kim, MD",
    licenseId: "ME-88081",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "laser"],
    priceRange: "$$$$",
    instagram: "ortega_med_spa",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["Dermatology oversight", "Clinical protocols", "Sensitive skin friendly"],
    phone: "(904) 555-1081",
    website: "https://www.ortega-med-spa.com",
  },
  {
    slug: "atlantic-beach-glow",
    name: "Atlantic Beach Glow",
    providerType: "med-spa",
    neighborhood: "Atlantic Beach",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Board-supervised aesthetics.",
    description: "Community-trusted aesthetics clinic known for no-pressure consultations and product lists before every visit.",
    rating: 4.8,
    reviewCount: 338,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Rachel Foster, MD",
    licenseId: "ME-88082",
    yearsOpen: 11,
    treatments: ["facial", "microneedling", "laser"],
    priceRange: "$$",
    instagram: "atlantic_beach_glow",
    productSlugs: ["skinmedica-ha5", "eltamd-uv-clear"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
    phone: "(904) 555-1082",
    website: "https://www.atlantic-beach-glow.com",
  },
  {
    slug: "san-jose-aesthetics-hub",
    name: "San Jose Aesthetics Hub",
    providerType: "aesthetics-clinic",
    neighborhood: "San Jose",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Transparent pricing, natural results.",
    description: "Results-driven med spa with verified visit reviews and comprehensive treatment menus.",
    rating: 4.9,
    reviewCount: 356,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Nicole Adams, NP (MSN)",
    licenseId: "ME-88083",
    yearsOpen: 12,
    treatments: ["body-contouring", "laser", "facial"],
    priceRange: "$$$",
    instagram: "san_jose_aesthetics_hub",
    productSlugs: ["epicutis-arctigenin", "skinceuticals-ce-ferulic"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
    phone: "(904) 555-1083",
    website: "https://www.san-jose-aesthetics-hub.com",
  },
  {
    slug: "riverside-dermatology-aesthetics",
    name: "Riverside Dermatology Aesthetics",
    providerType: "dermatology-aesthetics",
    neighborhood: "Riverside",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Advanced skin science.",
    description: "Premium skin lab combining clinical lasers, microneedling, and medical-grade facials under physician supervision.",
    rating: 4.5,
    reviewCount: 374,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Christopher Lee, MD",
    licenseId: "ME-88084",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial"],
    priceRange: "$$$",
    instagram: "riverside_dermatology_ae",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Neighborhood location"],
    phone: "(904) 555-1084",
    website: "https://www.riverside-dermatology-aesthetics.com",
  },
  {
    slug: "nocatee-skin-lab",
    name: "Nocatee Skin Lab",
    providerType: "med-spa",
    neighborhood: "Nocatee",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Your neighborhood med spa.",
    description: "Neighborhood beauty destination with transparent unit pricing and HIPAA-compliant practice standards.",
    rating: 4.6,
    reviewCount: 392,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jennifer Walsh, MD",
    licenseId: "ME-88085",
    yearsOpen: 4,
    treatments: ["laser", "body-contouring", "microneedling"],
    priceRange: "$$$$",
    instagram: "nocatee_skin_lab",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
    phone: "(904) 555-1085",
    website: "https://www.nocatee-skin-lab.com",
  },
  {
    slug: "fifth-avenue-aesthetics-naples",
    name: "Fifth Avenue Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Fifth Avenue",
    city: "Naples",
    metro: "southwest-florida",
    tagline: "Natural injectables. Transparent protocols.",
    description: "Board-supervised boutique med spa specializing in natural-looking injectables with full product disclosure before every appointment.",
    rating: 4.5,
    reviewCount: 206,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Sarah Mitchell, MD",
    licenseId: "ME-88086",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$",
    instagram: "fifth_avenue_aesthetics_",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
    phone: "(239) 555-1086",
    website: "https://www.fifth-avenue-aesthetics-naples.com",
  },
  {
    slug: "north-naples-medspa",
    name: "North Naples Medspa",
    providerType: "med-spa",
    neighborhood: "North Naples",
    city: "Naples",
    metro: "southwest-florida",
    tagline: "Luxury laser. Expert recovery.",
    description: "High-end laser and skin rejuvenation with published provider credentials and patch testing available.",
    rating: 4.6,
    reviewCount: 224,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. James Patterson, MD",
    licenseId: "ME-88087",
    yearsOpen: 4,
    treatments: ["laser", "facial", "microneedling", "body-contouring"],
    priceRange: "$$$",
    instagram: "north_naples_medspa",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
    phone: "(239) 555-1087",
    website: "https://www.north-naples-medspa.com",
  },
  {
    slug: "bonita-springs-glow",
    name: "Bonita Springs Glow",
    providerType: "med-spa",
    neighborhood: "Bonita Springs",
    city: "Bonita Springs",
    metro: "southwest-florida",
    tagline: "Coastal luxury skincare.",
    description: "Facial-forward med spa blending clinical treatments with premium skincare for first-time and returning clients.",
    rating: 4.7,
    reviewCount: 242,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Emily Nguyen, MD",
    licenseId: "ME-88088",
    yearsOpen: 5,
    treatments: ["facial", "microneedling", "botox"],
    priceRange: "$$$",
    instagram: "bonita_springs_glow",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Neighborhood location"],
    phone: "(239) 555-1088",
    website: "https://www.bonita-springs-glow.com",
  },
  {
    slug: "pelican-bay-skin-institute",
    name: "Pelican Bay Skin Institute",
    providerType: "dermatology-aesthetics",
    neighborhood: "Pelican Bay",
    city: "Naples",
    metro: "southwest-florida",
    tagline: "Artistry meets accountability.",
    description: "Modern injectables studio with transparent pricing, digital consent, and published medical director credentials.",
    rating: 4.8,
    reviewCount: 260,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Robert Hayes, MD",
    licenseId: "ME-88089",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "body-contouring"],
    priceRange: "$$$$",
    instagram: "pelican_bay_skin_institu",
    productSlugs: ["skinceuticals-ce-ferulic"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
    phone: "(239) 555-1089",
    website: "https://www.pelican-bay-skin-institute.com",
  },
  {
    slug: "naples-park-aesthetics",
    name: "Naples Park Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Naples Park",
    city: "Naples",
    metro: "southwest-florida",
    tagline: "Where precision meets trust.",
    description: "Full-service aesthetics clinic with verified licenses, lot-tracked injectables, and neighborhood convenience.",
    rating: 4.9,
    reviewCount: 278,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Lisa Chen, NP (MSN)",
    licenseId: "ME-88090",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$",
    instagram: "naples_park_aesthetics",
    productSlugs: ["revision-retinol", "skinmedica-ha5"],
    highlights: ["Same-day appointments", "Injectables specialists", "Transparent pricing"],
    phone: "(239) 555-1090",
    website: "https://www.naples-park-aesthetics.com",
  },
  {
    slug: "vanderbilt-beach-med-spa",
    name: "Vanderbilt Beach Med Spa",
    providerType: "med-spa",
    neighborhood: "Vanderbilt Beach",
    city: "Naples",
    metro: "southwest-florida",
    tagline: "Injectables-only excellence.",
    description: "Focused exclusively on Botox and fillers with board-certified injectors and same-day appointment availability.",
    rating: 4.5,
    reviewCount: 296,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Michael Torres, MD",
    licenseId: "ME-88091",
    yearsOpen: 8,
    treatments: ["botox", "fillers"],
    priceRange: "$$$",
    instagram: "vanderbilt_beach_med_spa",
    productSlugs: ["eltamd-uv-clear"],
    highlights: ["Medical director on file", "Florida DBPR licensed", "Verified reviews"],
    phone: "(239) 555-1091",
    website: "https://www.vanderbilt-beach-med-spa.com",
  },
  {
    slug: "marco-island-aesthetics",
    name: "Marco Island Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Marco Island",
    city: "Marco Island",
    metro: "southwest-florida",
    tagline: "Results you can verify.",
    description: "Dermatology-backed aesthetics practice offering laser, facial, and injectable protocols with medical oversight.",
    rating: 4.6,
    reviewCount: 314,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Amanda Brooks, MD",
    licenseId: "ME-88092",
    yearsOpen: 9,
    treatments: ["laser", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "marco_island_aesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "revision-retinol"],
    highlights: ["Bespoke treatment plans", "Private suites", "Premium skincare protocols"],
    phone: "(239) 555-1092",
    website: "https://www.marco-island-aesthetics.com",
  },
  {
    slug: "estero-laser-clinic",
    name: "Estero Laser Clinic",
    providerType: "med-spa",
    neighborhood: "Estero",
    city: "Estero",
    metro: "southwest-florida",
    tagline: "Clinical care, boutique feel.",
    description: "Luxury med spa serving professionals with bespoke treatment plans and private suites.",
    rating: 4.7,
    reviewCount: 332,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. David Kim, MD",
    licenseId: "ME-88093",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "laser"],
    priceRange: "$$$$",
    instagram: "estero_laser_clinic",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["Dermatology oversight", "Clinical protocols", "Sensitive skin friendly"],
    phone: "(239) 555-1093",
    website: "https://www.estero-laser-clinic.com",
  },
  {
    slug: "old-naples-injectables",
    name: "Old Naples Injectables",
    providerType: "aesthetics-clinic",
    neighborhood: "Old Naples",
    city: "Naples",
    metro: "southwest-florida",
    tagline: "Board-supervised aesthetics.",
    description: "Community-trusted aesthetics clinic known for no-pressure consultations and product lists before every visit.",
    rating: 4.8,
    reviewCount: 350,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Rachel Foster, MD",
    licenseId: "ME-88094",
    yearsOpen: 11,
    treatments: ["facial", "microneedling", "laser"],
    priceRange: "$$",
    instagram: "old_naples_injectables",
    productSlugs: ["skinmedica-ha5", "eltamd-uv-clear"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
    phone: "(239) 555-1094",
    website: "https://www.old-naples-injectables.com",
  },
  {
    slug: "golden-gate-beauty-lab",
    name: "Golden Gate Beauty Lab",
    providerType: "med-spa",
    neighborhood: "Golden Gate",
    city: "Naples",
    metro: "southwest-florida",
    tagline: "Transparent pricing, natural results.",
    description: "Results-driven med spa with verified visit reviews and comprehensive treatment menus.",
    rating: 4.9,
    reviewCount: 368,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Nicole Adams, NP (MSN)",
    licenseId: "ME-88095",
    yearsOpen: 12,
    treatments: ["body-contouring", "laser", "facial"],
    priceRange: "$$$",
    instagram: "golden_gate_beauty_lab",
    productSlugs: ["epicutis-arctigenin", "skinceuticals-ce-ferulic"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
    phone: "(239) 555-1095",
    website: "https://www.golden-gate-beauty-lab.com",
  },
  {
    slug: "naples-derm-aesthetics",
    name: "Naples Derm Aesthetics",
    providerType: "dermatology-aesthetics",
    neighborhood: "North Naples",
    city: "Naples",
    metro: "southwest-florida",
    tagline: "Advanced skin science.",
    description: "Premium skin lab combining clinical lasers, microneedling, and medical-grade facials under physician supervision.",
    rating: 4.5,
    reviewCount: 386,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Christopher Lee, MD",
    licenseId: "ME-88096",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial"],
    priceRange: "$$$",
    instagram: "naples_derm_aesthetics",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Neighborhood location"],
    phone: "(239) 555-1096",
    website: "https://www.naples-derm-aesthetics.com",
  },
  {
    slug: "mercato-aesthetics-collective",
    name: "Mercato Aesthetics Collective",
    providerType: "aesthetics-clinic",
    neighborhood: "Mercato",
    city: "Naples",
    metro: "southwest-florida",
    tagline: "Your neighborhood med spa.",
    description: "Neighborhood beauty destination with transparent unit pricing and HIPAA-compliant practice standards.",
    rating: 4.6,
    reviewCount: 404,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jennifer Walsh, MD",
    licenseId: "ME-88097",
    yearsOpen: 4,
    treatments: ["laser", "body-contouring", "microneedling"],
    priceRange: "$$$$",
    instagram: "mercato_aesthetics_colle",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
    phone: "(239) 555-1097",
    website: "https://www.mercato-aesthetics-collective.com",
  },
  {
    slug: "boca-raton-medspa",
    name: "Boca Raton Medspa",
    providerType: "med-spa",
    neighborhood: "Boca Raton",
    city: "Boca Raton",
    metro: "south-florida",
    tagline: "Natural injectables. Transparent protocols.",
    description: "Board-supervised boutique med spa specializing in natural-looking injectables with full product disclosure before every appointment.",
    rating: 4.5,
    reviewCount: 218,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Sarah Mitchell, MD",
    licenseId: "ME-88098",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$",
    instagram: "boca_raton_medspa",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
    phone: "(561) 555-1098",
    website: "https://www.boca-raton-medspa.com",
  },
  {
    slug: "west-palm-aesthetics",
    name: "West Palm Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "West Palm Beach",
    city: "West Palm Beach",
    metro: "south-florida",
    tagline: "Luxury laser. Expert recovery.",
    description: "High-end laser and skin rejuvenation with published provider credentials and patch testing available.",
    rating: 4.6,
    reviewCount: 236,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. James Patterson, MD",
    licenseId: "ME-88099",
    yearsOpen: 4,
    treatments: ["laser", "facial", "microneedling", "body-contouring"],
    priceRange: "$$$",
    instagram: "west_palm_aesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
    phone: "(561) 555-1099",
    website: "https://www.west-palm-aesthetics.com",
  },
  {
    slug: "palm-beach-gardens-skin-lab",
    name: "Palm Beach Gardens Skin Lab",
    providerType: "med-spa",
    neighborhood: "Palm Beach Gardens",
    city: "Palm Beach Gardens",
    metro: "south-florida",
    tagline: "Coastal luxury skincare.",
    description: "Facial-forward med spa blending clinical treatments with premium skincare for first-time and returning clients.",
    rating: 4.7,
    reviewCount: 254,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Emily Nguyen, MD",
    licenseId: "ME-88100",
    yearsOpen: 5,
    treatments: ["facial", "microneedling", "botox"],
    priceRange: "$$$",
    instagram: "palm_beach_gardens_skin_",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Neighborhood location"],
    phone: "(561) 555-1100",
    website: "https://www.palm-beach-gardens-skin-lab.com",
  },
  {
    slug: "delray-beach-glow",
    name: "Delray Beach Glow",
    providerType: "med-spa",
    neighborhood: "Delray Beach",
    city: "Delray Beach",
    metro: "south-florida",
    tagline: "Artistry meets accountability.",
    description: "Modern injectables studio with transparent pricing, digital consent, and published medical director credentials.",
    rating: 4.8,
    reviewCount: 272,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Robert Hayes, MD",
    licenseId: "ME-88101",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "body-contouring"],
    priceRange: "$$$$",
    instagram: "delray_beach_glow",
    productSlugs: ["skinceuticals-ce-ferulic"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
    phone: "(561) 555-1101",
    website: "https://www.delray-beach-glow.com",
  },
  {
    slug: "east-boca-injectables",
    name: "East Boca Injectables",
    providerType: "aesthetics-clinic",
    neighborhood: "Boca Raton",
    city: "Boca Raton",
    metro: "south-florida",
    tagline: "Where precision meets trust.",
    description: "Full-service aesthetics clinic with verified licenses, lot-tracked injectables, and neighborhood convenience.",
    rating: 4.9,
    reviewCount: 290,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Lisa Chen, NP (MSN)",
    licenseId: "ME-88102",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$",
    instagram: "east_boca_injectables",
    productSlugs: ["revision-retinol", "skinmedica-ha5"],
    highlights: ["Same-day appointments", "Injectables specialists", "Transparent pricing"],
    phone: "(561) 555-1102",
    website: "https://www.east-boca-injectables.com",
  },
  {
    slug: "worth-avenue-aesthetics",
    name: "Worth Avenue Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Palm Beach",
    city: "Palm Beach",
    metro: "south-florida",
    tagline: "Injectables-only excellence.",
    description: "Focused exclusively on Botox and fillers with board-certified injectors and same-day appointment availability.",
    rating: 4.5,
    reviewCount: 308,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Michael Torres, MD",
    licenseId: "ME-88103",
    yearsOpen: 8,
    treatments: ["botox", "fillers"],
    priceRange: "$$$",
    instagram: "worth_avenue_aesthetics",
    productSlugs: ["eltamd-uv-clear"],
    highlights: ["Medical director on file", "Florida DBPR licensed", "Verified reviews"],
    phone: "(561) 555-1103",
    website: "https://www.worth-avenue-aesthetics.com",
  },
  {
    slug: "juno-beach-med-spa",
    name: "Juno Beach Med Spa",
    providerType: "med-spa",
    neighborhood: "Juno Beach",
    city: "Juno Beach",
    metro: "south-florida",
    tagline: "Results you can verify.",
    description: "Dermatology-backed aesthetics practice offering laser, facial, and injectable protocols with medical oversight.",
    rating: 4.6,
    reviewCount: 326,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Amanda Brooks, MD",
    licenseId: "ME-88104",
    yearsOpen: 9,
    treatments: ["laser", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "juno_beach_med_spa",
    productSlugs: ["skinceuticals-ce-ferulic", "revision-retinol"],
    highlights: ["Bespoke treatment plans", "Private suites", "Premium skincare protocols"],
    phone: "(561) 555-1104",
    website: "https://www.juno-beach-med-spa.com",
  },
  {
    slug: "wellington-derm-aesthetics",
    name: "Wellington Derm Aesthetics",
    providerType: "dermatology-aesthetics",
    neighborhood: "Wellington",
    city: "Wellington",
    metro: "south-florida",
    tagline: "Clinical care, boutique feel.",
    description: "Luxury med spa serving professionals with bespoke treatment plans and private suites.",
    rating: 4.7,
    reviewCount: 344,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. David Kim, MD",
    licenseId: "ME-88105",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "laser"],
    priceRange: "$$$$",
    instagram: "wellington_derm_aestheti",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["Dermatology oversight", "Clinical protocols", "Sensitive skin friendly"],
    phone: "(561) 555-1105",
    website: "https://www.wellington-derm-aesthetics.com",
  },
  {
    slug: "royal-palm-beach-beauty",
    name: "Royal Palm Beach Beauty",
    providerType: "med-spa",
    neighborhood: "Royal Palm Beach",
    city: "Royal Palm Beach",
    metro: "south-florida",
    tagline: "Board-supervised aesthetics.",
    description: "Community-trusted aesthetics clinic known for no-pressure consultations and product lists before every visit.",
    rating: 4.8,
    reviewCount: 362,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Rachel Foster, MD",
    licenseId: "ME-88106",
    yearsOpen: 11,
    treatments: ["facial", "microneedling", "laser"],
    priceRange: "$$",
    instagram: "royal_palm_beach_beauty",
    productSlugs: ["skinmedica-ha5", "eltamd-uv-clear"],
    highlights: ["Full product disclosure", "Board-certified medical director", "Lot-tracked injectables"],
    phone: "(561) 555-1106",
    website: "https://www.royal-palm-beach-beauty.com",
  },
  {
    slug: "boynton-aesthetics-clinic",
    name: "Boynton Aesthetics Clinic",
    providerType: "aesthetics-clinic",
    neighborhood: "Boynton Beach",
    city: "Boynton Beach",
    metro: "south-florida",
    tagline: "Transparent pricing, natural results.",
    description: "Results-driven med spa with verified visit reviews and comprehensive treatment menus.",
    rating: 4.9,
    reviewCount: 380,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Nicole Adams, NP (MSN)",
    licenseId: "ME-88107",
    yearsOpen: 12,
    treatments: ["body-contouring", "laser", "facial"],
    priceRange: "$$$",
    instagram: "boynton_aesthetics_clini",
    productSlugs: ["epicutis-arctigenin", "skinceuticals-ce-ferulic"],
    highlights: ["Laser specialists", "Patch testing available", "Verified visit reviews"],
    phone: "(561) 555-1107",
    website: "https://www.boynton-aesthetics-clinic.com",
  },
  {
    slug: "lighthouse-point-skin-studio",
    name: "Lighthouse Point Skin Studio",
    providerType: "aesthetics-clinic",
    neighborhood: "Lighthouse Point",
    city: "Lighthouse Point",
    metro: "south-florida",
    tagline: "Advanced skin science.",
    description: "Premium skin lab combining clinical lasers, microneedling, and medical-grade facials under physician supervision.",
    rating: 4.5,
    reviewCount: 398,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Christopher Lee, MD",
    licenseId: "ME-88108",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial"],
    priceRange: "$$$",
    instagram: "lighthouse_point_skin_st",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["No-pressure consultations", "Product lists before visit", "Neighborhood location"],
    phone: "(561) 555-1108",
    website: "https://www.lighthouse-point-skin-studio.com",
  },
  {
    slug: "lake-worth-med-aesthetics",
    name: "Lake Worth Med Aesthetics",
    providerType: "med-spa",
    neighborhood: "Lake Worth",
    city: "Lake Worth Beach",
    metro: "south-florida",
    tagline: "Your neighborhood med spa.",
    description: "Neighborhood beauty destination with transparent unit pricing and HIPAA-compliant practice standards.",
    rating: 4.6,
    reviewCount: 416,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jennifer Walsh, MD",
    licenseId: "ME-88109",
    yearsOpen: 4,
    treatments: ["laser", "body-contouring", "microneedling"],
    priceRange: "$$$$",
    instagram: "lake_worth_med_aesthetic",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Transparent unit pricing", "Digital consent signatures", "Published credentials"],
    phone: "(561) 555-1109",
    website: "https://www.lake-worth-med-aesthetics.com",
  },
];

export const FLORIDA_SPA_IMAGE_IDS: Record<string, { heroId: string; g1: string; g2: string; g3: string }> = {
  "bay-shore-aesthetics-hyde-park": { heroId: "photo-1612349317150-e413f6a5b16d", g1: "photo-1438761681033-6461ffad8d80", g2: "photo-1524504388940-b1c1722653e1", g3: "photo-1524504388940-b1c1722653e1" },
  "south-tampa-medspa": { heroId: "photo-1556228720-195a672e8a03", g1: "photo-1507003211169-0a1dd7228f2d", g2: "photo-1531746020798-e6953c6e8e04", g3: "photo-1629909613654-28e377c37b09" },
  "westshore-laser-aesthetics": { heroId: "photo-1556228720-195a672e8a03", g1: "photo-1494790108377-be9c29b29330", g2: "photo-1506794778202-cad84cf45f1d", g3: "photo-1534528741775-53994a69daeb" },
  "st-pete-skin-institute": { heroId: "photo-1576091160399-112ba8d25d1d", g1: "photo-1534528741775-53994a69daeb", g2: "photo-1582750433449-648ed127bb54", g3: "photo-1582750433449-648ed127bb54" },
  "clearwater-glow-medspa": { heroId: "photo-1580618672591-eb180b1a973f", g1: "photo-1506794778202-cad84cf45f1d", g2: "photo-1580618672591-eb180b1a973f", g3: "photo-1519823551278-64ac92734fb1" },
  "hyde-park-injectables-lounge": { heroId: "photo-1516975080664-ed2fc6a32937", g1: "photo-1469334031218-e382a71b716b", g2: "photo-1560066984-138dadb4c035", g3: "photo-1560066984-138dadb4c035" },
  "tampa-bay-derm-aesthetics": { heroId: "photo-1522337360788-8b13dee7a37e", g1: "photo-1524504388940-b1c1722653e1", g2: "photo-1524504388940-b1c1722653e1", g3: "photo-1584515933487-779824d29309" },
  "channelside-aesthetics-clinic": { heroId: "photo-1438761681033-6461ffad8d80", g1: "photo-1531746020798-e6953c6e8e04", g2: "photo-1629909613654-28e377c37b09", g3: "photo-1629909613654-28e377c37b09" },
  "seminole-heights-beauty-lab": { heroId: "photo-1507003211169-0a1dd7228f2d", g1: "photo-1506794778202-cad84cf45f1d", g2: "photo-1534528741775-53994a69daeb", g3: "photo-1584515933487-779824d29309" },
  "carrollwood-med-aesthetics": { heroId: "photo-1494790108377-be9c29b29330", g1: "photo-1582750433449-648ed127bb54", g2: "photo-1582750433449-648ed127bb54", g3: "photo-1576091160399-112ba8d25d1d" },
  "davis-islands-skin-studio": { heroId: "photo-1534528741775-53994a69daeb", g1: "photo-1580618672591-eb180b1a973f", g2: "photo-1519823551278-64ac92734fb1", g3: "photo-1570172619644-dfd03ed5d881" },
  "ybor-aesthetics-collective": { heroId: "photo-1506794778202-cad84cf45f1d", g1: "photo-1560066984-138dadb4c035", g2: "photo-1560066984-138dadb4c035", g3: "photo-1540555700478-4be289fbecef" },
  "winter-park-aesthetics": { heroId: "photo-1469334031218-e382a71b716b", g1: "photo-1524504388940-b1c1722653e1", g2: "photo-1584515933487-779824d29309", g3: "photo-1515377905703-c4788e51af15" },
  "dr-phillips-medspa": { heroId: "photo-1524504388940-b1c1722653e1", g1: "photo-1629909613654-28e377c37b09", g2: "photo-1629909613654-28e377c37b09", g3: "photo-1612349317150-e413f6a5b16d" },
  "lake-nona-skin-lab": { heroId: "photo-1531746020798-e6953c6e8e04", g1: "photo-1534528741775-53994a69daeb", g2: "photo-1584515933487-779824d29309", g3: "photo-1544161515-4ab6ce6db874" },
  "downtown-orlando-injectables": { heroId: "photo-1506794778202-cad84cf45f1d", g1: "photo-1582750433449-648ed127bb54", g2: "photo-1576091160399-112ba8d25d1d", g3: "photo-1519823551278-64ac92734fb1" },
  "baldwin-park-beauty-clinic": { heroId: "photo-1582750433449-648ed127bb54", g1: "photo-1519823551278-64ac92734fb1", g2: "photo-1570172619644-dfd03ed5d881", g3: "photo-1570172619644-dfd03ed5d881" },
  "millenia-laser-aesthetics": { heroId: "photo-1580618672591-eb180b1a973f", g1: "photo-1560066984-138dadb4c035", g2: "photo-1540555700478-4be289fbecef", g3: "photo-1540555700478-4be289fbecef" },
  "thornton-park-med-spa": { heroId: "photo-1560066984-138dadb4c035", g1: "photo-1584515933487-779824d29309", g2: "photo-1515377905703-c4788e51af15", g3: "photo-1516975080664-ed2fc6a32937" },
  "windermere-aesthetics": { heroId: "photo-1524504388940-b1c1722653e1", g1: "photo-1629909613654-28e377c37b09", g2: "photo-1612349317150-e413f6a5b16d", g3: "photo-1556228578-0d85b1a4d571" },
  "celebration-skin-studio": { heroId: "photo-1629909613654-28e377c37b09", g1: "photo-1584515933487-779824d29309", g2: "photo-1544161515-4ab6ce6db874", g3: "photo-1612817288484-6f916006741a" },
  "college-park-derm-aesthetics": { heroId: "photo-1534528741775-53994a69daeb", g1: "photo-1576091160399-112ba8d25d1d", g2: "photo-1519823551278-64ac92734fb1", g3: "photo-1612349317150-e413f6a5b16d" },
  "altamonte-aesthetics-hub": { heroId: "photo-1582750433449-648ed127bb54", g1: "photo-1570172619644-dfd03ed5d881", g2: "photo-1570172619644-dfd03ed5d881", g3: "photo-1556228720-195a672e8a03" },
  "oviedo-glow-medspa": { heroId: "photo-1519823551278-64ac92734fb1", g1: "photo-1540555700478-4be289fbecef", g2: "photo-1540555700478-4be289fbecef", g3: "photo-1556228720-195a672e8a03" },
  "san-marco-aesthetics": { heroId: "photo-1560066984-138dadb4c035", g1: "photo-1515377905703-c4788e51af15", g2: "photo-1516975080664-ed2fc6a32937", g3: "photo-1576091160399-112ba8d25d1d" },
  "riverside-injectables-lounge": { heroId: "photo-1584515933487-779824d29309", g1: "photo-1612349317150-e413f6a5b16d", g2: "photo-1556228578-0d85b1a4d571", g3: "photo-1580618672591-eb180b1a973f" },
  "ponte-vedra-skin-institute": { heroId: "photo-1629909613654-28e377c37b09", g1: "photo-1544161515-4ab6ce6db874", g2: "photo-1612817288484-6f916006741a", g3: "photo-1516975080664-ed2fc6a32937" },
  "jax-beach-medspa": { heroId: "photo-1584515933487-779824d29309", g1: "photo-1519823551278-64ac92734fb1", g2: "photo-1612349317150-e413f6a5b16d", g3: "photo-1522337360788-8b13dee7a37e" },
  "avondale-aesthetics-clinic": { heroId: "photo-1576091160399-112ba8d25d1d", g1: "photo-1570172619644-dfd03ed5d881", g2: "photo-1556228720-195a672e8a03", g3: "photo-1438761681033-6461ffad8d80" },
  "st-johns-town-center-beauty": { heroId: "photo-1570172619644-dfd03ed5d881", g1: "photo-1540555700478-4be289fbecef", g2: "photo-1556228720-195a672e8a03", g3: "photo-1507003211169-0a1dd7228f2d" },
  "mandarin-derm-aesthetics": { heroId: "photo-1540555700478-4be289fbecef", g1: "photo-1516975080664-ed2fc6a32937", g2: "photo-1576091160399-112ba8d25d1d", g3: "photo-1494790108377-be9c29b29330" },
  "ortega-med-spa": { heroId: "photo-1515377905703-c4788e51af15", g1: "photo-1556228578-0d85b1a4d571", g2: "photo-1580618672591-eb180b1a973f", g3: "photo-1534528741775-53994a69daeb" },
  "atlantic-beach-glow": { heroId: "photo-1612349317150-e413f6a5b16d", g1: "photo-1612817288484-6f916006741a", g2: "photo-1516975080664-ed2fc6a32937", g3: "photo-1506794778202-cad84cf45f1d" },
  "san-jose-aesthetics-hub": { heroId: "photo-1544161515-4ab6ce6db874", g1: "photo-1612349317150-e413f6a5b16d", g2: "photo-1522337360788-8b13dee7a37e", g3: "photo-1469334031218-e382a71b716b" },
  "riverside-dermatology-aesthetics": { heroId: "photo-1519823551278-64ac92734fb1", g1: "photo-1556228720-195a672e8a03", g2: "photo-1438761681033-6461ffad8d80", g3: "photo-1524504388940-b1c1722653e1" },
  "nocatee-skin-lab": { heroId: "photo-1570172619644-dfd03ed5d881", g1: "photo-1556228720-195a672e8a03", g2: "photo-1507003211169-0a1dd7228f2d", g3: "photo-1531746020798-e6953c6e8e04" },
  "fifth-avenue-aesthetics-naples": { heroId: "photo-1540555700478-4be289fbecef", g1: "photo-1576091160399-112ba8d25d1d", g2: "photo-1494790108377-be9c29b29330", g3: "photo-1506794778202-cad84cf45f1d" },
  "north-naples-medspa": { heroId: "photo-1516975080664-ed2fc6a32937", g1: "photo-1580618672591-eb180b1a973f", g2: "photo-1534528741775-53994a69daeb", g3: "photo-1582750433449-648ed127bb54" },
  "bonita-springs-glow": { heroId: "photo-1556228578-0d85b1a4d571", g1: "photo-1516975080664-ed2fc6a32937", g2: "photo-1506794778202-cad84cf45f1d", g3: "photo-1580618672591-eb180b1a973f" },
  "pelican-bay-skin-institute": { heroId: "photo-1612817288484-6f916006741a", g1: "photo-1522337360788-8b13dee7a37e", g2: "photo-1469334031218-e382a71b716b", g3: "photo-1560066984-138dadb4c035" },
  "naples-park-aesthetics": { heroId: "photo-1612349317150-e413f6a5b16d", g1: "photo-1438761681033-6461ffad8d80", g2: "photo-1524504388940-b1c1722653e1", g3: "photo-1524504388940-b1c1722653e1" },
  "vanderbilt-beach-med-spa": { heroId: "photo-1556228720-195a672e8a03", g1: "photo-1507003211169-0a1dd7228f2d", g2: "photo-1531746020798-e6953c6e8e04", g3: "photo-1629909613654-28e377c37b09" },
  "marco-island-aesthetics": { heroId: "photo-1556228720-195a672e8a03", g1: "photo-1494790108377-be9c29b29330", g2: "photo-1506794778202-cad84cf45f1d", g3: "photo-1534528741775-53994a69daeb" },
  "estero-laser-clinic": { heroId: "photo-1576091160399-112ba8d25d1d", g1: "photo-1534528741775-53994a69daeb", g2: "photo-1582750433449-648ed127bb54", g3: "photo-1582750433449-648ed127bb54" },
  "old-naples-injectables": { heroId: "photo-1580618672591-eb180b1a973f", g1: "photo-1506794778202-cad84cf45f1d", g2: "photo-1580618672591-eb180b1a973f", g3: "photo-1519823551278-64ac92734fb1" },
  "golden-gate-beauty-lab": { heroId: "photo-1516975080664-ed2fc6a32937", g1: "photo-1469334031218-e382a71b716b", g2: "photo-1560066984-138dadb4c035", g3: "photo-1560066984-138dadb4c035" },
  "naples-derm-aesthetics": { heroId: "photo-1522337360788-8b13dee7a37e", g1: "photo-1524504388940-b1c1722653e1", g2: "photo-1524504388940-b1c1722653e1", g3: "photo-1584515933487-779824d29309" },
  "mercato-aesthetics-collective": { heroId: "photo-1438761681033-6461ffad8d80", g1: "photo-1531746020798-e6953c6e8e04", g2: "photo-1629909613654-28e377c37b09", g3: "photo-1629909613654-28e377c37b09" },
  "boca-raton-medspa": { heroId: "photo-1507003211169-0a1dd7228f2d", g1: "photo-1506794778202-cad84cf45f1d", g2: "photo-1534528741775-53994a69daeb", g3: "photo-1584515933487-779824d29309" },
  "west-palm-aesthetics": { heroId: "photo-1494790108377-be9c29b29330", g1: "photo-1582750433449-648ed127bb54", g2: "photo-1582750433449-648ed127bb54", g3: "photo-1576091160399-112ba8d25d1d" },
  "palm-beach-gardens-skin-lab": { heroId: "photo-1534528741775-53994a69daeb", g1: "photo-1580618672591-eb180b1a973f", g2: "photo-1519823551278-64ac92734fb1", g3: "photo-1570172619644-dfd03ed5d881" },
  "delray-beach-glow": { heroId: "photo-1506794778202-cad84cf45f1d", g1: "photo-1560066984-138dadb4c035", g2: "photo-1560066984-138dadb4c035", g3: "photo-1540555700478-4be289fbecef" },
  "east-boca-injectables": { heroId: "photo-1469334031218-e382a71b716b", g1: "photo-1524504388940-b1c1722653e1", g2: "photo-1584515933487-779824d29309", g3: "photo-1515377905703-c4788e51af15" },
  "worth-avenue-aesthetics": { heroId: "photo-1524504388940-b1c1722653e1", g1: "photo-1629909613654-28e377c37b09", g2: "photo-1629909613654-28e377c37b09", g3: "photo-1612349317150-e413f6a5b16d" },
  "juno-beach-med-spa": { heroId: "photo-1531746020798-e6953c6e8e04", g1: "photo-1534528741775-53994a69daeb", g2: "photo-1584515933487-779824d29309", g3: "photo-1544161515-4ab6ce6db874" },
  "wellington-derm-aesthetics": { heroId: "photo-1506794778202-cad84cf45f1d", g1: "photo-1582750433449-648ed127bb54", g2: "photo-1576091160399-112ba8d25d1d", g3: "photo-1519823551278-64ac92734fb1" },
  "royal-palm-beach-beauty": { heroId: "photo-1582750433449-648ed127bb54", g1: "photo-1519823551278-64ac92734fb1", g2: "photo-1570172619644-dfd03ed5d881", g3: "photo-1570172619644-dfd03ed5d881" },
  "boynton-aesthetics-clinic": { heroId: "photo-1580618672591-eb180b1a973f", g1: "photo-1560066984-138dadb4c035", g2: "photo-1540555700478-4be289fbecef", g3: "photo-1540555700478-4be289fbecef" },
  "lighthouse-point-skin-studio": { heroId: "photo-1560066984-138dadb4c035", g1: "photo-1584515933487-779824d29309", g2: "photo-1515377905703-c4788e51af15", g3: "photo-1516975080664-ed2fc6a32937" },
  "lake-worth-med-aesthetics": { heroId: "photo-1524504388940-b1c1722653e1", g1: "photo-1629909613654-28e377c37b09", g2: "photo-1612349317150-e413f6a5b16d", g3: "photo-1556228578-0d85b1a4d571" },
};