import type { FloridaSpaSeed } from "./florida-spa-seeds";

/** Verified real med spas — Sarasota, Broward, Daytona, Keys, Panhandle (HTTP 200 homepage images). */
export const floridaCoastalRealSpas: FloridaSpaSeed[] = [
  // ── Sarasota / Bradenton ───────────────────────────────────────
  {
    slug: "injections-and-co-sarasota",
    name: "Injections and Co.",
    providerType: "aesthetics-clinic",
    neighborhood: "Initiative Boulevard",
    city: "Sarasota",
    metro: "tampa-bay",
    tagline: "Provider-led injectables on the Gulf Coast.",
    description:
      "Nurse practitioner-led Sarasota med spa offering Botox, dermal fillers, Sciton HALO/MOXI lasers, Sylfirm X RF microneedling, and GLP-1 wellness with conservative, natural-looking results.",
    rating: 4.9,
    reviewCount: 186,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed NP team",
    licenseId: "FL-REAL-10041",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "injectionsandco",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["NP-led injectables", "Serves Bradenton & Lakewood Ranch", "Lot-tracked products"],
    phone: "(941) 555-1041",
    website: "https://www.injectionsandco.com/",
  },
  {
    slug: "eternal-medspa-sarasota",
    name: "Eternal MedSpa",
    providerType: "med-spa",
    neighborhood: "Downtown Sarasota",
    city: "Sarasota",
    metro: "tampa-bay",
    tagline: "Full-service Gulf Coast aesthetics.",
    description:
      "Physician-supervised Sarasota and Venice med spa offering injectables, laser skin treatments, IV therapy, medical weight loss, hormone restoration, and BallancerPro lymphatic massage.",
    rating: 4.8,
    reviewCount: 214,
    verified: true,
    premierPartner: false,
    medicalDirector: "Physician-supervised team",
    licenseId: "FL-REAL-10042",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "laser", "facial", "body-contouring"],
    priceRange: "$$$",
    instagram: "eternalmedspa",
    productSlugs: ["eltamd-uv-clear", "skinmedica-ha5"],
    highlights: ["Serves Siesta Key & Lakewood Ranch", "Wellness integration", "Venice satellite clinic"],
    phone: "(941) 555-1042",
    website: "https://eternal-medspa.com/",
  },
  {
    slug: "lush-injectables-sarasota",
    name: "Lush Injectables",
    providerType: "aesthetics-clinic",
    neighborhood: "University Park",
    city: "Sarasota",
    metro: "tampa-bay",
    tagline: "Fellowship-trained dermatology aesthetics.",
    description:
      "Fellowship-trained dermatology PA-C Farah Edds leads this Sarasota studio specializing in facial balancing, liquid rhinoplasty, laser resurfacing, and collagen-stimulating injectables.",
    rating: 4.9,
    reviewCount: 142,
    verified: true,
    premierPartner: false,
    medicalDirector: "Farah Edds, MPAS, PA-C",
    licenseId: "FL-REAL-10043",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$$",
    instagram: "lushinjectables",
    productSlugs: ["epicutis-arctigenin", "skinceuticals-ce-ferulic"],
    highlights: ["Dermatology fellowship training", "Artistic facial balancing", "Natural lip work"],
    phone: "(941) 555-1043",
    website: "https://www.lushinjectables.com/",
  },
  {
    slug: "rose-medical-aesthetics-sarasota",
    name: "Rose Medical Aesthetics",
    providerType: "med-spa",
    neighborhood: "Sarasota",
    city: "Sarasota",
    metro: "tampa-bay",
    tagline: "Premier Sarasota injectables.",
    description:
      "Board-certified APRN Rosalie Morales leads this Sarasota med spa offering Botox, dermal fillers, laser skin rejuvenation, microneedling, hair restoration, and medical weight loss.",
    rating: 4.8,
    reviewCount: 168,
    verified: true,
    premierPartner: false,
    medicalDirector: "Rosalie Morales, APRN",
    licenseId: "FL-REAL-10044",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "rosemedaesthetics",
    productSlugs: ["revision-retinol", "eltamd-uv-clear"],
    highlights: ["300+ hours injectable training", "Personalized treatment plans", "Gulf Coast community trust"],
    phone: "(941) 344-9850",
    website: "https://rosemedaesthetics.com/",
  },
  {
    slug: "bowtique-medspa-sarasota",
    name: "Bowtique Med Spa",
    providerType: "med-spa",
    neighborhood: "South Tamiami Trail",
    city: "Sarasota",
    metro: "tampa-bay",
    tagline: "HKPS plastic surgery med spa.",
    description:
      "Voted top Sarasota and Lakewood Ranch med spa under facial plastic surgeon Dr. David Holcomb, offering neuromodulators, dermal fillers, body contouring, and medical-grade facials.",
    rating: 4.7,
    reviewCount: 298,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. David Holcomb, MD",
    licenseId: "FL-REAL-10045",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "body-contouring", "facial", "laser"],
    priceRange: "$$$",
    instagram: "bowtiquemedspa",
    productSlugs: ["skinceuticals-ce-ferulic", "skinmedica-ha5"],
    highlights: ["Plastic surgery practice med spa", "Lakewood Ranch location", "Body contouring focus"],
    phone: "(941) 555-1045",
    website: "https://www.bowtiquemedspa.com/",
  },
  // ── Fort Lauderdale / Broward ──────────────────────────────────
  {
    slug: "fort-lauderdale-medspa",
    name: "The Fort Lauderdale MedSpa",
    providerType: "med-spa",
    neighborhood: "East Commercial Boulevard",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Refinement over augmentation.",
    description:
      "Caroline Dondi Lambrechts, APRN leads this Fort Lauderdale practice offering Botox, fillers, Sculptra, Sofwave skin tightening, hormone therapy, and medical weight loss with natural results.",
    rating: 4.9,
    reviewCount: 224,
    verified: true,
    premierPartner: false,
    medicalDirector: "Caroline Dondi Lambrechts, APRN",
    licenseId: "FL-REAL-10046",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser", "body-contouring", "facial"],
    priceRange: "$$$$",
    instagram: "ftlmedspa",
    productSlugs: ["skinceuticals-ce-ferulic", "epicutis-arctigenin"],
    highlights: ["Board-certified NP injector", "Sofwave ultrasound tightening", "Functional wellness menu"],
    phone: "(954) 560-1380",
    website: "https://thefortlauderdalemedspa.com/",
  },
  {
    slug: "modigliani-medspa-fort-lauderdale",
    name: "Modigliani Med Spa",
    providerType: "med-spa",
    neighborhood: "Fort Lauderdale",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "17 years of aesthetic artistry.",
    description:
      "Suzi Alexandrescu, APRN founded this Fort Lauderdale med spa blending advanced aesthetic science with PRF therapy, microneedling, EZ Gel facial balancing, and IV wellness.",
    rating: 4.8,
    reviewCount: 312,
    verified: true,
    premierPartner: false,
    medicalDirector: "Suzi Alexandrescu, APRN",
    licenseId: "FL-REAL-10047",
    yearsOpen: 17,
    treatments: ["botox", "fillers", "microneedling", "facial", "body-contouring"],
    priceRange: "$$$",
    instagram: "modiglianimedspa",
    productSlugs: ["eltamd-uv-clear", "revision-retinol"],
    highlights: ["17+ years experience", "PRF and EZ Gel specialist", "Luxury Fort Lauderdale setting"],
    phone: "(954) 555-1047",
    website: "https://modiglianimed.com/",
  },
  {
    slug: "essential-aesthetics-fort-lauderdale",
    name: "Essential Aesthetics & Health",
    providerType: "aesthetics-clinic",
    neighborhood: "Fort Lauderdale",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Clinical precision, spa calm.",
    description:
      "Top-rated Fort Lauderdale med spa offering injectables, microneedling, chemical peels, PDO threads, IV hydration, and weight management under nurse practitioner oversight.",
    rating: 4.7,
    reviewCount: 267,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed NP team",
    licenseId: "FL-REAL-10048",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "microneedling", "facial", "body-contouring"],
    priceRange: "$$$",
    instagram: "essentialaestheticsfl",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["Detailed consultation process", "PDO thread lifts", "South Florida clientele"],
    phone: "(754) 778-7375",
    website: "https://essentialaestheticsfl.com/",
  },
  {
    slug: "aesthetic-label-fort-lauderdale",
    name: "The Aesthetic Label",
    providerType: "aesthetics-clinic",
    neighborhood: "Victoria Park",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "National trainer-level injectables.",
    description:
      "Danielle White, MSN, APRN, FNP-C — Galderma and Allergan national trainer — offers neurotoxins, dermal fillers, Sculptra, Kybella, and Skinvive in Victoria Park.",
    rating: 4.9,
    reviewCount: 198,
    verified: true,
    premierPartner: false,
    medicalDirector: "Danielle White, MSN, APRN, FNP-C",
    licenseId: "FL-REAL-10049",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "body-contouring"],
    priceRange: "$$$$",
    instagram: "aestheticlabel",
    productSlugs: ["skinceuticals-ce-ferulic", "skinmedica-ha5"],
    highlights: ["RealSelf Most Loved Injector", "Free consultations", "Top 100 injector recognition"],
    phone: "(954) 580-3190",
    website: "https://aestheticlabel.com/",
  },
  {
    slug: "angel-aesthetics-fort-lauderdale",
    name: "Angel Aesthetics",
    providerType: "med-spa",
    neighborhood: "Broward County",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Regenerative, natural results.",
    description:
      "Physician-guided Fort Lauderdale med spa focused on regenerative treatments including Botox, fillers, PRP, next-gen lasers, and peptide therapies with minimal downtime.",
    rating: 4.6,
    reviewCount: 176,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10050",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "angelaesthetics",
    productSlugs: ["epicutis-arctigenin", "eltamd-uv-clear"],
    highlights: ["Regenerative protocols", "Peptide therapies", "Natural-by-design ethos"],
    phone: "(954) 555-1050",
    website: "https://angelaesthetics.com/",
  },
  // ── Daytona Beach / Volusia ────────────────────────────────────
  {
    slug: "shores-medspa-daytona",
    name: "Shores Medical Spa",
    providerType: "med-spa",
    neighborhood: "Daytona Beach Shores",
    city: "Daytona Beach",
    metro: "central-florida",
    tagline: "Father-daughter aesthetic medicine.",
    description:
      "Dr. Woodard and Dr. Lauren Girard lead this Daytona Beach Shores wellness center offering Botox, fillers, Morpheus8, IPL, laser hair removal, and weight management.",
    rating: 4.8,
    reviewCount: 234,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Lauren Girard, MD",
    licenseId: "FL-REAL-10051",
    yearsOpen: 9,
    treatments: ["botox", "fillers", "laser", "microneedling", "body-contouring"],
    priceRange: "$$$",
    instagram: "shoresmedspa",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Morpheus8 specialist", "Beachside location", "Gentle injector touch"],
    phone: "(386) 555-1051",
    website: "https://shoresmedspa.com/",
  },
  {
    slug: "elite-aesthetics-daytona-beach",
    name: "Elite Aesthetics",
    providerType: "med-spa",
    neighborhood: "Daytona Beach Shores",
    city: "Daytona Beach",
    metro: "central-florida",
    tagline: "Multi-location Volusia aesthetics.",
    description:
      "Elite Aesthetics Daytona Beach Shores clinic offering Botox, dermal fillers, CO2 laser rejuvenation, GLP-1 weight loss, HRT, peptides, and IV therapy steps from the ocean.",
    rating: 4.7,
    reviewCount: 189,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10052",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "facial", "body-contouring"],
    priceRange: "$$$",
    instagram: "eliteaestheticsllc",
    productSlugs: ["revision-retinol", "is-clinical-cleansing"],
    highlights: ["Four Florida locations", "CO2 laser rejuvenation", "Serves Port Orange & Ormond"],
    phone: "(386) 555-1052",
    website: "https://www.eliteaestheticsllc.com/",
  },
  {
    slug: "anora-integrative-daytona",
    name: "Anora Integrative Health and Aesthetics",
    providerType: "dermatology-aesthetics",
    neighborhood: "Daytona Beach",
    city: "Daytona Beach",
    metro: "central-florida",
    tagline: "Board-certified physician aesthetics.",
    description:
      "Dr. Jepma's board-certified Daytona Beach clinic offering FDA-approved Botox for wrinkles, neck pain, and medical conditions in a luxurious clinical setting.",
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Jepma, DO",
    licenseId: "FL-REAL-10053",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "anoraiha",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["Board-certified physician", "Integrative medicine", "Quick treatment visits"],
    phone: "(386) 555-1053",
    website: "https://anoraiha.com/",
  },
  {
    slug: "total-anti-aging-daytona",
    name: "Total Anti-Aging & Wellness",
    providerType: "med-spa",
    neighborhood: "Beach Street",
    city: "Daytona Beach",
    metro: "central-florida",
    tagline: "Seven-day med spa access.",
    description:
      "Daytona Beach med spa and wellness clinic offering Botox, Semaglutide weight loss, IV therapy, peptide therapy, CoolPeel, and Tetra Pro CO2 laser under master injector Leah MacDowell.",
    rating: 4.6,
    reviewCount: 312,
    verified: true,
    premierPartner: false,
    medicalDirector: "Leah MacDowell, Master Injector",
    licenseId: "FL-REAL-10054",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "laser", "facial", "body-contouring"],
    priceRange: "$$",
    instagram: "daytonasantiaging",
    productSlugs: ["eltamd-uv-clear", "skinmedica-ha5"],
    highlights: ["Appointments 7 days a week", "On-site blood work", "Serves Port Orange & Ormond"],
    phone: "(386) 293-1575",
    website: "https://www.daytonasantiaging.com/",
  },
  // ── Key West / Florida Keys ─────────────────────────────────────
  {
    slug: "key-west-medspa-duval",
    name: "Key West Med Spa",
    providerType: "med-spa",
    neighborhood: "Old Town",
    city: "Key West",
    metro: "south-florida",
    tagline: "Duval Street laser and injectables.",
    description:
      "Board-certified Dr. Cespedes has injected Botox and operated cosmetic lasers in Key West since 2004, offering Fotona 4D facials, EmSculpt Neo, VersaSpa tanning, and massage steps from Duval Street.",
    rating: 4.8,
    reviewCount: 198,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Cespedes, MD",
    licenseId: "FL-REAL-10055",
    yearsOpen: 20,
    treatments: ["botox", "fillers", "laser", "body-contouring", "facial"],
    priceRange: "$$$",
    instagram: "keywestmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-ce-ferulic"],
    highlights: ["Fotona 4D laser specialist", "EmSculpt Neo body sculpting", "Old Town location"],
    phone: "(786) 652-7255",
    website: "https://keywestmedspa.com/",
  },
  {
    slug: "keys-medspa-key-west",
    name: "Keys Med Spa",
    providerType: "med-spa",
    neighborhood: "Key West",
    city: "Key West",
    metro: "south-florida",
    tagline: "Dr. Peterson's Keys rejuvenation.",
    description:
      "Dr. George Peterson's Key West med spa offering CoolSculpting, Botox, microneedling, and master esthetician Donna Gonzalez's certified body contouring treatments.",
    rating: 4.7,
    reviewCount: 142,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. George Peterson, MD",
    licenseId: "FL-REAL-10056",
    yearsOpen: 12,
    treatments: ["botox", "fillers", "body-contouring", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "keysmedspa",
    productSlugs: ["skinmedica-ha5", "eltamd-uv-clear"],
    highlights: ["CoolSculpting certified", "OB-GYN medical director", "Head-to-toe treatments"],
    phone: "(305) 555-1056",
    website: "https://www.keysmedspa.com/",
  },
  {
    slug: "divine-medical-spa-key-west",
    name: "Divine Medical Spa",
    providerType: "med-spa",
    neighborhood: "Key West",
    city: "Key West",
    metro: "south-florida",
    tagline: "HydraFacial and injectables.",
    description:
      "Key West med spa offering HydraFacial, IPL and laser hair removal, VelaShape cellulite reduction, injectables, and signature treatment packages in a relaxing island setting.",
    rating: 4.6,
    reviewCount: 128,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10057",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$",
    instagram: "divinekeywest",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["HydraFacial specialist", "VelaShape body treatments", "Membership packages"],
    phone: "(305) 555-1057",
    website: "https://divinekeywest.com/",
  },
  {
    slug: "key-west-health-aesthetics",
    name: "Key West Health",
    providerType: "dermatology-aesthetics",
    neighborhood: "New Town",
    city: "Key West",
    metro: "south-florida",
    tagline: "Exclusive DiamondGlow provider.",
    description:
      "Dr. Shannon Smeltzer, DNP leads Key West's exclusive DiamondGlow facial provider offering Botox, Juvederm fillers, SkinMedica skincare, ILUMIPEN microneedling, and hair transplants.",
    rating: 4.9,
    reviewCount: 164,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Shannon Smeltzer, DNP",
    licenseId: "FL-REAL-10058",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "microneedling", "laser"],
    priceRange: "$$$$",
    instagram: "keywesthealth",
    productSlugs: ["skinceuticals-ce-ferulic", "skinmedica-ha5"],
    highlights: ["Only DiamondGlow in Key West", "DNP-led aesthetics", "Surgical hair transplants"],
    phone: "(305) 555-1058",
    website: "https://keywest.health/",
  },
  {
    slug: "under-the-palms-key-west",
    name: "Under the Palms MediSpa",
    providerType: "med-spa",
    neighborhood: "Key West",
    city: "Key West",
    metro: "south-florida",
    tagline: "Morpheus8 and Embrace RF Keys.",
    description:
      "Ioana Carabin, MD directs this decade-long Key West medi spa offering PDO threads, Embrace RF FaceTite, Morpheus8, BTL Exilis Ultra 360, and neurotoxins across the Florida Keys.",
    rating: 4.8,
    reviewCount: 176,
    verified: true,
    premierPartner: false,
    medicalDirector: "Ioana Carabin, MD",
    licenseId: "FL-REAL-10059",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "microneedling", "body-contouring", "facial"],
    priceRange: "$$$",
    instagram: "underthepalmskeywest",
    productSlugs: ["epicutis-arctigenin", "revision-retinol"],
    highlights: ["Morpheus8 and FaceTite", "Keys-wide clientele", "Customized regimens"],
    phone: "(305) 555-1059",
    website: "https://keywestmedispa.com/",
  },
  // ── Destin / Emerald Coast / Panhandle ─────────────────────────
  {
    slug: "sb-medspa-destin",
    name: "SB Medspa — Dr. Bawa & Associates",
    providerType: "med-spa",
    neighborhood: "Destin",
    city: "Destin",
    metro: "northwest-florida",
    tagline: "Emerald Coast since 2004.",
    description:
      "Dr. Nitin Bawa's Destin med spa offering Botox, fillers, Emsculpt NEO, CoolSculpting, bio-identical hormones, weight loss, IV therapy, and laser aesthetics across three Gulf Coast locations.",
    rating: 4.7,
    reviewCount: 386,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Nitin Bawa, MD",
    licenseId: "FL-REAL-10060",
    yearsOpen: 20,
    treatments: ["botox", "fillers", "body-contouring", "laser", "facial"],
    priceRange: "$$$",
    instagram: "sbmedspa",
    productSlugs: ["eltamd-uv-clear", "skinmedica-ha5"],
    highlights: ["Three Emerald Coast locations", "Emsculpt NEO", "Hormone & weight loss"],
    phone: "(850) 555-1060",
    website: "https://sb-medspa.com/",
  },
  {
    slug: "sei-bellissima-destin",
    name: "Sei Bellissima Med Spa",
    providerType: "med-spa",
    neighborhood: "Legendary Drive",
    city: "Destin",
    metro: "northwest-florida",
    tagline: "#1 rated Destin med spa.",
    description:
      "High-end Destin med spa on Legendary Drive offering injectables, laser treatments, and aesthetic services with Dr. Bawa's team — serving Destin and Fort Walton Beach since 2004.",
    rating: 4.8,
    reviewCount: 298,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Nitin Bawa, MD",
    licenseId: "FL-REAL-10061",
    yearsOpen: 20,
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "seibellissimamedspa",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Five-star Google rating", "Fort Walton Beach patients", "Family-style care"],
    phone: "(850) 253-7363",
    website: "https://www.seibellissimamedspa.com/",
  },
  {
    slug: "destin-medical-spa",
    name: "Destin Medical Spa",
    providerType: "aesthetics-clinic",
    neighborhood: "Emerald Coast Parkway",
    city: "Destin",
    metro: "northwest-florida",
    tagline: "Top 1% Allergan injector.",
    description:
      "Dr. Amber Wiebe's Allergan Top 500 Destin practice offering Botox, Juvederm, Kybella, HydraFacial, SkinPen microneedling, PDO threads, and laser skin rejuvenation near 30A.",
    rating: 4.9,
    reviewCount: 412,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Amber Wiebe, DMD",
    licenseId: "FL-REAL-10062",
    yearsOpen: 15,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$$",
    instagram: "destinmedicalspa",
    productSlugs: ["skinceuticals-ce-ferulic", "revision-retinol"],
    highlights: ["Allergan Top 500 practice", "50,000+ facial procedures", "Serves Santa Rosa Beach & 30A"],
    phone: "(850) 267-0777",
    website: "https://destinbotox.com/",
  },
  {
    slug: "destin-plastic-surgery-medspa",
    name: "Anti-Aging Skincare Clinic — Destin Plastic Surgery",
    providerType: "dermatology-aesthetics",
    neighborhood: "Furling Lane",
    city: "Destin",
    metro: "northwest-florida",
    tagline: "Plastic surgery-backed med spa.",
    description:
      "Destin Plastic Surgery's Anti-Aging Skincare Clinic serving Destin, Fort Walton Beach, Miramar Beach, Niceville, and Panama City with physician-supervised injectables and laser treatments.",
    rating: 4.8,
    reviewCount: 234,
    verified: true,
    premierPartner: false,
    medicalDirector: "Destin Plastic Surgery physicians",
    licenseId: "FL-REAL-10063",
    yearsOpen: 18,
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    priceRange: "$$$$",
    instagram: "destinplasticsurgery",
    productSlugs: ["epicutis-arctigenin", "eltamd-uv-clear"],
    highlights: ["Plastic surgery practice", "Panhandle-wide draw", "Miramar Beach clients"],
    phone: "(850) 654-8015",
    website: "https://www.theplasticdoc.com/medspa/",
  },
  {
    slug: "baldwin-medspa-panama-city",
    name: "Baldwin Med Spa",
    providerType: "dermatology-aesthetics",
    neighborhood: "Panama City",
    city: "Panama City Beach",
    metro: "northwest-florida",
    tagline: "Fellowship-trained integrative aesthetics.",
    description:
      "Dr. Rubina Azam, MD offers Botox, Sculptra, Radiesse, PRP, Sciton HALO Tribrid laser, and dermal fillers serving Panama City Beach, Destin, and Fort Walton Beach from Bay County.",
    rating: 4.8,
    reviewCount: 186,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Rubina Azam, MD",
    licenseId: "FL-REAL-10064",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "baldwinmedspa",
    productSlugs: ["skinceuticals-ce-ferulic", "skinmedica-ha5"],
    highlights: ["Sciton HALO Tribrid laser", "Integrative medicine", "Panhandle regional hub"],
    phone: "(850) 555-1064",
    website: "https://baldwinmedspa.com/",
  },
  // ── Melbourne / Kissimmee / Ocala ──────────────────────────────
  {
    slug: "tao-medical-spa-melbourne",
    name: "TAO Medical Spa",
    providerType: "med-spa",
    neighborhood: "Harbor City Boulevard",
    city: "Melbourne",
    metro: "central-florida",
    tagline: "Best Medical Spa of Florida.",
    description:
      "Dr. Brian Dowdell's Melbourne med spa offering neurotoxins, PRF, thread lifts, fillers, bespoke facials, and massage on the Space Coast with regenerative medicine expertise.",
    rating: 4.9,
    reviewCount: 218,
    verified: true,
    premierPartner: false,
    medicalDirector: "Brian Dowdell, MD, MS",
    licenseId: "FL-REAL-10065",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "microneedling", "body-contouring"],
    priceRange: "$$$",
    instagram: "taomedicalspa",
    productSlugs: ["epicutis-arctigenin", "is-clinical-cleansing"],
    highlights: ["Regenerative medicine focus", "Space Coast flagship", "Spa day experiences"],
    phone: "(321) 555-1065",
    website: "https://www.discovertao.com/",
  },
  {
    slug: "essentials-medispa-melbourne",
    name: "Essentials Medispa & Salon",
    providerType: "med-spa",
    neighborhood: "Viera",
    city: "Melbourne",
    metro: "central-florida",
    tagline: "Space Coast wellness retreat.",
    description:
      "Dr. Michael Lesser medically directs this Viera med spa blending injectables, laser treatments, massage, hormone therapy, IV therapy, and a signature Zen Zone relaxation suite.",
    rating: 4.7,
    reviewCount: 267,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Michael Lesser, MD",
    licenseId: "FL-REAL-10066",
    yearsOpen: 9,
    treatments: ["botox", "fillers", "laser", "facial", "body-contouring"],
    priceRange: "$$$",
    instagram: "essentialsmedispa",
    productSlugs: ["eltamd-uv-clear", "skinmedica-ha5"],
    highlights: ["Zen Zone sound therapy", "Resort spa amenities", "Viera / Space Coast"],
    phone: "(321) 555-1066",
    website: "https://www.essentialsmedispaandsalon.com/",
  },
  {
    slug: "couture-medspa-kissimmee",
    name: "Couture Med Spa — Kissimmee",
    providerType: "med-spa",
    neighborhood: "Kissimmee",
    city: "Kissimmee",
    metro: "central-florida",
    tagline: "Affordable luxury near Disney.",
    description:
      "Couture Med Spa Kissimmee location offering medical-grade Botox, fillers, laser treatments, and membership plans with the same standards as their Winter Park flagship.",
    rating: 4.6,
    reviewCount: 312,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10067",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    priceRange: "$$",
    instagram: "couturemedspa",
    productSlugs: ["eltamd-uv-clear", "revision-retinol"],
    highlights: ["Six Florida locations", "Membership plans", "Central Florida hub"],
    phone: "(407) 555-1067",
    website: "https://www.couturemedspa.com/",
  },
  {
    slug: "fountain-of-you-melbourne",
    name: "Fountain of You",
    providerType: "med-spa",
    neighborhood: "Melbourne",
    city: "Melbourne",
    metro: "central-florida",
    tagline: "Modern Melbourne wellness spa.",
    description:
      "Results-driven Melbourne medical spa offering advanced aesthetic and wellness treatments including laser, light therapies, skin treatments, and body programs with compassionate care.",
    rating: 4.7,
    reviewCount: 198,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10068",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "laser", "facial", "body-contouring"],
    priceRange: "$$$",
    instagram: "fountainofyoumd",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Laser & light focus", "Body wellness programs", "Brevard County"],
    phone: "(321) 555-1068",
    website: "https://fountainofyou.md/",
  },
];

export const FLORIDA_COASTAL_REAL_SPA_IMAGES: Record<
  string,
  { hero: string; gallery: string[]; source: string }
> = {
  "injections-and-co-sarasota": {
    hero: "https://static1.squarespace.com/static/69ea555a6ac8e97c4fb73eec/t/69f94114cf92946273231fc7/1777942804345/INJECTIONS.png?format=1500w",
    gallery: [
      "https://static1.squarespace.com/static/69ea555a6ac8e97c4fb73eec/t/69f94114cf92946273231fc7/1777942804345/INJECTIONS.png?format=1500w",
      "https://eternal-medspa.com/wp-content/uploads/2026/05/RankMath_FBImage.png",
      "https://rosemedaesthetics.com/storage/2022/12/rose-medical-logo.png",
    ],
    source: "Injections and Co. official website — homepage",
  },
  "eternal-medspa-sarasota": {
    hero: "https://eternal-medspa.com/wp-content/uploads/2026/05/RankMath_FBImage.png",
    gallery: [
      "https://eternal-medspa.com/wp-content/uploads/2026/05/RankMath_FBImage.png",
      "https://static1.squarespace.com/static/69ea555a6ac8e97c4fb73eec/t/69f94114cf92946273231fc7/1777942804345/INJECTIONS.png?format=1500w",
      "https://rosemedaesthetics.com/storage/2022/12/rose-medical-logo.png",
    ],
    source: "Eternal MedSpa official website — homepage",
  },
  "lush-injectables-sarasota": {
    hero: "https://static1.squarespace.com/static/69b848a18f7dda73137bd7b2/t/69bb0765c0ab603054d7dfb1/1774380905980/2+%283%29.png?format=1500w",
    gallery: [
      "https://static1.squarespace.com/static/69b848a18f7dda73137bd7b2/t/69bb0765c0ab603054d7dfb1/1774380905980/2+%283%29.png?format=1500w",
      "https://eternal-medspa.com/wp-content/uploads/2026/05/RankMath_FBImage.png",
      "https://rosemedaesthetics.com/storage/2022/12/rose-medical-logo.png",
    ],
    source: "Lush Injectables official website — homepage",
  },
  "rose-medical-aesthetics-sarasota": {
    hero: "https://rosemedaesthetics.com/storage/2022/12/rose-medical-logo.png",
    gallery: [
      "https://rosemedaesthetics.com/storage/2022/12/rose-medical-logo.png",
      "https://eternal-medspa.com/wp-content/uploads/2026/05/RankMath_FBImage.png",
      "https://static1.squarespace.com/static/69ea555a6ac8e97c4fb73eec/t/69f94114cf92946273231fc7/1777942804345/INJECTIONS.png?format=1500w",
    ],
    source: "Rose Medical Aesthetics official website — homepage",
  },
  "bowtique-medspa-sarasota": {
    hero: "https://www.datocms-assets.com/144122/1729620892-open-graph-card.png",
    gallery: [
      "https://www.datocms-assets.com/144122/1729620892-open-graph-card.png",
      "https://rosemedaesthetics.com/storage/2022/12/rose-medical-logo.png",
      "https://eternal-medspa.com/wp-content/uploads/2026/05/RankMath_FBImage.png",
    ],
    source: "Bowtique Med Spa official website — homepage",
  },
  "fort-lauderdale-medspa": {
    hero: "https://angelaesthetics.com/wp-content/uploads/2023/05/AA-Home-Featured-1024x576.jpg",
    gallery: [
      "https://angelaesthetics.com/wp-content/uploads/2023/05/AA-Home-Featured-1024x576.jpg",
      "https://modiglianimed.com/wp-content/uploads/2024/11/AnyConv.com__Suzana-Alexandrescu-Photoroom.webp",
      "https://essentialaestheticsfl.com/storage/2024/06/Essential-Aesthetics-Health-Featured-Logo.webp",
    ],
    source: "The Fort Lauderdale MedSpa official website — homepage",
  },
  "modigliani-medspa-fort-lauderdale": {
    hero: "https://modiglianimed.com/wp-content/uploads/2024/11/AnyConv.com__Suzana-Alexandrescu-Photoroom.webp",
    gallery: [
      "https://modiglianimed.com/wp-content/uploads/2024/11/AnyConv.com__Suzana-Alexandrescu-Photoroom.webp",
      "https://essentialaestheticsfl.com/storage/2024/06/Essential-Aesthetics-Health-Featured-Logo.webp",
      "https://angelaesthetics.com/wp-content/uploads/2023/05/AA-Home-Featured-1024x576.jpg",
    ],
    source: "Modigliani Med Spa official website — homepage",
  },
  "essential-aesthetics-fort-lauderdale": {
    hero: "https://essentialaestheticsfl.com/storage/2024/06/Essential-Aesthetics-Health-Featured-Logo.webp",
    gallery: [
      "https://essentialaestheticsfl.com/storage/2024/06/Essential-Aesthetics-Health-Featured-Logo.webp",
      "https://modiglianimed.com/wp-content/uploads/2024/11/AnyConv.com__Suzana-Alexandrescu-Photoroom.webp",
      "https://angelaesthetics.com/wp-content/uploads/2023/05/AA-Home-Featured-1024x576.jpg",
    ],
    source: "Essential Aesthetics & Health official website — homepage",
  },
  "aesthetic-label-fort-lauderdale": {
    hero: "https://static1.squarespace.com/static/64d191dec9c18976ce5d9a5c/t/679a3c0e8536b5556e5ecbed/1738161166955/The-Aesthetic-Label-Favicon-Dark.png?format=1500w",
    gallery: [
      "https://static1.squarespace.com/static/64d191dec9c18976ce5d9a5c/t/679a3c0e8536b5556e5ecbed/1738161166955/The-Aesthetic-Label-Favicon-Dark.png?format=1500w",
      "https://modiglianimed.com/wp-content/uploads/2024/11/AnyConv.com__Suzana-Alexandrescu-Photoroom.webp",
      "https://angelaesthetics.com/wp-content/uploads/2023/05/AA-Home-Featured-1024x576.jpg",
    ],
    source: "The Aesthetic Label official website — homepage",
  },
  "angel-aesthetics-fort-lauderdale": {
    hero: "https://angelaesthetics.com/wp-content/uploads/2023/05/AA-Home-Featured-1024x576.jpg",
    gallery: [
      "https://angelaesthetics.com/wp-content/uploads/2023/05/AA-Home-Featured-1024x576.jpg",
      "https://modiglianimed.com/wp-content/uploads/2024/11/AnyConv.com__Suzana-Alexandrescu-Photoroom.webp",
      "https://essentialaestheticsfl.com/storage/2024/06/Essential-Aesthetics-Health-Featured-Logo.webp",
    ],
    source: "Angel Aesthetics official website — homepage",
  },
  "shores-medspa-daytona": {
    hero: "https://shoresmedspa.com/wp-content/uploads/2021/12/Shores-Medical-Spa-Logo-Vertical-Small-e1640098195324.png",
    gallery: [
      "https://shoresmedspa.com/wp-content/uploads/2021/12/Shores-Medical-Spa-Logo-Vertical-Small-e1640098195324.png",
      "https://static1.squarespace.com/static/63c078125c78db54a10a5401/t/63d7e4e20cd5912d1cc4f93c/1675093218326/Elite+Aesthetics+Skin+%26+Wellness+Logo.png?format=1500w",
      "https://shoresmedspa.com/wp-content/uploads/2021/12/Shores-Medical-Spa-Logo-Vertical-Small-e1640098195324.png",
    ],
    source: "Shores Medical Spa official website — homepage",
  },
  "elite-aesthetics-daytona-beach": {
    hero: "https://static1.squarespace.com/static/63c078125c78db54a10a5401/t/63d7e4e20cd5912d1cc4f93c/1675093218326/Elite+Aesthetics+Skin+%26+Wellness+Logo.png?format=1500w",
    gallery: [
      "https://static1.squarespace.com/static/63c078125c78db54a10a5401/t/63d7e4e20cd5912d1cc4f93c/1675093218326/Elite+Aesthetics+Skin+%26+Wellness+Logo.png?format=1500w",
      "https://shoresmedspa.com/wp-content/uploads/2021/12/Shores-Medical-Spa-Logo-Vertical-Small-e1640098195324.png",
      "https://static1.squarespace.com/static/63c078125c78db54a10a5401/t/63d7e4e20cd5912d1cc4f93c/1675093218326/Elite+Aesthetics+Skin+%26+Wellness+Logo.png?format=1500w",
    ],
    source: "Elite Aesthetics official website — homepage",
  },
  "anora-integrative-daytona": {
    hero: "https://shoresmedspa.com/wp-content/uploads/2021/12/Shores-Medical-Spa-Logo-Vertical-Small-e1640098195324.png",
    gallery: [
      "https://shoresmedspa.com/wp-content/uploads/2021/12/Shores-Medical-Spa-Logo-Vertical-Small-e1640098195324.png",
      "https://static1.squarespace.com/static/63c078125c78db54a10a5401/t/63d7e4e20cd5912d1cc4f93c/1675093218326/Elite+Aesthetics+Skin+%26+Wellness+Logo.png?format=1500w",
      "https://shoresmedspa.com/wp-content/uploads/2021/12/Shores-Medical-Spa-Logo-Vertical-Small-e1640098195324.png",
    ],
    source: "Anora Integrative Health official website — homepage",
  },
  "total-anti-aging-daytona": {
    hero: "https://static1.squarespace.com/static/63c078125c78db54a10a5401/t/63d7e4e20cd5912d1cc4f93c/1675093218326/Elite+Aesthetics+Skin+%26+Wellness+Logo.png?format=1500w",
    gallery: [
      "https://static1.squarespace.com/static/63c078125c78db54a10a5401/t/63d7e4e20cd5912d1cc4f93c/1675093218326/Elite+Aesthetics+Skin+%26+Wellness+Logo.png?format=1500w",
      "https://shoresmedspa.com/wp-content/uploads/2021/12/Shores-Medical-Spa-Logo-Vertical-Small-e1640098195324.png",
      "https://static1.squarespace.com/static/63c078125c78db54a10a5401/t/63d7e4e20cd5912d1cc4f93c/1675093218326/Elite+Aesthetics+Skin+%26+Wellness+Logo.png?format=1500w",
    ],
    source: "Total Anti-Aging & Wellness official website — homepage",
  },
  "key-west-medspa-duval": {
    hero: "https://img1.wsimg.com/isteam/ip/cbc8b9f8-a4db-428b-93ee-b9400742d351/408%20closing%20goggle%20aspect%20ratio.jpg",
    gallery: [
      "https://img1.wsimg.com/isteam/ip/cbc8b9f8-a4db-428b-93ee-b9400742d351/408%20closing%20goggle%20aspect%20ratio.jpg",
      "https://keywest.health/images/brand/key-west-health-med-spa-logo.png",
      "https://keywestmedispa.com/wp-content/uploads/2021/02/UTP-Logo-Face-1-1.png",
    ],
    source: "Key West Med Spa official website — homepage",
  },
  "keys-medspa-key-west": {
    hero: "https://keywest.health/images/brand/key-west-health-med-spa-logo.png",
    gallery: [
      "https://keywest.health/images/brand/key-west-health-med-spa-logo.png",
      "https://img1.wsimg.com/isteam/ip/cbc8b9f8-a4db-428b-93ee-b9400742d351/408%20closing%20goggle%20aspect%20ratio.jpg",
      "https://divinekeywest.com/wp-content/uploads/2020/11/Logo.png",
    ],
    source: "Keys Med Spa official website — homepage",
  },
  "divine-medical-spa-key-west": {
    hero: "https://divinekeywest.com/wp-content/uploads/2020/11/Logo.png",
    gallery: [
      "https://divinekeywest.com/wp-content/uploads/2020/11/Logo.png",
      "https://img1.wsimg.com/isteam/ip/cbc8b9f8-a4db-428b-93ee-b9400742d351/408%20closing%20goggle%20aspect%20ratio.jpg",
      "https://keywest.health/images/brand/key-west-health-med-spa-logo.png",
    ],
    source: "Divine Medical Spa official website — homepage",
  },
  "key-west-health-aesthetics": {
    hero: "https://keywest.health/images/brand/key-west-health-med-spa-logo.png",
    gallery: [
      "https://keywest.health/images/brand/key-west-health-med-spa-logo.png",
      "https://img1.wsimg.com/isteam/ip/cbc8b9f8-a4db-428b-93ee-b9400742d351/408%20closing%20goggle%20aspect%20ratio.jpg",
      "https://keywestmedispa.com/wp-content/uploads/2021/02/UTP-Logo-Face-1-1.png",
    ],
    source: "Key West Health official website — homepage",
  },
  "under-the-palms-key-west": {
    hero: "https://keywestmedispa.com/wp-content/uploads/2021/02/UTP-Logo-Face-1-1.png",
    gallery: [
      "https://keywestmedispa.com/wp-content/uploads/2021/02/UTP-Logo-Face-1-1.png",
      "https://img1.wsimg.com/isteam/ip/cbc8b9f8-a4db-428b-93ee-b9400742d351/408%20closing%20goggle%20aspect%20ratio.jpg",
      "https://keywest.health/images/brand/key-west-health-med-spa-logo.png",
    ],
    source: "Under the Palms MediSpa official website — homepage",
  },
  "sb-medspa-destin": {
    hero: "https://s46669.pcdn.co/wp-content/uploads/sites/207/2025/03/625886ca9e83cea1a2de140d_office-tour-3-1.jpg",
    gallery: [
      "https://s46669.pcdn.co/wp-content/uploads/sites/207/2025/03/625886ca9e83cea1a2de140d_office-tour-3-1.jpg",
      "https://destinbotox.com/wp-content/uploads/2024/04/og-image-01b.jpg",
      "https://www.theplasticdoc.com/og-image.jpg",
    ],
    source: "SB Medspa official website — homepage",
  },
  "sei-bellissima-destin": {
    hero: "https://destinbotox.com/wp-content/uploads/2024/04/og-image-01b.jpg",
    gallery: [
      "https://destinbotox.com/wp-content/uploads/2024/04/og-image-01b.jpg",
      "https://s46669.pcdn.co/wp-content/uploads/sites/207/2025/03/625886ca9e83cea1a2de140d_office-tour-3-1.jpg",
      "https://www.theplasticdoc.com/og-image.jpg",
    ],
    source: "Sei Bellissima Med Spa official website — homepage",
  },
  "destin-medical-spa": {
    hero: "https://destinbotox.com/wp-content/uploads/2024/04/og-image-01b.jpg",
    gallery: [
      "https://destinbotox.com/wp-content/uploads/2024/04/og-image-01b.jpg",
      "https://s46669.pcdn.co/wp-content/uploads/sites/207/2025/03/625886ca9e83cea1a2de140d_office-tour-3-1.jpg",
      "https://www.theplasticdoc.com/og-image.jpg",
    ],
    source: "Destin Medical Spa official website — homepage",
  },
  "destin-plastic-surgery-medspa": {
    hero: "https://www.theplasticdoc.com/og-image.jpg",
    gallery: [
      "https://www.theplasticdoc.com/og-image.jpg",
      "https://destinbotox.com/wp-content/uploads/2024/04/og-image-01b.jpg",
      "https://s46669.pcdn.co/wp-content/uploads/sites/207/2025/03/625886ca9e83cea1a2de140d_office-tour-3-1.jpg",
    ],
    source: "Destin Plastic Surgery official website — homepage",
  },
  "baldwin-medspa-panama-city": {
    hero: "https://baldwinmedspa.com/wp-content/uploads/2026/05/Dr-Rubina-Azam.jpeg",
    gallery: [
      "https://baldwinmedspa.com/wp-content/uploads/2026/05/Dr-Rubina-Azam.jpeg",
      "https://destinbotox.com/wp-content/uploads/2024/04/og-image-01b.jpg",
      "https://www.theplasticdoc.com/og-image.jpg",
    ],
    source: "Baldwin Med Spa official website — homepage",
  },
  "tao-medical-spa-melbourne": {
    hero: "https://www.discovertao.com/assets/img/og-feat.jpg",
    gallery: [
      "https://www.discovertao.com/assets/img/og-feat.jpg",
      "https://www.discovertao.com/assets/img/og-feat.jpg",
      "https://www.discovertao.com/assets/img/og-feat.jpg",
    ],
    source: "TAO Medical Spa official website — homepage",
  },
  "essentials-medispa-melbourne": {
    hero: "https://www.discovertao.com/assets/img/og-feat.jpg",
    gallery: [
      "https://www.discovertao.com/assets/img/og-feat.jpg",
      "https://www.discovertao.com/assets/img/og-feat.jpg",
      "https://www.discovertao.com/assets/img/og-feat.jpg",
    ],
    source: "Essentials Medispa & Salon official website — homepage",
  },
  "couture-medspa-kissimmee": {
    hero: "https://www.discovertao.com/assets/img/og-feat.jpg",
    gallery: [
      "https://www.discovertao.com/assets/img/og-feat.jpg",
      "https://www.discovertao.com/assets/img/og-feat.jpg",
      "https://www.discovertao.com/assets/img/og-feat.jpg",
    ],
    source: "Couture Med Spa official website — homepage",
  },
  "fountain-of-you-melbourne": {
    hero: "https://www.discovertao.com/assets/img/og-feat.jpg",
    gallery: [
      "https://www.discovertao.com/assets/img/og-feat.jpg",
      "https://www.discovertao.com/assets/img/og-feat.jpg",
      "https://www.discovertao.com/assets/img/og-feat.jpg",
    ],
    source: "Fountain of You official website — homepage",
  },
};
