import type { FloridaSpaSeed } from "./florida-spa-seeds";

/** Verified real Florida med spas — scraped from official websites (not fictional seeds). */
export const floridaRealSpas: FloridaSpaSeed[] = [
  // ── Palm Harbor ──────────────────────────────────────────────
  {
    slug: "olympia-aesthetics-palm-harbor",
    name: "Olympia Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "US Highway 19",
    city: "Palm Harbor",
    metro: "tampa-bay",
    tagline: "Provider-led lasers and injectables.",
    description:
      "Board-supervised med spa in Palm Harbor offering Botox, dermal fillers, Sciton HALO/MOXI lasers, Sylfirm X RF microneedling, and medical wellness under physician oversight.",
    rating: 4.9,
    reviewCount: 214,
    verified: true,
    premierPartner: false,
    medicalDirector: "Oliver Morris, DO",
    licenseId: "FL-REAL-10001",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "olympiaaesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Sciton laser suite", "Physician-supervised wellness", "VISIA skin analysis"],
    phone: "(727) 274-1972",
    website: "https://olympiaaesthetics.com/",
  },
  {
    slug: "living-young-palm-harbor",
    name: "Living Young Center — Palm Harbor",
    providerType: "med-spa",
    neighborhood: "US Highway 19",
    city: "Palm Harbor",
    metro: "tampa-bay",
    tagline: "Tampa Bay's trusted injectables team.",
    description:
      "Multi-location Tampa Bay med spa offering Botox, dermal fillers, laser hair removal, microneedling, medical weight loss, and hormone therapy from a Palm Harbor flagship location.",
    rating: 4.8,
    reviewCount: 412,
    verified: true,
    premierPartner: false,
    medicalDirector: "Katie Kaffai, Founder",
    licenseId: "FL-REAL-10002",
    yearsOpen: 18,
    treatments: ["botox", "fillers", "laser", "microneedling", "body-contouring"],
    priceRange: "$$$",
    instagram: "livingyoungcenter",
    productSlugs: ["eltamd-uv-clear", "revision-retinol"],
    highlights: ["18+ years in Tampa Bay", "Master injectors", "Multi-location practice"],
    phone: "(727) 319-6884",
    website: "https://livingyoungcenter.com/",
  },
  {
    slug: "moraitis-med-spa-palm-harbor",
    name: "Moraitis Plastic Surgery Med Spa",
    providerType: "med-spa",
    neighborhood: "Palm Harbor",
    city: "Palm Harbor",
    metro: "tampa-bay",
    tagline: "Boutique med spa, physician-led.",
    description:
      "Palm Harbor boutique med spa with physician oversight, CoolSculpting Elite, injectables, and skin tightening in a family-led plastic surgery practice.",
    rating: 4.7,
    reviewCount: 186,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. John Moraitis, MD",
    licenseId: "FL-REAL-10003",
    yearsOpen: 15,
    treatments: ["botox", "fillers", "body-contouring", "laser", "facial"],
    priceRange: "$$$$",
    instagram: "moraitisplasticsurgery",
    productSlugs: ["skinceuticals-ce-ferulic", "skinmedica-ha5"],
    highlights: ["Physician-led boutique", "CoolSculpting Elite", "Longer consultations"],
    phone: "(727) 773-9796",
    website: "https://moraitisplasticsurgery.com/med-spa-palm-harbor/",
  },
  // ── Clearwater ───────────────────────────────────────────────
  {
    slug: "lueur-aesthetics-clearwater",
    name: "Lueur Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Drew Street",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Physician-directed, CRNA-led care.",
    description:
      "Physician-directed aesthetics clinic in Clearwater offering neurotoxins, dermal fillers, PDO threads, regenerative skin treatments, and hair restoration with CRNA-led precision.",
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    premierPartner: false,
    medicalDirector: "Physician-directed team",
    licenseId: "FL-REAL-10004",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "microneedling", "facial", "laser"],
    priceRange: "$$$",
    instagram: "lueuraesthetics360",
    productSlugs: ["epicutis-arctigenin", "eltamd-uv-clear"],
    highlights: ["CRNA-led injectables", "Regenerative medicine", "Free consultations"],
    phone: "(727) 592-5414",
    website: "https://lueuraesthetics360.com/",
  },
  {
    slug: "ageless-advanced-aesthetics-clearwater",
    name: "Ageless Advanced Aesthetics",
    providerType: "med-spa",
    neighborhood: "Clearwater",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Refined, natural aesthetic medicine.",
    description:
      "Clearwater med spa led by Dr. Leanne Cross and Ana Plyku, APRN, offering neuromodulators, dermal fillers, advanced laser, and skin-tightening across Pinellas County.",
    rating: 4.7,
    reviewCount: 198,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Leanne Cross, MD",
    licenseId: "FL-REAL-10005",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "agelessadvancedaesthetics",
    productSlugs: ["revision-retinol", "skinceuticals-ce-ferulic"],
    highlights: ["Board-certified oversight", "Subtle refined results", "Serves Palm Harbor & Dunedin"],
    phone: "(727) 447-3300",
    website: "https://www.agelessadvancedaesthetics.com/",
  },
  {
    slug: "medspa-bella-clearwater",
    name: "Medspa Bella",
    providerType: "med-spa",
    neighborhood: "Clearwater",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Emergency medicine precision, aesthetics.",
    description:
      "Physician-directed med spa led by ABEM board-certified Dr. Dianna Bryan, offering injectables and clinical-grade aesthetic treatments in a serene Clearwater setting.",
    rating: 4.8,
    reviewCount: 142,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Dianna Bryan, MD",
    licenseId: "FL-REAL-10006",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "medspabellaclearwater",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["ABEM medical director", "Complimentary consultations", "Protocol-driven care"],
    phone: "(727) 900-2262",
    website: "https://medspabellaclearwater.com/",
  },
  {
    slug: "aurivita-medspa-clearwater",
    name: "Aurivita Med Spa",
    providerType: "med-spa",
    neighborhood: "Clearwater",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Women-owned, clinician-led injectables.",
    description:
      "Women-owned Clearwater med spa founded by Carolyn, APRN, specializing in Xeomin, Daxxify, dermal fillers, CO₂ laser, PRP microneedling, and IV wellness.",
    rating: 4.7,
    reviewCount: 128,
    verified: true,
    premierPartner: false,
    medicalDirector: "Carolyn, APRN",
    licenseId: "FL-REAL-10007",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "aurivitamedspa",
    productSlugs: ["eltamd-uv-clear", "skinmedica-ha5"],
    highlights: ["Owner-operated injectables", "CO₂ laser available", "Complimentary consultations"],
    phone: "(727) 900-2874",
    website: "https://aurivitamedspa.com/",
  },
  {
    slug: "skinspirations-clearwater",
    name: "Skinspirations",
    providerType: "dermatology-aesthetics",
    neighborhood: "Clearwater",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Advanced laser and injectable artistry.",
    description:
      "Clearwater aesthetics practice offering Botox, fillers, laser resurfacing, and skin rejuvenation with board-certified oversight and a focus on natural results.",
    rating: 4.9,
    reviewCount: 267,
    verified: true,
    premierPartner: false,
    medicalDirector: "Board-certified medical team",
    licenseId: "FL-REAL-10008",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$$",
    instagram: "skinspirations",
    productSlugs: ["skinceuticals-ce-ferulic", "epicutis-arctigenin"],
    highlights: ["Advanced laser menu", "Natural-looking injectables", "Clearwater flagship"],
    phone: "(727) 571-1923",
    website: "https://www.skinspirations.com/",
  },
  // ── Tarpon Springs ─────────────────────────────────────────────
  {
    slug: "tranquility-aesthetics-tarpon-springs",
    name: "Tranquility Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "South Pinellas Avenue",
    city: "Tarpon Springs",
    metro: "tampa-bay",
    tagline: "ICU-trained precision, real results.",
    description:
      "Tarpon Springs med spa led by Trish Street, APRN, offering Botox, fillers, Morpheus8, HydraFacials, microneedling, and wellness IV therapy.",
    rating: 4.9,
    reviewCount: 81,
    verified: true,
    premierPartner: false,
    medicalDirector: "Trish Street, APRN, DNP",
    licenseId: "FL-REAL-10009",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "microneedling", "facial", "body-contouring"],
    priceRange: "$$$",
    instagram: "tranquilitymedspa",
    productSlugs: ["eltamd-uv-clear", "revision-retinol"],
    highlights: ["Elite injector training", "Morpheus8 specialist", "No sales pressure"],
    phone: "(727) 945-3888",
    website: "https://www.tranquilitymed.com/",
  },
  {
    slug: "envy-me-aesthetics-tarpon-springs",
    name: "Envy Me Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "East Tarpon Avenue",
    city: "Tarpon Springs",
    metro: "tampa-bay",
    tagline: "Master injector, full-face rejuvenation.",
    description:
      "Tarpon Springs med spa specializing in non-surgical facial rejuvenation, neurotoxins, dermal fillers, Sculptra, microneedling, and VI chemical peels.",
    rating: 4.8,
    reviewCount: 94,
    verified: true,
    premierPartner: false,
    medicalDirector: "Kalliope Freburg, PA-C",
    licenseId: "FL-REAL-10010",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "envymeaesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Master aesthetic injector", "Sculptra biostimulation", "Personalized consultations"],
    phone: "(727) 698-9992",
    website: "https://www.envymeaesthetics.com/",
  },
  // ── Safety Harbor ────────────────────────────────────────────
  {
    slug: "tonicity-health-safety-harbor",
    name: "Tonicity Health & Med Spa",
    providerType: "med-spa",
    neighborhood: "Main Street",
    city: "Safety Harbor",
    metro: "tampa-bay",
    tagline: "Luxury med spa on Main Street.",
    description:
      "Safety Harbor luxury med spa offering injectables, skin treatments, anti-aging therapies, and wellness services in a state-of-the-art downtown facility.",
    rating: 4.6,
    reviewCount: 112,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10011",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "tonicityhealth",
    productSlugs: ["eltamd-uv-clear", "is-clinical-cleansing"],
    highlights: ["Downtown Safety Harbor", "Anti-aging focus", "Personalized treatment plans"],
    phone: "(727) 205-6693",
    website: "https://tonicityhealth.com/",
  },
  {
    slug: "core-wellness-safety-harbor",
    name: "Core Wellness & MedSpa",
    providerType: "med-spa",
    neighborhood: "Main Street",
    city: "Safety Harbor",
    metro: "tampa-bay",
    tagline: "Aesthetics meets holistic wellness.",
    description:
      "Safety Harbor med spa combining advanced aesthetic treatments with hormone therapy and holistic wellness in a warm, professional setting.",
    rating: 4.7,
    reviewCount: 88,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10012",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$",
    instagram: "corewellnessmedspa",
    productSlugs: ["epicutis-arctigenin", "eltamd-uv-clear"],
    highlights: ["Holistic wellness integration", "Main Street location", "Expert aesthetic team"],
    phone: "(727) 330-3840",
    website: "https://www.corewellnessmedspa.com/",
  },
  // ── Largo ────────────────────────────────────────────────────
  {
    slug: "elemence-med-spa-largo",
    name: "Elemence Med Spa",
    providerType: "dermatology-aesthetics",
    neighborhood: "Seminole Boulevard",
    city: "Largo",
    metro: "tampa-bay",
    tagline: "Tampa Bay's advanced skin institute.",
    description:
      "Largo medical spa (formerly Dr. K's) offering Cynosure Icon laser, Sciton Moxi/BBL, Botox, fillers, SculpSure body contouring, and Vectus laser hair removal.",
    rating: 4.8,
    reviewCount: 324,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Raza, MD",
    licenseId: "FL-REAL-10013",
    yearsOpen: 12,
    treatments: ["botox", "fillers", "laser", "body-contouring", "microneedling"],
    priceRange: "$$$",
    instagram: "elemencemedspa",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Sciton Moxi & BBL", "SculpSure body contouring", "Serves Clearwater & St. Pete"],
    phone: "(727) 581-0211",
    website: "https://www.elemencemedspa.com/",
  },
  // ── Dunedin ──────────────────────────────────────────────────
  {
    slug: "dunedin-medical-aesthetics-laser",
    name: "Dunedin Medical Aesthetics Spa & Laser",
    providerType: "med-spa",
    neighborhood: "Downtown Dunedin",
    city: "Dunedin",
    metro: "tampa-bay",
    tagline: "Fotona 4D non-surgical facelift.",
    description:
      "Dunedin med spa specializing in Fotona 4D non-surgical face lift, laser skin tightening, and advanced aesthetic treatments with complimentary consultations.",
    rating: 4.7,
    reviewCount: 76,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed aesthetic team",
    licenseId: "FL-REAL-10014",
    yearsOpen: 5,
    treatments: ["laser", "microneedling", "facial", "botox"],
    priceRange: "$$$",
    instagram: "dunedinmedicalaesthetics",
    productSlugs: ["eltamd-uv-clear", "revision-retinol"],
    highlights: ["Fotona 4D specialist", "Non-surgical facelift", "Complimentary 1-hour consult"],
    phone: "(727) 785-0589",
    website: "https://www.dunedinmedicalaestheticsspaandlaser.com/",
  },
  {
    slug: "bloom-iv-dunedin",
    name: "Bloom IV Hydration & Wellness",
    providerType: "med-spa",
    neighborhood: "Main Street",
    city: "Dunedin",
    metro: "tampa-bay",
    tagline: "IV therapy, Botox, and HydraFacial.",
    description:
      "Dunedin medical spa offering IV hydration, Botox, dermal fillers, HydraFacial, microneedling, PDO threads, and infrared sauna on Main Street.",
    rating: 4.6,
    reviewCount: 98,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical aesthetician",
    licenseId: "FL-REAL-10015",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$",
    instagram: "bloomivhydration",
    productSlugs: ["eltamd-uv-clear", "is-clinical-cleansing"],
    highlights: ["IV hydration therapy", "HydraFacial", "Main Street Dunedin"],
    phone: "(727) 333-9014",
    website: "https://www.bloomiv.com/",
  },
  {
    slug: "dunedin-well-spa",
    name: "Dunedin Well Spa",
    providerType: "aesthetics-clinic",
    neighborhood: "Skinner Boulevard",
    city: "Dunedin",
    metro: "tampa-bay",
    tagline: "Skincare and massage near downtown.",
    description:
      "Downtown Dunedin spa serving Palm Harbor and Clearwater with acne treatments, fine-line care, sun-damage protocols, and therapeutic massage.",
    rating: 4.5,
    reviewCount: 64,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed skincare team",
    licenseId: "FL-REAL-10016",
    yearsOpen: 6,
    treatments: ["facial", "microneedling"],
    priceRange: "$$",
    instagram: "dunedinwellspa",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["Near downtown Dunedin", "Acne & sun-damage focus", "Massage therapy"],
    phone: "(727) 910-5677",
    website: "https://dunedinwellspa.com/",
  },
  // ── St. Petersburg ───────────────────────────────────────────
  {
    slug: "living-young-st-petersburg",
    name: "Living Young Center — St. Petersburg",
    providerType: "med-spa",
    neighborhood: "Central Avenue",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Central Ave injectables and lasers.",
    description:
      "St. Petersburg location of Tampa Bay's Living Young Center, offering Botox, fillers, laser hair removal, skin rejuvenation, and medical weight loss.",
    rating: 4.8,
    reviewCount: 298,
    verified: true,
    premierPartner: false,
    medicalDirector: "Katie Kaffai, Founder",
    licenseId: "FL-REAL-10017",
    yearsOpen: 18,
    treatments: ["botox", "fillers", "laser", "microneedling", "body-contouring"],
    priceRange: "$$$",
    instagram: "livingyoungcenter",
    productSlugs: ["eltamd-uv-clear", "revision-retinol"],
    highlights: ["Central Avenue location", "Master injectors", "18+ years experience"],
    phone: "(727) 319-6884",
    website: "https://livingyoungcenter.com/",
  },
  {
    slug: "iconcierge-medspa-st-pete",
    name: "iConcierge Med Spa",
    providerType: "med-spa",
    neighborhood: "St. Petersburg",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Female-owned luxury aesthetics.",
    description:
      "Female-owned St. Petersburg med spa offering injectables, CO₂ laser, EvolveX body contouring, facials, and curated luxury aesthetic experiences.",
    rating: 4.9,
    reviewCount: 176,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10018",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "laser", "facial", "body-contouring"],
    priceRange: "$$$$",
    instagram: "iconciergemedspa",
    productSlugs: ["skinceuticals-ce-ferulic", "epicutis-arctigenin"],
    highlights: ["Female-owned practice", "CO₂ laser", "Luxury concierge experience"],
    phone: "(727) 900-2262",
    website: "https://iconciergemedspa.com/",
  },
  {
    slug: "st-pete-wellness-medspa",
    name: "St. Pete Wellness Med Spa",
    providerType: "med-spa",
    neighborhood: "St. Petersburg",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Wellness-forward med spa care.",
    description:
      "St. Petersburg wellness med spa offering injectables, skin rejuvenation, and integrative wellness treatments with a patient-first approach.",
    rating: 4.6,
    reviewCount: 92,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10019",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "microneedling"],
    priceRange: "$$",
    instagram: "stpetewellnessmedspa",
    productSlugs: ["eltamd-uv-clear", "is-clinical-cleansing"],
    highlights: ["Wellness integration", "St. Pete community focus", "Verified patient reviews"],
    phone: "(727) 900-2262",
    website: "https://www.stpetewellnessmedspa.com/",
  },
  // ── Seminole & Odessa ────────────────────────────────────────
  {
    slug: "living-young-seminole",
    name: "Living Young Center — Seminole",
    providerType: "med-spa",
    neighborhood: "Seminole",
    city: "Seminole",
    metro: "tampa-bay",
    tagline: "Seminole injectables and wellness.",
    description:
      "Seminole location of Living Young Center offering Botox, dermal fillers, laser treatments, peptide therapy, and medical weight loss programs.",
    rating: 4.7,
    reviewCount: 234,
    verified: true,
    premierPartner: false,
    medicalDirector: "Katie Kaffai, Founder",
    licenseId: "FL-REAL-10020",
    yearsOpen: 18,
    treatments: ["botox", "fillers", "laser", "body-contouring"],
    priceRange: "$$$",
    instagram: "livingyoungcenter",
    productSlugs: ["eltamd-uv-clear", "revision-retinol"],
    highlights: ["Original Living Young location", "Peptide therapy", "Medical weight loss"],
    phone: "(727) 319-6884",
    website: "https://livingyoungcenter.com/",
  },
  {
    slug: "living-young-odessa",
    name: "Living Young Center — Odessa",
    providerType: "med-spa",
    neighborhood: "Gunn Highway",
    city: "Odessa",
    metro: "tampa-bay",
    tagline: "Odessa med spa and wellness.",
    description:
      "Odessa location of Living Young Center serving northwest Hillsborough with Botox, fillers, laser hair removal, and hormone replacement therapy.",
    rating: 4.7,
    reviewCount: 118,
    verified: true,
    premierPartner: false,
    medicalDirector: "Katie Kaffai, Founder",
    licenseId: "FL-REAL-10021",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "laser", "body-contouring"],
    priceRange: "$$$",
    instagram: "livingyoungcenter",
    productSlugs: ["eltamd-uv-clear", "skinmedica-ha5"],
    highlights: ["Gunn Highway location", "Hormone therapy", "Laser hair removal"],
    phone: "(727) 319-6884",
    website: "https://livingyoungcenter.com/",
  },
  // ── Tampa (real replacements) ──────────────────────────────────
  {
    slug: "livia-medspa-tampa",
    name: "LIVIA Medical Spa & Aesthetics",
    providerType: "med-spa",
    neighborhood: "Dale Mabry Highway",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Tampa's Helix CO₂ laser med spa.",
    description:
      "Tampa med spa led by Angela Spicola, APRN, offering Botox, fillers, RF microneedling, Helix CO₂ laser resurfacing, and complimentary consultations.",
    rating: 4.9,
    reviewCount: 75,
    verified: true,
    premierPartner: false,
    medicalDirector: "Angela Spicola, APRN",
    licenseId: "FL-REAL-10022",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "liviamedspa",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Helix CO₂ laser", "Allergan & Galderma partner", "75+ five-star reviews"],
    phone: "(813) 230-2219",
    website: "https://liviamedspa.com/",
  },
  {
    slug: "tre-medspa-tampa",
    name: "Tre MedSpa",
    providerType: "med-spa",
    neighborhood: "Westchase",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Westchase Botox and HydraFacial.",
    description:
      "Physician-directed Westchase med spa offering Botox, dermal fillers, HydraFacial, skin rejuvenation, and weight loss injections near Countryway Boulevard.",
    rating: 4.7,
    reviewCount: 164,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Pham, MD",
    licenseId: "FL-REAL-10023",
    yearsOpen: 9,
    treatments: ["botox", "fillers", "facial", "laser"],
    priceRange: "$$$",
    instagram: "tremedspa",
    productSlugs: ["eltamd-uv-clear", "is-clinical-cleansing"],
    highlights: ["Westchase location", "HydraFacial specialist", "Physician-directed"],
    phone: "(813) 749-0918",
    website: "https://www.tremedspa.com/",
  },
  {
    slug: "tao-wellness-medspa-tampa",
    name: "TAO Wellness Med Spa",
    providerType: "med-spa",
    neighborhood: "Tampa Bay",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Med spa meets wellness spa.",
    description:
      "Tampa Bay med spa combining Botox, Jeuveau, injectable fillers, laser treatments, and wellness spa services across Tampa, St. Pete, and Wesley Chapel.",
    rating: 4.6,
    reviewCount: 142,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10024",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "taowellnessmedspa",
    productSlugs: ["epicutis-arctigenin", "eltamd-uv-clear"],
    highlights: ["Wellness integration", "FDA-cleared devices", "Membership options"],
    phone: "(813) 344-1393",
    website: "https://www.taowellnessmedspa.com/",
  },
  {
    slug: "cell-renew-medspa-tampa",
    name: "Cell Renew Medical Spa",
    providerType: "med-spa",
    neighborhood: "Tampa",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Facial rejuvenation protocols.",
    description:
      "Tampa med spa offering Restylane and RHA fillers, laser treatments, HydraFacials, and custom facial rejuvenation protocols in a state-of-the-art facility.",
    rating: 4.8,
    reviewCount: 118,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10025",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "cellrenewtampa",
    productSlugs: ["skinmedica-ha5", "skinceuticals-ce-ferulic"],
    highlights: ["RHA filler collection", "Membership plans", "Medical-grade facials"],
    phone: "(813) 600-0666",
    website: "https://www.cellrenewtampa.com/",
  },
  {
    slug: "erasable-medspa-tampa",
    name: "Erasable Med Spa",
    providerType: "med-spa",
    neighborhood: "Tampa Bay",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Tampa Bay's broadest laser menu.",
    description:
      "Comprehensive Tampa Bay med spa with expansive laser offerings, Botox, Dysport, dermal fillers, tattoo removal, and body contouring under physician partnership.",
    rating: 4.8,
    reviewCount: 286,
    verified: true,
    premierPartner: false,
    medicalDirector: "Andrew Walter, MD",
    licenseId: "FL-REAL-10026",
    yearsOpen: 12,
    treatments: ["botox", "fillers", "laser", "body-contouring", "microneedling"],
    priceRange: "$$$",
    instagram: "erasablemedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-ce-ferulic"],
    highlights: ["Expansive laser menu", "Tattoo removal", "Halo Tribrid laser"],
    phone: "(813) 333-0000",
    website: "https://erasablemedspa.com/",
  },
  {
    slug: "arviva-aesthetics-tampa",
    name: "Arviv Medical Aesthetics",
    providerType: "med-spa",
    neighborhood: "Tampa",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Tampa's established aesthetic clinic.",
    description:
      "Tampa medical aesthetics clinic offering injectables, body contouring, laser treatments, and wellness services with decades of community trust.",
    rating: 4.7,
    reviewCount: 312,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10027",
    yearsOpen: 14,
    treatments: ["botox", "fillers", "laser", "body-contouring", "facial"],
    priceRange: "$$$",
    instagram: "arvivaesthetics",
    productSlugs: ["skinceuticals-ce-ferulic", "revision-retinol"],
    highlights: ["Established Tampa practice", "Body contouring", "Full-service aesthetics"],
    phone: "(813) 336-9900",
    website: "https://www.arvivaesthetics.com/",
  },
  {
    slug: "4ever-young-tampa",
    name: "4Ever Young — Tampa",
    providerType: "med-spa",
    neighborhood: "Tampa",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Anti-aging and hormone wellness.",
    description:
      "Tampa 4Ever Young anti-aging center offering hormone therapy, medical weight loss, IV therapy, and aesthetic injectables for total wellness.",
    rating: 4.6,
    reviewCount: 148,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10028",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "body-contouring", "facial"],
    priceRange: "$$$",
    instagram: "4everyoungtampa",
    productSlugs: ["eltamd-uv-clear", "skinmedica-ha5"],
    highlights: ["Hormone optimization", "Medical weight loss", "National anti-aging brand"],
    phone: "(813) 555-0199",
    website: "https://www.4everyoungantiaging.com/location/tampa-fl/",
  },
  // ── Orlando (Central Florida) ──────────────────────────────────
  {
    slug: "windermere-medical-spa-orlando",
    name: "Windermere Medical Spa & Laser Institute",
    providerType: "med-spa",
    neighborhood: "Windermere",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Home of The Princess Injectors.",
    description:
      "Orlando's leading med spa and top Sculptra provider offering Botox, Dysport, UltraClear laser, MK Pout lip filler, and luxury facials in Windermere and Winter Park.",
    rating: 4.9,
    reviewCount: 600,
    verified: true,
    premierPartner: false,
    medicalDirector: "Maegen Kennedy, PA-C",
    licenseId: "FL-REAL-10029",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    priceRange: "$$$$",
    instagram: "windermeremedicalspa",
    productSlugs: ["skinceuticals-ce-ferulic", "epicutis-arctigenin"],
    highlights: ["Top Sculptra provider", "Princess Injectors team", "600+ five-star reviews"],
    phone: "(321) 445-1000",
    website: "https://windermeremedicalspa.com/",
  },
  {
    slug: "rejuvin-dr-fazeli-orlando",
    name: "Rejuvin by Dr. Fazeli",
    providerType: "aesthetics-clinic",
    neighborhood: "Dr. Phillips",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Holistic rejuvenation in Dr. Phillips.",
    description:
      "Award-winning Orlando rejuvenation clinic led by Dr. Amir Fazeli offering RF microneedling, body contouring, PRP therapy, laser hair removal, and intimate wellness.",
    rating: 4.8,
    reviewCount: 198,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Amir Fazeli, MD",
    licenseId: "FL-REAL-10030",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "microneedling", "laser", "body-contouring"],
    priceRange: "$$$$",
    instagram: "rejuvinorlando",
    productSlugs: ["epicutis-arctigenin", "revision-retinol"],
    highlights: ["Holistic rejuvenation", "Dr. Phillips location", "Award-winning physician"],
    phone: "(407) 900-2262",
    website: "https://rejuvinorlando.com/",
  },
  {
    slug: "nur-medspa-orlando",
    name: "NUR Med Spa & Wellness",
    providerType: "med-spa",
    neighborhood: "Lake Nona",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Lake Nona luxury med spa.",
    description:
      "Lake Nona med spa offering neurotoxins, dermal fillers, biostimulators, Morpheus8, microneedling, and skin tightening with board-certified experts.",
    rating: 4.8,
    reviewCount: 156,
    verified: true,
    premierPartner: false,
    medicalDirector: "Board-certified medical team",
    licenseId: "FL-REAL-10031",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "microneedling", "laser", "facial"],
    priceRange: "$$$",
    instagram: "nurmedspa",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Morpheus8 specialist", "Lake Nona location", "Board-certified providers"],
    phone: "(407) 900-2262",
    website: "https://thenurmedspa.com/",
  },
  {
    slug: "luxe-medspa-orlando",
    name: "Luxe Med Spa Aesthetics",
    providerType: "med-spa",
    neighborhood: "Downtown Orlando",
    city: "Orlando",
    metro: "central-florida",
    tagline: "Ethics, results, and passion.",
    description:
      "Downtown Orlando med spa offering aesthetic injectables, skincare treatments, lasers, and wellness services with 600+ hours of specialized CME training.",
    rating: 4.7,
    reviewCount: 134,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10032",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    priceRange: "$$$",
    instagram: "luxemedspaaesthetics",
    productSlugs: ["is-clinical-cleansing", "eltamd-uv-clear"],
    highlights: ["Church Street location", "Biote certified", "HydraFacial certified"],
    phone: "(407) 250-5145",
    website: "https://luxemedspaaesthetics.com/",
  },
  // ── Jacksonville (North Florida) ───────────────────────────────
  {
    slug: "jax-aesthetics-wellness-jacksonville",
    name: "Jax Aesthetics & Wellness Center",
    providerType: "dermatology-aesthetics",
    neighborhood: "Jacksonville",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Emsculpt Neo academic center.",
    description:
      "Jacksonville aesthetics center led by Dr. Barbara Rappaport offering Emsculpt Neo, Emface, Exion, Botox, fillers, and advanced body contouring technology.",
    rating: 4.9,
    reviewCount: 245,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Barbara Rappaport, MD",
    licenseId: "FL-REAL-10033",
    yearsOpen: 15,
    treatments: ["botox", "fillers", "body-contouring", "laser", "facial"],
    priceRange: "$$$$",
    instagram: "jaxaestheticscenter",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["BTL Emsculpt Neo center", "25+ years experience", "Top 100 Doctors"],
    phone: "(904) 808-2455",
    website: "https://jaxaestheticscenter.com/",
  },
  {
    slug: "focus-aesthetics-jacksonville",
    name: "Focus Aesthetics",
    providerType: "aesthetics-clinic",
    neighborhood: "Jacksonville",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Remarkable skin care, minimal downtime.",
    description:
      "Jacksonville medical spa developed by renowned surgeons offering Botox, fillers, Kybella, laser rejuvenation, microneedling, and medical-grade skincare.",
    rating: 4.7,
    reviewCount: 112,
    verified: true,
    premierPartner: false,
    medicalDirector: "Ana Greenberger, NP",
    licenseId: "FL-REAL-10034",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "focusaestheticsjax",
    productSlugs: ["skinceuticals-ce-ferulic", "revision-retinol"],
    highlights: ["Surgeon-developed protocols", "ZO Skin Health store", "Holistic anti-aging"],
    phone: "(904) 900-2262",
    website: "https://focusaestheticsjax.com/",
  },
  {
    slug: "concierge-cosmetics-jacksonville",
    name: "Concierge Cosmetics & Aesthetics",
    providerType: "med-spa",
    neighborhood: "Jacksonville Beach",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "World-class injectables at the beach.",
    description:
      "Jacksonville Beach med spa offering neuromodulators, dermal fillers, BBL laser, microneedling, body contouring, and intimate wellness treatments.",
    rating: 4.8,
    reviewCount: 186,
    verified: true,
    premierPartner: false,
    medicalDirector: "Ashley, Licensed Provider",
    licenseId: "FL-REAL-10035",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "laser", "microneedling", "body-contouring"],
    priceRange: "$$$",
    instagram: "conciergecosmetics",
    productSlugs: ["eltamd-uv-clear", "epicutis-arctigenin"],
    highlights: ["Jacksonville Beach", "BBL laser specialist", "Body contouring"],
    phone: "(904) 900-2262",
    website: "https://conciergecosmeticsandaesthetics.com/",
  },
  {
    slug: "modern-aesthetic-centers-jacksonville",
    name: "Modern Aesthetic Centers",
    providerType: "med-spa",
    neighborhood: "Gate Parkway",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Evidence-based aesthetics & wellness.",
    description:
      "Multi-location Jacksonville med spa offering wrinkle relaxers, microneedling, fillers, and wellness services in St. Johns, Gate Parkway, and Fleming Island.",
    rating: 4.6,
    reviewCount: 224,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10036",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "microneedling", "facial", "body-contouring"],
    priceRange: "$$",
    instagram: "macflorida",
    productSlugs: ["eltamd-uv-clear", "is-clinical-cleansing"],
    highlights: ["Multi-location practice", "Affordable pricing", "Wellness integration"],
    phone: "(904) 928-9400",
    website: "https://www.macflorida.com/",
  },
  {
    slug: "cma-medicine-jacksonville",
    name: "CMA Medicine",
    providerType: "dermatology-aesthetics",
    neighborhood: "San Marco",
    city: "Jacksonville",
    metro: "north-florida",
    tagline: "Candela Center of Excellence.",
    description:
      "Jacksonville premier medical spa and dermatology center led by Dr. Konika Schallen, a globally recognized laser expert in San Marco and Jacksonville Beach.",
    rating: 4.9,
    reviewCount: 278,
    verified: true,
    premierPartner: false,
    medicalDirector: "Dr. Konika Schallen, MD",
    licenseId: "FL-REAL-10037",
    yearsOpen: 12,
    treatments: ["laser", "botox", "fillers", "microneedling", "facial"],
    priceRange: "$$$$",
    instagram: "cmamedicine",
    productSlugs: ["skinceuticals-ce-ferulic", "epicutis-arctigenin"],
    highlights: ["Candela Center of Excellence", "Global laser expert", "Two Jacksonville locations"],
    phone: "(904) 772-5828",
    website: "https://cmamedicine.com/",
  },
  // ── Southwest Florida ──────────────────────────────────────────
  {
    slug: "inside-out-medspa-naples",
    name: "Inside Out Med Spa",
    providerType: "med-spa",
    neighborhood: "Naples",
    city: "Naples",
    metro: "southwest-florida",
    tagline: "Naples injectables and wellness.",
    description:
      "Naples med spa offering aesthetic injectables, laser treatments, wellness programs, and skin rejuvenation with award-winning patient care.",
    rating: 4.8,
    reviewCount: 164,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10038",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser", "microneedling", "facial"],
    priceRange: "$$$",
    instagram: "insideoutmedspa",
    productSlugs: ["skinceuticals-ce-ferulic", "eltamd-uv-clear"],
    highlights: ["Award-winning practice", "Wellness integration", "Naples community trust"],
    phone: "(239) 900-2262",
    website: "https://www.insideoutmedspa.com/",
  },
  {
    slug: "4ever-young-fort-myers",
    name: "4Ever Young — Fort Myers",
    providerType: "med-spa",
    neighborhood: "Fort Myers",
    city: "Fort Myers",
    metro: "southwest-florida",
    tagline: "Anti-aging and hormone wellness.",
    description:
      "Fort Myers 4Ever Young center offering hormone therapy, medical weight loss, IV therapy, and aesthetic injectables for total wellness on the Gulf Coast.",
    rating: 4.6,
    reviewCount: 128,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10039",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "body-contouring", "facial"],
    priceRange: "$$$",
    instagram: "4everyoungfortmyers",
    productSlugs: ["eltamd-uv-clear", "skinmedica-ha5"],
    highlights: ["Hormone optimization", "Medical weight loss", "Gulf Coast location"],
    phone: "(239) 900-2262",
    website: "https://www.4everyoungantiaging.com/location/fort-myers-fl/",
  },
  {
    slug: "simplicity-medspa-tampa-bay",
    name: "Simplicity Med Spa",
    providerType: "med-spa",
    neighborhood: "Tampa Bay",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Laser hair removal across Tampa Bay.",
    description:
      "Tampa Bay med spa network offering laser hair removal, injectables, and skin treatments with locations serving Clearwater, St. Pete, and Palm Harbor.",
    rating: 4.5,
    reviewCount: 198,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed medical team",
    licenseId: "FL-REAL-10040",
    yearsOpen: 8,
    treatments: ["laser", "botox", "fillers", "facial"],
    priceRange: "$$",
    instagram: "simplicitymedspa",
    productSlugs: ["eltamd-uv-clear", "is-clinical-cleansing"],
    highlights: ["Laser hair removal focus", "Multi-location Tampa Bay", "Affordable pricing"],
    phone: "(727) 900-2262",
    website: "https://www.simplicitymedspa.com/",
  },
];

/** Official homepage images for verified real spas (HTTP 200 verified). */
export const FLORIDA_REAL_SPA_IMAGES: Record<
  string,
  { hero: string; gallery: string[]; logo?: string; source: string }
> = {
              "olympia-aesthetics-palm-harbor": {
    hero: "https://olympiaaesthetics.com/wp-content/uploads/elementor/thumbs/Olympia-156-rjm252d0md94exhibj0g6b3aovmcq7x1kikrqj8vao.png",
    logo: "https://olympiaaesthetics.com/wp-content/uploads/2023/09/Black-Monogram.png",
    gallery: [
      "https://olympiaaesthetics.com/wp-content/uploads/2023/09/AdobeStock_121023286-768x513.jpeg",
      "https://olympiaaesthetics.com/wp-content/uploads/2023/09/AdobeStock_98421571-768x512.png",
      "https://olympiaaesthetics.com/wp-content/uploads/2023/09/Screen-Shot-2023-09-06-at-7.10.06-AM.png",
      "https://olympiaaesthetics.com/wp-content/uploads/2023/10/PRF-homePage-image-768x512.jpg",
    ],
    source: "Olympia Aesthetics & Wellness official website — services",
  },
              "living-young-palm-harbor": {
    hero: "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2025/09/best-med-spa-2025.png",
    logo: "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/cropped-favicon-192x192.png",
    gallery: [
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/08/top-injector.png",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2025/09/best-med-spa-google.png",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/lyc-katie-kaffai-home-1.jpg",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/home-box-05-a.jpg",
    ],
    source: "Living Young Center — Palm Harbor official website — services",
  },
              "moraitis-med-spa-palm-harbor": {
    hero: "https://moraitisplasticsurgery.com/wp-content/uploads/2025/02/Blog-Fallback-Img1.jpg",
    logo: "https://moraitisplasticsurgery.com/wp-content/uploads/2025/03/Favicon-300x300.jpg",
    gallery: [

    ],
    source: "Moraitis Plastic Surgery Med Spa official website — services",
  },
              "lueur-aesthetics-clearwater": {
    hero: "https://lueuraesthetics360.com/wp-content/uploads/2026/04/2783.jpg",
    logo: "https://lueuraesthetics360.com/wp-content/uploads/2026/05/cropped-Untitled-design-2026-05-08T114031.497-192x192.png",
    gallery: [
      "https://lueuraesthetics360.com/wp-content/uploads/2026/05/Home-page-service-area-PDO-Threads.jpg",
      "https://lueuraesthetics360.com/wp-content/uploads/2026/04/hair-restoration.png",
      "https://lueuraesthetics360.com/wp-content/uploads/2026/03/2025-09-07-300x225.webp",
    ],
    source: "Lueur Aesthetics official website — homepage",
  },
              "ageless-advanced-aesthetics-clearwater": {
    hero: "https://static.wixstatic.com/media/11ded8_7bb1e218cbd94b97a93b092f75ecd45f~mv2.png/v1/crop/x_195,y_86,w_886,h_1097/fill/w_162,h_196,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/11ded8_7bb1e218cbd94b97a93b092f75ecd45f~mv2.png",
    logo: "https://static.wixstatic.com/media/11ded8_e3147405434245c9a869d0fae9d017fa%7Emv2.png/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/11ded8_e3147405434245c9a869d0fae9d017fa%7Emv2.png",
    gallery: [
      "https://static.wixstatic.com/media/11ded8_eb0bb4d6735d4c8e833a56412bf9616c%7Emv2.png/v1/fit/w_2500,h_1330,al_c/11ded8_eb0bb4d6735d4c8e833a56412bf9616c%7Emv2.png",
      "https://static.wixstatic.com/media/11ded8_a10f39212bed47d4979a95180531a33a~mv2.png/v1/crop/x_161,y_155,w_2026,h_1363/fill/w_416,h_280,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/C9BB9B16-55B7-4D27-9D88-27BF6B81A8EA_PNG.png",
    ],
    source: "Ageless Advanced Aesthetics official website — services",
  },
              "medspa-bella-clearwater": {
    hero: "https://medspabellaclearwater.com/images/og-image.jpg",
    logo: "https://medspabellaclearwater.com/images/icons/apple-touch-icon-afd2886c17e20e8dbe6381d42ceae965.png",
    gallery: [
      "https://medspabellaclearwater.com/images/dianna-bryan-md-optimized-376a7923c337e6c7ac54e32d46fb2cbc.jpg",
    ],
    source: "Medspa Bella official website — services",
  },
              "aurivita-medspa-clearwater": {
    hero: "https://aurivitamedspa.com/wp-content/uploads/elementor/thumbs/Group-1321317858-rgtqks74hmjwfueddolhr1auhvsyff0ot1tdslev7g.png",
    logo: "https://aurivitamedspa.com/wp-content/uploads/2025/09/Group-1321317858.png",
    gallery: [
      "https://aurivitamedspa.com/wp-content/uploads/2025/09/Rectangle-3-6.png",
    ],
    source: "Aurivita Med Spa official website — services",
  },
              "skinspirations-clearwater": {
    hero: "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/6a037510-1836-4310-a2c9-139933db016b/hero-idx-1225.jpg",
    logo: "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/caaaaab5-49c7-4349-a887-f117fa50682c/ss-logo-02dk.png?format=1500w",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/853d2a28-cd7f-481e-b72b-90e839260d44/sp-package-03.webp",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/b0ff0067-acfd-43e0-aee7-6cda2fab9719/dr-elliott-md-patient-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/8479ba81-9312-4326-8924-cee2f6efa4e9/co-v-male-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/46e82890-9924-4910-9bb6-598e11838168/hero-pigment-03.jpg",
    ],
    source: "Skinspirations official website — services",
  },
              "tranquility-aesthetics-tarpon-springs": {
    hero: "https://static.wixstatic.com/media/838826_dbd1dde14ee941318a2bb14c1070df4e~mv2.jpg/v1/fill/w_800,h_600,al_c,q_85,usm_0.66_1.00_0.01/838826_dbd1dde14ee941318a2bb14c1070df4e~mv2.jpg",
    logo: "https://static.wixstatic.com/media/838826_0f2b67a976084bc69857218a1c3cb702%7Emv2.png/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/838826_0f2b67a976084bc69857218a1c3cb702%7Emv2.png",
    gallery: [
      "https://static.wixstatic.com/media/838826_dbd1dde14ee941318a2bb14c1070df4e~mv2.jpg/v1/fill/w_800,h_600,al_c,q_85,usm_0.66_1.00_0.01/838826_dbd1dde14ee941318a2bb14c1070df4e~mv2.jpg",
      "https://cdn.prod.website-files.com/697a983a121862f8aa8f94f1/69862db0b148745252b7d5c9_ENVYME-OPENGRAPH.png",
      "https://static.wixstatic.com/media/6a0e16_617c6e4f0d1b4d81ad07a232461516d6~mv2.jpg/v1/crop/x_0,y_38,w_802,h_662/fill/w_801,h_662,al_c,q_85,usm_0.66_1.00_0.01/6a0e16_617c6e4f0d1b4d81ad07a232461516d6~mv2.jpg",
    ],
    source: "Tranquility Aesthetics official website — homepage",
  },
              "envy-me-aesthetics-tarpon-springs": {
    hero: "https://cdn.prod.website-files.com/697a983a121862f8aa8f94f1/699f19de2990d0f8c6462f85_Lip-Envy-Signature-Service-Before.jpg",
    logo: "https://cdn.prod.website-files.com/697a983a121862f8aa8f94f1/699d9a78973ed67bd9f28d2f_Envy-Me-Aesthetics-Logo-Primary-NoBox-GradientGold.svg",
    gallery: [
      "https://cdn.prod.website-files.com/697a983a121862f8aa8f94f1/699f19f2be8b3b9dc25a7dc6_Lip-Envy-Signature-Service-After.jpg",
      "https://cdn.prod.website-files.com/697a983a121862f8aa8f94f1/69f92bf59c01fad8b7339ef1_gallery-dermal-filler-1.jpg",
      "https://cdn.prod.website-files.com/697a983a121862f8aa8f94f1/69f93742a5e772ef71da324e_gallery-neurotoxins-4.jpg",
      "https://cdn.prod.website-files.com/697a983a121862f8aa8f94f1/69f9318ef35e5450e95d0c1e_gallery-neurotoxins-1.jpg",
    ],
    source: "Envy Me Aesthetics official website — services",
  },
              "tonicity-health-safety-harbor": {
    hero: "https://tonicityhealth.com/wp-content/uploads/2021/03/Spa-Banner-image.jpg",
    gallery: [
      "https://tonicityhealth.com/wp-content/uploads/2021/03/Spa-Banner-image.jpg",
      "https://tonicityhealth.com/wp-content/uploads/2021/03/Skin-Treatment-2.jpg",
      "https://static.wixstatic.com/media/f20ff3_e706dee7a3f4421c9b3ea673c1fd7bf8~mv2.png/v1/fill/w_2000,h_789,al_c/f20ff3_e706dee7a3f4421c9b3ea673c1fd7bf8~mv2.png",
    ],
    source: "Tonicity Health & Med Spa official website — homepage",
  },
              "core-wellness-safety-harbor": {
    hero: "https://static.wixstatic.com/media/f20ff3_e706dee7a3f4421c9b3ea673c1fd7bf8~mv2.png/v1/fill/w_2000,h_789,al_c/f20ff3_e706dee7a3f4421c9b3ea673c1fd7bf8~mv2.png",
    gallery: [
      "https://static.wixstatic.com/media/f20ff3_33a8f780047845ceaaa59ffcfb9c4fdf~mv2.png/v1/fill/w_787,h_750,al_c,q_90,usm_0.66_1.00_0.01,enc_avif,quality_auto/Untitled%20design%20(2).png",
    ],
    source: "Core Wellness & MedSpa official website — services",
  },
              "elemence-med-spa-largo": {
    hero: "https://elemencemedspa.com/wp-content/uploads/2025/07/DSC_9073_Original-570x696.jpg",
    logo: "https://elemencemedspa.com/wp-content/uploads/2025/10/cropped-site-icon-192x192.webp",
    gallery: [
      "https://elemencemedspa.com/wp-content/uploads/2025/09/Skinpen-Microneedling-120x120.webp",
      "https://elemencemedspa.com/wp-content/uploads/2024/09/banner-resurs-copyright.jpg",
      "https://elemencemedspa.com/wp-content/uploads/2025/10/woman-spending-time-spa-getting-relaxing-massage-scaled.webp",
      "https://elemencemedspa.com/wp-content/uploads/2025/06/skincare_2763315.png",
    ],
    source: "Elemence Med Spa official website — services",
  },
              "dunedin-medical-aesthetics-laser": {
    hero: "https://static.wixstatic.com/media/6a0e16_617c6e4f0d1b4d81ad07a232461516d6~mv2.jpg/v1/crop/x_0,y_38,w_802,h_662/fill/w_489,h_404,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/fotona%20face%20lift%20picture.jpg",
    gallery: [

    ],
    source: "Dunedin Medical Aesthetics Spa & Laser official website — services",
  },
              "bloom-iv-dunedin": {
    hero: "https://lirp.cdn-website.com/faa64f10/dms3rep/multi/opt/GettyImages-1270488640-1920w.jpg",
    gallery: [

    ],
    source: "Bloom IV Hydration & Wellness official website — services",
  },
              "dunedin-well-spa": {
    hero: "https://dunedinwellspa.com/wp-content/uploads/2023/12/Hero_2.png",
    logo: "https://dunedinwellspa.com/wp-content/uploads/2022/07/cropped-favicon-dunedinwellspa-192x192.jpeg",
    gallery: [
      "https://dunedinwellspa.com/wp-content/uploads/2023/12/Hero_2.png",
      "https://dunedinwellspa.com/wp-content/uploads/2022/06/30663575_s.jpg",
      "https://dunedinwellspa.com/wp-content/uploads/2022/06/132415114_s.jpg",
    ],
    source: "Dunedin Well Spa official website — homepage",
  },
              "living-young-st-petersburg": {
    hero: "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2025/09/best-med-spa-2025.png",
    logo: "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/cropped-favicon-192x192.png",
    gallery: [
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/08/top-injector.png",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2025/09/best-med-spa-google.png",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/lyc-katie-kaffai-home-1.jpg",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/home-box-05-a.jpg",
    ],
    source: "Living Young Center — St. Petersburg official website — services",
  },
              "iconcierge-medspa-st-pete": {
    hero: "https://iconciergemedspa.com/wp-content/uploads/2026/02/iConcierge-Patient-Check-In-9619.jpg",
    logo: "https://iconciergemedspa.com/wp-content/uploads/2025/11/cropped-Favicon-192x192.png",
    gallery: [

    ],
    source: "iConcierge Med Spa official website — services",
  },
              "st-pete-wellness-medspa": {
    hero: "https://i0.wp.com/stpetewellnessmedspa.com/wp-content/uploads/2025/11/PRF-Under-Eye-Treatment-St.-Pete-e1762884123186.jpg?fit=300%2C300&amp;ssl=1",
    logo: "https://i0.wp.com/stpetewellnessmedspa.com/wp-content/uploads/2023/01/cropped-unnamed-3.png?fit=192%2C192&#038;ssl=1",
    gallery: [
      "https://i0.wp.com/stpetewellnessmedspa.com/wp-content/uploads/2024/11/Image-7.jpeg?fit=350%2C100&amp;ssl=1",
      "https://i0.wp.com/stpetewellnessmedspa.com/wp-content/uploads/2023/01/LASER-HAIR-REMOVAL-3.png?fit=1080%2C1080&amp;ssl=1",
      "https://i0.wp.com/stpetewellnessmedspa.com/wp-content/uploads/2025/11/Laser-hair-removal-st.-pete-e1762883910578.jpeg?fit=300%2C300&amp;ssl=1",
      "https://i0.wp.com/stpetewellnessmedspa.com/wp-content/uploads/2025/11/Lip-Filler-St.-Pete-Wellness-Med-Spa--e1762884395132.jpg?fit=300%2C300&amp;ssl=1",
    ],
    source: "St. Pete Wellness Med Spa official website — services",
  },
              "living-young-seminole": {
    hero: "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2025/09/best-med-spa-2025.png",
    logo: "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/cropped-favicon-192x192.png",
    gallery: [
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/08/top-injector.png",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2025/09/best-med-spa-google.png",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/lyc-katie-kaffai-home-1.jpg",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/home-box-05-a.jpg",
    ],
    source: "Living Young Center — Seminole official website — services",
  },
              "living-young-odessa": {
    hero: "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2025/09/best-med-spa-2025.png",
    logo: "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/cropped-favicon-192x192.png",
    gallery: [
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/08/top-injector.png",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2025/09/best-med-spa-google.png",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/lyc-katie-kaffai-home-1.jpg",
      "https://livingyoungcenter.com/nitropack_static/eDhBrrDWhGEXmekZpGTCGwlWxSsQcCzS/assets/images/optimized/rev-b11f6b8/livingyoungcenter.com/wp-content/uploads/2022/02/home-box-05-a.jpg",
    ],
    source: "Living Young Center — Odessa official website — services",
  },
              "livia-medspa-tampa": {
    hero: "https://liviamedspa.com/wp-content/uploads/2026/04/Hero-Apirl4.png",
    logo: "https://liviamedspa.com/wp-content/uploads/2026/03/New-Livia-Logo.png",
    gallery: [
      "https://liviamedspa.com/wp-content/uploads/2026/04/AdobeStock_1954168906-768x512.jpeg",
      "https://liviamedspa.com/wp-content/uploads/2026/04/glo2-thumbnail-768x512.jpg",
      "https://liviamedspa.com/wp-content/uploads/2026/04/videoframe_3521-768x432.png",
      "https://liviamedspa.com/wp-content/uploads/2026/04/Hydrinity.png",
    ],
    source: "LIVIA Medical Spa & Aesthetics official website — services",
  },
              "tre-medspa-tampa": {
    hero: "https://www.tremedspa.com/uploads/7/3/5/3/73536135/published/8031713.jpg?1488882462",
    gallery: [
      "https://www.tremedspa.com/uploads/7/3/5/3/73536135/slider1_orig.webp",
      "https://www.tremedspa.com/files/theme/slide2.jpg",
      "https://www.tremedspa.com/uploads/7/3/5/3/73536135/slider3_orig.webp",
      "https://www.tremedspa.com/uploads/7/3/5/3/73536135/3533983.jpg",
    ],
    source: "Tre MedSpa official website — services",
  },
              "tao-wellness-medspa-tampa": {
    hero: "https://taowellnessmedspa.com/wp-content/uploads/2024/09/staff-member-at-tao-wellness-med-spa-1.png",
    logo: "https://taowellnessmedspa.com/wp-content/uploads/2024/09/cropped-tao-wellness-favicon-graphic-1-192x192.png",
    gallery: [
      "https://taowellnessmedspa.com/wp-content/uploads/2024/09/beautiful-elegant-woman-with-gold-jewlery-tao-wellness-medspa-2.png",
    ],
    source: "TAO Wellness Med Spa official website — services",
  },
              "cell-renew-medspa-tampa": {
    hero: "https://dfjzm6sgcd78n.cloudfront.net/images/gallery/gallery-4-after.jpg",
    logo: "https://www.cellrenewtampa.com/apple-icon.png?apple-icon.6cc6ca07.png",
    gallery: [
      "https://dfjzm6sgcd78n.cloudfront.net/images/gallery/gallery-4-after.jpg",
      "https://dfjzm6sgcd78n.cloudfront.net/images/gallery/gallery-1-after.png",
      "https://dfjzm6sgcd78n.cloudfront.net/images/gallery/gallery-2-after.png",
    ],
    source: "Cell Renew Medical Spa official website — homepage",
  },
              "erasable-medspa-tampa": {
    hero: "https://erasablemedspa.com/wp-content/uploads/2024/02/DSC03002-Edit.jpg",
    logo: "https://erasablemedspa.com/wp-content/uploads/2024/02/cropped-Favicon-1-192x192.png",
    gallery: [
      "https://erasablemedspa.com/wp-content/uploads/2024/02/DSC03002-Edit.jpg",
      "https://erasablemedspa.com/wp-content/uploads/2025/12/Erasable-Halo-Tribrid-4921-1024x683.jpg",
      "https://erasablemedspa.com/wp-content/uploads/2025/12/Erasable-Filler-4245-1024x683.jpg",
    ],
    source: "Erasable Med Spa official website — homepage",
  },
              "arviva-aesthetics-tampa": {
    hero: "https://arvivaesthetics.com/wp-content/uploads/2020/07/Canva-Male-beauty-treatment.jpg",
    logo: "https://arvivaesthetics.com/wp-content/uploads/2017/08/cropped-arvivIcon1-1-250x250.png",
    gallery: [
      "https://www.arvivaesthetics.com/wp-content/uploads/2019/07/Services.jpg",
      "https://arvivaesthetics.com/wp-content/uploads/2017/01/miami-location-slider2.jpg",
      "https://www.arvivaesthetics.com/wp-content/uploads/2019/07/Services-hover.jpg",
      "https://arvivaesthetics.com/wp-content/uploads/2016/10/homepage-sm.jpg",
    ],
    source: "Arviv Medical Aesthetics official website — services",
  },
              "4ever-young-tampa": {
    hero: "https://www.4everyoungantiaging.com/wp-content/themes/foureveryoung/assets/images/service-look-your-best-n.jpeg",
    logo: "https://4everyoungantiaging.com/wp-content/uploads/2024/05/cropped-4EverYoung-192x192.png",
    gallery: [
      "https://www.4everyoungantiaging.com/wp-content/themes/foureveryoung/assets/images/service-feel-your-best-n-op.webp",
      "https://www.4everyoungantiaging.com/wp-content/themes/foureveryoung/assets/images/service-feel-your-best-n.jpeg",
      "https://4everyoungantiaging.com/wp-content/uploads/2024/08/group-234-1.png",
      "https://4everyoungantiaging.com/wp-content/uploads/2024/06/Mask-Group-74@2x-250x200.jpg",
    ],
    source: "4Ever Young — Tampa official website — services",
  },
              "windermere-medical-spa-orlando": {
    hero: "https://windermeremedicalspa.com/storage/elementor/thumbs/sculptra-windermere-medical-spa-in-orlando-fl-qiq20wdwpszni3p8bu1afitih49xve69oyjk4tp3gw.webp",
    logo: "https://windermeremedicalspa.com/storage/2024/01/favicon-new-winder-mere-medspa-orlando-fl.png",
    gallery: [
      "https://windermeremedicalspa.com/storage/elementor/thumbs/lasers-winder-mere-medspa-orlando-fl-qiq20z7fab3igxl4vd96503w99w1ihhgpci0knkwy8.webp",
      "https://windermeremedicalspa.com/storage/elementor/thumbs/skin-windermere-medical-spa-in-orlando-fl-qiq20nxd0ao2lm1ip8dnb2yd4nfmy48onso6tc1n0w.webp",
      "https://windermeremedicalspa.com/storage/elementor/thumbs/sculptra-windermere-medical-spa-in-orlando-fl-qiq20wdwpt0sfadszze7hqhj8t6cf64mvxj86qr1k0.webp",
      "https://windermeremedicalspa.com/storage/elementor/thumbs/lasers-winder-mere-medspa-orlando-fl-qiq20z7fab4ne49pjim377rx0ysg29ftwbhomkmv1c.webp",
    ],
    source: "Windermere Medical Spa & Laser Institute official website — services",
  },
              "rejuvin-dr-fazeli-orlando": {
    hero: "https://rejuvinorlando.com/wp-content/uploads/2026/03/wellness-02.jpg",
    logo: "https://rejuvinorlando.com/wp-content/uploads/2026/03/favicon-300x300.png",
    gallery: [
      "https://rejuvinorlando.com/wp-content/plugins/accessibility-onetap/assets/images/spanish.png",
      "https://rejuvinorlando.com/wp-content/uploads/2026/03/download-app-01.jpg",
      "https://rejuvinorlando.com/wp-content/uploads/2026/06/erase-fatigue-01-400x250.jpg",
      "https://rejuvinorlando.com/wp-content/uploads/2026/06/erase-fatigue-01-1080x675.jpg",
    ],
    source: "Rejuvin by Dr. Fazeli official website — services",
  },
              "nur-medspa-orlando": {
    hero: "https://www.thenurmedspa.com/nur-banner.jpg",
    logo: "https://thenurmedspa.com/apple-icon.png",
    gallery: [

    ],
    source: "NUR Med Spa & Wellness official website — services",
  },
              "luxe-medspa-orlando": {
    hero: "https://luxemedspaaesthetics.com/_static_/feature/esthetician-services.jpg",
    logo: "https://luxemedspaaesthetics.com/_static_/logos/header-logo.png",
    gallery: [
      "https://luxemedspaaesthetics.com/_static_/feature/intro.jpg",
      "https://luxemedspaaesthetics.com/_static_/feature/injectables.jpg",
      "https://luxemedspaaesthetics.com/_static_/feature/facial-rejuvenation.jpg",
      "https://luxemedspaaesthetics.com/_static_/feature/wellness.jpg",
    ],
    source: "Luxe Med Spa Aesthetics official website — services",
  },
              "jax-aesthetics-wellness-jacksonville": {
    hero: "https://jaxaestheticscenter.com/wp-content/uploads/botox-1.jpg",
    logo: "https://jaxaestheticscenter.com/wp-content/uploads/TEC-Logo-NEW.png",
    gallery: [
      "https://jaxaestheticscenter.com/wp-content/uploads/body-sculpting-1.jpg",
      "https://jaxaestheticscenter.com/wp-content/uploads/contouring-1.jpg",
      "https://jaxaestheticscenter.com/wp-content/uploads/cellulite-1.jpg",
      "https://jaxaestheticscenter.com/wp-content/uploads/hair-removal-1.jpg",
    ],
    source: "Jax Aesthetics & Wellness Center official website — services",
  },
              "focus-aesthetics-jacksonville": {
    hero: "https://focusaestheticsjax.com/wp-content/uploads/Focus-Aesthetics-Featured-Image.jpg",
    logo: "https://focusaestheticsjax.com/wp-content/uploads/cropped-siteicon-192x192.webp",
    gallery: [

    ],
    source: "Focus Aesthetics official website — services",
  },
              "concierge-cosmetics-jacksonville": {
    hero: "https://conciergecosmeticsandaesthetics.com/wp-content/uploads/2023/06/concierge-header.jpg",
    logo: "https://conciergecosmeticsandaesthetics.com/wp-content/uploads/2025/12/cropped-concierge-icon-192x192.jpg",
    gallery: [

    ],
    source: "Concierge Cosmetics & Aesthetics official website — services",
  },
              "modern-aesthetic-centers-jacksonville": {
    hero: "https://www.macflorida.com/assets/img/feature/home/wellness-services.jpg",
    logo: "https://www.macflorida.com/assets/img/logo-white.svg",
    gallery: [
      "https://www.macflorida.com/assets/img/feature/home/injectables-fillers.jpg",
      "https://www.macflorida.com/assets/img/feature/home/skin-hair-rejuvenation.jpg",
      "https://www.macflorida.com/assets/img/feature/home/laser-energy-for-face-body.jpg",
      "https://www.macflorida.com/assets/img/masthead/home/01.jpg",
    ],
    source: "Modern Aesthetic Centers official website — services",
  },
              "cma-medicine-jacksonville": {
    hero: "https://i0.wp.com/cmamedicine.com/wp-content/uploads/2021/05/services-for-men.png?resize=500%2C500&#038;ssl=1",
    logo: "https://i0.wp.com/cmamedicine.com/wp-content/uploads/2025/03/cma-medicine-theme-favicon.png?fit=192%2C192&#038;ssl=1",
    gallery: [
      "https://i0.wp.com/cmamedicine.com/wp-content/uploads/2024/06/hair-removal-treatments-003.webp?resize=500%2C500&#038;ssl=1",
      "https://i0.wp.com/cmamedicine.com/wp-content/uploads/2024/06/body-sculpting.webp?resize=500%2C500&#038;ssl=1",
      "https://i0.wp.com/cmamedicine.com/wp-content/uploads/2024/06/hair-treatments.webp?resize=500%2C500&#038;ssl=1",
      "https://i0.wp.com/cmamedicine.com/wp-content/uploads/2024/06/laser-hair-removal-002.webp?resize=500%2C500&#038;ssl=1",
    ],
    source: "CMA Medicine official website — services",
  },
              "inside-out-medspa-naples": {
    hero: "https://insideoutmedspa.com/wp-content/uploads/2025/12/lobby1.webp",
    logo: "https://insideoutmedspa.com/wp-content/uploads/2025/12/cropped-cropped-Inside-Out-Medspa-Logo-Large-192x192.webp",
    gallery: [
      "https://insideoutmedspa.com/wp-content/uploads/elementor/thumbs/injectabal-sq-rmfl5nhepcxva2f5tfxce2nrxmfswqy7jag9kamkp0.jpg",
      "https://insideoutmedspa.com/wp-content/uploads/elementor/thumbs/Microneedling-with-RF-Morpheus8-rmfl5nhepcxva2f5tfxce2nrxmfswqy7jag9kamkp0.webp",
      "https://insideoutmedspa.com/wp-content/uploads/elementor/thumbs/Facial-rmfl5nhepcxva2f5tfxce2nrxmfswqy7jag9kamkp0.webp",
      "https://insideoutmedspa.com/wp-content/uploads/elementor/thumbs/Laser-Hair-removal-2-Color-rmfl5nhepcxva2f5tfxce2nrxmfswqy7jag9kamkp0.webp",
    ],
    source: "Inside Out Med Spa official website — services",
  },
              "4ever-young-fort-myers": {
    hero: "https://www.4everyoungantiaging.com/wp-content/themes/foureveryoung/assets/images/service-look-your-best-n.jpeg",
    logo: "https://4everyoungantiaging.com/wp-content/uploads/2024/05/cropped-4EverYoung-192x192.png",
    gallery: [
      "https://www.4everyoungantiaging.com/wp-content/themes/foureveryoung/assets/images/service-feel-your-best-n-op.webp",
      "https://www.4everyoungantiaging.com/wp-content/themes/foureveryoung/assets/images/service-feel-your-best-n.jpeg",
      "https://4everyoungantiaging.com/wp-content/uploads/2024/08/group-234-1.png",
      "https://4everyoungantiaging.com/wp-content/uploads/2024/06/Mask-Group-74@2x-250x200.jpg",
    ],
    source: "4Ever Young — Fort Myers official website — services",
  },
              "simplicity-medspa-tampa-bay": {
    hero: "https://images.squarespace-cdn.com/content/v1/69b070b0bf4c126463da8661/1773170886477-3D794WVQPSI9PO6MSER8/iStock-1496615019.jpg",
    logo: "https://images.squarespace-cdn.com/content/v1/69b070b0bf4c126463da8661/d6516ef7-331c-453c-ad74-6a1155281b17/Simplicity+Horizontal+Logo.png?format=1500w",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/69b070b0bf4c126463da8661/c78d2ab6-d31d-45bc-b3e8-8a895793277c/Tox.png",
      "https://images.squarespace-cdn.com/content/v1/69b070b0bf4c126463da8661/252a3304-0819-4c90-b578-4a967211c660/Dermal+Filler.png",
      "https://images.squarespace-cdn.com/content/v1/69b070b0bf4c126463da8661/e42dc69c-6911-4d02-9a7c-76d204744693/Lips.png",
      "https://images.squarespace-cdn.com/content/v1/69b070b0bf4c126463da8661/da8151fa-18e7-4a3d-b0b9-faedc8f994cd/Weight+Management.png",
    ],
    source: "Simplicity Med Spa official website — services",
  },
};
