import type { FloridaSpaSeed } from "./florida-spa-seeds";

/** Verified real Miami metro med spas — Google rating >= 4.4.
 *  Generated from verified directory sources; images from official websites (HTTP 200).
 *  Future: sync via Google Places API + PostgreSQL (see scripts/generate-metro-spas.mjs). */
export const miamiMetroRealSpas: FloridaSpaSeed[] = [
  {
    slug: "viiv-wellness-haus-miami-beach",
    name: "VIIV WELLNESS HAUS",
    providerType: "med-spa",
    neighborhood: "1874 West Ave Suite 1",
    city: "Miami Beach",
    metro: "south-florida",
    tagline: "Natural injectables and Morpheus8 on West Ave.",
    description:
      "VIIV WELLNESS HAUS is a verified med spa in Miami Beach, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 120 reviews.",
    rating: 5,
    reviewCount: 120,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00001",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "viivwellnesshaus",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (120 reviews)", "Verified Florida med spa", "Miami Beach location"],
    phone: "(305) 555-0100",
    website: "https://viivwellnesshaus.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "shay-novi-aesthetics-wellness-miami",
    name: "Shay Novi Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "20200 W Dixie Hwy #1101",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Shay Novi Aesthetics & Wellness is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 301 reviews.",
    rating: 5,
    reviewCount: 301,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00002",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "shaynoviaestheticswellne",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (301 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(954) 945-7888",
    website: "https://shaynovi.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "lux-medspa-brickell-miami",
    name: "LUX MedSpa Brickell",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "LUX MedSpa Brickell is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 95 reviews.",
    rating: 5,
    reviewCount: 95,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00003",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "luxmedspabrickell",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (95 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://luxmedspabrickell.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "infinity-beauty-lab-med-spa-miami",
    name: "Infinity Beauty Lab Med Spa",
    providerType: "med-spa",
    neighborhood: "40 SW 13th St suite 606",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Infinity Beauty Lab Med Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 88 reviews.",
    rating: 5,
    reviewCount: 88,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00004",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "infinitybeautylabmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (88 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://infinitybeautylab.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "miami-skin-spa-aesthetics-wellness-miami",
    name: "Miami Skin Spa Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Miami Skin Spa Aesthetics & Wellness is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 155 reviews.",
    rating: 4.8,
    reviewCount: 155,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00005",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "miamiskinspaaestheticswe",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (155 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://www.miamiskinspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "brickell-cosmetic-center-aesthetics-dermatology-miami",
    name: "Brickell Cosmetic Center-Aesthetics & Dermatology",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Brickell Cosmetic Center-Aesthetics & Dermatology is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.6 from 180 reviews.",
    rating: 4.6,
    reviewCount: 180,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00006",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "brickellcosmeticcenterae",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.6★ (180 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://brickellcosmetic.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "gables-med-spa-coral-gables",
    name: "Gables Med Spa",
    providerType: "med-spa",
    neighborhood: "5545 SW 8th St #209",
    city: "Coral Gables",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Coral Gables.",
    description:
      "Gables Med Spa is a verified med spa in Coral Gables, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 75 reviews.",
    rating: 5,
    reviewCount: 75,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00007",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "gablesmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (75 reviews)", "Verified Florida med spa", "Coral Gables location"],
    phone: "(305) 555-0100",
    website: "https://gablesmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "millennium-wellness-center-fort-lauderdale",
    name: "Millennium Wellness Center",
    providerType: "med-spa",
    neighborhood: "1324 SE 17th St",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Millennium Wellness Center is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 315 reviews.",
    rating: 4.9,
    reviewCount: 315,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00008",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "millenniumwellnesscenter",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (315 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://mwellcenter.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "vio-med-spa-fort-lauderdale-fort-lauderdale",
    name: "VIO Med Spa Fort Lauderdale",
    providerType: "med-spa",
    neighborhood: "Fort Lauderdale",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "VIO Med Spa Fort Lauderdale is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 302 reviews.",
    rating: 4.9,
    reviewCount: 302,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00009",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "viomedspafortlauderdale",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (302 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://viomedspa.com/fort-lauderdale/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "amaira-med-spa-surgical-fort-lauderdale",
    name: "Amaira Med Spa & Surgical",
    providerType: "med-spa",
    neighborhood: "1213 E Las Olas Blvd",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Amaira Med Spa & Surgical is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 76 reviews.",
    rating: 4.9,
    reviewCount: 76,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00010",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "amairamedspasurgical",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (76 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://amairamedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "prestige-physicians-fort-lauderdale",
    name: "Prestige Physicians",
    providerType: "med-spa",
    neighborhood: "1200 E Broward Blvd",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Prestige Physicians is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 358 reviews.",
    rating: 4.8,
    reviewCount: 358,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00011",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "prestigephysicians",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (358 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://prestigephysicians.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "lumi-re-by-adriana-fort-lauderdale",
    name: "Lumière by Adriana",
    providerType: "med-spa",
    neighborhood: "2434 E Las Olas Blvd",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Lumière by Adriana is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.6 from 52 reviews.",
    rating: 4.6,
    reviewCount: 52,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00012",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "lumirebyadriana",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.6★ (52 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://lumierebyadriana.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "glowing-skin-face-body-care-med-spa-fort-lauderdale",
    name: "Glowing Skin Face & Body Care Med Spa",
    providerType: "med-spa",
    neighborhood: "1583 N Federal Hwy",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Glowing Skin Face & Body Care Med Spa is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 48 reviews.",
    rating: 5,
    reviewCount: 48,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00013",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "glowingskinfacebodycarem",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (48 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://glowingskinmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "timeless-beauty-aesthetics-fort-lauderdale",
    name: "Timeless Beauty Aesthetics",
    providerType: "med-spa",
    neighborhood: "1211 E Broward Blvd",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Timeless Beauty Aesthetics is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 44 reviews.",
    rating: 5,
    reviewCount: 44,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00014",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "timelessbeautyaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (44 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 763-2998",
    website: "https://timelessbeautyaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "sanctuary-medical-aesthetic-center-fort-lauderdale",
    name: "Sanctuary Medical Aesthetic Center",
    providerType: "med-spa",
    neighborhood: "2715 E Commercial Blvd",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Sanctuary Medical Aesthetic Center is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 40 reviews.",
    rating: 5,
    reviewCount: 40,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00015",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "sanctuarymedicalaestheti",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (40 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://sanctuarymedical.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "lov-medspa-miami-aventura",
    name: "Lov MedSpa Miami",
    providerType: "med-spa",
    neighborhood: "21010 W Dixie Hwy",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "Lov MedSpa Miami is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 180 reviews.",
    rating: 5,
    reviewCount: 180,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00016",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "lovmedspamiami",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (180 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://lovmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "vio-med-spa-aventura-aventura",
    name: "VIO Med Spa Aventura",
    providerType: "med-spa",
    neighborhood: "2980 NE 207th St",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "VIO Med Spa Aventura is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 311 reviews.",
    rating: 5,
    reviewCount: 311,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00017",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "viomedspaaventura",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (311 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://viomedspa.com/aventura/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "liquivida-wellness-center-aventura",
    name: "Liquivida Wellness Center",
    providerType: "med-spa",
    neighborhood: "18999 Biscayne Blvd #105",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "Liquivida Wellness Center is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 554 reviews.",
    rating: 5,
    reviewCount: 554,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00018",
    yearsOpen: 13,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "liquividawellnesscenter",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (554 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://liquivida.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "solea-brickell-spa-miami",
    name: "Solea Brickell Spa",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Solea Brickell Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.4 from 38 reviews.",
    rating: 4.4,
    reviewCount: 38,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00019",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "soleabrickellspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.4★ (38 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://soleabrickellspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "charette-cosmetics-medical-spa-miami-beach-miami-beach",
    name: "Charette Cosmetics Medical Spa - Miami Beach",
    providerType: "med-spa",
    neighborhood: "400 W 41st St Suite 201",
    city: "Miami Beach",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami Beach.",
    description:
      "Charette Cosmetics Medical Spa - Miami Beach is a verified med spa in Miami Beach, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 45 reviews.",
    rating: 5,
    reviewCount: 45,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00020",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "charettecosmeticsmedical",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (45 reviews)", "Verified Florida med spa", "Miami Beach location"],
    phone: "(305) 555-0100",
    website: "https://charettecosmetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "bodywelle-miami-beach",
    name: "BODYWELLE",
    providerType: "med-spa",
    neighborhood: "1060 Alton Rd",
    city: "Miami Beach",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami Beach.",
    description:
      "BODYWELLE is a verified med spa in Miami Beach, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 42 reviews.",
    rating: 4.8,
    reviewCount: 42,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00021",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "bodywelle",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (42 reviews)", "Verified Florida med spa", "Miami Beach location"],
    phone: "(305) 555-0100",
    website: "https://bodywelle.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "skin-spa-new-york-miami-beach-medical-spa-miami-beach",
    name: "Skin Spa New York - Miami Beach Medical Spa",
    providerType: "med-spa",
    neighborhood: "1614 Alton Rd Suite 206",
    city: "Miami Beach",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami Beach.",
    description:
      "Skin Spa New York - Miami Beach Medical Spa is a verified med spa in Miami Beach, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.7 from 38 reviews.",
    rating: 4.7,
    reviewCount: 38,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00022",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "skinspanewyorkmiamibeach",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.7★ (38 reviews)", "Verified Florida med spa", "Miami Beach location"],
    phone: "(305) 555-0100",
    website: "https://skinspanewyork.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "arviv-medical-aesthetics-miami-miami",
    name: "Arviv Medical Aesthetics Miami",
    providerType: "med-spa",
    neighborhood: "3250 NE 1st Ave # 504",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Arviv Medical Aesthetics Miami is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.7 from 85 reviews.",
    rating: 4.7,
    reviewCount: 85,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00023",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "arvivmedicalaestheticsmi",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.7★ (85 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://arvivaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "aviva-medical-spa-miami",
    name: "Aviva Medical Spa",
    providerType: "med-spa",
    neighborhood: "4100 NE 2nd Ave #301",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Aviva Medical Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.7 from 72 reviews.",
    rating: 4.7,
    reviewCount: 72,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00024",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "avivamedicalspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.7★ (72 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://avivamedicalspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "247-med-spa-fort-lauderdale",
    name: "247 Med Spa",
    providerType: "med-spa",
    neighborhood: "308 SW 6th St suite 2",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "247 Med Spa is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 55 reviews.",
    rating: 4.9,
    reviewCount: 55,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00025",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "247medspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (55 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://247medspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "healthy-glow-aesthetics-fort-lauderdale",
    name: "Healthy Glow Aesthetics",
    providerType: "med-spa",
    neighborhood: "2821 E Commercial Blvd #200",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Healthy Glow Aesthetics is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 48 reviews.",
    rating: 5,
    reviewCount: 48,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00026",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "healthyglowaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (48 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://healthyglowaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "aguilar-aesthetics-medspa-wellness-aventura",
    name: "Aguilar Aesthetics Medspa & Wellness",
    providerType: "med-spa",
    neighborhood: "2820 NE 214th St Suite 905",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "Aguilar Aesthetics Medspa & Wellness is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 183 reviews.",
    rating: 5,
    reviewCount: 183,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00027",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "aguilaraestheticsmedspaw",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (183 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://aguilaraesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "yanasthetics-llc-aventura",
    name: "Yanasthetics LLC",
    providerType: "med-spa",
    neighborhood: "18501 NE 25th Ct suite 201",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "Yanasthetics LLC is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 81 reviews.",
    rating: 5,
    reviewCount: 81,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00028",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "yanastheticsllc",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (81 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://yanasthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "le-mar-aesthetics-kendall-medspa-miami",
    name: "Le Mar Aesthetics - Kendall MedSpa",
    providerType: "med-spa",
    neighborhood: "Kendall",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Le Mar Aesthetics - Kendall MedSpa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 55 reviews.",
    rating: 5,
    reviewCount: 55,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00029",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "lemaraestheticskendallme",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (55 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://lemaraesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "meraki-med-miami-miami",
    name: "Meraki Med Miami",
    providerType: "med-spa",
    neighborhood: "2828 SW 22nd St # 205",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Meraki Med Miami is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 48 reviews.",
    rating: 5,
    reviewCount: 48,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00030",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "merakimedmiami",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (48 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://merakimedmiami.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "nuyou-medical-aesthetics-miami",
    name: "NuYou Medical Aesthetics",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "NuYou Medical Aesthetics is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 42 reviews.",
    rating: 5,
    reviewCount: 42,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00031",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "nuyoumedicalaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (42 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://nuyoumedicalaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "white-coat-med-spa-miami",
    name: "White Coat Med Spa",
    providerType: "med-spa",
    neighborhood: "7319 NW 36th St",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "White Coat Med Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 38 reviews.",
    rating: 5,
    reviewCount: 38,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00032",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "whitecoatmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (38 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://whitecoatmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "bella-vida-aesthetics-wellness-miami",
    name: "Bella Vida Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "151 SE 1st St Ph 05",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Bella Vida Aesthetics & Wellness is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 28 reviews.",
    rating: 4.8,
    reviewCount: 28,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00033",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "bellavidaaestheticswelln",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (28 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://bellavidaaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "4beauty-medspa-miami",
    name: "4Beauty Medspa",
    providerType: "med-spa",
    neighborhood: "2310 S Dixie Hwy 2nd Floor",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "4Beauty Medspa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 18 reviews.",
    rating: 4.9,
    reviewCount: 18,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00034",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "4beautymedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (18 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://4beautymedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "golden-aesthetics-wellness-miami",
    name: "Golden Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "6840 SW 40th St #207",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Golden Aesthetics & Wellness is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 14 reviews.",
    rating: 4.9,
    reviewCount: 14,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00035",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "goldenaestheticswellness",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (14 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://goldenaestheticswellness.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "get-refreshed-miami",
    name: "Get Refreshed",
    providerType: "med-spa",
    neighborhood: "2455 SW 27th Ave Suite 200",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Get Refreshed is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.7 from 12 reviews.",
    rating: 4.7,
    reviewCount: 12,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00036",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "getrefreshed",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.7★ (12 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://getrefreshed.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "aesthetic305-miami",
    name: "Aesthetic305",
    providerType: "med-spa",
    neighborhood: "20200 W Dixie Hwy Ste 808c",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Aesthetic305 is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 70 reviews.",
    rating: 5,
    reviewCount: 70,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00037",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "aesthetic305",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (70 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://aesthetic305.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "laria-medspa-miami",
    name: "Laria MedSpa",
    providerType: "med-spa",
    neighborhood: "5751 Bird Rd Suite A",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Laria MedSpa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 30 reviews.",
    rating: 5,
    reviewCount: 30,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00038",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "lariamedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (30 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://lariamedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "monaco-medspa-miami",
    name: "Monaco MedSpa",
    providerType: "med-spa",
    neighborhood: "2930 NE 2nd Ct",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Monaco MedSpa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 28 reviews.",
    rating: 5,
    reviewCount: 28,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00039",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "monacomedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (28 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://monacomedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "serenity-medical-spa-miami",
    name: "Serenity Medical & Spa",
    providerType: "med-spa",
    neighborhood: "10686 Coral Wy",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Serenity Medical & Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 22 reviews.",
    rating: 5,
    reviewCount: 22,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00040",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "serenitymedicalspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (22 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://serenitymedicalspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "join-body-good-miami",
    name: "Join Body Good",
    providerType: "med-spa",
    neighborhood: "290 NW 165th St",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Join Body Good is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 118 reviews.",
    rating: 4.8,
    reviewCount: 118,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00041",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "joinbodygood",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (118 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://joinbodygood.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "new-image-works-aventura-aventura",
    name: "New Image Works Aventura",
    providerType: "med-spa",
    neighborhood: "2920 NE 207th St Ste 1005",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "New Image Works Aventura is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 333 reviews.",
    rating: 5,
    reviewCount: 333,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00042",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "newimageworksaventura",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (333 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://newimageworks.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "the-beauty-clinic-aventura-aventura",
    name: "The Beauty Clinic Aventura",
    providerType: "med-spa",
    neighborhood: "18157 Biscayne Blvd",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "The Beauty Clinic Aventura is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 758 reviews.",
    rating: 5,
    reviewCount: 758,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00043",
    yearsOpen: 18,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "thebeautyclinicaventura",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (758 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://thebeautyclinic.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "xs-medspa-fort-lauderdale",
    name: "XS MedSpa",
    providerType: "med-spa",
    neighborhood: "Fort Lauderdale",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "XS MedSpa is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.5 from 85 reviews.",
    rating: 4.5,
    reviewCount: 85,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00044",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "xsmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.5★ (85 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://xsmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "novaskin-med-spa-miami",
    name: "Novaskin Med Spa",
    providerType: "med-spa",
    neighborhood: "Miami",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Novaskin Med Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 88 reviews.",
    rating: 4.9,
    reviewCount: 88,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00045",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "novaskinmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (88 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://novaskinmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "surface-level-med-spa-miami",
    name: "Surface Level Med Spa",
    providerType: "med-spa",
    neighborhood: "Wynwood",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Surface Level Med Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 75 reviews.",
    rating: 4.9,
    reviewCount: 75,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00046",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "surfacelevelmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (75 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://www.thesurfacelevel.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "aventura-med-spa-aventura",
    name: "Aventura Med Spa",
    providerType: "med-spa",
    neighborhood: "Aventura",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "Aventura Med Spa is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 200 reviews.",
    rating: 4.9,
    reviewCount: 200,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00047",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "aventuramedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (200 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://aventuramedspa.com/",
    reviewSource: "Google Business Profile",
  }
];

export const MIAMI_METRO_REAL_SPA_IMAGES: Record<
  string,
  { hero: string; gallery: string[]; logo?: string; source: string }
> = {
                "viiv-wellness-haus-miami-beach": {
    hero: "https://viivwellnesshaus.com/storage/elementor/thumbs/Services-Jaw-Sculpting-at-Viiv-in-Miami-Beach-r8xaiyd1qpv9f07ay7d2asacd8axskte7siw82t2tw.webp",
    logo: "https://viivwellnesshaus.com/storage/2025/07/Viiv-Wellness-Favicon.png",
    gallery: [
      "https://viivwellnesshaus.com/storage/2025/02/Viiv-subscribe-popup.webp",
      "https://viivwellnesshaus.com/storage/elementor/thumbs/Services-Cheek-Counturing-at-Viiv-in-miami-beach-r8xa82ecksyoxm0nizxmx174njyvmslbpwhf3oy8wk.webp",
      "https://viivwellnesshaus.com/storage/2025/02/carousal-a-scaled.webp",
      "https://viivwellnesshaus.com/storage/sb-instagram-feed-images/viivwellnesshaus.webp",
    ],
    source: "VIIV WELLNESS HAUS official website — services",
  },
                "shay-novi-aesthetics-wellness-miami": {
    hero: "https://shaynovi.com/wp-content/uploads/2024/11/hero-new-1.jpg",
    logo: "https://shaynovi.com/wp-content/uploads/2024/11/cropped-favicon-192x192.png",
    gallery: [
      "https://shaynovi.com/wp-content/uploads/celebrity-news.png",
      "https://shaynovi.com/wp-content/uploads/nbc.png",
      "https://shaynovi.com/wp-content/uploads/cbs-1.jpg",
      "https://shaynovi.com/wp-content/uploads/usa.png",
    ],
    source: "Shay Novi Aesthetics & Wellness official website",
  },
                      "lux-medspa-brickell-miami": {
    hero: "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/b80811c5-d8f8-44d3-bcb1-4e32e5dcac05/alan-araujo-featured-at-best-of-miami-dade-as-a-founder-with-vision-consistency-and-care.jpeg?format=1000w",
    logo: "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/5e8beb48-d3d2-417d-82b2-127355c149a0/LOGO-OF-THE-BEST-SPA-IN-MIAMI-LUX.png?format=1500w",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/eac81bd5-4e7b-4648-bbfc-1c08df165c71/client-during-ultraformer-mpt-non-surgical-face-lift-at-lux-medspa-brickell.jpg?format=1000w",
      "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/82027f3a-1d45-4cb4-9252-8d2a579e2114/lux-medspa-brickell-alan-araujo-best-facial-massage-couples-massage-miami.jpg?format=1000w",
      "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/0f096125-0259-4fd4-9e87-cbabcc8aa3f3/Best-Couples-Massage-in-Brickell-Miami-Lux-MedSpa-10%3A10-Review.jpg?format=750w",
      "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/eb4b8400-40dd-42a7-b8e1-2e7c50df8b49/monique-sandoval-licensed-massage-therapist-lux-medspa-brickell.jpg?format=1000w",
    ],
    source: "LUX MedSpa Brickell official website",
  },
                "infinity-beauty-lab-med-spa-miami": {
    hero: "https://cdn.prod.website-files.com/683928088bad0b5b8e3c0b2a/684863ac0850b04113b27869_Morpheus%208.webp",
    logo: "https://cdn.prod.website-files.com/683928088bad0b5b8e3c0b2a/683f83168c4365b4bb5bae87_Infinity%20(2).webp",
    gallery: [
      "https://cdn.prod.website-files.com/683928088bad0b5b8e3c0b2a/69c927d4ae3f694becbad9b8_WhatsApp%20Image%202026-03-29%20at%2010.23.11.jpeg",
      "https://cdn.prod.website-files.com/683928088bad0b5b8e3c0b2a/6965f477af04759f5d6a7a16_WhatsApp%20Image%202026-01-12%20at%203.05.26%20PM.jpeg",
      "https://cdn.prod.website-files.com/683928088bad0b5b8e3c0b2a/683a4e4027d44bc11ea68fd9_qt%3Dq_95.webp",
      "https://cdn.prod.website-files.com/683928088bad0b5b8e3c0b2a/684a0a7dfc68718ac7f07a7f_Infinity%20(3).webp",
    ],
    source: "Infinity Beauty Lab Med Spa official website — services",
  },
                "miami-skin-spa-aesthetics-wellness-miami": {
    hero: "https://www.miamiskinspa.com/og-default.jpg",
    logo: "https://www.miamiskinspa.com/favicon.ico",
    gallery: [
      "https://www.miamiskinspa.com/_astro/hero-poster.1z-EgmWj_Z1KpGeO.jpg",
      "https://www.miamiskinspa.com/_astro/services-face.Dm1WIjc0_Jc50s.webp",
      "https://www.miamiskinspa.com/_astro/services-injectables.Frtuh_Sn_Z19UROG.webp",
      "https://www.miamiskinspa.com/_astro/morpheus8-front-0.Drv_3tan_Z2gyiio.webp",
    ],
    source: "Miami Skin Spa Aesthetics & Wellness official website",
  },
                "brickell-cosmetic-center-aesthetics-dermatology-miami": {
    hero: "https://brickellcosmetic.com/wp-content/uploads/2025/03/new-bg-img-01-desktop-1024x533.jpg",
    logo: "https://brickellcosmetic.com/wp-content/uploads/2025/02/fav-icon.png",
    gallery: [
      "https://brickellcosmetic.com/wp-content/uploads/2025/04/two-header-mobile-2-min.jpg",
      "https://brickellcosmetic.com/wp-content/uploads/2026/06/before-after-home-img3-desktop.jpg",
      "https://brickellcosmetic.com/wp-content/uploads/2026/06/before-after-home-img2-desktop.jpg",
      "https://brickellcosmetic.com/wp-content/uploads/2026/06/before-after-home-img1-desktop.jpg",
    ],
    source: "Brickell Cosmetic Center-Aesthetics & Dermatology official website",
  },
                "gables-med-spa-coral-gables": {
    hero: "https://static.wixstatic.com/media/ca9f79_4e5d07db02704320bb15e9cc849ce972~mv2.png/v1/fill/w_1150,h_700,al_c/ca9f79_4e5d07db02704320bb15e9cc849ce972~mv2.png",
    logo: "https://static.wixstatic.com/media/ca9f79_03fb0d729a8b4e29b9393cca42d3e371%7Emv2.png/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/ca9f79_03fb0d729a8b4e29b9393cca42d3e371%7Emv2.png",
    gallery: [
      "https://static.wixstatic.com/media/ca9f79_d4e248284c2c410b9df0a1b1baf1abf6~mv2.png",
      "https://static.wixstatic.com/media/ca9f79_7ac87cabba0e420dae1b9ad4e474c9e6~mv2.png/v1/crop/x_769,y_0,w_961,h_1125/fill/w_206,h_242,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/10.png",
      "https://static.wixstatic.com/media/ca9f79_e4f4b063e64a4ca78f104bbbf914928c~mv2.jpg/v1/crop/x_212,y_0,w_2476,h_2900/fill/w_206,h_242,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/vitamin_d3_injec.jpg",
    ],
    source: "Gables Med Spa official website",
  },
                "millennium-wellness-center-fort-lauderdale": {
    hero: "https://mwellcenter.com/assets/og-image.png",
    logo: "https://mwellcenter.com/assets/apple-touch-icon.png",
    gallery: [
      "https://mwellcenter.com/assets/millenium-wellness.jpg",
      "https://mwellcenter.com/assets/goal-01.jpg",
      "https://mwellcenter.com/assets/goal-02.jpg",
      "https://mwellcenter.com/assets/goal-03.jpg",
    ],
    source: "Millennium Wellness Center official website",
  },
                "vio-med-spa-fort-lauderdale-fort-lauderdale": {
    hero: "https://viomedspa.com/fort-lauderdale/wp-content/uploads/2026/03/Hero-micro.jpg",
    logo: "https://viomedspa.com/fort-lauderdale/wp-content/uploads/2026/04/512x512.png",
    gallery: [
      "https://viomedspa.com/fort-lauderdale/wp-content/uploads/2026/05/QUIZ-1200x1200.jpg",
      "https://viomedspa.com/fort-lauderdale/wp-content/uploads/2026/04/vio-face-1024x841.jpg",
      "https://viomedspa.com/fort-lauderdale/wp-content/uploads/2026/04/clubVIO-hero-2-150x150.png",
    ],
    source: "VIO Med Spa Fort Lauderdale official website",
  },
                "amaira-med-spa-surgical-fort-lauderdale": {
    hero: "https://amairamedspa.com/wp-content/uploads/2026/02/TreatmentService-Page-Desktop-Cover-1.png",
    logo: "https://amairamedspa.com/wp-content/uploads/2024/02/Amaira_Logomark_Blush.png",
    gallery: [
      "https://amairamedspa.com/wp-content/uploads/2023/09/Before-and-After-Botox-Amaira-Med-Spa-10.jpg",
      "https://amairamedspa.com/wp-content/uploads/2023/07/Before-and-After-Botox-Amaira-Med-Spa-4.jpg",
      "https://amairamedspa.com/wp-content/uploads/2023/07/Before-and-After-Botox-Amaira-Med-Spa-5.jpg",
      "https://amairamedspa.com/wp-content/uploads/2023/07/Before-and-After-Botox-Amaira-Med-Spa-6.jpg",
    ],
    source: "Amaira Med Spa & Surgical official website — services",
  },
                "prestige-physicians-fort-lauderdale": {
    hero: "https://prestigephysicians.com/wp-content/uploads/2021/12/AdobeStock_177090077-scaled.jpeg",
    logo: "https://prestigephysicians.com/wp-content/uploads/2021/10/Group-2.svg",
    gallery: [
      "https://prestigephysicians.com/wp-content/uploads/2021/12/AdobeStock_240393284-scaled.jpeg",
      "https://prestigephysicians.com/wp-content/uploads/2021/10/sclupa.png",
      "https://prestigephysicians.com/wp-content/uploads/2021/10/2086709.png",
      "https://prestigephysicians.com/wp-content/uploads/2021/10/1771751.png",
    ],
    source: "Prestige Physicians official website — services",
  },
                "lumi-re-by-adriana-fort-lauderdale": {
    hero: "https://lumierebyadriana.com/wp-content/uploads/2023/04/photo-rejuvenation.jpg",
    logo: "https://lumierebyadriana.com/wp-content/uploads/2023/05/cropped-fav-icon-192x192.png",
    gallery: [
      "https://lumierebyadriana.com/wp-content/uploads/2023/04/facials.jpg",
      "https://lumierebyadriana.com/wp-content/uploads/2023/04/body-conturing.jpg",
      "https://lumierebyadriana.com/wp-content/uploads/2023/04/tribella.jpg",
    ],
    source: "Lumière by Adriana official website — services",
  },
                "glowing-skin-face-body-care-med-spa-fort-lauderdale": {
    hero: "https://static.wixstatic.com/media/23cad5_55ed9a9d120a4b319f1bd4bdc09b470b~mv2.jpg/v1/fill/w_1200,h_630,al_c/23cad5_55ed9a9d120a4b319f1bd4bdc09b470b~mv2.jpg",
    logo: "https://static.wixstatic.com/media/23cad5_f3c9e549c8a745c6890d6badec2d19a8~mv2.png/v1/crop/x_0,y_128,w_427,h_87/fill/w_290,h_59,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/GlowingSkin%20MedSpa%20Logo.png",
    gallery: [

    ],
    source: "Glowing Skin Face & Body Care Med Spa official website — services",
  },
                "timeless-beauty-aesthetics-fort-lauderdale": {
    hero: "https://static.wixstatic.com/media/ccc8d7_8cfadcabee3e4f6b8e21f5c1a602d49d%7Emv2.png/v1/fit/w_2500,h_1330,al_c/ccc8d7_8cfadcabee3e4f6b8e21f5c1a602d49d%7Emv2.png",
    logo: "https://static.wixstatic.com/media/ccc8d7_0c17cf7770df451eb44c2b1839d2b61a%7Emv2.png/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/ccc8d7_0c17cf7770df451eb44c2b1839d2b61a%7Emv2.png",
    gallery: [
      "https://static.wixstatic.com/media/846edb_2684efdcf1ff4b27b5a66af4bb7a0de2~mv2_d_2250_2564_s_2.jpg/v1/crop/x_0,y_292,w_2250,h_1687/fill/w_560,h_420,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/michelle%20hoff%20picture_edited.jpg",
      "https://static.wixstatic.com/media/d10fb4_a3f8cb929ab34f2089d1161450613578~mv2.jpg/v1/fill/w_144,h_144,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/dermal-fillers-1.jpg",
      "https://static.wixstatic.com/media/c5258c_30791ae7d6ef46ddbca1ad70f469610e~mv2_d_5824_7764_s_4_2.jpg/v1/fill/w_144,h_144,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/c5258c_30791ae7d6ef46ddbca1ad70f469610e~mv2_d_5824_7764_s_4_2.jpg",
      "https://static.wixstatic.com/media/c5258c_34f91e16f09742e9a6e602fa3758303a~mv2_d_5327_2848_s_4_2.jpg/v1/crop/x_2355,y_0,w_2845,h_2848/fill/w_144,h_144,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/c5258c_34f91e16f09742e9a6e602fa3758303a~mv2_d_5327_2848_s_4_2.jpg",
    ],
    source: "Timeless Beauty Aesthetics official website",
  },
                "sanctuary-medical-aesthetic-center-fort-lauderdale": {
    hero: "https://www.sanctuarymedical.com/wp-content/uploads/2021/11/preview-full-Monday-Makeover-Banner-FACE1.png",
    logo: "https://www.sanctuarymedical.com/wp-content/uploads/2024/03/fav-icon_32x32.webp",
    gallery: [
      "https://www.sanctuarymedical.com/wp-content/uploads/2025/10/6.png",
      "https://www.sanctuarymedical.com/wp-content/uploads/2022/03/home-1.webp",
      "https://www.sanctuarymedical.com/wp-content/uploads/2022/03/shop-1.webp",
      "https://www.sanctuarymedical.com/wp-content/uploads/2022/03/special.webp",
    ],
    source: "Sanctuary Medical Aesthetic Center official website",
  },
                  "lov-medspa-miami-aventura": {
    hero: "https://www.lovmedspa.com/og-image.jpg",
    logo: "https://www.lovmedspa.com/icon.png",
    gallery: [

    ],
    source: "Lov MedSpa Miami official website — services",
  },
                "vio-med-spa-aventura-aventura": {
    hero: "https://viomedspa.com/aventura/wp-content/uploads/2026/03/Hero-micro.jpg",
    logo: "https://viomedspa.com/aventura/wp-content/uploads/2026/04/512x512.png",
    gallery: [
      "https://viomedspa.com/aventura/wp-content/uploads/2026/05/QUIZ-1200x1200.jpg",
      "https://viomedspa.com/aventura/wp-content/uploads/2026/04/vio-face-1024x841.jpg",
      "https://viomedspa.com/aventura/wp-content/uploads/2026/04/clubVIO-hero-2-150x150.png",
    ],
    source: "VIO Med Spa Aventura official website",
  },
                "liquivida-wellness-center-aventura": {
    hero: "https://www.liquivida.com/hubfs/Website%20Redesign%202025/Page%20Thumbnails/deals-promotions-liquivida-thumbnail.webp",
    logo: "https://www.liquivida.com/hs-fs/hubfs/Liquivida%202020%20logo_horizontal%20wht-blue.png?width=121&amp;height=30&amp;name=Liquivida%202020%20logo_horizontal%20wht-blue.png",
    gallery: [
      "https://www.liquivida.com/hs-fs/hubfs/Website%20Redesign%202025/1.%20Home/Happy%20female%20Liquivida%20client%20getting%20IV%20drips.webp?width=1360&amp;height=765&amp;name=Happy%20female%20Liquivida%20client%20getting%20IV%20drips.webp",
      "https://www.liquivida.com/hs-fs/hubfs/Website%20Redesign%202025/Home/liquivida-wellness-center-deals.webp?width=1360&amp;height=765&amp;name=liquivida-wellness-center-deals.webp",
      "https://www.liquivida.com/hs-fs/hubfs/Website%20Redesign%202025/Home/LiquiXo%20Liquivida.webp?width=1361&amp;height=765&amp;name=LiquiXo%20Liquivida.webp",
      "https://www.liquivida.com/hs-fs/hubfs/SmartGraft/Liquivida%20Drop%20Testimonial.jpg?width=1081&amp;height=1080&amp;name=Liquivida%20Drop%20Testimonial.jpg",
    ],
    source: "Liquivida Wellness Center official website",
  },
                "solea-brickell-spa-miami": {
    hero: "https://soleabrickellspa.com/wp-content/uploads/2024/07/Morpheus8.webp",
    logo: "https://soleabrickellspa.com/wp-content/themes/spa/images/logo.png",
    gallery: [
      "https://soleabrickellspa.com/wp-content/uploads/2022/11/slide-2.jpg",
      "https://soleabrickellspa.com/wp-content/uploads/2022/11/slide-1.jpg",
      "https://soleabrickellspa.com/wp-content/uploads/2024/07/Morpheus8-300x200.webp",
      "https://soleabrickellspa.com/wp-content/uploads/2026/04/Lumeca-Miami-Main.jpg",
    ],
    source: "Solea Brickell Spa official website",
  },
                "charette-cosmetics-medical-spa-miami-beach-miami-beach": {
    hero: "https://charettecosmetics.com/wp-content/uploads/2024/07/Salmon-DNA-Injections-hero-1-scaled.jpg",
    logo: "https://charettecosmetics.com/wp-content/uploads/2024/07/Charette-Favicon1-300x300.png",
    gallery: [
      "https://charettecosmetics.com/wp-content/uploads/2022/06/Microneedling-7-e1755873558939.png",
      "https://charettecosmetics.com/wp-content/uploads/2024/07/Charette-Botox-LP-1.jpeg",
      "https://charettecosmetics.com/wp-content/uploads/2024/05/liip-filler-recovery-scaled.jpg",
      "https://charettecosmetics.com/wp-content/uploads/2025/03/Masseter-Botox.jpg",
    ],
    source: "Charette Cosmetics Medical Spa - Miami Beach official website — services",
  },
                        "bodywelle-miami-beach": {
    hero: "https://alonsomartinmd.com/wp-content/uploads/elementor/thumbs/chemical-peel-treatment-types-01-rn6jq8e9qmz7hsgbe8mflexk9k7abu1m8l0yrfpbgw.jpg",
    logo: "https://alonsomartinmd.com/wp-content/uploads/2025/07/favicon-1-300x300.png",
    gallery: [

    ],
    source: "BODYWELLE official website — services",
  },
                "skin-spa-new-york-miami-beach-medical-spa-miami-beach": {
    hero: "http://skinspanewyork.com/cdn/shop/files/newsletter-header.png?v=1748060296",
    logo: "https://skinspanewyork.com/cdn/shop/files/Skin_Spa_Flat_Logo_WHITE.png?v=1779322779&amp;width=600",
    gallery: [
      "https://skinspanewyork.com/cdn/shop/collections/skinspa_teaser.jpg?v=1764364140&width=1500",
      "https://skinspanewyork.com/cdn/shop/collections/Stocksy_txp196d0de8Y0F300_Small_1993728.jpg?v=1753138816&width=1500",
      "https://skinspanewyork.com/cdn/shop/collections/image.jpg?v=1753227349&width=1500",
      "https://skinspanewyork.com/cdn/shop/collections/Screenshot_2025-09-17_at_11.15.54_PM.png?v=1758165526&width=1500",
    ],
    source: "Skin Spa New York - Miami Beach Medical Spa official website",
  },
                "arviv-medical-aesthetics-miami-miami": {
    hero: "https://arvivaesthetics.com/wp-content/uploads/2016/10/homepage-sm.jpg",
    logo: "https://arvivaesthetics.com/wp-content/uploads/2017/08/cropped-arvivIcon1-1-250x250.png",
    gallery: [
      "https://arvivaesthetics.com/wp-content/plugins/translatepress-multilingual/assets/images/flags/es_MX.png",
      "https://arvivaesthetics.com/wp-content/uploads/2024/08/1-Homepage%20Slider.jpg",
      "https://arvivaesthetics.com/wp-content/uploads/2016/10/home-image.jpg",
      "https://arvivaesthetics.com/wp-content/uploads/2020/07/Canva-Group-of-Friends-Having-Fun-Together-Outdoors.jpg",
    ],
    source: "Arviv Medical Aesthetics Miami official website",
  },
                "aviva-medical-spa-miami": {
    hero: "https://avivamedicalspa.com/wp-content/uploads/2025/12/aviva-CO2-Laser-Treatment-instagram-922x1024.png",
    logo: "https://avivamedicalspa.com/wp-content/uploads/2023/10/android-chrome-512x512-1-300x300.png",
    gallery: [
      "https://avivamedicalspa.com/wp-content/uploads/2024/11/Resident-copia-1024x271.png",
      "https://avivamedicalspa.com/wp-content/uploads/2024/11/miami-bureau-2.png",
      "https://avivamedicalspa.com/wp-content/uploads/2025/12/aviva-render-waiting-room-view-1-1-1024x716.png",
      "https://avivamedicalspa.com/wp-content/uploads/2025/12/aviva-miami-home-promo-new-client-1024x1024.png",
    ],
    source: "Aviva Medical Spa official website — services",
  },
                "247-med-spa-fort-lauderdale": {
    hero: "https://247medspa.com/wp-content/uploads/2025/12/cropped-Untitled-design.png",
    logo: "https://247medspa.com/wp-content/uploads/2025/12/cropped-Untitled-design-192x192.png",
    gallery: [
      "https://247medspa.com/wp-content/uploads/2025/12/cropped-Untitled-design-270x270.png",
      "https://247medspa.com/wp-content/uploads/2025/12/7BEC6F3F-41BF-4671-9898-A9454507D0A2.jpg",
      "https://247medspa.com/wp-content/uploads/2025/12/Gemini_Generated_Image_kjhu77kjhu77kjhu-1.png",
      "https://247medspa.com/wp-content/uploads/2025/12/Gemini_Generated_Image_7uh6za7uh6za7uh6.png",
    ],
    source: "247 Med Spa official website",
  },
                "healthy-glow-aesthetics-fort-lauderdale": {
    hero: "https://healthyglowaesthetics.com/wp-content/uploads/2025/10/Breeze-Infusion-Treatment.png",
    logo: "https://healthyglowaesthetics.com/wp-content/uploads/2025/05/favicon-300x300.png",
    gallery: [
      "https://healthyglowaesthetics.com/wp-content/uploads/2025/01/Healthy-Glow-Aesthetics-chemical-peel-in-lauderdale-FL.webp",
      "https://healthyglowaesthetics.com/wp-content/uploads/2026/02/beautician-doing-injection-filler-female-client-scaled.jpg",
      "https://healthyglowaesthetics.com/wp-content/uploads/2026/02/laser-epilation-hair-removal-therapy.jpg",
      "https://healthyglowaesthetics.com/wp-content/uploads/2025/05/img-1.webp",
    ],
    source: "Healthy Glow Aesthetics official website — services",
  },
                "aguilar-aesthetics-medspa-wellness-aventura": {
    hero: "https://aguilaraesthetics.com/wp-content/uploads/2025/08/MEDSPA-Bottom-Branded-Imgv2.png",
    logo: "https://aguilaraesthetics.com/wp-content/uploads/2022/06/aguilar-aesthetics-fort-lauderdale-fl-logo.jpg",
    gallery: [
      "https://aguilaraesthetics.com/wp-content/uploads/2023/09/AAMEDSPA-Lina-Entrance-1005x772-1.jpg",
      "https://aguilaraesthetics.com/wp-content/uploads/2026/02/cannabis.png",
      "https://aguilaraesthetics.com/wp-content/uploads/2026/02/injection.png",
      "https://aguilaraesthetics.com/wp-content/uploads/2026/02/barcode-scanner.png",
    ],
    source: "Aguilar Aesthetics Medspa & Wellness official website",
  },
                "yanasthetics-llc-aventura": {
    hero: "https://yanasthetics.com/wp-content/uploads/2025/12/IMG_6537-1.webp",
    logo: "https://yanasthetics.com/wp-content/uploads/2025/12/icon.png",
    gallery: [
      "https://yanasthetics.com/wp-content/uploads/2025/12/IMG_9732-1.webp",
      "https://yanasthetics.com/wp-content/uploads/2025/12/IMG_9506.webp",
      "https://yanasthetics.com/wp-content/uploads/2025/12/348589573_270654898753235_5871146489113647707_n.jpg",
      "https://yanasthetics.com/wp-content/uploads/2025/12/025-pore.png",
    ],
    source: "Yanasthetics LLC official website",
  },
                "le-mar-aesthetics-kendall-medspa-miami": {
    hero: "https://lemaraesthetics.com/wp-content/uploads/2025/07/Wox4ussAsset-1@300x-scaled.png",
    logo: "https://lemaraesthetics.com/wp-content/uploads/2025/07/lemaraestheticsicon.webp",
    gallery: [
      "https://lemaraesthetics.com/wp-content/uploads/2025/07/JnYsAsset-1@300x.webp",
      "https://lemaraesthetics.com/wp-content/uploads/2025/08/0101.jpg",
      "https://lemaraesthetics.com/wp-content/uploads/2025/08/20.jpg",
      "https://lemaraesthetics.com/wp-content/uploads/2025/08/21.jpg",
    ],
    source: "Le Mar Aesthetics - Kendall MedSpa official website",
  },
                "meraki-med-miami-miami": {
    hero: "https://static.wixstatic.com/media/11062b_c08353118ce849f98c46f9788443b1fe~mv2.jpg/v1/crop/x_0,y_164,w_5000,h_3005/fill/w_872,h_524,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Laser%20Facial%20Treatment.jpg",
    logo: "https://static.wixstatic.com/media/f061f0_81c2762314a54693b2d6650d3cac7307%7Emv2.jpg/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/f061f0_81c2762314a54693b2d6650d3cac7307%7Emv2.jpg",
    gallery: [
      "https://static.wixstatic.com/media/f061f0_007eef60591547f2a27eca0a0c1f16ad~mv2.png/v1/fill/w_188,h_250,fp_0.50_0.50,q_35,blur_30,enc_avif,quality_auto/f061f0_007eef60591547f2a27eca0a0c1f16ad~mv2.webp",
      "https://static.wixstatic.com/media/f061f0_82e9ca4c27db4784be0ad066c03d3431~mv2.png/v1/fill/w_500,h_500,al_c/f061f0_82e9ca4c27db4784be0ad066c03d3431~mv2.png",
      "https://static.wixstatic.com/media/nsplsh_81195f4c7ab54054ae4f6d272bc13462~mv2.jpg/v1/crop/x_0,y_247,w_2624,h_3441/fill/w_456,h_598,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/Image%20by%20Toa%20Heftiba.jpg",
      "https://static.wixstatic.com/media/f061f0_a65a2ad0148e483d9bac288a4b05f8fb~mv2.webp/v1/fill/w_140,h_140,al_c,q_80,usm_0.66_1.00_0.01,blur_2,enc_avif,quality_auto/f061f0_a65a2ad0148e483d9bac288a4b05f8fb~mv2.webp",
    ],
    source: "Meraki Med Miami official website — services",
  },
                      "nuyou-medical-aesthetics-miami": {
    hero: "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/34689224-0680-4f39-ac86-368c79adca92/whyus-sectionbg%402x-scaled+%281%29+3.jpg",
    logo: "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/e66d1a3b-a611-404e-bce9-4969b8349dc5/NuYou+Logo+copy+%284%29.png?format=1500w",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/176a96c6-233f-42e1-9f1b-fae24bfcc5ec/photo-output+2.JPEG",
      "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/d295c737-40cd-475b-b23d-2bf5720dedb7/savingPNG+219.PNG",
      "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/2d68560a-4fce-45de-a0ca-d8705c3e5c11/savingPNG+10.PNG",
      "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/29e62652-a0fa-478a-8d57-577f747cd99d/Signature+%282%29.png",
    ],
    source: "NuYou Medical Aesthetics official website",
  },
                "white-coat-med-spa-miami": {
    hero: "https://whitecoatmedspa.com/wp-content/uploads/2023/02/servicios-OXINA-BOTULINICA-Y-RELLENOS.png",
    logo: "https://whitecoatmedspa.com/wp-content/uploads/2023/02/imagen-1.png",
    gallery: [
      "https://whitecoatmedspa.com/wp-content/uploads/2023/02/imagen.png",
      "https://whitecoatmedspa.com/wp-content/plugins/translatepress-multilingual/assets/images/flags/es_ES.png",
      "https://whitecoatmedspa.com/wp-content/plugins/translatepress-multilingual/assets/images/flags/en_US.png",
    ],
    source: "White Coat Med Spa official website",
  },
                "bella-vida-aesthetics-wellness-miami": {
    hero: "https://bellavidaaesthetics.com/wp-content/uploads/2024/03/bella-vida-aesthetics-in-miami-sm.jpg",
    logo: "https://bellavidaaesthetics.com/wp-content/uploads/2022/09/cropped-BVA_Favicon-192x192.jpg",
    gallery: [
      "https://bellavidaaesthetics.com/wp-content/uploads/2025/02/Photo-Jan-15-2024-10-58-26-PM-1-1-scaled.jpg",
      "https://bellavidaaesthetics.com/wp-content/uploads/2023/10/neurotoxin-at-bella-vida-img.jpg",
      "https://bellavidaaesthetics.com/wp-content/uploads/2023/10/microneeding-at-bella-vida-img.jpg",
      "https://bellavidaaesthetics.com/wp-content/uploads/2023/10/dermal-fillers-at-bella-vida-img.png",
    ],
    source: "Bella Vida Aesthetics & Wellness official website",
  },
                "4beauty-medspa-miami": {
    hero: "https://4beautymedspa.com/wp-content/uploads/2024/08/slider.jpg",
    logo: "https://4beautymedspa.com/wp-content/uploads/2024/08/cropped-favicon-192x192.webp",
    gallery: [
      "https://4beautymedspa.com/wp-content/uploads/2024/09/photo2.jpg",
      "https://4beautymedspa.com/wp-content/uploads/2024/09/Laser-treatments.jpg",
      "https://4beautymedspa.com/wp-content/uploads/2024/10/DSC00431.jpeg",
      "https://4beautymedspa.com/wp-content/uploads/2024/09/4Beauty-Med-Spa-IMG-1176.jpg",
    ],
    source: "4Beauty Medspa official website",
  },
                "golden-aesthetics-wellness-miami": {
    hero: "https://content.app-sources.com/s/497367612352444631/thumbnails/640x480/Images/continuous-one-line-drawing-hand-holding-syringe-lips-injection-beauty-procedures-fillers_1-7945186.png?format=webp",
    logo: "https://content.app-sources.com/s/497367612352444631/uploads/Downloaded/aefeGroup_46-2611706.png",
    gallery: [
      "https://content.app-sources.com/s/497367612352444631/thumbnails/640x480/Images/continuous-one-line-drawing-hand-holding-syringe-lips-injection-beauty-procedures-fillers-7945214.png?format=webp",
      "https://content.app-sources.com/s/497367612352444631/uploads/Images/continuous-one-line-drawing-hand-holding-syringe-lips-injection-beauty-procedures-fillers_1-7945186.png?format=webp",
      "https://content.app-sources.com/s/497367612352444631/uploads/Images/continuous-one-line-drawing-hand-holding-syringe-lips-injection-beauty-procedures-fillers-7945214.png?format=webp",
    ],
    source: "Golden Aesthetics & Wellness official website — services",
  },
                "get-refreshed-miami": {
    hero: "https://www.getrefreshed.com/wp-content/uploads/2026/03/radiesse-treatment-uai-1080x1080.webp",
    logo: "https://www.getrefreshed.com/wp-content/uploads/2026/04/cropped-logo-gr-favicon-darkmode-whitefirst-192x192.png",
    gallery: [
      "https://www.getrefreshed.com/wp-content/uploads/2024/06/Botox-Home-uai-400x300.webp",
      "https://www.getrefreshed.com/wp-content/uploads/2025/10/Facial-Balancing-miami-13-uai-400x266.jpg",
      "https://www.getrefreshed.com/wp-content/uploads/2025/01/Chin-Jawline-Filler-miami-01-uai-400x266.jpg",
      "https://www.getrefreshed.com/wp-content/uploads/2024/07/Facial-Harmonization-miami-04-uai-400x266.webp",
    ],
    source: "Get Refreshed official website — services",
  },
                        "aesthetic305-miami": {
    hero: "https://www.medaestheticsmiami.com/wp-content/uploads/2023/04/services-advanced500.jpg",
    logo: "https://www.medaestheticsmiami.com/wp-content/uploads/2022/10/medam-logo-vertical-216.png",
    gallery: [
      "https://www.medaestheticsmiami.com/wp-content/uploads/2023/04/swich-facials.jpg",
      "https://www.medaestheticsmiami.com/wp-content/uploads/2023/04/services-laser500.jpg",
      "https://www.medaestheticsmiami.com/wp-content/uploads/2023/04/services-core500.jpg",
      "https://www.medaestheticsmiami.com/wp-content/uploads/2023/04/services-injectables500.jpg",
    ],
    source: "Aesthetic305 official website — services",
  },
                  "laria-medspa-miami": {
    hero: "https://lariamedspa.com/wp-content/uploads/bb-plugin/cache/spa-member-landscape-22b6003f4b7aab5b4b33d9ae32cbc92f-n3z4ybxuveap.jpg",
    logo: "https://lariamedspa.com/wp-content/uploads/2023/11/logo@1.2x-1.png",
    gallery: [
      "https://lariamedspa.com/wp-content/uploads/2026/02/team.jpg",
      "https://lariamedspa.com/wp-content/uploads/2023/11/botox.png",
      "https://lariamedspa.com/wp-content/uploads/2023/11/sculptra.png",
      "https://lariamedspa.com/wp-content/uploads/2023/11/hydrafacial.png",
    ],
    source: "Laria MedSpa official website — services",
  },
                        "monaco-medspa-miami": {
    hero: "https://lirp.cdn-website.com/cee2bf2b/dms3rep/multi/opt/PhotoRetouch1752622202476-1920w.jpg",
    logo: "https://irp.cdn-website.com/cee2bf2b/dms3rep/multi/Home-screen-icon-Monaco-MedSpa.png",
    gallery: [

    ],
    source: "Monaco MedSpa official website — services",
  },
                "serenity-medical-spa-miami": {
    hero: "https://serenitymedicalspa.com/wp-content/uploads/2023/11/294280474_10158540543185264_3624624063560670121_n.png",
    logo: "https://serenitymedicalspa.com/wp-content/uploads/2023/12/favicon-200x200.png",
    gallery: [
      "https://serenitymedicalspa.com/wp-content/uploads/2024/12/Imago-Dei-Photography-Lindsey-Eveler-3-1463x2048-1-1.jpg",
      "https://serenitymedicalspa.com/wp-content/uploads/2024/12/sugaring-pic-1024x576-1.jpg",
      "https://serenitymedicalspa.com/wp-content/uploads/2024/12/IMG_4894-1-1024x768-1.jpg",
      "https://serenitymedicalspa.com/wp-content/uploads/2023/11/serenity-3.png",
    ],
    source: "Serenity Medical & Spa official website",
  },
                "join-body-good-miami": {
    hero: "https://joinbodygood.com/images/dr-linda-hero.jpg",
    logo: "https://joinbodygood.com/apple-icon.png?apple-icon.0qb5oly_4cr.-.png",
    gallery: [
      "https://joinbodygood.com/images/weight-loss-card.jpg",
      "https://joinbodygood.com/images/glp1-medications.png",
      "https://joinbodygood.com/images/wellness-injections-card.jpg",
      "https://joinbodygood.com/images/care-plan-card.jpg",
    ],
    source: "Join Body Good official website",
  },
                "new-image-works-aventura-aventura": {
    hero: "https://newimageworks.com/wp-content/themes/niw_4_2_9/img/new-image-works-og.jpg",
    logo: "https://newimageworks.com/wp-content/uploads/2021/02/cropped-niw-logo-192x192.jpg",
    gallery: [
      "https://newimageworks.com/wp-content/uploads/2025/10/allergan-2025.webp",
      "https://newimageworks.com/wp-content/uploads/2025/03/new-image-works-award-2025-chicago.webp",
      "https://newimageworks.com/wp-content/uploads/2024/03/award-2024-1.webp",
      "https://newimageworks.com/wp-content/uploads/2024/03/award-2024-2.webp",
    ],
    source: "New Image Works Aventura official website",
  },
                "the-beauty-clinic-aventura-aventura": {
    hero: "https://thebeautyclinic.com/wp-content/uploads/2021/02/The-Beauty-Clinic-Web-Design-by-Inga-Brel-EYEBRANDIT-1-scaled.jpg?wsr",
    logo: "https://thebeautyclinic.com/wp-content/uploads/2020/05/cropped-THEBEAUTYCLINIC_square-1-192x192.png",
    gallery: [
      "https://thebeautyclinic.com/wp-content/uploads/2020/05/cropped-THEBEAUTYCLINIC_square-1-270x270.png",
      "https://thebeautyclinic.com/wp-content/uploads/2020/05/THEBEAUTYCLINIC_square-1019x1024.png",
      "https://thebeautyclinic.com/wp-content/uploads/2020/10/Shape1.png",
      "https://thebeautyclinic.com/wp-content/uploads/2025/05/botaxfillerimg.webp",
    ],
    source: "The Beauty Clinic Aventura official website",
  },
                        "xs-medspa-fort-lauderdale": {
    hero: "https://medspaflorida.com/wp-content/uploads/2025/07/Medspa_florida3-2-1.png",
    logo: "https://refreshmedical.com/wp-content/uploads/2025/04/Final-05-07-removebg-preview-1-100x100.png",
    gallery: [

    ],
    source: "XS MedSpa official website — services",
  },
                "novaskin-med-spa-miami": {
    hero: "https://novaskinmedspa.com/wp-content/uploads/2025/07/laser-treatments-600x400-1.jpg",
    logo: "https://novaskinmedspa.com/wp-content/uploads/2026/01/LOGO-2.svg",
    gallery: [
      "https://novaskinmedspa.com/wp-content/uploads/2025/07/skin-tightening-600x400-1.png",
      "https://novaskinmedspa.com/wp-content/uploads/2025/07/hair-loss-treatment-miami-600x400-1.jpg",
      "https://novaskinmedspa.com/wp-content/uploads/2026/01/hydrafacial-miami-novaskin-med-spa.jpg",
      "https://novaskinmedspa.com/wp-content/uploads/2025/07/body-contouring-miami-600x400-1.png",
    ],
    source: "Novaskin Med Spa official website — services",
  },
                "surface-level-med-spa-miami": {
    hero: "https://www.thesurfacelevel.com/_static_/background/og-feat.png",
    logo: "https://www.thesurfacelevel.com/_static_/logos/header.png",
    gallery: [
      "https://www.thesurfacelevel.com/_static_/masthead/masthead-01.jpg",
      "https://www.thesurfacelevel.com/_static_/masthead/option-2.jpg?1751399839898",
      "https://www.thesurfacelevel.com/_static_/feature/next_feature.jpg?1750965375618",
      "https://www.thesurfacelevel.com/_static_/feature/Frame-1623.jpg",
    ],
    source: "Surface Level Med Spa official website",
  },
                "aventura-med-spa-aventura": {
    hero: "https://cdn.aventuramedspa.com/site/social/twitter-image.png",
    logo: "https://aventuramedspa.com/icon.png?98c428477c867c58",
    gallery: [
      "https://cdn.aventuramedspa.com/site/images/Background.png",
      "https://cdn.aventuramedspa.com/site/images/Background6.png",
      "https://aventuramedspa.com/new-images/home/Hero.png?dpl=dpl_5XJQG9n6AvqvLuYqF6j9AG6fVwYZ",
      "https://aventuramedspa.com/new-images/home/peptide.png?dpl=dpl_5XJQG9n6AvqvLuYqF6j9AG6fVwYZ",
    ],
    source: "Aventura Med Spa official website",
  }
};
