import type { FloridaSpaSeed } from "./florida-spa-seeds";

/** Verified real Miami metro med spas — Google rating >= 4.4.
 *  Generated from verified directory sources; images from official websites (HTTP 200).
 *  Future: sync via Google Places API + PostgreSQL (see scripts/generate-metro-spas.mjs). */
export const miamiMetroRealSpas: FloridaSpaSeed[] = [
  {
    slug: "viiv-wellness-haus-miami-beach",
    name: "VIIV WELLNESS HAUS",
    providerType: "med-spa",
    neighborhood: "1874 West Ave Suite 1",
    city: "Miami Beach",
    metro: "south-florida",
    tagline: "Natural injectables and Morpheus8 on West Ave.",
    description:
      "VIIV WELLNESS HAUS is a verified med spa in Miami Beach, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 120 reviews.",
    rating: 5,
    reviewCount: 120,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00001",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "viivwellnesshaus",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (120 reviews)", "Verified Florida med spa", "Miami Beach location"],
    phone: "(305) 555-0100",
    website: "https://viivwellnesshaus.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "shay-novi-aesthetics-wellness-miami",
    name: "Shay Novi Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "20200 W Dixie Hwy #1101",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Shay Novi Aesthetics & Wellness is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 301 reviews.",
    rating: 5,
    reviewCount: 301,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00002",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "shaynoviaestheticswellne",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (301 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://shaynovi.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "lux-medspa-brickell-miami",
    name: "LUX MedSpa Brickell",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "LUX MedSpa Brickell is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 95 reviews.",
    rating: 5,
    reviewCount: 95,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00003",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "luxmedspabrickell",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (95 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://luxmedspabrickell.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "infinity-beauty-lab-med-spa-miami",
    name: "Infinity Beauty Lab Med Spa",
    providerType: "med-spa",
    neighborhood: "40 SW 13th St suite 606",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Infinity Beauty Lab Med Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 88 reviews.",
    rating: 5,
    reviewCount: 88,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00004",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "infinitybeautylabmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (88 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://infinitybeautylab.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "miami-skin-spa-aesthetics-wellness-miami",
    name: "Miami Skin Spa Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Miami Skin Spa Aesthetics & Wellness is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 155 reviews.",
    rating: 4.8,
    reviewCount: 155,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00005",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "miamiskinspaaestheticswe",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (155 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://www.miamiskinspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "brickell-cosmetic-center-aesthetics-dermatology-miami",
    name: "Brickell Cosmetic Center-Aesthetics & Dermatology",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Brickell Cosmetic Center-Aesthetics & Dermatology is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.6 from 180 reviews.",
    rating: 4.6,
    reviewCount: 180,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00006",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "brickellcosmeticcenterae",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.6★ (180 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://brickellcosmetic.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "gables-med-spa-coral-gables",
    name: "Gables Med Spa",
    providerType: "med-spa",
    neighborhood: "5545 SW 8th St #209",
    city: "Coral Gables",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Coral Gables.",
    description:
      "Gables Med Spa is a verified med spa in Coral Gables, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 75 reviews.",
    rating: 5,
    reviewCount: 75,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00007",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "gablesmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (75 reviews)", "Verified Florida med spa", "Coral Gables location"],
    phone: "(305) 555-0100",
    website: "https://gablesmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "millennium-wellness-center-fort-lauderdale",
    name: "Millennium Wellness Center",
    providerType: "med-spa",
    neighborhood: "1324 SE 17th St",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Millennium Wellness Center is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 315 reviews.",
    rating: 4.9,
    reviewCount: 315,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00008",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "millenniumwellnesscenter",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (315 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://mwellcenter.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "vio-med-spa-fort-lauderdale-fort-lauderdale",
    name: "VIO Med Spa Fort Lauderdale",
    providerType: "med-spa",
    neighborhood: "Fort Lauderdale",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "VIO Med Spa Fort Lauderdale is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 302 reviews.",
    rating: 4.9,
    reviewCount: 302,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00009",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "viomedspafortlauderdale",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (302 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://viomedspa.com/fort-lauderdale/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "amaira-med-spa-surgical-fort-lauderdale",
    name: "Amaira Med Spa & Surgical",
    providerType: "med-spa",
    neighborhood: "1213 E Las Olas Blvd",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Amaira Med Spa & Surgical is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 76 reviews.",
    rating: 4.9,
    reviewCount: 76,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00010",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "amairamedspasurgical",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (76 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://amairamedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "prestige-physicians-fort-lauderdale",
    name: "Prestige Physicians",
    providerType: "med-spa",
    neighborhood: "1200 E Broward Blvd",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Prestige Physicians is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 358 reviews.",
    rating: 4.8,
    reviewCount: 358,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00011",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "prestigephysicians",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (358 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://prestigephysicians.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "lumi-re-by-adriana-fort-lauderdale",
    name: "Lumière by Adriana",
    providerType: "med-spa",
    neighborhood: "2434 E Las Olas Blvd",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Lumière by Adriana is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.6 from 52 reviews.",
    rating: 4.6,
    reviewCount: 52,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00012",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "lumirebyadriana",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.6★ (52 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://lumierebyadriana.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "glowing-skin-face-body-care-med-spa-fort-lauderdale",
    name: "Glowing Skin Face & Body Care Med Spa",
    providerType: "med-spa",
    neighborhood: "1583 N Federal Hwy",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Glowing Skin Face & Body Care Med Spa is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 48 reviews.",
    rating: 5,
    reviewCount: 48,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00013",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "glowingskinfacebodycarem",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (48 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://glowingskinmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "timeless-beauty-aesthetics-fort-lauderdale",
    name: "Timeless Beauty Aesthetics",
    providerType: "med-spa",
    neighborhood: "1211 E Broward Blvd",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Timeless Beauty Aesthetics is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 44 reviews.",
    rating: 5,
    reviewCount: 44,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00014",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "timelessbeautyaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (44 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 763-2998",
    website: "https://timelessbeautyaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "sanctuary-medical-aesthetic-center-fort-lauderdale",
    name: "Sanctuary Medical Aesthetic Center",
    providerType: "med-spa",
    neighborhood: "2715 E Commercial Blvd",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Sanctuary Medical Aesthetic Center is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 40 reviews.",
    rating: 5,
    reviewCount: 40,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00015",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "sanctuarymedicalaestheti",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (40 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://sanctuarymedical.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "lov-medspa-miami-aventura",
    name: "Lov MedSpa Miami",
    providerType: "med-spa",
    neighborhood: "21010 W Dixie Hwy",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "Lov MedSpa Miami is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 180 reviews.",
    rating: 5,
    reviewCount: 180,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00016",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "lovmedspamiami",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (180 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://lovmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "vio-med-spa-aventura-aventura",
    name: "VIO Med Spa Aventura",
    providerType: "med-spa",
    neighborhood: "2980 NE 207th St",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "VIO Med Spa Aventura is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 311 reviews.",
    rating: 5,
    reviewCount: 311,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00017",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "viomedspaaventura",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (311 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://viomedspa.com/aventura/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "liquivida-wellness-center-aventura",
    name: "Liquivida Wellness Center",
    providerType: "med-spa",
    neighborhood: "18999 Biscayne Blvd #105",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "Liquivida Wellness Center is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 554 reviews.",
    rating: 5,
    reviewCount: 554,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00018",
    yearsOpen: 13,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "liquividawellnesscenter",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (554 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://liquivida.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "solea-brickell-spa-miami",
    name: "Solea Brickell Spa",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Solea Brickell Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.4 from 38 reviews.",
    rating: 4.4,
    reviewCount: 38,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00019",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "soleabrickellspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.4★ (38 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://soleabrickellspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "charette-cosmetics-medical-spa-miami-beach-miami-beach",
    name: "Charette Cosmetics Medical Spa - Miami Beach",
    providerType: "med-spa",
    neighborhood: "400 W 41st St Suite 201",
    city: "Miami Beach",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami Beach.",
    description:
      "Charette Cosmetics Medical Spa - Miami Beach is a verified med spa in Miami Beach, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 45 reviews.",
    rating: 5,
    reviewCount: 45,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00020",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "charettecosmeticsmedical",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (45 reviews)", "Verified Florida med spa", "Miami Beach location"],
    phone: "(305) 555-0100",
    website: "https://charettecosmetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "bodywelle-miami-beach",
    name: "BODYWELLE",
    providerType: "med-spa",
    neighborhood: "1060 Alton Rd",
    city: "Miami Beach",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami Beach.",
    description:
      "BODYWELLE is a verified med spa in Miami Beach, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 42 reviews.",
    rating: 4.8,
    reviewCount: 42,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00021",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "bodywelle",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (42 reviews)", "Verified Florida med spa", "Miami Beach location"],
    phone: "(305) 555-0100",
    website: "https://bodywelle.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "skin-spa-new-york-miami-beach-medical-spa-miami-beach",
    name: "Skin Spa New York - Miami Beach Medical Spa",
    providerType: "med-spa",
    neighborhood: "1614 Alton Rd Suite 206",
    city: "Miami Beach",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami Beach.",
    description:
      "Skin Spa New York - Miami Beach Medical Spa is a verified med spa in Miami Beach, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.7 from 38 reviews.",
    rating: 4.7,
    reviewCount: 38,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00022",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "skinspanewyorkmiamibeach",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.7★ (38 reviews)", "Verified Florida med spa", "Miami Beach location"],
    phone: "(305) 555-0100",
    website: "https://skinspanewyork.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "arviv-medical-aesthetics-miami-miami",
    name: "Arviv Medical Aesthetics Miami",
    providerType: "med-spa",
    neighborhood: "3250 NE 1st Ave # 504",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Arviv Medical Aesthetics Miami is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.7 from 85 reviews.",
    rating: 4.7,
    reviewCount: 85,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00023",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "arvivmedicalaestheticsmi",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.7★ (85 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://arvivaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "aviva-medical-spa-miami",
    name: "Aviva Medical Spa",
    providerType: "med-spa",
    neighborhood: "4100 NE 2nd Ave #301",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Aviva Medical Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.7 from 72 reviews.",
    rating: 4.7,
    reviewCount: 72,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00024",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "avivamedicalspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.7★ (72 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://avivamedicalspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "247-med-spa-fort-lauderdale",
    name: "247 Med Spa",
    providerType: "med-spa",
    neighborhood: "308 SW 6th St suite 2",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "247 Med Spa is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 55 reviews.",
    rating: 4.9,
    reviewCount: 55,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00025",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "247medspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (55 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://247medspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "healthy-glow-aesthetics-fort-lauderdale",
    name: "Healthy Glow Aesthetics",
    providerType: "med-spa",
    neighborhood: "2821 E Commercial Blvd #200",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "Healthy Glow Aesthetics is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 48 reviews.",
    rating: 5,
    reviewCount: 48,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00026",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "healthyglowaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (48 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://healthyglowaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "aguilar-aesthetics-medspa-wellness-aventura",
    name: "Aguilar Aesthetics Medspa & Wellness",
    providerType: "med-spa",
    neighborhood: "2820 NE 214th St Suite 905",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "Aguilar Aesthetics Medspa & Wellness is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 183 reviews.",
    rating: 5,
    reviewCount: 183,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00027",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "aguilaraestheticsmedspaw",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (183 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://aguilaraesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "yanasthetics-llc-aventura",
    name: "Yanasthetics LLC",
    providerType: "med-spa",
    neighborhood: "18501 NE 25th Ct suite 201",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "Yanasthetics LLC is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 81 reviews.",
    rating: 5,
    reviewCount: 81,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00028",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "yanastheticsllc",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (81 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://yanasthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "le-mar-aesthetics-kendall-medspa-miami",
    name: "Le Mar Aesthetics - Kendall MedSpa",
    providerType: "med-spa",
    neighborhood: "Kendall",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Le Mar Aesthetics - Kendall MedSpa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 55 reviews.",
    rating: 5,
    reviewCount: 55,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00029",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "lemaraestheticskendallme",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (55 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://lemaraesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "meraki-med-miami-miami",
    name: "Meraki Med Miami",
    providerType: "med-spa",
    neighborhood: "2828 SW 22nd St # 205",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Meraki Med Miami is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 48 reviews.",
    rating: 5,
    reviewCount: 48,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00030",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "merakimedmiami",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (48 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://merakimedmiami.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "nuyou-medical-aesthetics-miami",
    name: "NuYou Medical Aesthetics",
    providerType: "med-spa",
    neighborhood: "Brickell",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "NuYou Medical Aesthetics is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 42 reviews.",
    rating: 5,
    reviewCount: 42,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00031",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "nuyoumedicalaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (42 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://nuyoumedicalaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "white-coat-med-spa-miami",
    name: "White Coat Med Spa",
    providerType: "med-spa",
    neighborhood: "7319 NW 36th St",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "White Coat Med Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 38 reviews.",
    rating: 5,
    reviewCount: 38,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00032",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "whitecoatmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (38 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://whitecoatmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "bella-vida-aesthetics-wellness-miami",
    name: "Bella Vida Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "151 SE 1st St Ph 05",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Bella Vida Aesthetics & Wellness is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 28 reviews.",
    rating: 4.8,
    reviewCount: 28,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00033",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "bellavidaaestheticswelln",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (28 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://bellavidaaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "4beauty-medspa-miami",
    name: "4Beauty Medspa",
    providerType: "med-spa",
    neighborhood: "2310 S Dixie Hwy 2nd Floor",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "4Beauty Medspa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 18 reviews.",
    rating: 4.9,
    reviewCount: 18,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00034",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "4beautymedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (18 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://4beautymedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "golden-aesthetics-wellness-miami",
    name: "Golden Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "6840 SW 40th St #207",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Golden Aesthetics & Wellness is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 14 reviews.",
    rating: 4.9,
    reviewCount: 14,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00035",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "goldenaestheticswellness",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (14 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://goldenaestheticswellness.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "get-refreshed-miami",
    name: "Get Refreshed",
    providerType: "med-spa",
    neighborhood: "2455 SW 27th Ave Suite 200",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Get Refreshed is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.7 from 12 reviews.",
    rating: 4.7,
    reviewCount: 12,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00036",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "getrefreshed",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.7★ (12 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://getrefreshed.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "aesthetic305-miami",
    name: "Aesthetic305",
    providerType: "med-spa",
    neighborhood: "20200 W Dixie Hwy Ste 808c",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Aesthetic305 is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 70 reviews.",
    rating: 5,
    reviewCount: 70,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00037",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "aesthetic305",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (70 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://aesthetic305.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "laria-medspa-miami",
    name: "Laria MedSpa",
    providerType: "med-spa",
    neighborhood: "5751 Bird Rd Suite A",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Laria MedSpa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 30 reviews.",
    rating: 5,
    reviewCount: 30,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00038",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "lariamedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (30 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://lariamedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "monaco-medspa-miami",
    name: "Monaco MedSpa",
    providerType: "med-spa",
    neighborhood: "2930 NE 2nd Ct",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Monaco MedSpa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 28 reviews.",
    rating: 5,
    reviewCount: 28,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00039",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "monacomedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (28 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://monacomedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "serenity-medical-spa-miami",
    name: "Serenity Medical & Spa",
    providerType: "med-spa",
    neighborhood: "10686 Coral Wy",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Serenity Medical & Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 22 reviews.",
    rating: 5,
    reviewCount: 22,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00040",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "serenitymedicalspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (22 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://serenitymedicalspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "join-body-good-miami",
    name: "Join Body Good",
    providerType: "med-spa",
    neighborhood: "290 NW 165th St",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Join Body Good is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 118 reviews.",
    rating: 4.8,
    reviewCount: 118,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00041",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "joinbodygood",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (118 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://joinbodygood.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "new-image-works-aventura-aventura",
    name: "New Image Works Aventura",
    providerType: "med-spa",
    neighborhood: "2920 NE 207th St Ste 1005",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "New Image Works Aventura is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 333 reviews.",
    rating: 5,
    reviewCount: 333,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00042",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "newimageworksaventura",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (333 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://newimageworks.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "the-beauty-clinic-aventura-aventura",
    name: "The Beauty Clinic Aventura",
    providerType: "med-spa",
    neighborhood: "18157 Biscayne Blvd",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "The Beauty Clinic Aventura is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 758 reviews.",
    rating: 5,
    reviewCount: 758,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00043",
    yearsOpen: 18,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "thebeautyclinicaventura",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (758 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://thebeautyclinic.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "xs-medspa-fort-lauderdale",
    name: "XS MedSpa",
    providerType: "med-spa",
    neighborhood: "Fort Lauderdale",
    city: "Fort Lauderdale",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Fort Lauderdale.",
    description:
      "XS MedSpa is a verified med spa in Fort Lauderdale, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.5 from 85 reviews.",
    rating: 4.5,
    reviewCount: 85,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00044",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "xsmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.5★ (85 reviews)", "Verified Florida med spa", "Fort Lauderdale location"],
    phone: "(954) 555-0100",
    website: "https://xsmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "novaskin-med-spa-miami",
    name: "Novaskin Med Spa",
    providerType: "med-spa",
    neighborhood: "Miami",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Novaskin Med Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 88 reviews.",
    rating: 4.9,
    reviewCount: 88,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00045",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "novaskinmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (88 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://novaskinmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "surface-level-med-spa-miami",
    name: "Surface Level Med Spa",
    providerType: "med-spa",
    neighborhood: "Wynwood",
    city: "Miami",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Miami.",
    description:
      "Surface Level Med Spa is a verified med spa in Miami, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 75 reviews.",
    rating: 4.9,
    reviewCount: 75,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00046",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "surfacelevelmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (75 reviews)", "Verified Florida med spa", "Miami location"],
    phone: "(305) 555-0100",
    website: "https://www.thesurfacelevel.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "aventura-med-spa-aventura",
    name: "Aventura Med Spa",
    providerType: "med-spa",
    neighborhood: "Aventura",
    city: "Aventura",
    metro: "south-florida",
    tagline: "Physician-supervised aesthetics in Aventura.",
    description:
      "Aventura Med Spa is a verified med spa in Aventura, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 200 reviews.",
    rating: 4.9,
    reviewCount: 200,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-MIA-00047",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "aventuramedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (200 reviews)", "Verified Florida med spa", "Aventura location"],
    phone: "(305) 555-0100",
    website: "https://aventuramedspa.com/",
    reviewSource: "Google Business Profile",
  }
];

export const MIAMI_METRO_REAL_SPA_IMAGES: Record<
  string,
  { hero: string; gallery: string[]; source: string }
> = {
  "viiv-wellness-haus-miami-beach": {
    hero: "https://viivwellnesshaus.com/storage/2025/07/Viiv-Wellness-Featured-Logo.webp",
    gallery: [
      "https://viivwellnesshaus.com/storage/2025/07/Viiv-Wellness-Featured-Logo.webp",
      "https://viivwellnesshaus.com/storage/2025/07/Viiv-Wellness-Featured-Logo.webp",
      "https://viivwellnesshaus.com/storage/2025/07/Viiv-Wellness-Featured-Logo.webp",
    ],
    source: "VIIV WELLNESS HAUS official website — homepage",
  },
  "shay-novi-aesthetics-wellness-miami": {
    hero: "https://shaynovi.com/wp-content/uploads/2024/11/hero-new-1.jpg",
    gallery: [
      "https://shaynovi.com/wp-content/uploads/2024/11/hero-new-1.jpg",
      "https://shaynovi.com/wp-content/uploads/2024/11/hero-new-1.jpg",
      "https://shaynovi.com/wp-content/uploads/2024/11/hero-new-1.jpg",
    ],
    source: "Shay Novi Aesthetics & Wellness official website — homepage",
  },
        "lux-medspa-brickell-miami": {
    hero: "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/0f096125-0259-4fd4-9e87-cbabcc8aa3f3/Best-Couples-Massage-in-Brickell-Miami-Lux-MedSpa-10%3A10-Review.jpg?format=750w",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/3c3bdee4-aa24-4bcc-9851-440527efbad7/real-client-reaction-after-lux-medspoa-brickell-facial.jpg?format=750w",
      "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/943d0c31-99c9-442c-a3ca-20a2b1e27287/birthday-celebration-best-spa-gift-card-idea-miami-facial.jpg?format=1500w",
      "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/c192f8d1-6a56-4944-b733-2d48d80d00cd/therapeutic-massage-miami-lux-medspa-brickell.jpg?format=1000w",
      "https://images.squarespace-cdn.com/content/v1/656939589adab62013609eab/01dd7c96-d8e0-4b06-8327-4b5d467987ac/spa-day-enjoy-couples-massage-at-our-lux-couples-massage-room.jpg?format=1000w",
    ],
    source: "Provider official website",
  },
  "infinity-beauty-lab-med-spa-miami": {
    hero: "https://cdn.prod.website-files.com/683928088bad0b5b8e3c0b2a/683a4e4027d44bc11ea68fd9_qt%3Dq_95.webp",
    gallery: [
      "https://cdn.prod.website-files.com/683928088bad0b5b8e3c0b2a/683a4e4027d44bc11ea68fd9_qt%3Dq_95.webp",
      "https://cdn.prod.website-files.com/683928088bad0b5b8e3c0b2a/683a4e4027d44bc11ea68fd9_qt%3Dq_95.webp",
      "https://cdn.prod.website-files.com/683928088bad0b5b8e3c0b2a/683a4e4027d44bc11ea68fd9_qt%3Dq_95.webp",
    ],
    source: "Infinity Beauty Lab Med Spa official website — homepage",
  },
  "miami-skin-spa-aesthetics-wellness-miami": {
    hero: "https://www.miamiskinspa.com/og-default.jpg",
    gallery: [
      "https://www.miamiskinspa.com/og-default.jpg",
      "https://www.miamiskinspa.com/og-default.jpg",
      "https://www.miamiskinspa.com/og-default.jpg",
    ],
    source: "Miami Skin Spa Aesthetics & Wellness official website — homepage",
  },
  "brickell-cosmetic-center-aesthetics-dermatology-miami": {
    hero: "https://brickellcosmetic.com/wp-content/uploads/2025/03/new-bg-img-01-desktop-1024x533.jpg",
    gallery: [
      "https://brickellcosmetic.com/wp-content/uploads/2025/03/new-bg-img-01-desktop-1024x533.jpg",
      "https://brickellcosmetic.com/wp-content/uploads/2025/03/new-bg-img-01-desktop-1024x533.jpg",
      "https://brickellcosmetic.com/wp-content/uploads/2025/03/new-bg-img-01-desktop-1024x533.jpg",
    ],
    source: "Brickell Cosmetic Center-Aesthetics & Dermatology official website — homepage",
  },
  "gables-med-spa-coral-gables": {
    hero: "https://static.wixstatic.com/media/ca9f79_4e5d07db02704320bb15e9cc849ce972~mv2.png/v1/fill/w_1150,h_700,al_c/ca9f79_4e5d07db02704320bb15e9cc849ce972~mv2.png",
    gallery: [
      "https://static.wixstatic.com/media/ca9f79_4e5d07db02704320bb15e9cc849ce972~mv2.png/v1/fill/w_1150,h_700,al_c/ca9f79_4e5d07db02704320bb15e9cc849ce972~mv2.png",
      "https://static.wixstatic.com/media/ca9f79_4e5d07db02704320bb15e9cc849ce972~mv2.png/v1/fill/w_1150,h_700,al_c/ca9f79_4e5d07db02704320bb15e9cc849ce972~mv2.png",
      "https://static.wixstatic.com/media/ca9f79_4e5d07db02704320bb15e9cc849ce972~mv2.png/v1/fill/w_1150,h_700,al_c/ca9f79_4e5d07db02704320bb15e9cc849ce972~mv2.png",
    ],
    source: "Gables Med Spa official website — homepage",
  },
  "millennium-wellness-center-fort-lauderdale": {
    hero: "https://mwellcenter.com/assets/og-image.png",
    gallery: [
      "https://mwellcenter.com/assets/og-image.png",
      "https://mwellcenter.com/assets/og-image.png",
      "https://mwellcenter.com/assets/og-image.png",
    ],
    source: "Millennium Wellness Center official website — homepage",
  },
  "vio-med-spa-fort-lauderdale-fort-lauderdale": {
    hero: "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
    gallery: [
      "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
      "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
      "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
    ],
    source: "VIO Med Spa Fort Lauderdale official website — homepage",
  },
  "amaira-med-spa-surgical-fort-lauderdale": {
    hero: "https://amairamedspa.com/wp-content/uploads/2024/02/Amaira_Logo_Full_Color.png",
    gallery: [
      "https://amairamedspa.com/wp-content/uploads/2024/02/Amaira_Logo_Full_Color.png",
      "https://amairamedspa.com/wp-content/uploads/2024/02/Amaira_Logo_Full_Color.png",
      "https://amairamedspa.com/wp-content/uploads/2024/02/Amaira_Logo_Full_Color.png",
    ],
    source: "Amaira Med Spa & Surgical official website — homepage",
  },
  "prestige-physicians-fort-lauderdale": {
    hero: "https://prestigephysicians.com/wp-content/uploads/2021/10/Group-3.svg",
    gallery: [
      "https://prestigephysicians.com/wp-content/uploads/2021/10/Group-3.svg",
      "https://prestigephysicians.com/wp-content/uploads/2021/10/Group-3.svg",
      "https://prestigephysicians.com/wp-content/uploads/2021/10/Group-3.svg",
    ],
    source: "Prestige Physicians official website — homepage",
  },
  "lumi-re-by-adriana-fort-lauderdale": {
    hero: "https://lumierebyadriana.com/wp-content/uploads/2023/04/body-conturing.jpg",
    gallery: [
      "https://lumierebyadriana.com/wp-content/uploads/2023/04/body-conturing.jpg",
      "https://lumierebyadriana.com/wp-content/uploads/2023/04/body-conturing.jpg",
      "https://lumierebyadriana.com/wp-content/uploads/2023/04/body-conturing.jpg",
    ],
    source: "Lumière by Adriana official website — homepage",
  },
  "glowing-skin-face-body-care-med-spa-fort-lauderdale": {
    hero: "https://static.wixstatic.com/media/23cad5_55ed9a9d120a4b319f1bd4bdc09b470b~mv2.jpg/v1/fill/w_1200,h_630,al_c/23cad5_55ed9a9d120a4b319f1bd4bdc09b470b~mv2.jpg",
    gallery: [
      "https://static.wixstatic.com/media/23cad5_55ed9a9d120a4b319f1bd4bdc09b470b~mv2.jpg/v1/fill/w_1200,h_630,al_c/23cad5_55ed9a9d120a4b319f1bd4bdc09b470b~mv2.jpg",
      "https://static.wixstatic.com/media/23cad5_55ed9a9d120a4b319f1bd4bdc09b470b~mv2.jpg/v1/fill/w_1200,h_630,al_c/23cad5_55ed9a9d120a4b319f1bd4bdc09b470b~mv2.jpg",
      "https://static.wixstatic.com/media/23cad5_55ed9a9d120a4b319f1bd4bdc09b470b~mv2.jpg/v1/fill/w_1200,h_630,al_c/23cad5_55ed9a9d120a4b319f1bd4bdc09b470b~mv2.jpg",
    ],
    source: "Glowing Skin Face & Body Care Med Spa official website — homepage",
  },
  "timeless-beauty-aesthetics-fort-lauderdale": {
    hero: "https://static.wixstatic.com/media/ccc8d7_8cfadcabee3e4f6b8e21f5c1a602d49d%7Emv2.png/v1/fit/w_2500,h_1330,al_c/ccc8d7_8cfadcabee3e4f6b8e21f5c1a602d49d%7Emv2.png",
    gallery: [
      "https://static.wixstatic.com/media/ccc8d7_8cfadcabee3e4f6b8e21f5c1a602d49d%7Emv2.png/v1/fit/w_2500,h_1330,al_c/ccc8d7_8cfadcabee3e4f6b8e21f5c1a602d49d%7Emv2.png",
      "https://static.wixstatic.com/media/ccc8d7_8cfadcabee3e4f6b8e21f5c1a602d49d%7Emv2.png/v1/fit/w_2500,h_1330,al_c/ccc8d7_8cfadcabee3e4f6b8e21f5c1a602d49d%7Emv2.png",
      "https://static.wixstatic.com/media/ccc8d7_8cfadcabee3e4f6b8e21f5c1a602d49d%7Emv2.png/v1/fit/w_2500,h_1330,al_c/ccc8d7_8cfadcabee3e4f6b8e21f5c1a602d49d%7Emv2.png",
    ],
    source: "Timeless Beauty Aesthetics official website — homepage",
  },
  "sanctuary-medical-aesthetic-center-fort-lauderdale": {
    hero: "https://www.sanctuarymedical.com/wp-content/uploads/2021/11/preview-full-Monday-Makeover-Banner-FACE1.png",
    gallery: [
      "https://www.sanctuarymedical.com/wp-content/uploads/2021/11/preview-full-Monday-Makeover-Banner-FACE1.png",
      "https://www.sanctuarymedical.com/wp-content/uploads/2021/11/preview-full-Monday-Makeover-Banner-FACE1.png",
      "https://www.sanctuarymedical.com/wp-content/uploads/2021/11/preview-full-Monday-Makeover-Banner-FACE1.png",
    ],
    source: "Sanctuary Medical Aesthetic Center official website — homepage",
  },
  "lov-medspa-miami-aventura": {
    hero: "https://www.lovmedspa.com/og-image.jpg",
    gallery: [
      "https://www.lovmedspa.com/og-image.jpg",
      "https://www.lovmedspa.com/og-image.jpg",
      "https://www.lovmedspa.com/og-image.jpg",
    ],
    source: "Lov MedSpa Miami official website — homepage",
  },
  "vio-med-spa-aventura-aventura": {
    hero: "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
    gallery: [
      "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
      "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
      "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
    ],
    source: "VIO Med Spa Aventura official website — homepage",
  },
  "liquivida-wellness-center-aventura": {
    hero: "https://www.liquivida.com/hubfs/Website%20Redesign%202025/Page%20Thumbnails/deals-promotions-liquivida-thumbnail.webp",
    gallery: [
      "https://www.liquivida.com/hubfs/Website%20Redesign%202025/Page%20Thumbnails/deals-promotions-liquivida-thumbnail.webp",
      "https://www.liquivida.com/hubfs/Website%20Redesign%202025/Page%20Thumbnails/deals-promotions-liquivida-thumbnail.webp",
      "https://www.liquivida.com/hubfs/Website%20Redesign%202025/Page%20Thumbnails/deals-promotions-liquivida-thumbnail.webp",
    ],
    source: "Liquivida Wellness Center official website — homepage",
  },
  "solea-brickell-spa-miami": {
    hero: "https://soleabrickellspa.com/wp-content/uploads/2024/07/Morpheus8.webp",
    gallery: [
      "https://soleabrickellspa.com/wp-content/uploads/2024/07/Morpheus8.webp",
      "https://soleabrickellspa.com/wp-content/uploads/2024/07/Morpheus8.webp",
      "https://soleabrickellspa.com/wp-content/uploads/2024/07/Morpheus8.webp",
    ],
    source: "Solea Brickell Spa official website — homepage",
  },
  "charette-cosmetics-medical-spa-miami-beach-miami-beach": {
    hero: "https://charettecosmetics.com/wp-content/uploads/2024/07/Charette-Favicon1.png",
    gallery: [
      "https://charettecosmetics.com/wp-content/uploads/2024/07/Charette-Favicon1.png",
      "https://charettecosmetics.com/wp-content/uploads/2024/07/Charette-Favicon1.png",
      "https://charettecosmetics.com/wp-content/uploads/2024/07/Charette-Favicon1.png",
    ],
    source: "Charette Cosmetics Medical Spa - Miami Beach official website — homepage",
  },
        "bodywelle-miami-beach": {
    hero: "https://alonsomartinmd.com/wp-content/uploads/2025/07/bodywelle-bg-miami-beach.jpg",
    gallery: [

    ],
    source: "Provider official website",
  },
  "skin-spa-new-york-miami-beach-medical-spa-miami-beach": {
    hero: "http://skinspanewyork.com/cdn/shop/files/newsletter-header.png?v=1748060296",
    gallery: [
      "http://skinspanewyork.com/cdn/shop/files/newsletter-header.png?v=1748060296",
      "http://skinspanewyork.com/cdn/shop/files/newsletter-header.png?v=1748060296",
      "http://skinspanewyork.com/cdn/shop/files/newsletter-header.png?v=1748060296",
    ],
    source: "Skin Spa New York - Miami Beach Medical Spa official website — homepage",
  },
  "arviv-medical-aesthetics-miami-miami": {
    hero: "https://arvivaesthetics.com/wp-content/uploads/2016/10/homepage-sm.jpg",
    gallery: [
      "https://arvivaesthetics.com/wp-content/uploads/2016/10/homepage-sm.jpg",
      "https://arvivaesthetics.com/wp-content/uploads/2016/10/homepage-sm.jpg",
      "https://arvivaesthetics.com/wp-content/uploads/2016/10/homepage-sm.jpg",
    ],
    source: "Arviv Medical Aesthetics Miami official website — homepage",
  },
  "aviva-medical-spa-miami": {
    hero: "https://avivamedicalspa.com/wp-content/uploads/2023/10/Logo-aviva.png",
    gallery: [
      "https://avivamedicalspa.com/wp-content/uploads/2023/10/Logo-aviva.png",
      "https://avivamedicalspa.com/wp-content/uploads/2023/10/Logo-aviva.png",
      "https://avivamedicalspa.com/wp-content/uploads/2023/10/Logo-aviva.png",
    ],
    source: "Aviva Medical Spa official website — homepage",
  },
  "247-med-spa-fort-lauderdale": {
    hero: "https://247medspa.com/wp-content/uploads/2025/12/cropped-Untitled-design.png",
    gallery: [
      "https://247medspa.com/wp-content/uploads/2025/12/cropped-Untitled-design.png",
      "https://247medspa.com/wp-content/uploads/2025/12/cropped-Untitled-design.png",
      "https://247medspa.com/wp-content/uploads/2025/12/cropped-Untitled-design.png",
    ],
    source: "247 Med Spa official website — homepage",
  },
  "healthy-glow-aesthetics-fort-lauderdale": {
    hero: "https://healthyglowaesthetics.com/wp-content/uploads/2025/03/Healthy-Glow-Aesthetics-Sharing-Logo-in-lauderdale-FL.webp",
    gallery: [
      "https://healthyglowaesthetics.com/wp-content/uploads/2025/03/Healthy-Glow-Aesthetics-Sharing-Logo-in-lauderdale-FL.webp",
      "https://healthyglowaesthetics.com/wp-content/uploads/2025/03/Healthy-Glow-Aesthetics-Sharing-Logo-in-lauderdale-FL.webp",
      "https://healthyglowaesthetics.com/wp-content/uploads/2025/03/Healthy-Glow-Aesthetics-Sharing-Logo-in-lauderdale-FL.webp",
    ],
    source: "Healthy Glow Aesthetics official website — homepage",
  },
  "aguilar-aesthetics-medspa-wellness-aventura": {
    hero: "https://aguilaraesthetics.com/wp-content/uploads/2025/08/MEDSPA-Bottom-Branded-Imgv2.png",
    gallery: [
      "https://aguilaraesthetics.com/wp-content/uploads/2025/08/MEDSPA-Bottom-Branded-Imgv2.png",
      "https://aguilaraesthetics.com/wp-content/uploads/2025/08/MEDSPA-Bottom-Branded-Imgv2.png",
      "https://aguilaraesthetics.com/wp-content/uploads/2025/08/MEDSPA-Bottom-Branded-Imgv2.png",
    ],
    source: "Aguilar Aesthetics Medspa & Wellness official website — homepage",
  },
  "yanasthetics-llc-aventura": {
    hero: "https://yanasthetics.com/wp-content/uploads/2025/12/IMG_6537-1.webp",
    gallery: [
      "https://yanasthetics.com/wp-content/uploads/2025/12/IMG_6537-1.webp",
      "https://yanasthetics.com/wp-content/uploads/2025/12/IMG_6537-1.webp",
      "https://yanasthetics.com/wp-content/uploads/2025/12/IMG_6537-1.webp",
    ],
    source: "Yanasthetics LLC official website — homepage",
  },
  "le-mar-aesthetics-kendall-medspa-miami": {
    hero: "https://lemaraesthetics.com/wp-content/uploads/2025/07/Wox4ussAsset-1@300x-scaled.png",
    gallery: [
      "https://lemaraesthetics.com/wp-content/uploads/2025/07/Wox4ussAsset-1@300x-scaled.png",
      "https://lemaraesthetics.com/wp-content/uploads/2025/07/Wox4ussAsset-1@300x-scaled.png",
      "https://lemaraesthetics.com/wp-content/uploads/2025/07/Wox4ussAsset-1@300x-scaled.png",
    ],
    source: "Le Mar Aesthetics - Kendall MedSpa official website — homepage",
  },
  "meraki-med-miami-miami": {
    hero: "https://static.wixstatic.com/media/f061f0_82e9ca4c27db4784be0ad066c03d3431~mv2.png/v1/fill/w_500,h_500,al_c/f061f0_82e9ca4c27db4784be0ad066c03d3431~mv2.png",
    gallery: [
      "https://static.wixstatic.com/media/f061f0_82e9ca4c27db4784be0ad066c03d3431~mv2.png/v1/fill/w_500,h_500,al_c/f061f0_82e9ca4c27db4784be0ad066c03d3431~mv2.png",
      "https://static.wixstatic.com/media/f061f0_82e9ca4c27db4784be0ad066c03d3431~mv2.png/v1/fill/w_500,h_500,al_c/f061f0_82e9ca4c27db4784be0ad066c03d3431~mv2.png",
      "https://static.wixstatic.com/media/f061f0_82e9ca4c27db4784be0ad066c03d3431~mv2.png/v1/fill/w_500,h_500,al_c/f061f0_82e9ca4c27db4784be0ad066c03d3431~mv2.png",
    ],
    source: "Meraki Med Miami official website — homepage",
  },
        "nuyou-medical-aesthetics-miami": {
    hero: "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/34689224-0680-4f39-ac86-368c79adca92/whyus-sectionbg%402x-scaled+%281%29+3.jpg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/176a96c6-233f-42e1-9f1b-fae24bfcc5ec/photo-output+2.JPEG",
      "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/d295c737-40cd-475b-b23d-2bf5720dedb7/savingPNG+219.PNG",
      "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/2d68560a-4fce-45de-a0ca-d8705c3e5c11/savingPNG+10.PNG",
      "https://images.squarespace-cdn.com/content/v1/6540846c9a348a20ed212bb7/29e62652-a0fa-478a-8d57-577f747cd99d/Signature+%282%29.png",
    ],
    source: "Provider official website",
  },
  "white-coat-med-spa-miami": {
    hero: "https://whitecoatmedspa.com/wp-content/uploads/2023/02/servicios-OXINA-BOTULINICA-Y-RELLENOS.png",
    gallery: [
      "https://whitecoatmedspa.com/wp-content/uploads/2023/02/servicios-OXINA-BOTULINICA-Y-RELLENOS.png",
      "https://whitecoatmedspa.com/wp-content/uploads/2023/02/servicios-OXINA-BOTULINICA-Y-RELLENOS.png",
      "https://whitecoatmedspa.com/wp-content/uploads/2023/02/servicios-OXINA-BOTULINICA-Y-RELLENOS.png",
    ],
    source: "White Coat Med Spa official website — homepage",
  },
  "bella-vida-aesthetics-wellness-miami": {
    hero: "https://bellavidaaesthetics.com/wp-content/uploads/2024/03/bella-vida-aesthetics-in-miami-sm.jpg",
    gallery: [
      "https://bellavidaaesthetics.com/wp-content/uploads/2024/03/bella-vida-aesthetics-in-miami-sm.jpg",
      "https://bellavidaaesthetics.com/wp-content/uploads/2024/03/bella-vida-aesthetics-in-miami-sm.jpg",
      "https://bellavidaaesthetics.com/wp-content/uploads/2024/03/bella-vida-aesthetics-in-miami-sm.jpg",
    ],
    source: "Bella Vida Aesthetics & Wellness official website — homepage",
  },
  "4beauty-medspa-miami": {
    hero: "https://4beautymedspa.com/wp-content/uploads/2024/08/slider.jpg",
    gallery: [
      "https://4beautymedspa.com/wp-content/uploads/2024/08/slider.jpg",
      "https://4beautymedspa.com/wp-content/uploads/2024/08/slider.jpg",
      "https://4beautymedspa.com/wp-content/uploads/2024/08/slider.jpg",
    ],
    source: "4Beauty Medspa official website — homepage",
  },
  "golden-aesthetics-wellness-miami": {
    hero: "https://content.app-sources.com/s/497367612352444631/uploads/Downloaded/aefeGroup_46-2611706.png",
    gallery: [
      "https://content.app-sources.com/s/497367612352444631/uploads/Downloaded/aefeGroup_46-2611706.png",
      "https://content.app-sources.com/s/497367612352444631/uploads/Downloaded/aefeGroup_46-2611706.png",
      "https://content.app-sources.com/s/497367612352444631/uploads/Downloaded/aefeGroup_46-2611706.png",
    ],
    source: "Golden Aesthetics & Wellness official website — homepage",
  },
  "get-refreshed-miami": {
    hero: "https://www.getrefreshed.com/wp-content/uploads/2026/03/get-refreshed-logo-black.jpg",
    gallery: [
      "https://www.getrefreshed.com/wp-content/uploads/2026/03/get-refreshed-logo-black.jpg",
      "https://www.getrefreshed.com/wp-content/uploads/2026/03/get-refreshed-logo-black.jpg",
      "https://www.getrefreshed.com/wp-content/uploads/2026/03/get-refreshed-logo-black.jpg",
    ],
    source: "Get Refreshed official website — homepage",
  },
        "aesthetic305-miami": {
    hero: "https://miamiaestheticinstitute.com/wp-content/uploads/2020/01/featured-blog.jpg",
    gallery: [

    ],
    source: "Provider official website",
  },
  "laria-medspa-miami": {
    hero: "https://lariamedspa.com/wp-content/uploads/2023/11/logo-featuredimg.png",
    gallery: [
      "https://lariamedspa.com/wp-content/uploads/2023/11/logo-featuredimg.png",
      "https://lariamedspa.com/wp-content/uploads/2023/11/logo-featuredimg.png",
      "https://lariamedspa.com/wp-content/uploads/2023/11/logo-featuredimg.png",
    ],
    source: "Laria MedSpa official website — homepage",
  },
        "monaco-medspa-miami": {
    hero: "https://lirp.cdn-website.com/cee2bf2b/dms3rep/multi/opt/PhotoRetouch1752622202476-1920w.jpg",
    gallery: [

    ],
    source: "Provider official website",
  },
  "serenity-medical-spa-miami": {
    hero: "https://serenitymedicalspa.com/wp-content/uploads/2023/11/294280474_10158540543185264_3624624063560670121_n.png",
    gallery: [
      "https://serenitymedicalspa.com/wp-content/uploads/2023/11/294280474_10158540543185264_3624624063560670121_n.png",
      "https://serenitymedicalspa.com/wp-content/uploads/2023/11/294280474_10158540543185264_3624624063560670121_n.png",
      "https://serenitymedicalspa.com/wp-content/uploads/2023/11/294280474_10158540543185264_3624624063560670121_n.png",
    ],
    source: "Serenity Medical & Spa official website — homepage",
  },
  "join-body-good-miami": {
    hero: "https://joinbodygood.com/images/dr-linda-hero.jpg",
    gallery: [
      "https://joinbodygood.com/images/dr-linda-hero.jpg",
      "https://joinbodygood.com/images/dr-linda-hero.jpg",
      "https://joinbodygood.com/images/dr-linda-hero.jpg",
    ],
    source: "Join Body Good official website — homepage",
  },
  "new-image-works-aventura-aventura": {
    hero: "https://newimageworks.com/wp-content/themes/niw_4_2_9/img/new-image-works-og.jpg",
    gallery: [
      "https://newimageworks.com/wp-content/themes/niw_4_2_9/img/new-image-works-og.jpg",
      "https://newimageworks.com/wp-content/themes/niw_4_2_9/img/new-image-works-og.jpg",
      "https://newimageworks.com/wp-content/themes/niw_4_2_9/img/new-image-works-og.jpg",
    ],
    source: "New Image Works Aventura official website — homepage",
  },
  "the-beauty-clinic-aventura-aventura": {
    hero: "https://thebeautyclinic.com/wp-content/uploads/2021/02/The-Beauty-Clinic-Web-Design-by-Inga-Brel-EYEBRANDIT-1-scaled.jpg?wsr",
    gallery: [
      "https://thebeautyclinic.com/wp-content/uploads/2021/02/The-Beauty-Clinic-Web-Design-by-Inga-Brel-EYEBRANDIT-1-scaled.jpg?wsr",
      "https://thebeautyclinic.com/wp-content/uploads/2021/02/The-Beauty-Clinic-Web-Design-by-Inga-Brel-EYEBRANDIT-1-scaled.jpg?wsr",
      "https://thebeautyclinic.com/wp-content/uploads/2021/02/The-Beauty-Clinic-Web-Design-by-Inga-Brel-EYEBRANDIT-1-scaled.jpg?wsr",
    ],
    source: "The Beauty Clinic Aventura official website — homepage",
  },
        "xs-medspa-fort-lauderdale": {
    hero: "https://refreshmedical.com/wp-content/uploads/2025/04/Final-05-07-removebg-preview-1.png",
    gallery: [

    ],
    source: "Provider official website",
  },
  "novaskin-med-spa-miami": {
    hero: "https://novaskinmedspa.com/wp-content/uploads/2026/01/LOGO-2.svg",
    gallery: [
      "https://novaskinmedspa.com/wp-content/uploads/2026/01/LOGO-2.svg",
      "https://novaskinmedspa.com/wp-content/uploads/2026/01/LOGO-2.svg",
      "https://novaskinmedspa.com/wp-content/uploads/2026/01/LOGO-2.svg",
    ],
    source: "Novaskin Med Spa official website — homepage",
  },
  "surface-level-med-spa-miami": {
    hero: "https://www.thesurfacelevel.com/_static_/background/og-feat.png",
    gallery: [
      "https://www.thesurfacelevel.com/_static_/background/og-feat.png",
      "https://www.thesurfacelevel.com/_static_/background/og-feat.png",
      "https://www.thesurfacelevel.com/_static_/background/og-feat.png",
    ],
    source: "Surface Level Med Spa official website — homepage",
  },
  "aventura-med-spa-aventura": {
    hero: "https://cdn.aventuramedspa.com/site/social/og-image.png",
    gallery: [
      "https://cdn.aventuramedspa.com/site/social/og-image.png",
      "https://cdn.aventuramedspa.com/site/social/og-image.png",
      "https://cdn.aventuramedspa.com/site/social/og-image.png",
    ],
    source: "Aventura Med Spa official website — homepage",
  }
};
