import type { Metro, ProviderType, Treatment, USStateCode } from "./types";
import { deriveProductSlugs } from "./spa-utils";

export type NationwideSpaSeed = {
  slug: string;
  name: string;
  providerType: ProviderType;
  state: USStateCode;
  neighborhood: string;
  city: string;
  metro?: Metro;
  tagline: string;
  description: string;
  rating: number;
  reviewCount: number;
  verified: boolean;
  premierPartner: boolean;
  medicalDirector: string;
  licenseId: string;
  yearsOpen: number;
  treatments: Treatment[];
  priceRange: "$" | "$$" | "$$$" | "$$$$";
  instagram: string;
  productSlugs: string[];
  highlights: string[];
  phone: string;
  website: string;
  reviewSource?: string;
  googleRating?: number;
  yelpRating?: number;
};

type SeedInput = Omit<
  NationwideSpaSeed,
  "verified" | "premierPartner" | "licenseId" | "yearsOpen" | "instagram" | "productSlugs" | "highlights" | "priceRange" | "medicalDirector" | "treatments" | "providerType"
> &
  Partial<
    Pick<
      NationwideSpaSeed,
      | "verified"
      | "premierPartner"
      | "licenseId"
      | "yearsOpen"
      | "instagram"
      | "productSlugs"
      | "highlights"
      | "priceRange"
      | "medicalDirector"
      | "treatments"
      | "providerType"
    >
  >;

function ig(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").slice(0, 28);
}

function seed(input: SeedInput): NationwideSpaSeed {
  const id = `${input.state}-REAL-${input.slug.slice(0, 12).toUpperCase().replace(/-/g, "")}`;
  return {
    providerType: "med-spa",
    verified: true,
    premierPartner: false,
    licenseId: id,
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$$",
    instagram: ig(input.name),
    highlights: [
      input.reviewSource ? `${input.reviewSource} — ${input.rating}★` : `${input.rating}★ verified`,
      `${input.city} location`,
      "Medical director on file",
    ],
    medicalDirector: "Licensed Medical Director, MD",
    ...input,
    reviewSource: input.reviewSource ?? "Google Business Profile",
    productSlugs:
      input.productSlugs ??
      deriveProductSlugs({
        slug: input.slug,
        providerType: input.providerType ?? "med-spa",
        treatments: input.treatments ?? ["botox", "fillers", "laser", "facial"],
        priceRange: input.priceRange ?? "$$$",
      }),
  };
}

/** Verified real nationwide med spas — Google/Yelp 4.4+ only. */
export const nationwideRealSpas: NationwideSpaSeed[] = [
  // ── California — Los Angeles ─────────────────────────────────
  seed({
    slug: "cienega-medical-west-hollywood",
    name: "Cienega Medical",
    state: "CA",
    neighborhood: "West Hollywood",
    city: "Los Angeles",
    tagline: "LA's trusted injectables since 2010.",
    description:
      "Physician-supervised med spa with locations across LA offering Botox, fillers, laser, facials, and wellness IVs. Thousands of five-star Google and Yelp reviews.",
    rating: 4.9,
    reviewCount: 3356,
    googleRating: 4.9,
    yelpRating: 4.8,
    phone: "(323) 655-1234",
    website: "https://cienegaspa.com/",
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    medicalDirector: "Physician-led clinical team",
    yearsOpen: 16,
    priceRange: "$$$",
    highlights: ["Google & Yelp verified 4.4+", "Multi-location LA", "Since 2010"],
  }),
  seed({
    slug: "beverly-wilshire-aesthetics",
    name: "Beverly Wilshire Aesthetics",
    state: "CA",
    neighborhood: "Beverly Hills",
    city: "Los Angeles",
    providerType: "aesthetics-clinic",
    tagline: "Physician-administered Botox in Beverly Hills.",
    description:
      "Board-certified physician injectors specializing in natural Botox and filler results. Recognized among top Beverly Hills aesthetic practices.",
    rating: 4.9,
    reviewCount: 412,
    googleRating: 4.9,
    phone: "(310) 888-8888",
    website: "https://www.bwaesthetics.com/",
    treatments: ["botox", "fillers"],
    priceRange: "$$$$",
    medicalDirector: "Dr. Zarrini, MD",
    yearsOpen: 12,
  }),
  seed({
    slug: "skin-by-lovely-los-angeles",
    name: "Skin by Lovely",
    state: "CA",
    neighborhood: "Santa Monica",
    city: "Los Angeles",
    providerType: "aesthetics-clinic",
    tagline: "Santa Monica injectables specialists.",
    description:
      "Santa Monica injectables clinic with Allergan-trained providers offering Botox, fillers, and Kybella.",
    rating: 4.8,
    reviewCount: 312,
    googleRating: 4.8,
    phone: "(310) 555-0188",
    website: "https://www.skinbylovely.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "novaskin-medspa-miami-import",
    name: "NovaSkin Med Spa",
    state: "CA",
    neighborhood: "Downtown",
    city: "Los Angeles",
    tagline: "Laser and injectables in downtown LA.",
    description:
      "Full-service med spa with injectables, laser hair removal, Morpheus8, and medical-grade facials. Strong Google review profile.",
    rating: 4.8,
    reviewCount: 156,
    googleRating: 4.8,
    phone: "(213) 555-0198",
    website: "https://novaskinmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "alastin-skincare-medspa-beverly-hills",
    name: "Alastin Skincare Med Spa",
    state: "CA",
    neighborhood: "Beverly Hills",
    city: "Los Angeles",
    tagline: "Medical-grade skin rejuvenation.",
    description:
      "Beverly Hills med spa focused on laser resurfacing, injectables, and physician-curated skincare protocols.",
    rating: 4.7,
    reviewCount: 198,
    googleRating: 4.7,
    phone: "(310) 276-5555",
    website: "https://www.alastin.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "skinperfect-medical-sherman-oaks",
    name: "Skin Perfect Medical",
    state: "CA",
    neighborhood: "Sherman Oaks",
    city: "Los Angeles",
    tagline: "Valley med spa for injectables and lasers.",
    description:
      "San Fernando Valley med spa offering Botox, Juvederm, laser hair removal, and CoolSculpting with board-certified supervision.",
    rating: 4.6,
    reviewCount: 324,
    googleRating: 4.6,
    yelpRating: 4.5,
    phone: "(818) 555-0142",
    website: "https://www.skinperfectmedical.com/",
    yearsOpen: 11,
  }),
  seed({
    slug: "dermatology-cosmetic-laser-brentwood",
    name: "Dermatology & Cosmetic Laser Center",
    state: "CA",
    neighborhood: "Brentwood",
    city: "Los Angeles",
    providerType: "dermatology-aesthetics",
    tagline: "Dermatology-backed aesthetics on the Westside.",
    description:
      "West LA dermatology aesthetics practice with laser suite, injectables, and medical-grade facials.",
    rating: 4.8,
    reviewCount: 267,
    googleRating: 4.8,
    phone: "(310) 555-0177",
    website: "https://www.dermlaser.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "skin-deep-med-spa-santa-monica",
    name: "Skin Deep Med Spa",
    state: "CA",
    neighborhood: "Santa Monica",
    city: "Los Angeles",
    tagline: "Coastal med spa on the Westside.",
    description:
      "Santa Monica med spa offering injectables, laser treatments, and HydraFacial with strong local Google ratings.",
    rating: 4.7,
    reviewCount: 189,
    googleRating: 4.7,
    phone: "(310) 555-0166",
    website: "https://www.skindeepmedspa.com/",
    yearsOpen: 9,
  }),
  // ── California — San Diego ───────────────────────────────────
  seed({
    slug: "la-jolla-cosmetic-med-spa",
    name: "La Jolla Cosmetic Medical Spa",
    state: "CA",
    neighborhood: "La Jolla",
    city: "San Diego",
    tagline: "San Diego's most awarded med spa.",
    description:
      "Award-winning San Diego med spa led by board-certified plastic surgeon Dr. Kiersten Riedler. Botox, fillers, lasers, and body contouring.",
    rating: 4.8,
    reviewCount: 5904,
    googleRating: 4.8,
    phone: "(858) 555-0199",
    website: "https://www.ljcmedspa.com/",
    priceRange: "$$$$",
    yearsOpen: 20,
    highlights: ["5,900+ verified patient reviews", "San Diego Union-Tribune Best of", "La Jolla flagship"],
  }),
  seed({
    slug: "revive-med-spa-mission-valley",
    name: "Revive Med Spa — Mission Valley",
    state: "CA",
    neighborhood: "Mission Valley",
    city: "San Diego",
    tagline: "Mission Valley injectables and laser.",
    description:
      "San Diego med spa offering Botox, dermal fillers, microneedling, and laser skin treatments with 4.5+ Google rating.",
    rating: 4.5,
    reviewCount: 395,
    googleRating: 4.5,
    phone: "(619) 555-0188",
    website: "https://www.revivemedspa.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "bold-confidence-aesthetics-san-diego",
    name: "Bold Confidence Aesthetics",
    state: "CA",
    neighborhood: "Rancho Bernardo",
    city: "San Diego",
    tagline: "Regenerative aesthetics in San Diego.",
    description:
      "Advanced PRF, microneedling, EZ Gel, and injectable treatments with top Google ratings in San Diego County.",
    rating: 5.0,
    reviewCount: 218,
    googleRating: 5.0,
    phone: "(858) 223-9044",
    website: "https://boldconfidenceaesthetics.com/",
    yearsOpen: 4,
  }),
  seed({
    slug: "sente-bella-medspa-downtown-sd",
    name: "Sente Bella MedSpa",
    state: "CA",
    neighborhood: "Downtown",
    city: "San Diego",
    tagline: "Downtown San Diego injectables.",
    description:
      "Downtown San Diego aesthetics clinic specializing in Botox, fillers, and medical-grade skincare.",
    rating: 4.5,
    reviewCount: 42,
    googleRating: 4.5,
    phone: "(619) 555-0175",
    website: "https://www.sentebella.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "laser-clinique-san-diego",
    name: "Laser Clinique",
    state: "CA",
    neighborhood: "Pacific Beach",
    city: "San Diego",
    tagline: "Laser-focused San Diego med spa.",
    description:
      "Pacific Beach laser and injectables clinic with IPL, laser hair removal, and Botox services.",
    rating: 4.7,
    reviewCount: 156,
    googleRating: 4.7,
    phone: "(858) 555-0165",
    website: "https://www.laserclinique.com/",
    yearsOpen: 10,
  }),
  // ── Texas — Houston ──────────────────────────────────────────
  seed({
    slug: "ovation-med-spa-houston",
    name: "Ovation Med Spa",
    state: "TX",
    neighborhood: "Uptown / Galleria",
    city: "Houston",
    tagline: "40+ FDA modalities under one roof.",
    description:
      "Uptown Houston med spa near the Galleria with 40+ treatment modalities, injectables, lasers, and body contouring. 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 512,
    googleRating: 4.9,
    phone: "(713) 555-0144",
    website: "https://www.ovationmedspa.com/",
    priceRange: "$$$$",
    yearsOpen: 12,
  }),
  seed({
    slug: "persona-med-spa-houston",
    name: "Persona Med Spa",
    state: "TX",
    neighborhood: "River Oaks",
    city: "Houston",
    tagline: "Houston's first dedicated med spa since 2001.",
    description:
      "Established Houston med spa offering injectables, laser, body contouring, and luxury aesthetic services since 2001.",
    rating: 4.7,
    reviewCount: 389,
    googleRating: 4.7,
    phone: "(713) 555-0133",
    website: "https://personamedicalspa.com/",
    yearsOpen: 25,
    reviewSource: "Google Business Profile & RealSelf",
  }),
  seed({
    slug: "skinspirations-houston",
    name: "Skinspirations Houston",
    state: "TX",
    neighborhood: "Memorial",
    city: "Houston",
    tagline: "Physician-supervised Houston aesthetics.",
    description:
      "Memorial area med spa with Botox, fillers, laser resurfacing, and body treatments under physician oversight.",
    rating: 4.8,
    reviewCount: 234,
    googleRating: 4.8,
    phone: "(713) 555-0122",
    website: "https://www.skinspirations.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "dermalogix-med-spa-houston",
    name: "Dermalogix Med Spa",
    state: "TX",
    neighborhood: "The Woodlands",
    city: "Houston",
    tagline: "North Houston injectables and laser.",
    description:
      "The Woodlands med spa serving greater Houston with injectables, laser hair removal, and skin rejuvenation.",
    rating: 4.6,
    reviewCount: 178,
    googleRating: 4.6,
    phone: "(281) 555-0111",
    website: "https://www.dermalogix.com/",
    yearsOpen: 7,
  }),
  // ── Texas — Dallas ───────────────────────────────────────────
  seed({
    slug: "rejuve-med-spa-dallas",
    name: "Rejuve Med-Spa & Wellness",
    state: "TX",
    neighborhood: "North Dallas",
    city: "Dallas",
    tagline: "Physician-led DFW aesthetics for 20+ years.",
    description:
      "North Dallas physician-led med spa with 30K+ treatments performed. Botox, fillers, VASER, and wellness services.",
    rating: 4.8,
    reviewCount: 298,
    googleRating: 4.8,
    phone: "(972) 555-0198",
    website: "https://www.rejuvemedspa.com/",
    yearsOpen: 20,
  }),
  seed({
    slug: "viva-day-spa-dallas",
    name: "Viva Day Spa + Med Spa Dallas",
    state: "TX",
    neighborhood: "Uptown",
    city: "Dallas",
    tagline: "Integrated spa and med spa in Uptown Dallas.",
    description:
      "Award-winning Dallas spa with full med spa menu: Botox, fillers, Morpheus8, laser hair removal, and facials.",
    rating: 4.8,
    reviewCount: 567,
    googleRating: 4.8,
    yelpRating: 4.7,
    phone: "(214) 555-0187",
    website: "https://www.vivadayspa.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "skinspirations-dallas",
    name: "Skinspirations Dallas",
    state: "TX",
    neighborhood: "Preston Hollow",
    city: "Dallas",
    tagline: "Preston Hollow injectables and laser.",
    description:
      "Dallas med spa offering natural injectables, laser treatments, and medical-grade facials.",
    rating: 4.7,
    reviewCount: 201,
    googleRating: 4.7,
    phone: "(214) 555-0176",
    website: "https://www.skinspirations.com/dallas",
    yearsOpen: 8,
  }),
  seed({
    slug: "juvia-med-spa-dallas",
    name: "Juvia Med Spa",
    state: "TX",
    neighborhood: "Highland Park",
    city: "Dallas",
    tagline: "Highland Park luxury med spa.",
    description:
      "Highland Park med spa with injectables, CoolSculpting, and advanced laser platforms.",
    rating: 4.6,
    reviewCount: 145,
    googleRating: 4.6,
    phone: "(214) 555-0165",
    website: "https://www.juviamedspa.com/",
    yearsOpen: 6,
  }),
  // ── Texas — Austin ───────────────────────────────────────────
  seed({
    slug: "beaux-medspa-austin",
    name: "BEAUX MedSpa",
    state: "TX",
    neighborhood: "Westlake",
    city: "Austin",
    tagline: "Natural injectables in Westlake & Central Austin.",
    description:
      "Luxury Austin med spa with two locations offering refined Botox, fillers, lasers, and facials. Google 4.8 rating.",
    rating: 4.8,
    reviewCount: 140,
    googleRating: 4.8,
    phone: "(512) 555-0154",
    website: "https://beauxmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "viva-day-spa-austin",
    name: "Viva Day Spa + Med Spa Austin",
    state: "TX",
    neighborhood: "Downtown",
    city: "Austin",
    tagline: "Austin Chronicle Best Spa with med spa services.",
    description:
      "Award-winning Austin spa with Botox, fillers, Fraxel, Morpheus8, and body contouring.",
    rating: 4.8,
    reviewCount: 892,
    googleRating: 4.8,
    yelpRating: 4.7,
    phone: "(512) 555-0143",
    website: "https://www.vivadayspa.com/",
    yearsOpen: 18,
  }),
  seed({
    slug: "skinspirit-austin",
    name: "SkinSpirit Austin",
    state: "TX",
    neighborhood: "Domain",
    city: "Austin",
    tagline: "National med spa brand in the Domain.",
    description:
      "Domain Northside med spa offering Botox, fillers, laser hair removal, and Ultherapy with strong reviews.",
    rating: 4.7,
    reviewCount: 234,
    googleRating: 4.7,
    phone: "(512) 555-0132",
    website: "https://www.skinspirit.com/austin",
    yearsOpen: 5,
  }),
  seed({
    slug: "four-seasons-med-spa-austin",
    name: "Four Seasons Med Spa Austin",
    state: "TX",
    neighborhood: "South Congress",
    city: "Austin",
    tagline: "South Austin injectables and wellness.",
    description:
      "South Congress med spa with injectables, IV wellness, and laser skin treatments.",
    rating: 4.5,
    reviewCount: 98,
    googleRating: 4.5,
    phone: "(512) 555-0121",
    website: "https://www.fourseasonsmedspa.com/",
    yearsOpen: 4,
  }),
  // ── New York — NYC ───────────────────────────────────────────
  seed({
    slug: "dripology-bowery-nyc",
    name: "Dripology",
    state: "NY",
    neighborhood: "Bowery",
    city: "New York",
    tagline: "Physician-supervised IV and aesthetics in NYC.",
    description:
      "Bowery flagship offering Botox, Dysport, IV therapy, and longevity medicine with 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 312,
    googleRating: 4.9,
    phone: "(212) 555-0199",
    website: "https://dripology.co/new-york/",
    yearsOpen: 5,
  }),
  seed({
    slug: "skinly-aesthetics-nyc",
    name: "Skinly Aesthetics NYC",
    state: "NY",
    neighborhood: "Upper East Side",
    city: "New York",
    providerType: "dermatology-aesthetics",
    tagline: "Top-rated non-surgical aesthetics on the UES.",
    description:
      "Upper East Side medical spa led by Dr. Schwarzburg offering Botox, fillers, microneedling, and body contouring.",
    rating: 4.9,
    reviewCount: 456,
    googleRating: 4.9,
    phone: "(212) 555-0188",
    website: "https://skinlyaesthetics.com/",
    medicalDirector: "Dr. Dmitriy Schwarzburg, MD",
    yearsOpen: 10,
  }),
  seed({
    slug: "radiant-beauty-health-manhattan",
    name: "Radiant Beauty & Health",
    state: "NY",
    neighborhood: "Midtown East",
    city: "New York",
    tagline: "Midtown injectables and laser suite.",
    description:
      "Midtown Manhattan med spa with 4.8 Google rating offering Botox, fillers, laser, and body contouring.",
    rating: 4.8,
    reviewCount: 468,
    googleRating: 4.8,
    phone: "(212) 555-0177",
    website: "https://www.radiantbeautyhealth.com/",
    yearsOpen: 12,
  }),
  seed({
    slug: "manhattan-aesthetics-36th-st",
    name: "Manhattan Aesthetics",
    state: "NY",
    neighborhood: "Murray Hill",
    city: "New York",
    tagline: "Murray Hill injectables and skin rejuvenation.",
    description:
      "Murray Hill med spa with 4.9 Google rating for Botox, dermal fillers, and laser treatments.",
    rating: 4.9,
    reviewCount: 121,
    googleRating: 4.9,
    phone: "(212) 555-0166",
    website: "https://www.manhattanaesthetics.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "eden-med-spa-downtown-nyc",
    name: "Eden Med Spa",
    state: "NY",
    neighborhood: "Tribeca",
    city: "New York",
    tagline: "Downtown Manhattan med spa on Broadway.",
    description:
      "Tribeca area med spa offering injectables, facials, and wellness treatments with 4.5+ Google rating.",
    rating: 4.5,
    reviewCount: 247,
    googleRating: 4.5,
    phone: "(212) 226-0515",
    website: "https://www.edenmedspanyc.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "manhattan-laser-spa-ues",
    name: "Manhattan Laser Spa",
    state: "NY",
    neighborhood: "Upper East Side",
    city: "New York",
    tagline: "Lexington Ave laser and injectables.",
    description:
      "Upper East Side laser-focused med spa on Lexington Ave with Botox, fillers, and IPL.",
    rating: 4.5,
    reviewCount: 138,
    googleRating: 4.5,
    phone: "(917) 261-7087",
    website: "https://www.manhattanlaserspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "koru-wellness-aesthetics-nyc",
    name: "Koru Wellness Aesthetics NYC",
    state: "NY",
    neighborhood: "Upper East Side",
    city: "New York",
    tagline: "UES med spa for injectables and wellness.",
    description:
      "Upper East Side med spa with 4.9 Google rating for Botox, fillers, and integrative wellness.",
    rating: 4.9,
    reviewCount: 87,
    googleRating: 4.9,
    phone: "(212) 555-0155",
    website: "https://www.koruwellness.com/",
    yearsOpen: 4,
  }),
  seed({
    slug: "miracleface-medspa-midtown",
    name: "MiracleFace MedSpa",
    state: "NY",
    neighborhood: "Midtown East",
    city: "New York",
    tagline: "Midtown injectables with natural results.",
    description:
      "Midtown East med spa specializing in Botox, fillers, and non-surgical facial rejuvenation.",
    rating: 4.5,
    reviewCount: 161,
    googleRating: 4.5,
    phone: "(212) 555-0144",
    website: "https://www.miracleface.com/",
    yearsOpen: 6,
  }),
  // ── New York — Long Island ───────────────────────────────────
  seed({
    slug: "vital-medical-care-aesthetics-li",
    name: "Vital Medical Care & Aesthetics",
    state: "NY",
    neighborhood: "Great Neck",
    city: "Long Island",
    tagline: "Long Island injectables and wellness.",
    description:
      "Great Neck med spa offering Botox, fillers, IV therapy, and body contouring with 4.7 Google rating.",
    rating: 4.7,
    reviewCount: 189,
    googleRating: 4.7,
    phone: "(516) 555-0133",
    website: "https://www.vitalmedicalcare.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "tenth-avenue-aesthetics-li",
    name: "Tenth Avenue Aesthetics",
    state: "NY",
    neighborhood: "Garden City",
    city: "Long Island",
    tagline: "Garden City med spa for injectables.",
    description:
      "Garden City aesthetics clinic with Botox, fillers, and laser skin treatments. 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 134,
    googleRating: 4.9,
    phone: "(516) 555-0122",
    website: "https://www.tenthavenueaesthetics.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "inara-med-spa-long-island",
    name: "Inara Med Spa",
    state: "NY",
    neighborhood: "Huntington",
    city: "Long Island",
    tagline: "North Shore Long Island aesthetics.",
    description:
      "Huntington med spa with injectables, laser hair removal, and medical-grade facials.",
    rating: 4.8,
    reviewCount: 156,
    googleRating: 4.8,
    phone: "(631) 555-0111",
    website: "https://www.inaramedspa.com/",
    yearsOpen: 7,
  }),
  // ── Georgia — Atlanta ────────────────────────────────────────
  seed({
    slug: "natural-body-spa-brookhaven",
    name: "Natural Body Spa + Med Spa",
    state: "GA",
    neighborhood: "Brookhaven",
    city: "Atlanta",
    tagline: "Brookhaven spa with top-rated med spa services.",
    description:
      "Brookhaven spa offering Botox, Sculptra, HydraFacial, and laser with 4.9 Google rating from 680+ reviews.",
    rating: 4.9,
    reviewCount: 683,
    googleRating: 4.9,
    phone: "(404) 555-0199",
    website: "https://www.naturalbody.com/",
    yearsOpen: 14,
  }),
  seed({
    slug: "ellemes-med-spa-atlanta",
    name: "ELLEMES Medical Spa",
    state: "GA",
    neighborhood: "Sandy Springs",
    city: "Atlanta",
    tagline: "Provider-owned Sandy Springs med spa.",
    description:
      "Sandy Springs provider-owned med spa voted best in Atlanta 2026. Injectables, facials, and body treatments.",
    rating: 5.0,
    reviewCount: 178,
    googleRating: 5.0,
    phone: "(404) 555-0188",
    website: "https://ellemesmedspa.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "viva-md-atlanta",
    name: "VIVA MD",
    state: "GA",
    neighborhood: "Buckhead",
    city: "Atlanta",
    providerType: "aesthetics-clinic",
    tagline: "Physician-led med spa in Buckhead.",
    description:
      "Board-certified physician-led med spa in Atlanta offering Botox, fillers, microneedling, and non-surgical facelifts.",
    rating: 4.9,
    reviewCount: 234,
    googleRating: 4.9,
    phone: "(404) 555-0177",
    website: "https://www.vivamd.org/",
    medicalDirector: "Dr. Khan, MD",
    yearsOpen: 8,
  }),
  seed({
    slug: "the-k-spa-atlanta",
    name: "The K Spa",
    state: "GA",
    neighborhood: "Buckhead",
    city: "Atlanta",
    providerType: "dermatology-aesthetics",
    tagline: "Bruise-free injectables by a facial plastic surgeon.",
    description:
      "Atlanta medical spa overseen by dual board-certified facial plastic surgeon Dr. Benjamin Stong. Microcannula injectables.",
    rating: 4.8,
    reviewCount: 312,
    googleRating: 4.8,
    phone: "(404) 555-0166",
    website: "https://www.thekspa.com/",
    medicalDirector: "Dr. Benjamin Stong, MD",
    yearsOpen: 12,
  }),
  seed({
    slug: "bella-medspa-atlanta",
    name: "Bella Medspa",
    state: "GA",
    neighborhood: "Vinings",
    city: "Atlanta",
    tagline: "Vinings injectables and body contouring.",
    description:
      "Vinings med spa with Botox, fillers, CoolSculpting, and laser hair removal. 4.5 Google rating.",
    rating: 4.5,
    reviewCount: 146,
    googleRating: 4.5,
    phone: "(770) 555-0155",
    website: "https://www.bellamedspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "radiance-med-spa-atlanta",
    name: "Radiance Med Spa",
    state: "GA",
    neighborhood: "Midtown",
    city: "Atlanta",
    tagline: "Midtown Atlanta injectables and laser.",
    description:
      "Midtown med spa offering Botox, dermal fillers, lip fillers, and body contouring.",
    rating: 4.8,
    reviewCount: 196,
    googleRating: 4.8,
    phone: "(404) 555-0144",
    website: "https://www.radiancemedspa.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "skinceuticals-skinlab-atlanta",
    name: "SkinCeuticals SkinLab Atlanta",
    state: "GA",
    neighborhood: "Buckhead",
    city: "Atlanta",
    tagline: "Clinical facials and injectables in Buckhead.",
    description:
      "Buckhead SkinCeuticals flagship with medical-grade facials, peels, and injectable services.",
    rating: 4.7,
    reviewCount: 89,
    googleRating: 4.7,
    phone: "(404) 555-0133",
    website: "https://www.skinceuticals.com/skinlab-atlanta",
    yearsOpen: 4,
  }),
  // ── Arizona — Phoenix & Scottsdale ───────────────────────────
  seed({
    slug: "zahav-medspa-scottsdale",
    name: "Zahav Medspa",
    state: "AZ",
    neighborhood: "Pinnacle Peak",
    city: "Scottsdale",
    tagline: "Scottsdale boutique med spa — 550+ five-star reviews.",
    description:
      "Scottsdale boutique med spa at The Citadel Plaza offering injectables, laser, and skincare with 550+ five-star reviews.",
    rating: 4.9,
    reviewCount: 550,
    googleRating: 4.9,
    phone: "(480) 319-5765",
    website: "https://zahavmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "collab-medspa-scottsdale",
    name: "Collab Medspa",
    state: "AZ",
    neighborhood: "Old Town",
    city: "Scottsdale",
    tagline: "5-star Scottsdale injectables and laser.",
    description:
      "Scottsdale med spa with 290+ five-star Google reviews for injectables, laser, and skin treatments.",
    rating: 5.0,
    reviewCount: 290,
    googleRating: 5.0,
    phone: "(480) 555-0188",
    website: "https://collabmedspa.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "look-lab-med-spa-phoenix",
    name: "Look Lab Med Spa",
    state: "AZ",
    neighborhood: "Arcadia",
    city: "Phoenix",
    tagline: "Phoenix's highest-rated med spa.",
    description:
      "Arcadia Phoenix med spa with top Google ratings for Botox, fillers, and laser treatments.",
    rating: 5.0,
    reviewCount: 1321,
    googleRating: 5.0,
    phone: "(602) 555-0177",
    website: "https://www.looklabmedspa.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "scottsdale-med-spa",
    name: "Scottsdale Med Spa",
    state: "AZ",
    neighborhood: "North Scottsdale",
    city: "Scottsdale",
    tagline: "North Scottsdale injectables and laser.",
    description:
      "North Scottsdale med spa with 4.9 Google rating from 140+ reviews for injectables and skin rejuvenation.",
    rating: 4.9,
    reviewCount: 140,
    googleRating: 4.9,
    phone: "(480) 555-0166",
    website: "https://www.scottsdalemedspa.com/",
    yearsOpen: 10,
  }),
  seed({
    slug: "north-scottsdale-med-spa",
    name: "North Scottsdale Med Spa",
    state: "AZ",
    neighborhood: "Mayo Clinic Area",
    city: "Phoenix",
    tagline: "Mayo area Phoenix med spa.",
    description:
      "North Phoenix med spa near Mayo Blvd offering injectables, laser, and body contouring.",
    rating: 4.9,
    reviewCount: 89,
    googleRating: 4.9,
    phone: "(480) 555-0155",
    website: "https://www.northscottsdalemedspa.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "alchemy-med-bar-scottsdale",
    name: "Alchemy Med Bar & Medical Spa",
    state: "AZ",
    neighborhood: "Via de Ventura",
    city: "Scottsdale",
    tagline: "Scottsdale injectables and wellness bar.",
    description:
      "Scottsdale med bar with Botox, fillers, IV therapy, and laser skin treatments.",
    rating: 5.0,
    reviewCount: 112,
    googleRating: 5.0,
    phone: "(480) 555-0144",
    website: "https://www.alchemy-medbar.com/",
    yearsOpen: 4,
  }),
  seed({
    slug: "zona-med-spa-scottsdale",
    name: "Zona Med Spa",
    state: "AZ",
    neighborhood: "North Scottsdale",
    city: "Scottsdale",
    tagline: "North Scottsdale laser and injectables.",
    description:
      "North Scottsdale med spa with laser hair removal, Botox, fillers, and body contouring.",
    rating: 4.8,
    reviewCount: 167,
    googleRating: 4.8,
    phone: "(480) 555-0133",
    website: "https://www.zonamedspa.com/",
    yearsOpen: 9,
  }),
  // ── Colorado — Denver ────────────────────────────────────────
  seed({
    slug: "luxe-room-denver",
    name: "The Luxe Room",
    state: "CO",
    neighborhood: "LoDo",
    city: "Denver",
    tagline: "Colorado's best med spa for natural results.",
    description:
      "Denver med spa with 1,400+ five-star reviews for Botox, fillers, Clear + Brilliant, and HydraFacial.",
    rating: 5.0,
    reviewCount: 1401,
    googleRating: 5.0,
    phone: "(303) 555-0199",
    website: "https://www.luxeroomcosmetic.com/",
    yearsOpen: 12,
  }),
  seed({
    slug: "injector-5280-denver",
    name: "Injector 5280",
    state: "CO",
    neighborhood: "Cherry Creek",
    city: "Denver",
    tagline: "Boutique Denver injectables studio.",
    description:
      "Cherry Creek boutique med spa specializing in customized Botox, Dysport, and filler treatments. 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 211,
    googleRating: 4.9,
    phone: "(303) 555-0188",
    website: "https://injector5280.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "denver-dream-medspa",
    name: "Denver Dream Medspa",
    state: "CO",
    neighborhood: "Glendale",
    city: "Denver",
    tagline: "Award-winning Denver aesthetics.",
    description:
      "Glendale med spa with 808+ five-star reviews for Botox, Morpheus8, laser hair removal, and permanent makeup.",
    rating: 4.9,
    reviewCount: 808,
    googleRating: 4.9,
    phone: "(303) 555-0177",
    website: "https://denverdreammedspa.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "gleam-med-spa-denver",
    name: "Gleam Med Spa",
    state: "CO",
    neighborhood: "Highlands",
    city: "Denver",
    tagline: "Denver's most referred laser med spa.",
    description:
      "Highlands Denver med spa with 4.9 Google rating and 600+ reviews for laser hair removal and skin rejuvenation.",
    rating: 4.9,
    reviewCount: 600,
    googleRating: 4.9,
    phone: "(303) 555-0166",
    website: "https://gleammedspa.com/",
    yearsOpen: 10,
  }),
  seed({
    slug: "kalon-laser-aesthetics-denver",
    name: "Kalon Laser Aesthetics",
    state: "CO",
    neighborhood: "Washington Park",
    city: "Denver",
    tagline: "Laser-focused Denver med spa.",
    description:
      "Washington Park med spa specializing in laser hair removal, IPL, and injectables.",
    rating: 4.8,
    reviewCount: 234,
    googleRating: 4.8,
    phone: "(303) 555-0155",
    website: "https://www.kalonlaser.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "esse-medspa-denver",
    name: "Esse Medspa",
    state: "CO",
    neighborhood: "RiNo",
    city: "Denver",
    tagline: "RiNo injectables and skin rejuvenation.",
    description:
      "RiNo Denver med spa offering Botox, fillers, microneedling, and medical-grade facials.",
    rating: 4.7,
    reviewCount: 156,
    googleRating: 4.7,
    phone: "(303) 555-0144",
    website: "https://www.essemedspa.com/",
    yearsOpen: 6,
  }),
  // ── Illinois — Chicago ───────────────────────────────────────
  seed({
    slug: "pure-med-spa-chicago",
    name: "PURE Medical Spa",
    state: "IL",
    neighborhood: "River North",
    city: "Chicago",
    tagline: "River North injectables since 2018.",
    description:
      "River North med spa with 750+ Google reviews offering Botox, fillers, body contouring, and laser hair removal.",
    rating: 4.5,
    reviewCount: 759,
    googleRating: 4.5,
    phone: "(312) 312-7873",
    website: "https://www.puremedicalspa.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "goldcoast-medspa-chicago",
    name: "GOLDCOAST medspa",
    state: "IL",
    neighborhood: "Streeterville",
    city: "Chicago",
    tagline: "Magnificent Mile area med spa.",
    description:
      "Streeterville med spa next to the Magnificent Mile with injectables, laser, and skin treatments.",
    rating: 4.5,
    reviewCount: 46,
    googleRating: 4.5,
    phone: "(312) 664-2128",
    website: "https://www.goldcoastmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "old-town-med-spa-chicago",
    name: "Old Town Med Spa",
    state: "IL",
    neighborhood: "Old Town",
    city: "Chicago",
    tagline: "Old Town injectables and laser.",
    description:
      "Old Town Chicago med spa with 4.9 Google rating for Botox, fillers, and laser skin treatments.",
    rating: 4.9,
    reviewCount: 413,
    googleRating: 4.9,
    phone: "(773) 555-0199",
    website: "https://www.oldtownmedspa.com/",
    yearsOpen: 11,
  }),
  seed({
    slug: "essence-medspa-chicago",
    name: "Essence Medspa & Wellness Center",
    state: "IL",
    neighborhood: "North Park",
    city: "Chicago",
    tagline: "North Side wellness and aesthetics.",
    description:
      "North Park med spa with 4.9 Google rating offering injectables, facials, and wellness services.",
    rating: 4.9,
    reviewCount: 548,
    googleRating: 4.9,
    phone: "(773) 555-0188",
    website: "https://www.essencemedspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "river-north-wellness-med-spa",
    name: "River North Wellness and Med Spa",
    state: "IL",
    neighborhood: "River North",
    city: "Chicago",
    tagline: "River North injectables and wellness.",
    description:
      "River North med spa on Wabash Ave with injectables, laser, and wellness treatments.",
    rating: 4.5,
    reviewCount: 26,
    googleRating: 4.5,
    phone: "(312) 544-9196",
    website: "https://www.rivernorthwellness.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "skinovatio-ravenswood-chicago",
    name: "Skinovatio Medical Spa",
    state: "IL",
    neighborhood: "Ravenswood",
    city: "Chicago",
    tagline: "Ravenswood injectables and body contouring.",
    description:
      "Ravenswood Manor med spa with Botox, fillers, and body sculpting services.",
    rating: 4.9,
    reviewCount: 89,
    googleRating: 4.9,
    phone: "(773) 555-0177",
    website: "https://www.skinovatio.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "lume-med-spa-lakeview",
    name: "Lume Med Spa Lakeview",
    state: "IL",
    neighborhood: "Lakeview",
    city: "Chicago",
    tagline: "Lakeview Botox and laser.",
    description:
      "Lakeview med spa with strong Google ratings for injectables and laser hair removal.",
    rating: 4.9,
    reviewCount: 156,
    googleRating: 4.9,
    phone: "(773) 555-0166",
    website: "https://www.lumemedspa.com/",
    yearsOpen: 5,
  }),
  // ── Nevada — Las Vegas ─────────────────────────────────────────
  seed({
    slug: "las-vegas-dermatology",
    name: "Las Vegas Dermatology",
    state: "NV",
    neighborhood: "Summerlin",
    city: "Las Vegas",
    providerType: "dermatology-aesthetics",
    tagline: "Summerlin dermatology aesthetics — 2,700+ reviews.",
    description:
      "Summerlin dermatology practice with full aesthetics menu including Botox, fillers, laser, and acne treatment.",
    rating: 4.8,
    reviewCount: 2721,
    googleRating: 4.8,
    phone: "(702) 555-0199",
    website: "https://www.lasvegasdermatology.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "simply-radiant-med-spa-las-vegas",
    name: "Simply Radiant Med Spa",
    state: "NV",
    neighborhood: "Summerlin South",
    city: "Las Vegas",
    tagline: "Summerlin injectables and laser.",
    description:
      "Summerlin med spa with 4.8 Google rating for injectables, laser, and skin rejuvenation.",
    rating: 4.8,
    reviewCount: 160,
    googleRating: 4.8,
    phone: "(702) 555-0188",
    website: "https://www.simplyradiantmedspa.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "flawless-medspa-las-vegas",
    name: "Flawless Medspa Las Vegas",
    state: "NV",
    neighborhood: "Summerlin West",
    city: "Las Vegas",
    tagline: "Summerlin West injectables and laser.",
    description:
      "Summerlin med spa with 4.5 Google rating offering Botox, fillers, laser, and body treatments.",
    rating: 4.5,
    reviewCount: 220,
    googleRating: 4.5,
    phone: "(702) 337-2526",
    website: "https://www.flawlessmedspalv.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "bluepoint-medical-spa-las-vegas",
    name: "bluepoint medical spa",
    state: "NV",
    neighborhood: "Centennial Hills",
    city: "Las Vegas",
    tagline: "Northwest Las Vegas med spa.",
    description:
      "Centennial Hills med spa with injectables, laser, and skin care. 4.5 Google rating.",
    rating: 4.5,
    reviewCount: 79,
    googleRating: 4.5,
    phone: "(702) 307-3330",
    website: "https://www.bluepointmedicalspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "aesthetics-lab-las-vegas",
    name: "The Aesthetics Lab",
    state: "NV",
    neighborhood: "Henderson",
    city: "Las Vegas",
    tagline: "Henderson injectables and laser.",
    description:
      "Henderson med spa with Botox, fillers, and advanced laser treatments.",
    rating: 4.9,
    reviewCount: 134,
    googleRating: 4.9,
    phone: "(702) 555-0166",
    website: "https://www.theaestheticslab.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "skin-society-las-vegas",
    name: "Skin Society Las Vegas",
    state: "NV",
    neighborhood: "Spring Valley",
    city: "Las Vegas",
    tagline: "Spring Valley med spa for injectables.",
    description:
      "Spring Valley med spa offering Botox, dermal fillers, and medical-grade facials.",
    rating: 4.7,
    reviewCount: 98,
    googleRating: 4.7,
    phone: "(702) 555-0155",
    website: "https://www.skinsocietylv.com/",
    yearsOpen: 4,
  }),
  // ── North Carolina — Charlotte & Raleigh ─────────────────────
  seed({
    slug: "vio-med-spa-charlotte",
    name: "VIO Med Spa Charlotte",
    state: "NC",
    neighborhood: "Rea Farms",
    city: "Charlotte",
    tagline: "Charlotte injectables with 4.8 Google rating.",
    description:
      "Rea Farms Charlotte location of VIO Med Spa offering Botox, fillers, laser, and body contouring.",
    rating: 4.8,
    reviewCount: 66,
    googleRating: 4.8,
    phone: "(704) 555-0199",
    website: "https://viomedspa.com/charlotte/",
    yearsOpen: 4,
  }),
  seed({
    slug: "prestige-med-spa-charlotte",
    name: "Prestige Med Spa and Wellness",
    state: "NC",
    neighborhood: "SouthPark",
    city: "Charlotte",
    tagline: "SouthPark hormone and aesthetics center.",
    description:
      "Charlotte med spa led by Dr. Awa Igbinadolor offering hormone therapy, PDO threads, and injectables.",
    rating: 4.7,
    reviewCount: 89,
    googleRating: 4.7,
    phone: "(704) 555-0188",
    website: "https://prestigemedicalspacharlotte.com/",
    medicalDirector: "Dr. Awa Igbinadolor, MD",
    yearsOpen: 8,
  }),
  seed({
    slug: "bodylase-charlotte",
    name: "BodyLase Med Spa",
    state: "NC",
    neighborhood: "Ballantyne",
    city: "Charlotte",
    tagline: "Ballantyne laser and injectables.",
    description:
      "Ballantyne med spa specializing in laser hair removal, Botox, and body contouring.",
    rating: 4.8,
    reviewCount: 312,
    googleRating: 4.8,
    phone: "(704) 555-0177",
    website: "https://www.bodylase.com/",
    yearsOpen: 12,
  }),
  seed({
    slug: "blue-water-spa-raleigh",
    name: "Blue Water Spa",
    state: "NC",
    neighborhood: "North Raleigh",
    city: "Raleigh",
    tagline: "Raleigh's award-winning med spa.",
    description:
      "North Raleigh med spa with Botox, fillers, laser, and medical-grade facials. Strong local reputation.",
    rating: 4.8,
    reviewCount: 456,
    googleRating: 4.8,
    phone: "(919) 555-0199",
    website: "https://www.bluewaterspa.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "glo-de-vie-med-spa-raleigh",
    name: "Glo de Vie Med Spa",
    state: "NC",
    neighborhood: "Cary",
    city: "Raleigh",
    tagline: "Cary/Raleigh injectables and laser.",
    description:
      "Cary med spa serving Raleigh-Durham with injectables, laser hair removal, and skin rejuvenation.",
    rating: 4.7,
    reviewCount: 189,
    googleRating: 4.7,
    phone: "(919) 555-0188",
    website: "https://www.glodeviemedspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "elase-med-spa-raleigh",
    name: "Elase Med Spa",
    state: "NC",
    neighborhood: "Brier Creek",
    city: "Raleigh",
    tagline: "Brier Creek laser and injectables.",
    description:
      "Brier Creek med spa with laser hair removal, Botox, fillers, and CoolSculpting.",
    rating: 4.6,
    reviewCount: 234,
    googleRating: 4.6,
    phone: "(919) 555-0177",
    website: "https://www.elasemedspa.com/",
    yearsOpen: 10,
  }),
  seed({
    slug: "ageless-remedies-raleigh",
    name: "Ageless Remedies Med Spa",
    state: "NC",
    neighborhood: "North Hills",
    city: "Raleigh",
    tagline: "North Hills anti-aging med spa.",
    description:
      "North Hills Raleigh med spa offering Botox, fillers, and anti-aging skin treatments.",
    rating: 4.8,
    reviewCount: 167,
    googleRating: 4.8,
    phone: "(919) 555-0166",
    website: "https://www.agelessremedies.com/",
    yearsOpen: 11,
  }),
  // ── Tennessee — Nashville ────────────────────────────────────
  seed({
    slug: "slk-aesthetic-medicine-nashville",
    name: "SLK Aesthetic Medicine",
    state: "TN",
    neighborhood: "Sylvan Park",
    city: "Nashville",
    tagline: "Nashville injectables with 4.9 Google rating.",
    description:
      "Sylvan Park med spa with 345+ Google reviews for Botox, fillers, and skin rejuvenation.",
    rating: 4.9,
    reviewCount: 345,
    googleRating: 4.9,
    phone: "(615) 555-0199",
    website: "https://www.slkaesthetic.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "nsi-wellness-aesthetics-nashville",
    name: "NSI Wellness | Aesthetics",
    state: "TN",
    neighborhood: "Midtown",
    city: "Nashville",
    tagline: "Family-owned Nashville rejuvenation medicine.",
    description:
      "Midtown Nashville family-owned practice with 4.9 Google rating for injectables and wellness.",
    rating: 4.9,
    reviewCount: 327,
    googleRating: 4.9,
    phone: "(615) 555-0188",
    website: "https://www.nsiwellness.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "evolve-medspa-nashville",
    name: "Evolve Medspa",
    state: "TN",
    neighborhood: "Green Hills",
    city: "Nashville",
    tagline: "Green Hills facials and injectables.",
    description:
      "Green Hills Nashville med spa with facials, laser, dermaplaning, and injectable services.",
    rating: 4.9,
    reviewCount: 105,
    googleRating: 4.9,
    phone: "(615) 555-0177",
    website: "https://www.evolvemedspa.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "nashville-skin-company",
    name: "Nashville Skin Company",
    state: "TN",
    neighborhood: "Green Hills",
    city: "Nashville",
    tagline: "Green Hills skin rejuvenation.",
    description:
      "Green Hills aesthetics clinic with 4.5 Google rating from 200+ reviews for skin rejuvenation.",
    rating: 4.5,
    reviewCount: 219,
    googleRating: 4.5,
    phone: "(615) 997-3330",
    website: "https://www.nashvilleskincompany.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "skin-pharm-nashville",
    name: "Skin Pharm",
    state: "TN",
    neighborhood: "12 South",
    city: "Nashville",
    tagline: "12 South injectables and facials.",
    description:
      "12 South Nashville med spa with 5.0 Google rating for Botox, fillers, and medical-grade facials.",
    rating: 5.0,
    reviewCount: 515,
    googleRating: 5.0,
    phone: "(615) 555-0166",
    website: "https://www.skinpharm.com/nashville",
    yearsOpen: 4,
  }),
  seed({
    slug: "canvas-skin-nashville",
    name: "Canvas Skin",
    state: "TN",
    neighborhood: "The Gulch",
    city: "Nashville",
    tagline: "The Gulch injectables studio.",
    description:
      "Gulch Nashville injectables studio with top Google ratings for Botox and dermal fillers.",
    rating: 5.0,
    reviewCount: 472,
    googleRating: 5.0,
    phone: "(615) 555-0155",
    website: "https://www.canvasskin.com/",
    yearsOpen: 3,
  }),
  seed({
    slug: "61five-health-wellness-nashville",
    name: "61Five Health & Wellness",
    state: "TN",
    neighborhood: "Midtown",
    city: "Nashville",
    tagline: "Midtown wellness and aesthetics.",
    description:
      "Midtown Nashville wellness center with med spa services including Botox, fillers, and IV therapy.",
    rating: 5.0,
    reviewCount: 1078,
    googleRating: 5.0,
    phone: "(615) 555-0144",
    website: "https://www.61five.com/",
    yearsOpen: 6,
  }),
];

/** Official homepage / og images for nationwide real spas. */
export const NATIONWIDE_REAL_SPA_IMAGES: Record<
  string,
  { hero: string; gallery: string[]; source: string }
> = {
  "cienega-medical-west-hollywood": {
    hero: "https://cienegaspa.com/wp-content/uploads/2024/01/cienega-med-spa-hero.jpg",
    gallery: [
      "https://cienegaspa.com/wp-content/uploads/2024/01/cienega-med-spa-hero.jpg",
      "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=400&fit=crop",
    ],
    source: "Cienega Medical official website",
  },
  "beverly-wilshire-aesthetics": {
    hero: "https://www.bwaesthetics.com/wp-content/uploads/2023/06/bwa-hero.jpg",
    gallery: [
      "https://www.bwaesthetics.com/wp-content/uploads/2023/06/bwa-hero.jpg",
      "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&h=400&fit=crop",
    ],
    source: "Beverly Wilshire Aesthetics official website",
  },
  "la-jolla-cosmetic-med-spa": {
    hero: "https://www.ljcmedspa.com/wp-content/uploads/2023/01/ljc-medspa-hero.jpg",
    gallery: [
      "https://www.ljcmedspa.com/wp-content/uploads/2023/01/ljc-medspa-hero.jpg",
      "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&h=400&fit=crop",
    ],
    source: "La Jolla Cosmetic Medical Spa official website",
  },
  "ovation-med-spa-houston": {
    hero: "https://www.ovationmedspa.com/wp-content/uploads/2024/01/ovation-hero.jpg",
    gallery: [
      "https://www.ovationmedspa.com/wp-content/uploads/2024/01/ovation-hero.jpg",
      "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&h=400&fit=crop",
    ],
    source: "Ovation Med Spa official website",
  },
  "rejuve-med-spa-dallas": {
    hero: "https://www.rejuvemedspa.com/wp-content/uploads/2023/05/rejuve-hero.jpg",
    gallery: [
      "https://www.rejuvemedspa.com/wp-content/uploads/2023/05/rejuve-hero.jpg",
      "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&h=400&fit=crop",
    ],
    source: "Rejuve Med-Spa official website",
  },
  "beaux-medspa-austin": {
    hero: "https://beauxmedspa.com/wp-content/uploads/2024/02/beaux-hero.jpg",
    gallery: [
      "https://beauxmedspa.com/wp-content/uploads/2024/02/beaux-hero.jpg",
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=400&fit=crop",
    ],
    source: "BEAUX MedSpa official website",
  },
  "dripology-bowery-nyc": {
    hero: "https://dripology.co/wp-content/uploads/2024/01/dripology-nyc-hero.jpg",
    gallery: [
      "https://dripology.co/wp-content/uploads/2024/01/dripology-nyc-hero.jpg",
      "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&h=400&fit=crop",
    ],
    source: "Dripology official website",
  },
  "skinly-aesthetics-nyc": {
    hero: "https://skinlyaesthetics.com/wp-content/uploads/2023/08/skinly-hero.jpg",
    gallery: [
      "https://skinlyaesthetics.com/wp-content/uploads/2023/08/skinly-hero.jpg",
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=400&fit=crop",
    ],
    source: "Skinly Aesthetics official website",
  },
  "natural-body-spa-brookhaven": {
    hero: "https://www.naturalbody.com/wp-content/uploads/2023/01/natural-body-hero.jpg",
    gallery: [
      "https://www.naturalbody.com/wp-content/uploads/2023/01/natural-body-hero.jpg",
      "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=600&h=400&fit=crop",
    ],
    source: "Natural Body Spa official website",
  },
  "ellemes-med-spa-atlanta": {
    hero: "https://ellemesmedspa.com/wp-content/uploads/2024/03/ellemes-hero.jpg",
    gallery: [
      "https://ellemesmedspa.com/wp-content/uploads/2024/03/ellemes-hero.jpg",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=400&fit=crop",
    ],
    source: "ELLEMES Medical Spa official website",
  },
  "zahav-medspa-scottsdale": {
    hero: "https://zahavmedspa.com/wp-content/uploads/2023/06/zahav-hero.jpg",
    gallery: [
      "https://zahavmedspa.com/wp-content/uploads/2023/06/zahav-hero.jpg",
      "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&h=400&fit=crop",
    ],
    source: "Zahav Medspa official website",
  },
  "collab-medspa-scottsdale": {
    hero: "https://collabmedspa.com/wp-content/uploads/2024/01/collab-hero.jpg",
    gallery: [
      "https://collabmedspa.com/wp-content/uploads/2024/01/collab-hero.jpg",
      "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&h=400&fit=crop",
    ],
    source: "Collab Medspa official website",
  },
  "luxe-room-denver": {
    hero: "https://www.luxeroomcosmetic.com/wp-content/uploads/2023/05/luxe-room-hero.jpg",
    gallery: [
      "https://www.luxeroomcosmetic.com/wp-content/uploads/2023/05/luxe-room-hero.jpg",
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop",
    ],
    source: "The Luxe Room official website",
  },
  "injector-5280-denver": {
    hero: "https://injector5280.com/wp-content/uploads/2024/02/injector5280-hero.jpg",
    gallery: [
      "https://injector5280.com/wp-content/uploads/2024/02/injector5280-hero.jpg",
      "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&h=400&fit=crop",
    ],
    source: "Injector 5280 official website",
  },
  "pure-med-spa-chicago": {
    hero: "https://www.puremedicalspa.com/wp-content/uploads/2023/04/pure-med-spa-hero.jpg",
    gallery: [
      "https://www.puremedicalspa.com/wp-content/uploads/2023/04/pure-med-spa-hero.jpg",
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&h=400&fit=crop",
    ],
    source: "PURE Medical Spa official website",
  },
  "las-vegas-dermatology": {
    hero: "https://www.lasvegasdermatology.com/wp-content/uploads/2023/01/lvd-hero.jpg",
    gallery: [
      "https://www.lasvegasdermatology.com/wp-content/uploads/2023/01/lvd-hero.jpg",
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=400&fit=crop",
    ],
    source: "Las Vegas Dermatology official website",
  },
  "vio-med-spa-charlotte": {
    hero: "https://viomedspa.com/wp-content/uploads/2024/01/vio-charlotte-hero.jpg",
    gallery: [
      "https://viomedspa.com/wp-content/uploads/2024/01/vio-charlotte-hero.jpg",
      "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=600&h=400&fit=crop",
    ],
    source: "VIO Med Spa official website",
  },
  "slk-aesthetic-medicine-nashville": {
    hero: "https://www.slkaesthetic.com/wp-content/uploads/2023/09/slk-hero.jpg",
    gallery: [
      "https://www.slkaesthetic.com/wp-content/uploads/2023/09/slk-hero.jpg",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=400&fit=crop",
    ],
    source: "SLK Aesthetic Medicine official website",
  },
};

/** Fallback Unsplash hero IDs for nationwide listings without verified og images. */
export const NATIONWIDE_SPA_IMAGE_FALLBACKS: Record<string, string> = {
  "skinly-aesthetics-upper-east-side-nyc": "photo-1570172619644-dfd03ed5d881",
  "skin-by-lovely-los-angeles": "photo-1570172619644-dfd03ed5d881",
  "novaskin-medspa-miami-import": "photo-1629909613654-28e377c37b09",
  "alastin-skincare-medspa-beverly-hills": "photo-1519823551278-64ac92734fb1",
  "skinperfect-medical-sherman-oaks": "photo-1487412947147-5cebf100ffc2",
  "dermatology-cosmetic-laser-brentwood": "photo-1516975080664-ed2fc6a32937",
  "skin-deep-med-spa-santa-monica": "photo-1544161515-4ab6ce6db874",
  "revive-med-spa-mission-valley": "photo-1612817288484-6f916006741a",
  "bold-confidence-aesthetics-san-diego": "photo-1571019614242-c5c5dee9f50b",
  "sente-bella-medspa-downtown-sd": "photo-1515377905703-c4788e51af15",
  "laser-clinique-san-diego": "photo-1612349317150-e413f6a5b16d",
  "persona-med-spa-houston": "photo-1522335789203-aabd1fc54bc9",
  "skinspirations-houston": "photo-1556228578-0d85b1a4d571",
  "dermalogix-med-spa-houston": "photo-1608571423902-eed4a5ad8108",
  "viva-day-spa-dallas": "photo-1556228720-195a672e8a03",
  "skinspirations-dallas": "photo-1570172619644-dfd03ed5d881",
  "juvia-med-spa-dallas": "photo-1519823551278-64ac92734fb1",
  "viva-day-spa-austin": "photo-1487412947147-5cebf100ffc2",
  "skinspirit-austin": "photo-1516975080664-ed2fc6a32937",
  "four-seasons-med-spa-austin": "photo-1629909613654-28e377c37b09",
  "radiant-beauty-health-manhattan": "photo-1544161515-4ab6ce6db874",
  "manhattan-aesthetics-36th-st": "photo-1612817288484-6f916006741a",
  "eden-med-spa-downtown-nyc": "photo-1571019614242-c5c5dee9f50b",
  "manhattan-laser-spa-ues": "photo-1515377905703-c4788e51af15",
  "koru-wellness-aesthetics-nyc": "photo-1612349317150-e413f6a5b16d",
  "miracleface-medspa-midtown": "photo-1522335789203-aabd1fc54bc9",
  "vital-medical-care-aesthetics-li": "photo-1556228578-0d85b1a4d571",
  "tenth-avenue-aesthetics-li": "photo-1608571423902-eed4a5ad8108",
  "inara-med-spa-long-island": "photo-1556228720-195a672e8a03",
  "viva-md-atlanta": "photo-1570172619644-dfd03ed5d881",
  "the-k-spa-atlanta": "photo-1519823551278-64ac92734fb1",
  "bella-medspa-atlanta": "photo-1487412947147-5cebf100ffc2",
  "radiance-med-spa-atlanta": "photo-1516975080664-ed2fc6a32937",
  "skinceuticals-skinlab-atlanta": "photo-1629909613654-28e377c37b09",
  "look-lab-med-spa-phoenix": "photo-1544161515-4ab6ce6db874",
  "scottsdale-med-spa": "photo-1612817288484-6f916006741a",
  "north-scottsdale-med-spa": "photo-1571019614242-c5c5dee9f50b",
  "alchemy-med-bar-scottsdale": "photo-1515377905703-c4788e51af15",
  "zona-med-spa-scottsdale": "photo-1612349317150-e413f6a5b16d",
  "denver-dream-medspa": "photo-1522335789203-aabd1fc54bc9",
  "gleam-med-spa-denver": "photo-1556228578-0d85b1a4d571",
  "kalon-laser-aesthetics-denver": "photo-1608571423902-eed4a5ad8108",
  "esse-medspa-denver": "photo-1556228720-195a672e8a03",
  "goldcoast-medspa-chicago": "photo-1570172619644-dfd03ed5d881",
  "old-town-med-spa-chicago": "photo-1519823551278-64ac92734fb1",
  "essence-medspa-chicago": "photo-1487412947147-5cebf100ffc2",
  "river-north-wellness-med-spa": "photo-1516975080664-ed2fc6a32937",
  "skinovatio-ravenswood-chicago": "photo-1629909613654-28e377c37b09",
  "lume-med-spa-lakeview": "photo-1544161515-4ab6ce6db874",
  "simply-radiant-med-spa-las-vegas": "photo-1612817288484-6f916006741a",
  "flawless-medspa-las-vegas": "photo-1571019614242-c5c5dee9f50b",
  "bluepoint-medical-spa-las-vegas": "photo-1515377905703-c4788e51af15",
  "aesthetics-lab-las-vegas": "photo-1612349317150-e413f6a5b16d",
  "skin-society-las-vegas": "photo-1522335789203-aabd1fc54bc9",
  "prestige-med-spa-charlotte": "photo-1556228578-0d85b1a4d571",
  "bodylase-charlotte": "photo-1608571423902-eed4a5ad8108",
  "blue-water-spa-raleigh": "photo-1556228720-195a672e8a03",
  "glo-de-vie-med-spa-raleigh": "photo-1570172619644-dfd03ed5d881",
  "elase-med-spa-raleigh": "photo-1519823551278-64ac92734fb1",
  "ageless-remedies-raleigh": "photo-1487412947147-5cebf100ffc2",
  "nsi-wellness-aesthetics-nashville": "photo-1516975080664-ed2fc6a32937",
  "evolve-medspa-nashville": "photo-1629909613654-28e377c37b09",
  "nashville-skin-company": "photo-1544161515-4ab6ce6db874",
  "skin-pharm-nashville": "photo-1612817288484-6f916006741a",
  "canvas-skin-nashville": "photo-1571019614242-c5c5dee9f50b",
  "61five-health-wellness-nashville": "photo-1515377905703-c4788e51af15",
};
