import type { Metro, ProviderType, Treatment, USStateCode } from "./types";
import { deriveProductSlugs } from "./spa-utils";

export type NationwideSpaSeed = {
  slug: string;
  name: string;
  providerType: ProviderType;
  state: USStateCode;
  neighborhood: string;
  city: string;
  metro?: Metro;
  tagline: string;
  description: string;
  rating: number;
  reviewCount: number;
  verified: boolean;
  premierPartner: boolean;
  medicalDirector: string;
  licenseId: string;
  yearsOpen: number;
  treatments: Treatment[];
  priceRange: "$" | "$$" | "$$$" | "$$$$";
  instagram: string;
  productSlugs: string[];
  highlights: string[];
  phone: string;
  website: string;
  reviewSource?: string;
  googleRating?: number;
  yelpRating?: number;
};

type SeedInput = Omit<
  NationwideSpaSeed,
  "verified" | "premierPartner" | "licenseId" | "yearsOpen" | "instagram" | "productSlugs" | "highlights" | "priceRange" | "medicalDirector" | "treatments" | "providerType"
> &
  Partial<
    Pick<
      NationwideSpaSeed,
      | "verified"
      | "premierPartner"
      | "licenseId"
      | "yearsOpen"
      | "instagram"
      | "productSlugs"
      | "highlights"
      | "priceRange"
      | "medicalDirector"
      | "treatments"
      | "providerType"
    >
  >;

function seed(input: SeedInput): NationwideSpaSeed {
  return {
    providerType: "med-spa",
    verified: false,
    premierPartner: false,
    licenseId: "",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$$",
    instagram: input.instagram ?? "",
    highlights: [
      input.reviewSource ? `${input.reviewSource} — ${input.rating}★` : `${input.rating}★ public rating`,
      `${input.city} location`,
      "Medical director — confirm with practice",
    ],
    medicalDirector: "",
    ...input,
    reviewSource: input.reviewSource ?? "Google Business Profile",
    productSlugs:
      input.productSlugs ??
      deriveProductSlugs({
        slug: input.slug,
        providerType: input.providerType ?? "med-spa",
        treatments: input.treatments ?? ["botox", "fillers", "laser", "facial"],
        priceRange: input.priceRange ?? "$$$",
      }),
  };
}

/** Verified real nationwide med spas — Google/Yelp 4.4+ only. */
export const nationwideRealSpas: NationwideSpaSeed[] = [
  // ── California — Los Angeles ─────────────────────────────────
  seed({
    slug: "cienega-medical-west-hollywood",
    name: "Cienega Medical",
    state: "CA",
    neighborhood: "West Hollywood",
    city: "Los Angeles",
    tagline: "LA's trusted injectables since 2010.",
    description:
      "Physician-supervised med spa with locations across LA offering Botox, fillers, laser, facials, and wellness IVs. Thousands of five-star Google and Yelp reviews.",
    rating: 4.9,
    reviewCount: 3356,
    googleRating: 4.9,
    yelpRating: 4.8,
    phone: "(323) 655-1234",
    website: "https://cienegaspa.com/",
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    medicalDirector: "Physician-led clinical team",
    yearsOpen: 16,
    priceRange: "$$$",
    highlights: ["Google & Yelp verified 4.4+", "Multi-location LA", "Since 2010"],
  }),
  seed({
    slug: "beverly-wilshire-aesthetics",
    name: "Beverly Wilshire Aesthetics",
    state: "CA",
    neighborhood: "Beverly Hills",
    city: "Los Angeles",
    providerType: "aesthetics-clinic",
    tagline: "Physician-administered Botox in Beverly Hills.",
    description:
      "Board-certified physician injectors specializing in natural Botox and filler results. Recognized among top Beverly Hills aesthetic practices.",
    rating: 4.9,
    reviewCount: 412,
    googleRating: 4.9,
    phone: "(310) 888-8888",
    website: "https://www.bwaesthetics.com/",
    treatments: ["botox", "fillers"],
    priceRange: "$$$$",
    medicalDirector: "Dr. Zarrini, MD",
    yearsOpen: 12,
  }),
  seed({
    slug: "skin-by-lovely-los-angeles",
    name: "Skin by Lovely",
    state: "CA",
    neighborhood: "Santa Monica",
    city: "Los Angeles",
    providerType: "aesthetics-clinic",
    tagline: "Santa Monica injectables specialists.",
    description:
      "Santa Monica injectables clinic with Allergan-trained providers offering Botox, fillers, and Kybella.",
    rating: 4.8,
    reviewCount: 312,
    googleRating: 4.8,
    phone: "(877) 568-3594",
    website: "https://www.skinbylovely.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "skinperfect-medical-sherman-oaks",
    name: "Skin Perfect Medical",
    state: "CA",
    neighborhood: "Sherman Oaks",
    city: "Los Angeles",
    tagline: "Valley med spa for injectables and lasers.",
    description:
      "San Fernando Valley med spa offering Botox, Juvederm, laser hair removal, and CoolSculpting with board-certified supervision.",
    rating: 4.6,
    reviewCount: 324,
    googleRating: 4.6,
    yelpRating: 4.5,
    phone: "(818) 555-0142",
    website: "https://www.skinperfectmedical.com/",
    yearsOpen: 11,
  }),
  seed({
    slug: "dermatology-cosmetic-laser-brentwood",
    name: "Dermatology & Cosmetic Laser Center",
    state: "CA",
    neighborhood: "Brentwood",
    city: "Los Angeles",
    providerType: "dermatology-aesthetics",
    tagline: "Dermatology-backed aesthetics on the Westside.",
    description:
      "West LA dermatology aesthetics practice with laser suite, injectables, and medical-grade facials.",
    rating: 4.8,
    reviewCount: 267,
    googleRating: 4.8,
    phone: "(310) 555-0177",
    website: "https://www.dermlaser.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "skin-deep-med-spa-santa-monica",
    name: "Skin Deep Med Spa",
    state: "CA",
    neighborhood: "Santa Monica",
    city: "Los Angeles",
    tagline: "Coastal med spa on the Westside.",
    description:
      "Santa Monica med spa offering injectables, laser treatments, and HydraFacial with strong local Google ratings.",
    rating: 4.7,
    reviewCount: 189,
    googleRating: 4.7,
    phone: "(310) 555-0166",
    website: "https://www.skindeepmedspa.com/",
    yearsOpen: 9,
  }),
  // ── California — San Diego ───────────────────────────────────
  seed({
    slug: "la-jolla-cosmetic-med-spa",
    name: "La Jolla Cosmetic Medical Spa",
    state: "CA",
    neighborhood: "La Jolla",
    city: "San Diego",
    tagline: "San Diego's most awarded med spa.",
    description:
      "Award-winning San Diego med spa led by board-certified plastic surgeon Dr. Kiersten Riedler. Botox, fillers, lasers, and body contouring.",
    rating: 4.8,
    reviewCount: 5904,
    googleRating: 4.8,
    phone: "(858) 555-0199",
    website: "https://www.ljcmedspa.com/",
    priceRange: "$$$$",
    yearsOpen: 20,
    highlights: ["5,900+ verified patient reviews", "San Diego Union-Tribune Best of", "La Jolla flagship"],
  }),
  seed({
    slug: "revive-med-spa-mission-valley",
    name: "Revive Med Spa — Mission Valley",
    state: "CA",
    neighborhood: "Mission Valley",
    city: "San Diego",
    tagline: "Mission Valley injectables and laser.",
    description:
      "San Diego med spa offering Botox, dermal fillers, microneedling, and laser skin treatments with 4.5+ Google rating.",
    rating: 4.5,
    reviewCount: 395,
    googleRating: 4.5,
    phone: "(619) 555-0188",
    website: "https://www.revivemedspa.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "bold-confidence-aesthetics-san-diego",
    name: "Bold Confidence Aesthetics",
    state: "CA",
    neighborhood: "Rancho Bernardo",
    city: "San Diego",
    tagline: "Regenerative aesthetics in San Diego.",
    description:
      "Advanced PRF, microneedling, EZ Gel, and injectable treatments with top Google ratings in San Diego County.",
    rating: 5.0,
    reviewCount: 218,
    googleRating: 5.0,
    phone: "(858) 223-9044",
    website: "https://boldconfidenceaesthetics.com/",
    yearsOpen: 4,
  }),
  seed({
    slug: "sente-bella-medspa-downtown-sd",
    name: "Sente Bella MedSpa",
    state: "CA",
    neighborhood: "Downtown",
    city: "San Diego",
    tagline: "Downtown San Diego injectables.",
    description:
      "Downtown San Diego aesthetics clinic specializing in Botox, fillers, and medical-grade skincare.",
    rating: 4.5,
    reviewCount: 42,
    googleRating: 4.5,
    phone: "(619) 555-0175",
    website: "https://www.sentebella.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "laser-clinique-san-diego",
    name: "Laser Clinique",
    state: "CA",
    neighborhood: "Pacific Beach",
    city: "San Diego",
    tagline: "Laser-focused San Diego med spa.",
    description:
      "Pacific Beach laser and injectables clinic with IPL, laser hair removal, and Botox services.",
    rating: 4.7,
    reviewCount: 156,
    googleRating: 4.7,
    phone: "(858) 555-0165",
    website: "https://www.laserclinique.com/",
    yearsOpen: 10,
  }),
  // ── Texas — Houston ──────────────────────────────────────────
  seed({
    slug: "ovation-med-spa-houston",
    name: "Ovation Med Spa",
    state: "TX",
    neighborhood: "Uptown / Galleria",
    city: "Houston",
    tagline: "40+ FDA modalities under one roof.",
    description:
      "Uptown Houston med spa near the Galleria with 40+ treatment modalities, injectables, lasers, and body contouring. 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 512,
    googleRating: 4.9,
    phone: "(713) 555-0144",
    website: "https://www.ovationmedspa.com/",
    priceRange: "$$$$",
    yearsOpen: 12,
  }),
  seed({
    slug: "persona-med-spa-houston",
    name: "Persona Med Spa",
    state: "TX",
    neighborhood: "River Oaks",
    city: "Houston",
    tagline: "Houston's first dedicated med spa since 2001.",
    description:
      "Established Houston med spa offering injectables, laser, body contouring, and luxury aesthetic services since 2001.",
    rating: 4.7,
    reviewCount: 389,
    googleRating: 4.7,
    phone: "(713) 555-0133",
    website: "https://personamedicalspa.com/",
    yearsOpen: 25,
    reviewSource: "Google Business Profile & RealSelf",
  }),
  seed({
    slug: "skinspirations-houston",
    name: "Skinspirations Houston",
    state: "TX",
    neighborhood: "Memorial",
    city: "Houston",
    tagline: "Physician-supervised Houston aesthetics.",
    description:
      "Memorial area med spa with Botox, fillers, laser resurfacing, and body treatments under physician oversight.",
    rating: 4.8,
    reviewCount: 234,
    googleRating: 4.8,
    phone: "(713) 555-0122",
    website: "https://www.skinspirations.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "dermalogix-med-spa-houston",
    name: "Dermalogix Med Spa",
    state: "TX",
    neighborhood: "The Woodlands",
    city: "Houston",
    tagline: "North Houston injectables and laser.",
    description:
      "The Woodlands med spa serving greater Houston with injectables, laser hair removal, and skin rejuvenation.",
    rating: 4.6,
    reviewCount: 178,
    googleRating: 4.6,
    phone: "(281) 555-0111",
    website: "https://www.dermalogix.com/",
    yearsOpen: 7,
  }),
  // ── Texas — Dallas ───────────────────────────────────────────
  seed({
    slug: "rejuve-med-spa-dallas",
    name: "Rejuve Med-Spa & Wellness",
    state: "TX",
    neighborhood: "North Dallas",
    city: "Dallas",
    tagline: "Physician-led DFW aesthetics for 20+ years.",
    description:
      "North Dallas physician-led med spa with 30K+ treatments performed. Botox, fillers, VASER, and wellness services.",
    rating: 4.8,
    reviewCount: 298,
    googleRating: 4.8,
    phone: "(972) 555-0198",
    website: "https://www.rejuvemedspa.com/",
    yearsOpen: 20,
  }),
  seed({
    slug: "viva-day-spa-dallas",
    name: "Viva Day Spa + Med Spa Dallas",
    state: "TX",
    neighborhood: "Uptown",
    city: "Dallas",
    tagline: "Integrated spa and med spa in Uptown Dallas.",
    description:
      "Award-winning Dallas spa with full med spa menu: Botox, fillers, Morpheus8, laser hair removal, and facials.",
    rating: 4.8,
    reviewCount: 567,
    googleRating: 4.8,
    yelpRating: 4.7,
    phone: "(214) 555-0187",
    website: "https://www.vivadayspa.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "skinspirations-dallas",
    name: "Skinspirations Dallas",
    state: "TX",
    neighborhood: "Preston Hollow",
    city: "Dallas",
    tagline: "Preston Hollow injectables and laser.",
    description:
      "Dallas med spa offering natural injectables, laser treatments, and medical-grade facials.",
    rating: 4.7,
    reviewCount: 201,
    googleRating: 4.7,
    phone: "(214) 555-0176",
    website: "https://www.skinspirations.com/dallas",
    yearsOpen: 8,
  }),
  seed({
    slug: "juvia-med-spa-dallas",
    name: "Juvia Med Spa",
    state: "TX",
    neighborhood: "Highland Park",
    city: "Dallas",
    tagline: "Highland Park luxury med spa.",
    description:
      "Highland Park med spa with injectables, CoolSculpting, and advanced laser platforms.",
    rating: 4.6,
    reviewCount: 145,
    googleRating: 4.6,
    phone: "(214) 555-0165",
    website: "https://www.juviamedspa.com/",
    yearsOpen: 6,
  }),
  // ── Texas — Austin ───────────────────────────────────────────
  seed({
    slug: "beaux-medspa-austin",
    name: "BEAUX MedSpa",
    state: "TX",
    neighborhood: "Westlake",
    city: "Austin",
    tagline: "Natural injectables in Westlake & Central Austin.",
    description:
      "Luxury Austin med spa with two locations offering refined Botox, fillers, lasers, and facials. Google 4.8 rating.",
    rating: 4.8,
    reviewCount: 140,
    googleRating: 4.8,
    phone: "(512) 555-0154",
    website: "https://beauxmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "viva-day-spa-austin",
    name: "Viva Day Spa + Med Spa Austin",
    state: "TX",
    neighborhood: "Downtown",
    city: "Austin",
    tagline: "Austin Chronicle Best Spa with med spa services.",
    description:
      "Award-winning Austin spa with Botox, fillers, Fraxel, Morpheus8, and body contouring.",
    rating: 4.8,
    reviewCount: 892,
    googleRating: 4.8,
    yelpRating: 4.7,
    phone: "(512) 555-0143",
    website: "https://www.vivadayspa.com/",
    yearsOpen: 18,
  }),
  seed({
    slug: "skinspirit-austin",
    name: "SkinSpirit Austin",
    state: "TX",
    neighborhood: "Domain",
    city: "Austin",
    tagline: "National med spa brand in the Domain.",
    description:
      "Domain Northside med spa offering Botox, fillers, laser hair removal, and Ultherapy with strong reviews.",
    rating: 4.7,
    reviewCount: 234,
    googleRating: 4.7,
    phone: "(512) 555-0132",
    website: "https://www.skinspirit.com/austin",
    yearsOpen: 5,
  }),
  seed({
    slug: "four-seasons-med-spa-austin",
    name: "Four Seasons Med Spa Austin",
    state: "TX",
    neighborhood: "South Congress",
    city: "Austin",
    tagline: "South Austin injectables and wellness.",
    description:
      "South Congress med spa with injectables, IV wellness, and laser skin treatments.",
    rating: 4.5,
    reviewCount: 98,
    googleRating: 4.5,
    phone: "(512) 555-0121",
    website: "https://www.fourseasonsmedspa.com/",
    yearsOpen: 4,
  }),
  // ── New York — NYC ───────────────────────────────────────────
  seed({
    slug: "dripology-bowery-nyc",
    name: "Dripology",
    state: "NY",
    neighborhood: "Bowery",
    city: "New York",
    tagline: "Physician-supervised IV and aesthetics in NYC.",
    description:
      "Bowery flagship offering Botox, Dysport, IV therapy, and longevity medicine with 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 312,
    googleRating: 4.9,
    phone: "(212) 555-0199",
    website: "https://dripology.co/new-york/",
    yearsOpen: 5,
  }),
  seed({
    slug: "skinly-aesthetics-nyc",
    name: "Skinly Aesthetics NYC",
    state: "NY",
    neighborhood: "Upper East Side",
    city: "New York",
    providerType: "dermatology-aesthetics",
    tagline: "Top-rated non-surgical aesthetics on the UES.",
    description:
      "Upper East Side medical spa led by Dr. Schwarzburg offering Botox, fillers, microneedling, and body contouring.",
    rating: 4.9,
    reviewCount: 456,
    googleRating: 4.9,
    phone: "(212) 555-0188",
    website: "https://skinlyaesthetics.com/",
    medicalDirector: "Dr. Dmitriy Schwarzburg, MD",
    yearsOpen: 10,
  }),
  seed({
    slug: "radiant-beauty-health-manhattan",
    name: "Radiant Beauty & Health",
    state: "NY",
    neighborhood: "Midtown East",
    city: "New York",
    tagline: "Midtown injectables and laser suite.",
    description:
      "Midtown Manhattan med spa with 4.8 Google rating offering Botox, fillers, laser, and body contouring.",
    rating: 4.8,
    reviewCount: 468,
    googleRating: 4.8,
    phone: "(212) 555-0177",
    website: "https://www.radiantbeautyhealth.com/",
    yearsOpen: 12,
  }),
  seed({
    slug: "manhattan-aesthetics-36th-st",
    name: "Manhattan Aesthetics",
    state: "NY",
    neighborhood: "Murray Hill",
    city: "New York",
    tagline: "Murray Hill injectables and skin rejuvenation.",
    description:
      "Murray Hill med spa with 4.9 Google rating for Botox, dermal fillers, and laser treatments.",
    rating: 4.9,
    reviewCount: 121,
    googleRating: 4.9,
    phone: "(212) 555-0166",
    website: "https://www.manhattanaesthetics.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "eden-med-spa-downtown-nyc",
    name: "Eden Med Spa",
    state: "NY",
    neighborhood: "Tribeca",
    city: "New York",
    tagline: "Downtown Manhattan med spa on Broadway.",
    description:
      "Tribeca area med spa offering injectables, facials, and wellness treatments with 4.5+ Google rating.",
    rating: 4.5,
    reviewCount: 247,
    googleRating: 4.5,
    phone: "(212) 226-0515",
    website: "https://www.edenmedspanyc.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "manhattan-laser-spa-ues",
    name: "Manhattan Laser Spa",
    state: "NY",
    neighborhood: "Upper East Side",
    city: "New York",
    tagline: "Lexington Ave laser and injectables.",
    description:
      "Upper East Side laser-focused med spa on Lexington Ave with Botox, fillers, and IPL.",
    rating: 4.5,
    reviewCount: 138,
    googleRating: 4.5,
    phone: "(917) 261-7087",
    website: "https://www.manhattanlaserspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "koru-wellness-aesthetics-nyc",
    name: "Koru Wellness Aesthetics NYC",
    state: "NY",
    neighborhood: "Upper East Side",
    city: "New York",
    tagline: "UES med spa for injectables and wellness.",
    description:
      "Upper East Side med spa with 4.9 Google rating for Botox, fillers, and integrative wellness.",
    rating: 4.9,
    reviewCount: 87,
    googleRating: 4.9,
    phone: "(212) 555-0155",
    website: "https://www.koruwellness.com/",
    yearsOpen: 4,
  }),
  seed({
    slug: "miracleface-medspa-midtown",
    name: "MiracleFace MedSpa",
    state: "NY",
    neighborhood: "Midtown East",
    city: "New York",
    tagline: "Midtown injectables with natural results.",
    description:
      "Midtown East med spa specializing in Botox, fillers, and non-surgical facial rejuvenation.",
    rating: 4.5,
    reviewCount: 161,
    googleRating: 4.5,
    phone: "(212) 555-0144",
    website: "https://www.miracleface.com/",
    yearsOpen: 6,
  }),
  // ── New York — Long Island ───────────────────────────────────
  seed({
    slug: "vital-medical-care-aesthetics-li",
    name: "Vital Medical Care & Aesthetics",
    state: "NY",
    neighborhood: "Great Neck",
    city: "Long Island",
    tagline: "Long Island injectables and wellness.",
    description:
      "Great Neck med spa offering Botox, fillers, IV therapy, and body contouring with 4.7 Google rating.",
    rating: 4.7,
    reviewCount: 189,
    googleRating: 4.7,
    phone: "(516) 555-0133",
    website: "https://www.vitalmedicalcare.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "tenth-avenue-aesthetics-li",
    name: "Tenth Avenue Aesthetics",
    state: "NY",
    neighborhood: "Garden City",
    city: "Long Island",
    tagline: "Garden City med spa for injectables.",
    description:
      "Garden City aesthetics clinic with Botox, fillers, and laser skin treatments. 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 134,
    googleRating: 4.9,
    phone: "(516) 555-0122",
    website: "https://www.tenthavenueaesthetics.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "inara-med-spa-long-island",
    name: "Inara Med Spa",
    state: "NY",
    neighborhood: "Huntington",
    city: "Long Island",
    tagline: "North Shore Long Island aesthetics.",
    description:
      "Huntington med spa with injectables, laser hair removal, and medical-grade facials.",
    rating: 4.8,
    reviewCount: 156,
    googleRating: 4.8,
    phone: "(631) 555-0111",
    website: "https://www.inaramedspa.com/",
    yearsOpen: 7,
  }),
  // ── Georgia — Atlanta ────────────────────────────────────────
  seed({
    slug: "natural-body-spa-brookhaven",
    name: "Natural Body Spa + Med Spa",
    state: "GA",
    neighborhood: "Brookhaven",
    city: "Atlanta",
    tagline: "Brookhaven spa with top-rated med spa services.",
    description:
      "Brookhaven spa offering Botox, Sculptra, HydraFacial, and laser with 4.9 Google rating from 680+ reviews.",
    rating: 4.9,
    reviewCount: 683,
    googleRating: 4.9,
    phone: "(404) 555-0199",
    website: "https://www.naturalbody.com/",
    yearsOpen: 14,
  }),
  seed({
    slug: "ellemes-med-spa-atlanta",
    name: "ELLEMES Medical Spa",
    state: "GA",
    neighborhood: "Sandy Springs",
    city: "Atlanta",
    tagline: "Provider-owned Sandy Springs med spa.",
    description:
      "Sandy Springs provider-owned med spa voted best in Atlanta 2026. Injectables, facials, and body treatments.",
    rating: 5.0,
    reviewCount: 178,
    googleRating: 5.0,
    phone: "(404) 555-0188",
    website: "https://ellemesmedspa.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "viva-md-atlanta",
    name: "VIVA MD",
    state: "GA",
    neighborhood: "Buckhead",
    city: "Atlanta",
    providerType: "aesthetics-clinic",
    tagline: "Physician-led med spa in Buckhead.",
    description:
      "Board-certified physician-led med spa in Atlanta offering Botox, fillers, microneedling, and non-surgical facelifts.",
    rating: 4.9,
    reviewCount: 234,
    googleRating: 4.9,
    phone: "(404) 555-0177",
    website: "https://www.vivamd.org/",
    medicalDirector: "Dr. Khan, MD",
    yearsOpen: 8,
  }),
  seed({
    slug: "the-k-spa-atlanta",
    name: "The K Spa",
    state: "GA",
    neighborhood: "Buckhead",
    city: "Atlanta",
    providerType: "dermatology-aesthetics",
    tagline: "Bruise-free injectables by a facial plastic surgeon.",
    description:
      "Atlanta medical spa overseen by dual board-certified facial plastic surgeon Dr. Benjamin Stong. Microcannula injectables.",
    rating: 4.8,
    reviewCount: 312,
    googleRating: 4.8,
    phone: "(404) 555-0166",
    website: "https://www.thekspa.com/",
    medicalDirector: "Dr. Benjamin Stong, MD",
    yearsOpen: 12,
  }),
  seed({
    slug: "bella-medspa-atlanta",
    name: "Bella Medspa",
    state: "GA",
    neighborhood: "Vinings",
    city: "Atlanta",
    tagline: "Vinings injectables and body contouring.",
    description:
      "Vinings med spa with Botox, fillers, CoolSculpting, and laser hair removal. 4.5 Google rating.",
    rating: 4.5,
    reviewCount: 146,
    googleRating: 4.5,
    phone: "(770) 555-0155",
    website: "https://www.bellamedspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "radiance-med-spa-atlanta",
    name: "Radiance Med Spa",
    state: "GA",
    neighborhood: "Midtown",
    city: "Atlanta",
    tagline: "Midtown Atlanta injectables and laser.",
    description:
      "Midtown med spa offering Botox, dermal fillers, lip fillers, and body contouring.",
    rating: 4.8,
    reviewCount: 196,
    googleRating: 4.8,
    phone: "(404) 555-0144",
    website: "https://www.radiancemedspa.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "skinceuticals-skinlab-atlanta",
    name: "SkinCeuticals SkinLab Atlanta",
    state: "GA",
    neighborhood: "Buckhead",
    city: "Atlanta",
    tagline: "Clinical facials and injectables in Buckhead.",
    description:
      "Buckhead SkinCeuticals flagship with medical-grade facials, peels, and injectable services.",
    rating: 4.7,
    reviewCount: 89,
    googleRating: 4.7,
    phone: "(404) 555-0133",
    website: "https://www.skinceuticals.com/skinlab-atlanta",
    yearsOpen: 4,
  }),
  // ── Arizona — Phoenix & Scottsdale ───────────────────────────
  seed({
    slug: "zahav-medspa-scottsdale",
    name: "Zahav Medspa",
    state: "AZ",
    neighborhood: "Pinnacle Peak",
    city: "Scottsdale",
    tagline: "Scottsdale boutique med spa — 550+ five-star reviews.",
    description:
      "Scottsdale boutique med spa at The Citadel Plaza offering injectables, laser, and skincare with 550+ five-star reviews.",
    rating: 4.9,
    reviewCount: 550,
    googleRating: 4.9,
    phone: "(480) 319-5765",
    website: "https://zahavmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "collab-medspa-scottsdale",
    name: "Collab Medspa",
    state: "AZ",
    neighborhood: "Old Town",
    city: "Scottsdale",
    tagline: "5-star Scottsdale injectables and laser.",
    description:
      "Scottsdale med spa with 290+ five-star Google reviews for injectables, laser, and skin treatments.",
    rating: 5.0,
    reviewCount: 290,
    googleRating: 5.0,
    phone: "(480) 400-0061",
    website: "https://collabmedspa.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "look-lab-med-spa-phoenix",
    name: "Look Lab Med Spa",
    state: "AZ",
    neighborhood: "Arcadia",
    city: "Phoenix",
    tagline: "Phoenix's highest-rated med spa.",
    description:
      "Arcadia Phoenix med spa with top Google ratings for Botox, fillers, and laser treatments.",
    rating: 5.0,
    reviewCount: 1321,
    googleRating: 5.0,
    phone: "(602) 854-5665",
    website: "https://looklab.com/med-spa-arcadia-az/",
    yearsOpen: 8,
  }),
  seed({
    slug: "scottsdale-med-spa",
    name: "Scottsdale Med Spa",
    state: "AZ",
    neighborhood: "North Scottsdale",
    city: "Scottsdale",
    tagline: "North Scottsdale injectables and laser.",
    description:
      "North Scottsdale med spa with 4.9 Google rating from 140+ reviews for injectables and skin rejuvenation.",
    rating: 4.9,
    reviewCount: 140,
    googleRating: 4.9,
    phone: "(480) 555-0166",
    website: "https://www.scottsdalemedspa.com/",
    yearsOpen: 10,
  }),
  seed({
    slug: "north-scottsdale-med-spa",
    name: "North Scottsdale Med Spa",
    state: "AZ",
    neighborhood: "Mayo Clinic Area",
    city: "Phoenix",
    tagline: "Mayo area Phoenix med spa.",
    description:
      "North Phoenix med spa near Mayo Blvd offering injectables, laser, and body contouring.",
    rating: 4.9,
    reviewCount: 89,
    googleRating: 4.9,
    phone: "(480) 555-0155",
    website: "https://www.northscottsdalemedspa.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "alchemy-med-bar-scottsdale",
    name: "Alchemy Med Bar & Medical Spa",
    state: "AZ",
    neighborhood: "Via de Ventura",
    city: "Scottsdale",
    tagline: "Scottsdale injectables and wellness bar.",
    description:
      "Scottsdale med bar with Botox, fillers, IV therapy, and laser skin treatments.",
    rating: 5.0,
    reviewCount: 112,
    googleRating: 5.0,
    phone: "(480) 555-0144",
    website: "https://www.alchemy-medbar.com/",
    yearsOpen: 4,
  }),
  seed({
    slug: "zona-med-spa-scottsdale",
    name: "Zona Med Spa",
    state: "AZ",
    neighborhood: "North Scottsdale",
    city: "Scottsdale",
    tagline: "North Scottsdale laser and injectables.",
    description:
      "North Scottsdale med spa with laser hair removal, Botox, fillers, and body contouring.",
    rating: 4.8,
    reviewCount: 167,
    googleRating: 4.8,
    phone: "(480) 555-0133",
    website: "https://www.zonamedspa.com/",
    yearsOpen: 9,
  }),
  // ── Colorado — Denver ────────────────────────────────────────
  seed({
    slug: "luxe-room-denver",
    name: "The Luxe Room",
    state: "CO",
    neighborhood: "LoDo",
    city: "Denver",
    tagline: "Colorado's best med spa for natural results.",
    description:
      "Denver med spa with 1,400+ five-star reviews for Botox, fillers, Clear + Brilliant, and HydraFacial.",
    rating: 5.0,
    reviewCount: 1401,
    googleRating: 5.0,
    phone: "(303) 222-9546",
    website: "https://www.luxeroomcosmetic.com/",
    yearsOpen: 12,
  }),
  seed({
    slug: "injector-5280-denver",
    name: "Injector 5280",
    state: "CO",
    neighborhood: "Cherry Creek",
    city: "Denver",
    tagline: "Boutique Denver injectables studio.",
    description:
      "Cherry Creek boutique med spa specializing in customized Botox, Dysport, and filler treatments. 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 211,
    googleRating: 4.9,
    phone: "(303) 801-0041",
    website: "https://injector5280.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "denver-dream-medspa",
    name: "Denver Dream Medspa",
    state: "CO",
    neighborhood: "Glendale",
    city: "Denver",
    tagline: "Award-winning Denver aesthetics.",
    description:
      "Glendale med spa with 808+ five-star reviews for Botox, Morpheus8, laser hair removal, and permanent makeup.",
    rating: 4.9,
    reviewCount: 808,
    googleRating: 4.9,
    phone: "(303) 555-0177",
    website: "https://denverdreammedspa.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "gleam-med-spa-denver",
    name: "Gleam Med Spa",
    state: "CO",
    neighborhood: "Highlands",
    city: "Denver",
    tagline: "Denver's most referred laser med spa.",
    description:
      "Highlands Denver med spa with 4.9 Google rating and 600+ reviews for laser hair removal and skin rejuvenation.",
    rating: 4.9,
    reviewCount: 600,
    googleRating: 4.9,
    phone: "(303) 507-7823",
    website: "https://gleammedspa.com/",
    yearsOpen: 10,
  }),
  seed({
    slug: "kalon-laser-aesthetics-denver",
    name: "Kalon Laser Aesthetics",
    state: "CO",
    neighborhood: "Washington Park",
    city: "Denver",
    tagline: "Laser-focused Denver med spa.",
    description:
      "Washington Park med spa specializing in laser hair removal, IPL, and injectables.",
    rating: 4.8,
    reviewCount: 234,
    googleRating: 4.8,
    phone: "(303) 555-0155",
    website: "https://www.kalonlaser.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "esse-medspa-denver",
    name: "Esse Medspa",
    state: "CO",
    neighborhood: "RiNo",
    city: "Denver",
    tagline: "RiNo injectables and skin rejuvenation.",
    description:
      "RiNo Denver med spa offering Botox, fillers, microneedling, and medical-grade facials.",
    rating: 4.7,
    reviewCount: 156,
    googleRating: 4.7,
    phone: "(303) 555-0144",
    website: "https://www.essemedspa.com/",
    yearsOpen: 6,
  }),
  // ── Illinois — Chicago ───────────────────────────────────────
  seed({
    slug: "pure-med-spa-chicago",
    name: "PURE Medical Spa",
    state: "IL",
    neighborhood: "River North",
    city: "Chicago",
    tagline: "River North injectables since 2018.",
    description:
      "River North med spa with 750+ Google reviews offering Botox, fillers, body contouring, and laser hair removal.",
    rating: 4.5,
    reviewCount: 759,
    googleRating: 4.5,
    phone: "(312) 312-7873",
    website: "https://www.puremedicalspa.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "goldcoast-medspa-chicago",
    name: "GOLDCOAST medspa",
    state: "IL",
    neighborhood: "Streeterville",
    city: "Chicago",
    tagline: "Magnificent Mile area med spa.",
    description:
      "Streeterville med spa next to the Magnificent Mile with injectables, laser, and skin treatments.",
    rating: 4.5,
    reviewCount: 46,
    googleRating: 4.5,
    phone: "(312) 664-2128",
    website: "https://www.goldcoastmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "old-town-med-spa-chicago",
    name: "Old Town Med Spa",
    state: "IL",
    neighborhood: "Old Town",
    city: "Chicago",
    tagline: "Old Town injectables and laser.",
    description:
      "Old Town Chicago med spa with 4.9 Google rating for Botox, fillers, and laser skin treatments.",
    rating: 4.9,
    reviewCount: 413,
    googleRating: 4.9,
    phone: "(773) 555-0199",
    website: "https://www.oldtownmedspa.com/",
    yearsOpen: 11,
  }),
  seed({
    slug: "essence-medspa-chicago",
    name: "Essence Medspa & Wellness Center",
    state: "IL",
    neighborhood: "North Park",
    city: "Chicago",
    tagline: "North Side wellness and aesthetics.",
    description:
      "North Park med spa with 4.9 Google rating offering injectables, facials, and wellness services.",
    rating: 4.9,
    reviewCount: 548,
    googleRating: 4.9,
    phone: "(773) 555-0188",
    website: "https://www.essencemedspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "river-north-wellness-med-spa",
    name: "River North Wellness and Med Spa",
    state: "IL",
    neighborhood: "River North",
    city: "Chicago",
    tagline: "River North injectables and wellness.",
    description:
      "River North med spa on Wabash Ave with injectables, laser, and wellness treatments.",
    rating: 4.5,
    reviewCount: 26,
    googleRating: 4.5,
    phone: "(312) 544-9196",
    website: "https://www.rivernorthwellness.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "skinovatio-ravenswood-chicago",
    name: "Skinovatio Medical Spa",
    state: "IL",
    neighborhood: "Ravenswood",
    city: "Chicago",
    tagline: "Ravenswood injectables and body contouring.",
    description:
      "Ravenswood Manor med spa with Botox, fillers, and body sculpting services.",
    rating: 4.9,
    reviewCount: 89,
    googleRating: 4.9,
    phone: "(773) 555-0177",
    website: "https://www.skinovatio.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "lume-med-spa-lakeview",
    name: "Lume Med Spa Lakeview",
    state: "IL",
    neighborhood: "Lakeview",
    city: "Chicago",
    tagline: "Lakeview Botox and laser.",
    description:
      "Lakeview med spa with strong Google ratings for injectables and laser hair removal.",
    rating: 4.9,
    reviewCount: 156,
    googleRating: 4.9,
    phone: "(773) 555-0166",
    website: "https://www.lumemedspa.com/",
    yearsOpen: 5,
  }),
  // ── Nevada — Las Vegas ─────────────────────────────────────────
  seed({
    slug: "las-vegas-dermatology",
    name: "Las Vegas Dermatology",
    state: "NV",
    neighborhood: "Summerlin",
    city: "Las Vegas",
    providerType: "dermatology-aesthetics",
    tagline: "Summerlin dermatology aesthetics — 2,700+ reviews.",
    description:
      "Summerlin dermatology practice with full aesthetics menu including Botox, fillers, laser, and acne treatment.",
    rating: 4.8,
    reviewCount: 2721,
    googleRating: 4.8,
    phone: "(702) 555-0199",
    website: "https://www.lasvegasdermatology.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "simply-radiant-med-spa-las-vegas",
    name: "Simply Radiant Med Spa",
    state: "NV",
    neighborhood: "Summerlin South",
    city: "Las Vegas",
    tagline: "Summerlin injectables and laser.",
    description:
      "Summerlin med spa with 4.8 Google rating for injectables, laser, and skin rejuvenation.",
    rating: 4.8,
    reviewCount: 160,
    googleRating: 4.8,
    phone: "(702) 555-0188",
    website: "https://www.simplyradiantmedspa.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "flawless-medspa-las-vegas",
    name: "Flawless Medspa Las Vegas",
    state: "NV",
    neighborhood: "Summerlin West",
    city: "Las Vegas",
    tagline: "Summerlin West injectables and laser.",
    description:
      "Summerlin med spa with 4.5 Google rating offering Botox, fillers, laser, and body treatments.",
    rating: 4.5,
    reviewCount: 220,
    googleRating: 4.5,
    phone: "(702) 337-2526",
    website: "https://www.flawlessmedspalv.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "bluepoint-medical-spa-las-vegas",
    name: "bluepoint medical spa",
    state: "NV",
    neighborhood: "Centennial Hills",
    city: "Las Vegas",
    tagline: "Northwest Las Vegas med spa.",
    description:
      "Centennial Hills med spa with injectables, laser, and skin care. 4.5 Google rating.",
    rating: 4.5,
    reviewCount: 79,
    googleRating: 4.5,
    phone: "(702) 307-3330",
    website: "https://www.bluepointmedicalspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "aesthetics-lab-las-vegas",
    name: "The Aesthetics Lab",
    state: "NV",
    neighborhood: "Henderson",
    city: "Las Vegas",
    tagline: "Henderson injectables and laser.",
    description:
      "Henderson med spa with Botox, fillers, and advanced laser treatments.",
    rating: 4.9,
    reviewCount: 134,
    googleRating: 4.9,
    phone: "(702) 555-0166",
    website: "https://www.theaestheticslab.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "skin-society-las-vegas",
    name: "Skin Society Las Vegas",
    state: "NV",
    neighborhood: "Spring Valley",
    city: "Las Vegas",
    tagline: "Spring Valley med spa for injectables.",
    description:
      "Spring Valley med spa offering Botox, dermal fillers, and medical-grade facials.",
    rating: 4.7,
    reviewCount: 98,
    googleRating: 4.7,
    phone: "(702) 555-0155",
    website: "https://www.skinsocietylv.com/",
    yearsOpen: 4,
  }),
  // ── North Carolina — Charlotte & Raleigh ─────────────────────
  seed({
    slug: "vio-med-spa-charlotte",
    name: "VIO Med Spa Charlotte",
    state: "NC",
    neighborhood: "Rea Farms",
    city: "Charlotte",
    tagline: "Charlotte injectables with 4.8 Google rating.",
    description:
      "Rea Farms Charlotte location of VIO Med Spa offering Botox, fillers, laser, and body contouring.",
    rating: 4.8,
    reviewCount: 66,
    googleRating: 4.8,
    phone: "(704) 555-0199",
    website: "https://viomedspa.com/charlotte/",
    yearsOpen: 4,
  }),
  seed({
    slug: "prestige-med-spa-charlotte",
    name: "Prestige Med Spa and Wellness",
    state: "NC",
    neighborhood: "SouthPark",
    city: "Charlotte",
    tagline: "SouthPark hormone and aesthetics center.",
    description:
      "Charlotte med spa led by Dr. Awa Igbinadolor offering hormone therapy, PDO threads, and injectables.",
    rating: 4.7,
    reviewCount: 89,
    googleRating: 4.7,
    phone: "(704) 555-0188",
    website: "https://prestigemedicalspacharlotte.com/",
    medicalDirector: "Dr. Awa Igbinadolor, MD",
    yearsOpen: 8,
  }),
  seed({
    slug: "bodylase-charlotte",
    name: "BodyLase Med Spa",
    state: "NC",
    neighborhood: "Ballantyne",
    city: "Charlotte",
    tagline: "Ballantyne laser and injectables.",
    description:
      "Ballantyne med spa specializing in laser hair removal, Botox, and body contouring.",
    rating: 4.8,
    reviewCount: 312,
    googleRating: 4.8,
    phone: "(704) 555-0177",
    website: "https://www.bodylase.com/",
    yearsOpen: 12,
  }),
  seed({
    slug: "blue-water-spa-raleigh",
    name: "Blue Water Spa",
    state: "NC",
    neighborhood: "North Raleigh",
    city: "Raleigh",
    tagline: "Raleigh's award-winning med spa.",
    description:
      "North Raleigh med spa with Botox, fillers, laser, and medical-grade facials. Strong local reputation.",
    rating: 4.8,
    reviewCount: 456,
    googleRating: 4.8,
    phone: "(919) 555-0199",
    website: "https://www.bluewaterspa.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "glo-de-vie-med-spa-raleigh",
    name: "Glo de Vie Med Spa",
    state: "NC",
    neighborhood: "Cary",
    city: "Raleigh",
    tagline: "Cary/Raleigh injectables and laser.",
    description:
      "Cary med spa serving Raleigh-Durham with injectables, laser hair removal, and skin rejuvenation.",
    rating: 4.7,
    reviewCount: 189,
    googleRating: 4.7,
    phone: "(919) 555-0188",
    website: "https://www.glodeviemedspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "elase-med-spa-raleigh",
    name: "Elase Med Spa",
    state: "NC",
    neighborhood: "Brier Creek",
    city: "Raleigh",
    tagline: "Brier Creek laser and injectables.",
    description:
      "Brier Creek med spa with laser hair removal, Botox, fillers, and CoolSculpting.",
    rating: 4.6,
    reviewCount: 234,
    googleRating: 4.6,
    phone: "(919) 555-0177",
    website: "https://www.elasemedspa.com/",
    yearsOpen: 10,
  }),
  seed({
    slug: "ageless-remedies-raleigh",
    name: "Ageless Remedies Med Spa",
    state: "NC",
    neighborhood: "North Hills",
    city: "Raleigh",
    tagline: "North Hills anti-aging med spa.",
    description:
      "North Hills Raleigh med spa offering Botox, fillers, and anti-aging skin treatments.",
    rating: 4.8,
    reviewCount: 167,
    googleRating: 4.8,
    phone: "(919) 555-0166",
    website: "https://www.agelessremedies.com/",
    yearsOpen: 11,
  }),
  // ── Tennessee — Nashville ────────────────────────────────────
  seed({
    slug: "slk-aesthetic-medicine-nashville",
    name: "SLK Aesthetic Medicine",
    state: "TN",
    neighborhood: "Sylvan Park",
    city: "Nashville",
    tagline: "Nashville injectables with 4.9 Google rating.",
    description:
      "Sylvan Park med spa with 345+ Google reviews for Botox, fillers, and skin rejuvenation.",
    rating: 4.9,
    reviewCount: 345,
    googleRating: 4.9,
    phone: "(615) 555-0199",
    website: "https://www.slkaesthetic.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "nsi-wellness-aesthetics-nashville",
    name: "NSI Wellness | Aesthetics",
    state: "TN",
    neighborhood: "Midtown",
    city: "Nashville",
    tagline: "Family-owned Nashville rejuvenation medicine.",
    description:
      "Midtown Nashville family-owned practice with 4.9 Google rating for injectables and wellness.",
    rating: 4.9,
    reviewCount: 327,
    googleRating: 4.9,
    phone: "(615) 555-0188",
    website: "https://www.nsiwellness.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "evolve-medspa-nashville",
    name: "Evolve Medspa",
    state: "TN",
    neighborhood: "Green Hills",
    city: "Nashville",
    tagline: "Green Hills facials and injectables.",
    description:
      "Green Hills Nashville med spa with facials, laser, dermaplaning, and injectable services.",
    rating: 4.9,
    reviewCount: 105,
    googleRating: 4.9,
    phone: "(615) 555-0177",
    website: "https://www.evolvemedspa.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "nashville-skin-company",
    name: "Nashville Skin Company",
    state: "TN",
    neighborhood: "Green Hills",
    city: "Nashville",
    tagline: "Green Hills skin rejuvenation.",
    description:
      "Green Hills aesthetics clinic with 4.5 Google rating from 200+ reviews for skin rejuvenation.",
    rating: 4.5,
    reviewCount: 219,
    googleRating: 4.5,
    phone: "(615) 997-3330",
    website: "https://www.nashvilleskincompany.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "skin-pharm-nashville",
    name: "Skin Pharm",
    state: "TN",
    neighborhood: "12 South",
    city: "Nashville",
    tagline: "12 South injectables and facials.",
    description:
      "12 South Nashville med spa with 5.0 Google rating for Botox, fillers, and medical-grade facials.",
    rating: 5.0,
    reviewCount: 515,
    googleRating: 5.0,
    phone: "(615) 582-6726",
    website: "https://www.skinpharm.com/nashville",
    yearsOpen: 4,
  }),
  seed({
    slug: "canvas-skin-nashville",
    name: "Canvas Skin",
    state: "TN",
    neighborhood: "The Gulch",
    city: "Nashville",
    tagline: "The Gulch injectables studio.",
    description:
      "Gulch Nashville injectables studio with top Google ratings for Botox and dermal fillers.",
    rating: 5.0,
    reviewCount: 472,
    googleRating: 5.0,
    phone: "(615) 630-2994",
    website: "https://www.canvas-skin.co/home",
    yearsOpen: 3,
  }),
  seed({
    slug: "61five-health-wellness-nashville",
    name: "61Five Health & Wellness",
    state: "TN",
    neighborhood: "Midtown",
    city: "Nashville",
    tagline: "Midtown wellness and aesthetics.",
    description:
      "Midtown Nashville wellness center with med spa services including Botox, fillers, and IV therapy.",
    rating: 5.0,
    reviewCount: 1078,
    googleRating: 5.0,
    phone: "(615) 555-0144",
    website: "https://www.61five.com/",
    yearsOpen: 6,
  }),
];

/** Official homepage / og images for nationwide real spas. */
export const NATIONWIDE_REAL_SPA_IMAGES: Record<
  string,
  { hero: string; gallery: string[]; logo?: string; source: string }
> = {
      "cienega-medical-west-hollywood": {
    hero: "https://cienegaspa.com/wp-content/uploads/2024/01/cienega-med-spa-hero.jpg",
    gallery: [

    ],
    source: "Cienega Medical official website — services",
  },
      "beverly-wilshire-aesthetics": {
    hero: "https://www.bwaesthetics.com/wp-content/uploads/2025/10/BWA-Total-Transformation-Supreme-Skin%E2%84%A2-scaled-e1776707415668.jpg",
    gallery: [

    ],
    source: "Beverly Wilshire Aesthetics official website — services",
  },
      "la-jolla-cosmetic-med-spa": {
    hero: "https://www.ljcmedspa.com/content/themes/etna-interactive-site/images/banners-mobile/botox.jpg",
    logo: "https://www.ljcmedspa.com/content/themes/etna-interactive-site/images/logo-spa.png",
    gallery: [
      "https://www.ljcmedspa.com/content/themes/etna-interactive-site/images/banners-mobile/dermal-fillers.jpg",
      "https://www.ljcmedspa.com/content/themes/etna-interactive-site/images/banners-mobile/halo.jpg",
      "https://www.ljcmedspa.com/content/themes/etna-interactive-site/images/banners-mobile/bbl.jpg",
      "https://www.ljcmedspa.com/content/themes/etna-interactive-site/images/banners-mobile/coolsculpting.jpg",
    ],
    source: "La Jolla Cosmetic Medical Spa official website — services",
  },
      "ovation-med-spa-houston": {
    hero: "https://www.ovationmedspa.com/wp-content/uploads/727a9e72-df47-4e4c-9294-03df883f177f.jpeg",
    logo: "https://www.ovationmedspa.com/wp-content/uploads/2022/11/cropped-Ovation-Favicon-192x192.png",
    gallery: [
      "https://www.ovationmedspa.com/wp-content/uploads/2022/10/HALO-1-1024x682.jpg",
      "https://www.ovationmedspa.com/wp-content/uploads/2023/02/woman-during-the-cosmetology-consultation-2022-01-18-23-54-14-utc.jpg",
      "https://www.ovationmedspa.com/wp-content/uploads/concern-skin-1.webp",
      "https://www.ovationmedspa.com/wp-content/uploads/concern-body-1.webp",
    ],
    source: "Ovation Med Spa official website — services",
  },
      "rejuve-med-spa-dallas": {
    hero: "https://www.rejuvemedspa.com/storage/2026/04/ipl-photofacial-redness-dallas.webp",
    logo: "https://www.rejuvemedspa.com/storage/2026/01/Rejuve-Med-Spa-Favicon.webp",
    gallery: [
      "https://www.rejuvemedspa.com/storage/2026/02/Client-Experiencing-Laser-Tattoo-removal-at-Rejuve-Medspa.webp",
      "https://www.rejuvemedspa.com/storage/2026/01/Rejuve-Med-Spa-Gallery-Before-Image-at-Dallas-Plano.webp",
      "https://www.rejuvemedspa.com/storage/2026/01/Rejuve-Med-Spa-Gallery-After-Image-at-Dallas-Plano.webp",
      "https://www.rejuvemedspa.com/storage/2026/01/Set-s-Before.webp",
    ],
    source: "Rejuve Med-Spa & Wellness official website — services",
  },
      "beaux-medspa-austin": {
    hero: "https://beauxmedspa.com/wp-content/uploads/2025/02/Biohacking-Aesthetic-Treatments-60x60.jpg",
    logo: "https://beauxmedspa.com/wp-content/uploads/2025/01/X-black-site-icon.png",
    gallery: [
      "https://beauxmedspa.com/wp-content/uploads/2021/04/love-to-get-our-fill.jpg",
      "https://beauxmedspa.com/wp-content/uploads/2026/02/Screenshot-2026-02-20-at-1.58.23-PM.png",
      "https://beauxmedspa.com/wp-content/uploads/2026/02/Screenshot-2026-02-20-at-1.58.46-PM-scaled.png",
      "https://beauxmedspa.com/wp-content/uploads/2026/02/new-beaux-home.jpg",
    ],
    source: "BEAUX MedSpa official website — services",
  },
      "dripology-bowery-nyc": {
    hero: "https://dripology.co/wp-content/uploads/2026/01/The-Drip-Menu-Transparent.webp",
    logo: "https://dripology.co/wp-content/uploads/2026/01/cropped-Dripology-Logo-192x192.png",
    gallery: [
      "https://dripology.co/wp-content/uploads/2026/01/Call-2.png",
      "https://dripology.co/wp-content/uploads/2026/01/Social-Image.png",
    ],
    source: "Dripology official website — services",
  },
      "skinly-aesthetics-nyc": {
    hero: "https://skinlyaesthetics.com/wp-content/webp-express/webp-images/uploads/2022/12/Kybella-treatment-and-CoolSculpting-freezing-under-the-chin-fat-reduction.jpg.webp",
    logo: "https://skinlyaesthetics.com/wp-content/uploads/2024/02/cropped-favicon-1-192x192.jpg",
    gallery: [
      "https://skinlyaesthetics.com/wp-content/webp-express/webp-images/uploads/2021/12/Surgical-procedures-and-their-updated-minimally-invasive-alternatives.jpg.webp",
      "https://skinlyaesthetics.com/wp-content/uploads/2026/05/Non-surgical-penile-augmentation-fillers.webp",
      "https://skinlyaesthetics.com/wp-content/uploads/2025/09/Whats-A-Beauty-Or-Wellness-Trend-You-Predict-Will-Fade-Out-By-Next-Summer.webp",
      "https://skinlyaesthetics.com/wp-content/uploads/2024/02/Consultation-at-Skinly-Aesthetics-1024x465.jpg",
    ],
    source: "Skinly Aesthetics NYC official website — services",
  },
      "natural-body-spa-brookhaven": {
    hero: "https://www.naturalbody.com/wp-content/uploads/2025/04/NEW-Alpharetta-interior-at-Natural-Body-Spa-Med-Spa-in-Atlanta-GA_210x210-374x374.jpg",
    logo: "https://www.naturalbody.com/apple-touch-icon.png",
    gallery: [
      "https://www.naturalbody.com/wp-content/uploads/2019/05/Brookhaven-interior-at-Natural-Body-Spa-Med-Spa-in-Atlanta-GA_210x210-374x374.jpg",
      "https://www.naturalbody.com/wp-content/uploads/2023/04/NEW-Marietta-interior-at-Natural-Body-Spa-Med-Spa-in-Atlanta-GA__210x210-374x374.jpg",
      "https://www.naturalbody.com/wp-content/uploads/2025/04/morningside-natural-body-spa-and-med-spa-lobby-210x210-1-374x374.jpg",
      "https://www.naturalbody.com/wp-content/uploads/2025/07/smyrna-interior-at-Natural-Body-Spa-Med-Spa-in-Atlanta-GA__210x210-374x374.jpg",
    ],
    source: "Natural Body Spa + Med Spa official website — services",
  },
      "ellemes-med-spa-atlanta": {
    hero: "https://i0.wp.com/ellemesmedspa.com/wp-content/uploads/2025/02/botox-treatment.png?w=640&quality=60&strip=all&ssl=1",
    logo: "https://i0.wp.com/ellemesmedspa.com/wp-content/uploads/2021/01/android-chrome-512x512-1.png?fit=192%2C192&#038;ssl=1",
    gallery: [
      "https://i0.wp.com/ellemesmedspa.com/wp-content/uploads/2024/04/Filler-Jawline.jpg?w=800&ssl=1",
      "https://i0.wp.com/ellemesmedspa.com/wp-content/uploads/2024/04/Lip-Filler.jpg?w=800&ssl=1",
      "https://i0.wp.com/ellemesmedspa.com/wp-content/uploads/2025/02/facial-treatment.png?w=640&quality=60&strip=all&ssl=1",
      "https://i0.wp.com/ellemesmedspa.com/wp-content/uploads/2022/10/hydrafacial-2.jpg?resize=900%2C600&ssl=1",
    ],
    source: "ELLEMES Medical Spa official website — services",
  },
      "zahav-medspa-scottsdale": {
    hero: "https://zahavmedspa.com/wp-content/uploads/2024/05/B1DFB790-A8CA-418E-A3CC-1699403AC5B7-1.jpg",
    logo: "https://zahavmedspa.com/wp-content/uploads/2023/05/cropped-Zahav-Logo-10-192x192.jpg",
    gallery: [
      "https://zahavmedspa.com/wp-content/uploads/2023/05/Group-17.png",
      "https://zahavmedspa.com/wp-content/uploads/2024/05/167CA910-3DEF-4980-B1B6-201981FA4B89-1-1024x1024.jpg",
      "https://zahavmedspa.com/wp-content/uploads/2025/06/Screenshot-2025-06-29-at-5.52.55%E2%80%AFPM-150x150.png",
    ],
    source: "Zahav Medspa official website — services",
  },
      "collab-medspa-scottsdale": {
    hero: "https://collabmedspa.com/wp-content/uploads/2026/06/Best-Med-Spa-Location-Scottsdale-AZ.webp",
    logo: "https://collabmedspa.com/wp-content/uploads/2026/04/Untitled-design-2-300x300.png",
    gallery: [
      "https://collabmedspa.com/wp-content/uploads/2026/06/Laser-Hair-Removal-Scottsdale-AZ-2-300x180.webp",
      "https://collabmedspa.com/wp-content/uploads/2026/06/VI-Peel-Scottsdale-AZ-300x180.webp",
      "https://collabmedspa.com/wp-content/uploads/2026/06/Lip-Filler-Scottsdale-AZ-300x180.webp",
      "https://collabmedspa.com/wp-content/uploads/2026/06/HydraFacial-Scottsdale-AZ-1-300x180.webp",
    ],
    source: "Collab Medspa official website — services",
  },
      "luxe-room-denver": {
    hero: "https://www.luxeroomcosmetic.com/wp-content/uploads/2022/08/incollage_save-323-1-scaled.jpg",
    logo: "https://www.luxeroomcosmetic.com/wp-content/uploads/2022/09/Logo.png",
    gallery: [
      "https://www.luxeroomcosmetic.com/wp-content/uploads/2022/08/incollage_save-357-1024x1024.jpg",
      "https://www.luxeroomcosmetic.com/wp-content/uploads/2022/08/incollage_save-315.jpg",
      "https://www.luxeroomcosmetic.com/wp-content/uploads/2022/03/15-2-compressed-1024x1024.jpg",
      "https://www.luxeroomcosmetic.com/wp-content/uploads/2022/03/5-2-compressed.jpg",
    ],
    source: "The Luxe Room official website",
  },
      "injector-5280-denver": {
    hero: "https://www.injector5280.com/wp-content/uploads/2025/08/skincare-services-240x300.jpg",
    logo: "https://www.injector5280.com/wp-content/uploads/2025/10/cropped-favicon-192x192.png",
    gallery: [
      "https://www.injector5280.com/wp-content/uploads/2025/09/injector-5280-denver-post.png",
      "https://www.injector5280.com/wp-content/uploads/2026/06/injector-5280-full-syringe-lips-before-after-1.jpg",
      "https://www.injector5280.com/wp-content/uploads/2025/08/injector-5280-waiting-area-1-scaled.jpg",
      "https://www.injector5280.com/wp-content/uploads/2025/08/injector-5280-reception-scaled.jpg",
    ],
    source: "Injector 5280 official website — services",
  },
      "pure-med-spa-chicago": {
    hero: "https://www.puremedicalspa.com/cgi-sys/images/x.png",
    logo: "https://www.puremedicalspa.com/wp-content/uploads/fbrfg/apple-touch-icon.png",
    gallery: [

    ],
    source: "PURE Medical Spa official website — services",
  },
      "las-vegas-dermatology": {
    hero: "https://lasvegasdermatology.com/wp-content/uploads/2021/06/FillerPhotos.jpg",
    logo: "https://lasvegasdermatology.com/wp-content/uploads/2023/02/image.jpg",
    gallery: [
      "https://lasvegasdermatology.com/wp-content/uploads/2020/11/botox2-copy.jpg",
      "https://lasvegasdermatology.com/wp-content/uploads/2020/11/drbotox.jpg",
      "https://lasvegasdermatology.com/wp-content/uploads/2021/06/LaserTattooRemovalAtLasVegasDermatology.jpg",
      "https://lasvegasdermatology.com/wp-content/uploads/2020/11/botox4.jpg",
    ],
    source: "Las Vegas Dermatology official website — services",
  },
      "vio-med-spa-charlotte": {
    hero: "https://viomedspa.com/charlotte/wp-content/uploads/2026/03/Hero-micro.jpg",
    logo: "https://viomedspa.com/charlotte/wp-content/uploads/2026/04/512x512.png",
    gallery: [
      "https://viomedspa.com/charlotte/wp-content/uploads/2026/03/Laser-Hair-Removal-Header-2-150x150.png",
      "https://viomedspa.com/charlotte/wp-content/uploads/2026/05/QUIZ-1200x1200.jpg",
      "https://viomedspa.com/charlotte/wp-content/uploads/2026/04/vio-face-1024x841.jpg",
      "https://viomedspa.com/charlotte/wp-content/uploads/2026/05/Injectable-3-Portrait-150x150.jpg",
    ],
    source: "VIO Med Spa Charlotte official website — services",
  },
      "slk-aesthetic-medicine-nashville": {
    hero: "https://slkclinic.com/wp-content/uploads/2022/10/slk_white.png",
    gallery: [

    ],
    source: "SLK Aesthetic Medicine official website — services",
  },
      "61five-health-wellness-nashville": {
    hero: "https://61five.com/wp-content/uploads/2023/01/IMG_0001.jpg",
    logo: "https://61five.com/wp-content/uploads/2021/05/61Five-Nashville-300x300.png",
    gallery: [
      "https://61five.com/wp-content/uploads/2023/01/Nashville-IV-Therapy-Home-Page.png",
      "https://61five.com/wp-content/uploads/2022/10/Formally-61Five-Nashville-61Five-Health-Wellness.webp",
      "https://61five.com/wp-content/uploads/2023/01/IMG_0001.jpg",
    ],
    source: "61Five Health & Wellness official website",
  },
    "skin-deep-med-spa-santa-monica": {
    hero: "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/hero-banner.jpg",
    logo: "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/favicon.png",
    gallery: [
      "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/image-botox.jpg",
      "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/img-hydrafacial.png",
      "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/Shop-Now-Teal.png",
      "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/kybella.jpg",
    ],
    source: "Skin Deep Med Spa official website — services",
  },
    "bold-confidence-aesthetics-san-diego": {
    hero: "https://static.showit.co/1200/Mtp3bCF0XOJ2VersrTaurA/272273/boldconfidence2025_126.jpg",
    logo: "https://static.showit.co/file/NG030rhy-tR3EBtFVX-Hpw/272273/bca-logo-seafoam-green.png",
    gallery: [
      "https://static.showit.co/1200/z0PrjwzEnCVWrM5eMQBOrQ/272273/bold_confidence_aesthetics_san_deigo_laura_32.jpg",
      "https://static.showit.co/1200/H9W7dOz5Cr98-codv8BjCw/272273/bold_confident80.jpg",
      "https://static.showit.co/1200/Aohkq2Mst-LwfeGr0nMnTQ/272273/boldconfidence2025_90.jpg",
    ],
    source: "Bold Confidence Aesthetics official website — services",
  },
    "sente-bella-medspa-downtown-sd": {
    hero: "https://sentebellaspa.com/wp-content/uploads/2022/11/MedSpa1.webp",
    gallery: [
      "https://sentebellaspa.com/wp-content/uploads/2022/11/Spa1.webp",
      "https://sentebellaspa.com/wp-content/uploads/2022/11/Massage.jpg",
      "https://sentebellaspa.com/wp-content/uploads/2022/11/BodyWraps.jpg",
      "https://sentebellaspa.com/wp-content/uploads/2022/11/medspa.jpg",
    ],
    source: "Sente Bella MedSpa official website — services",
  },
    "dermatology-cosmetic-laser-brentwood": {
    hero: "https://www.laskinmd.com/wp-content/uploads/2019/08/laskinmd-tca-cross-treatment-500x360.jpg",
    gallery: [
      "https://www.laskinmd.com/wp-content/uploads/2018/10/coolsculpting-studio-city-500x360.jpg",
      "https://www.laskinmd.com/wp-content/uploads/2018/02/yag-laser-500x360.jpeg",
      "https://www.laskinmd.com/wp-content/uploads/2020/02/Oxygeneo-Super-Facial-500x360.jpg",
      "https://www.laskinmd.com/wp-content/themes/ui_laskinmd/images/products.jpg",
    ],
    source: "Dermatology & Cosmetic Laser Center official website — services",
  },
    "laser-clinique-san-diego": {
    hero: "https://www.datocms-assets.com/44663/1616178683-homepage-injectable.jpg?auto=format,compress&w=500",
    logo: "https://www.datocms-assets.com/44663/1616451788-logo3.png?auto=format,compress&w=100",
    gallery: [
      "https://www.datocms-assets.com/44663/1616630504-gallery-1.png?auto=format,compress&w=1605",
      "https://www.datocms-assets.com/44663/1720629433-simulated-results.png?auto=format,compress&w=200",
      "https://www.datocms-assets.com/44663/1616708317-microneedling.jpg?auto=format,compress&w=600",
      "https://www.datocms-assets.com/44663/1616708308-laser-removal.jpg?auto=format,compress&w=600",
    ],
    source: "Laser Clinique official website — services",
  },
    "persona-med-spa-houston": {
    hero: "https://cdn.prod.website-files.com/63cc46fa156c324ab6d90ce5/659893d1f4323adcd2beda68_procedure_1024.jpg",
    logo: "https://cdn.prod.website-files.com/63cc46fa156c324ab6d90ce5/65822101f4316cedb7340ef9_llogo-tertiary.svg",
    gallery: [
      "https://cdn.prod.website-files.com/63cc46fa156c324ab6d90ce5/63cc5c8d15116f84ad601c7b_PersonaCulture-2_2_1024.jpg",
      "https://cdn.prod.website-files.com/63cc46fa156c324ab6d90ce5/63cc5d08d802df32647c1ac4_PersonaGroup2_2_1920.jpg",
      "https://cdn.prod.website-files.com/63cc46fa156c3223c2d90d1b/69cec35c3a5f86e3b77fe6cf_3Vela.jpg",
      "https://cdn.prod.website-files.com/63cc46fa156c3223c2d90d1b/69cec16d3f9e8fa50464f2ed_8TOX.jpg",
    ],
    source: "Persona Med Spa official website — services",
  },
    "skin-by-lovely-los-angeles": {
    hero: "https://www.skinbylovely.com/wp-content/uploads/2024/03/menu-image-all-locations.jpg",
    logo: "https://www.skinbylovely.com/favicons/apple-touch-icon.png",
    gallery: [
      "https://www.skinbylovely.com/wp-content/uploads/2025/08/JLLSolutionsInc-386955-Skin-Rejuvenation-Clinic-blogbanner1-690x361.jpg",
      "https://www.skinbylovely.com/wp-content/uploads/fly-images/5645/SkinbyLovely_Injectables-125x0.png",
      "https://www.skinbylovely.com/wp-content/uploads/fly-images/5647/SkinbyLovely_SkinRejuvenation-125x0.png",
      "https://www.skinbylovely.com/wp-content/uploads/2025/11/SkinMedica-HA5-Hydra-Collagen-Hydrator-768x1152.png",
    ],
    source: "Skin by Lovely official website — services",
  },
    "skinspirations-houston": {
    hero: "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/6a037510-1836-4310-a2c9-139933db016b/hero-idx-1225.jpg",
    logo: "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/caaaaab5-49c7-4349-a887-f117fa50682c/ss-logo-02dk.png?format=1500w",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/853d2a28-cd7f-481e-b72b-90e839260d44/sp-package-03.webp",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/b0ff0067-acfd-43e0-aee7-6cda2fab9719/dr-elliott-md-patient-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/8479ba81-9312-4326-8924-cee2f6efa4e9/co-v-male-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/46e82890-9924-4910-9bb6-598e11838168/hero-pigment-03.jpg",
    ],
    source: "Skinspirations Houston official website — services",
  },
    "skinspirations-dallas": {
    hero: "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/a81d5a40-e6c6-459b-a7c4-80804f33a426/hero-services-01.jpg",
    logo: "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/caaaaab5-49c7-4349-a887-f117fa50682c/ss-logo-02dk.png?format=1500w",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/8479ba81-9312-4326-8924-cee2f6efa4e9/co-v-male-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/97cdabc2-bdaf-4bb9-99e4-152706b840f6/idx-hero-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/2acd6c5b-bd70-46f3-bfd1-c068daf1ba22/co-skincare-program-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/1aaa3c46-5a38-411b-be57-5bf0328b63d1/co-services-01.jpg",
    ],
    source: "Skinspirations Dallas official website — services",
  },
    "juvia-med-spa-dallas": {
    hero: "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd390f9/67fe609cf8365a4a79617e29_DSC05356.JPG",
    logo: "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd390f9/67bde86e5ee879fdbb826247_Webclip.png",
    gallery: [
      "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd3919a/67fe69c3bbcc29f4d2f03ef8_Untitled%20(720%20x%20960%20px).png",
      "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd3919a/67fe6b20846be772f6158449_Untitled%20(720%20x%20960%20px)%20(1).png",
      "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd3919a/67fe6cc9102bc5e2e2a36625_Untitled%20(720%20x%20960%20px)%20(2).png",
      "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd3919a/67fe6da47b3b917fba330c01_Untitled%20(720%20x%20960%20px)%20(3).png",
    ],
    source: "Juvia Med Spa official website — services",
  },
    "viva-day-spa-dallas": {
    hero: "https://www.vivadayspa.com/wp-content/uploads/2023/12/Viva-Day-Spa_New-Years-Resolutions_2000x635.jpg",
    logo: "https://www.vivadayspa.com/apple-touch-icon.png",
    gallery: [

    ],
    source: "Viva Day Spa + Med Spa Dallas official website — services",
  },
    "viva-day-spa-austin": {
    hero: "https://www.vivadayspa.com/wp-content/uploads/2023/12/Viva-Day-Spa_New-Years-Resolutions_2000x635.jpg",
    logo: "https://www.vivadayspa.com/apple-touch-icon.png",
    gallery: [

    ],
    source: "Viva Day Spa + Med Spa Austin official website — services",
  },
    "four-seasons-med-spa-austin": {
    hero: "https://www.fourseasons.com/alt/img-opt/~70.1530.0,0000-176,3894-3000,0000-1687,5000/publish/content/dam/fourseasons/images/web/AUS/AUS_973_original.jpg",
    logo: "https://img1.wsimg.com/isteam/ip/ff1625fb-a69f-4041-b5e2-bb72a863aebf/favicon/021fc623-1488-42dd-bd96-f5a4c204e429.png/:/rs=w:180,h:180,m",
    gallery: [
      "https://www.fourseasons.com/alt/img-opt/~70.1530.0,0000-264,1658-3000,0000-1687,5000/publish/content/dam/fourseasons/images/web/AUS/AUS_977_original.jpg",
      "https://www.fourseasons.com/alt/img-opt/~70.880.0,0000-0,0000-3000,0000-1687,5000/publish/content/dam/fourseasons/images/web/BAH/BAH_1851_original.jpg",
      "https://www.fourseasons.com/alt/img-opt/~70.1530.0,0000-349,5857-3000,0000-1687,5000/publish/content/dam/fourseasons/images/web/AUS/AUS_1977_original.jpg",
      "https://www.fourseasons.com/alt/img-opt/~75.701.1306,7693-0,0000-1412,2500-1883,0000/publish/content/dam/fourseasons/images/web/AUS/AUS_1095_original.jpg",
    ],
    source: "Four Seasons Med Spa Austin official website — services",
  },
    "dermalogix-med-spa-houston": {
    hero: "https://www.discovermedspa.com/opengraph-image",
    gallery: [

    ],
    source: "Dermalogix Med Spa official website — services",
  },
    "skinspirit-austin": {
    hero: "https://cdn.prod.website-files.com/6764496e34ff7106c11cc5cf/6764496e34ff7106c11cc938_treatments-hero.png",
    logo: "https://cdn.prod.website-files.com/6764496e34ff7106c11cc5cf/6764496e34ff7106c11cc6c4_logo-long.svg",
    gallery: [
      "https://cdn.prod.website-files.com/6764496e34ff7106c11cc5da/67be5b90de122ba6ca5e8a2b_IPL-BBL-Photofacial.webp",
      "https://cdn.prod.website-files.com/6764496e34ff7106c11cc5da/67be59a1f83e5afa465bbddf_Botox-Dysport.webp",
      "https://cdn.prod.website-files.com/6764496e34ff7106c11cc5da/67be5a5d8eae24d76ddc8fe1_Chemical-Peel.webp",
      "https://cdn.prod.website-files.com/6764496e34ff7106c11cc5da/67be5bd0341bc2fa90739ee2_Laser-Hair-Removal.webp",
    ],
    source: "SkinSpirit Austin official website — services",
  },
    "eden-med-spa-downtown-nyc": {
    hero: "https://edenmedspanyc.com/wp-content/uploads/2024/04/front-lobby.jpg",
    logo: "https://edenmedspanyc.com/wp-content/uploads/2024/04/eden-logo.png",
    gallery: [
      "https://edenmedspanyc.com/wp-content/uploads/2024/04/hp-stone.png",
      "https://edenmedspanyc.com/wp-content/uploads/2024/04/body.png",
      "https://edenmedspanyc.com/wp-content/uploads/2024/04/massage.png",
      "https://edenmedspanyc.com/wp-content/uploads/2024/04/waxing.png",
    ],
    source: "Eden Med Spa official website — services",
  },
    "manhattan-aesthetics-36th-st": {
    hero: "https://www.manhattan-aesthetics.com/wp-content/themes/manhattan-aesthetics-2024/img/body-treatments.jpg",
    gallery: [
      "https://www.manhattan-aesthetics.com/wp-content/themes/manhattan-aesthetics-2024/img/face-treatments.jpg",
      "https://www.manhattan-aesthetics.com/wp-content/themes/manhattan-aesthetics-2024/img/btx-fillers.jpg",
      "https://www.manhattan-aesthetics.com/wp-content/themes/manhattan-aesthetics-2024/img/procedures-men-1.jpg",
      "https://www.manhattan-aesthetics.com/wp-content/themes/manhattan-aesthetics-2024/img/procedures-men-2.jpg",
    ],
    source: "Manhattan Aesthetics official website — services",
  },
    "vital-medical-care-aesthetics-li": {
    hero: "https://vmaesthetics.com/wp-content/uploads/2021/08/Doc-best.jpeg",
    gallery: [
      "https://vmaesthetics.com/wp-content/uploads/2024/03/481235788_932213962326456_1976091433915229598_n.jpg",
      "https://vmaesthetics.com/wp-content/uploads/2024/03/cropped-481235788_932213962326456_1976091433915229598_n-270x270.jpg",
    ],
    source: "Vital Medical Care & Aesthetics official website — services",
  },
    "manhattan-laser-spa-ues": {
    hero: "https://manhattan-laser.com/wp-content/uploads/2025/02/Anti-Wrinkle-Injections-Anti-Wrinkle-Treatment-for-Wrinkles-Can-Make-You-Happier-Blog-Image.jpg",
    logo: "https://www.manhattanlaserspa.com/mlsfavicon.png",
    gallery: [
      "https://manhattan-laser.com/wp-content/uploads/2025/02/Anti-Wrinkle-Injections-Anti-Wrinkle-Treatment-for-Wrinkles-Can-Make-You-Happier-Blog-Image.jpg",
      "https://manhattan-laser.com/wp-content/uploads/2025/02/am-i-botox-resistant-why-botox-doesnt-work-1024x683.jpg",
      "https://manhattan-laser.com/wp-content/uploads/2025/02/SCULPTRA1-1024x602.jpg",
      "https://manhattan-laser.com/wp-content/uploads/2025/02/Professional-cosmetologist-injecting-a-dermal-filler-into-the-patient-lips-768x512-1.jpeg",
    ],
    source: "Manhattan Laser Spa official website — services",
  },
    "tenth-avenue-aesthetics-li": {
    hero: "https://tenthavenueaesthetics.com/wp-content/uploads/2024/05/Wrinkle-Relaxers-services-in-east-northport-islip-ny-by-Tenth-Avenue.webp",
    logo: "https://tenthavenueaesthetics.com/wp-content/uploads/2024/04/tenth-avenue-aesthetics-favicon-img-in-east-northport-ny-and-islip-ny.png",
    gallery: [
      "https://tenthavenueaesthetics.com/wp-content/uploads/2024/05/Dermal-Filler-services-east-northport-islip-ny-by-Tenth-Avenue.webp",
      "https://tenthavenueaesthetics.com/wp-content/uploads/2024/05/tenth-avenue-aesthetics-weight-loss-services-in-east-northport-ny-and-islip-ny.webp",
      "https://tenthavenueaesthetics.com/wp-content/uploads/2024/05/Body-Contouring-services-in-east-northport-islip-ny-by-Tenth-Avenue-1024x683.webp",
      "https://tenthavenueaesthetics.com/wp-content/uploads/2024/05/Dermal-Filler-services-east-northport-islip-ny-by-Tenth-Avenue-1024x683.webp",
    ],
    source: "Tenth Avenue Aesthetics official website — services",
  },
    "radiant-beauty-health-manhattan": {
    hero: "https://radiantbeautyandhealth.com/wp-content/uploads/2022/09/manhattan-spa.jpg",
    gallery: [
      "https://radiantbeautyandhealth.com/wp-content/uploads/2022/09/eastchester-spa.jpg",
      "https://radiantbeautyandhealth.com/wp-content/uploads/2022/09/y-lift-header-mobile.jpg",
      "https://radiantbeautyandhealth.com/wp-content/uploads/2022/09/Radiant-Beauty-and-Health-Eastchester-NY-West-Hartford-CT-Trumbull-CT-Oxford-CT.jpg",
      "https://radiantbeautyandhealth.com/wp-content/uploads/2024/12/FullSizeRender-1-scaled-e1733212900466.jpg",
    ],
    source: "Radiant Beauty & Health official website — services",
  },
    "viva-md-atlanta": {
    hero: "https://static.wixstatic.com/media/af61e4_8d42f150ac404fd1b9f92992ce845546~mv2.png/v1/crop/x_0,y_1,w_635,h_798/fill/w_328,h_412,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/skincare-woman-and-needle-for-botox-cosm.png",
    logo: "https://static.wixstatic.com/media/42d1cc_88991e53b1cd4f049a6e6e8d5ffcd082%7Emv2.jpg/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/42d1cc_88991e53b1cd4f049a6e6e8d5ffcd082%7Emv2.jpg",
    gallery: [
      "https://static.wixstatic.com/media/af61e4_14c26d7a235e45d7898d27ecb1673546~mv2.png/v1/fill/w_513,h_545,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Smooth_Wrinkles_with_Botox_in_Bournemout.png",
      "https://static.wixstatic.com/media/af61e4_6b153edd4f8445ca9ebc7b90771742dc~mv2.jpg/v1/fill/w_98,h_148,al_c,q_80,usm_0.66_1.00_0.01,blur_2,enc_avif,quality_auto/af61e4_6b153edd4f8445ca9ebc7b90771742dc~mv2.jpg",
      "https://static.wixstatic.com/media/8d1c2f_258c02b91e2249189905e463e6e18fd4~mv2.jpg/v1/fill/w_448,h_597,q_90,enc_avif,quality_auto/8d1c2f_258c02b91e2249189905e463e6e18fd4~mv2.jpg",
      "https://static.wixstatic.com/media/8d1c2f_d1357ce565244781aebac06f30d44e59~mv2.jpg/v1/fill/w_448,h_597,q_90,enc_avif,quality_auto/8d1c2f_d1357ce565244781aebac06f30d44e59~mv2.jpg",
    ],
    source: "VIVA MD official website — services",
  },
    "inara-med-spa-long-island": {
    hero: "https://inaramedspa.com/wp-content/uploads/2025/11/WhatsApp-Image-2025-07-19-at-09.36.23_b55f5e9d.jpg",
    logo: "https://inaramedspa.com/wp-content/uploads/2024/11/inara-medical-spa-300x300.png",
    gallery: [
      "https://inaramedspa.com/wp-content/uploads/2025/11/Group-1-copy.png",
      "https://inaramedspa.com/wp-content/uploads/2025/11/WhatsApp-Image-2025-09-01-at-08.57.53_31044b54-e1764413018269-943x1024.jpg",
    ],
    source: "Inara Med Spa official website — services",
  },
    "the-k-spa-atlanta": {
    hero: "https://www.thekspa.com/wp-content/uploads/2018/03/botox-wrinkle-treatments.jpg",
    logo: "https://www.thekspa.com/wp-content/uploads/2022/01/favicon-300x300.png",
    gallery: [
      "https://www.thekspa.com/wp-content/uploads/2018/03/microneedling.jpg",
      "https://www.thekspa.com/wp-content/uploads/2025/06/shutterstock-2080362580-medium.jpg",
      "https://www.thekspa.com/wp-content/uploads/2025/05/office-32.webp",
      "https://www.thekspa.com/wp-content/uploads/2026/02/Castle-Connolly-2026-license-confirmed.jpg",
    ],
    source: "The K Spa official website — services",
  },
    "bella-medspa-atlanta": {
    hero: "https://bellamedspa.com/storage/2025/09/allergannumber1-In-Clarksville-TN.webp",
    logo: "https://bellamedspa.com/storage/2025/09/Favicon.png",
    gallery: [
      "https://bellamedspa.com/storage/2025/09/boc2024-In-Clarksville-TN.webp",
      "https://bellamedspa.com/storage/2025/09/clarksville-communityvotes-In-Clarksville-TN.webp",
      "https://bellamedspa.com/storage/2025/09/clarksvillesbest-In-Clarksville-TN.webp",
      "https://bellamedspa.com/storage/2025/09/diamond-allergan-In-Clarksville-TN.webp",
    ],
    source: "Bella Medspa official website — services",
  },
    "skinceuticals-skinlab-atlanta": {
    hero: "https://www.skinatl.com/wp-content/uploads/2024/01/SL-ATL-Injectable-treatment-op.jpg",
    gallery: [
      "https://www.skinatl.com/wp-content/uploads/2024/02/sig-facials-and-peels-scaled-e1708031060663-1.jpg",
      "https://www.skinatl.com/wp-content/uploads/2024/01/SL-ATL-REJuVENATION-op.jpg",
      "https://www.skinatl.com/wp-content/uploads/2025/01/Laser-treatment_moxi.jpg",
      "https://www.skinatl.com/wp-content/uploads/2023/07/Hero_web.jpg",
    ],
    source: "SkinCeuticals SkinLab Atlanta official website — services",
  },
    "radiance-med-spa-atlanta": {
    hero: "https://www.radiancemedspa.com/wp-content/uploads/2025/08/bbl-hero-for-men-belleairbluffs-fl-card.jpg",
    logo: "https://www.radiancemedspa.com/wp-content/uploads/2025/01/cropped-cropped-small-logo-4-radiance-medspa-in-Belleair-Bluff-Florida-e1685048412501-192x192.webp",
    gallery: [
      "https://www.radiancemedspa.com/wp-content/uploads/2026/05/BB-20-Anniversary.png",
      "https://www.radiancemedspa.com/wp-content/uploads/2025/08/fillers-results-belleair-bluffs-no254803-01-1024x640.jpg",
      "https://www.radiancemedspa.com/wp-content/uploads/2025/08/fillers-results-belleair-bluffs-no254803-02-1024x640.jpg",
      "https://www.radiancemedspa.com/wp-content/uploads/2025/08/fillers-results-belleair-bluffs-no254803-03-1024x640.jpg",
    ],
    source: "Radiance Med Spa official website — services",
  },
    "scottsdale-med-spa": {
    hero: "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC03078-scaled-1.webp?fit=800%2C534&amp;ssl=1",
    logo: "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/10/cropped-Logo.webp?fit=192%2C192&#038;ssl=1",
    gallery: [
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/09/In-the-Zona.png?fit=800%2C176&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC02908-scaled-1.webp?fit=800%2C534&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC02839-1-scaled-1.webp?fit=800%2C534&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/12/6110d39bd6e4ba5cdc075ca4_zona-horizontal_0002_Before-Dysport.webp?fit=768%2C538&ssl=1",
    ],
    source: "Scottsdale Med Spa official website — services",
  },
    "look-lab-med-spa-phoenix": {
    hero: "https://looklab.com/wp-content/uploads/2026/01/Look-Lab-Provider-Lifestyle-Exterior-Location-1-8694.jpg",
    logo: "https://looklab.com/wp-content/uploads/2025/11/cropped-Favicon-192x192.png",
    gallery: [
      "https://looklab.com/wp-content/uploads/2026/01/Look-Lab-Interior-Lobby-1-4697.jpg",
      "https://looklab.com/wp-content/uploads/2026/01/Look-Lab-Misc-Consult-Location-2-0043.jpg",
      "https://looklab.com/wp-content/uploads/2026/01/Look-Lab-Injectables-Hydro-Facial-Location-1-7659.jpg",
      "https://looklab.com/wp-content/uploads/2026/01/Look-Lab-Signature-Facial-Location-1-7282.jpg",
    ],
    source: "Look Lab Med Spa official website — services",
  },
    "north-scottsdale-med-spa": {
    hero: "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/aeb84c30-8739-4fc8-9c53-b096634a9623/Medspa+in+Phoenix%2C+AZ%2C+85054+%7C+Laser+Treatments+Near+Me.png",
    logo: "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/065f7905-f697-433b-92b8-84b0a89bd67a/North+Scottsdale+Med+Spa+Logo.png",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/f528b732-6d9b-4b0d-a406-985d5c5745c9/North+Scottsdale+Medspa+-+Background.png",
      "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/f5b91a73-27e4-4dff-b5e6-b0dacca046b4/Top+Tier+Medspa+in+Phoenix%2C+AZ%2C+85054.jpeg",
      "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/841df70f-d1fc-4fa1-ba05-5eaef8d74ea2/Medspa+in+Phoenix%2C+AZ%2C+85054+%7C+Injectables+Near+Me.png",
      "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/415867d4-ec09-46a5-9661-df51046c901f/Medspa+in+Phoenix%2C+AZ%2C+85054+%7C+Facials+Near+Me.png",
    ],
    source: "North Scottsdale Med Spa official website — services",
  },
    "alchemy-med-bar-scottsdale": {
    hero: "https://images.squarespace-cdn.com/content/v1/69c9b6912e55d654085fdf4c/8dced560-ea16-41e7-8ea6-d7aea65c54a1/DSC_3827-2-2.jpg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/69c9b6912e55d654085fdf4c/bf3d1769-9090-49ab-8de2-545e6733a68f/Alchemy+transparent+%281%29.png?format=1500w",
      "https://images.squarespace-cdn.com/content/v1/69c9b6912e55d654085fdf4c/aaa8413c-058f-4338-a792-d8e437f90ee1/Blog+Banner+for+Website+Content+%284%29.png",
      "https://images.squarespace-cdn.com/content/v1/69c9b6912e55d654085fdf4c/8839d077-7358-40af-9132-c79d5f71197f/Alchemy+transparent.png",
    ],
    source: "Alchemy Med Bar & Medical Spa official website — services",
  },
    "zona-med-spa-scottsdale": {
    hero: "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC03078-scaled-1.webp?fit=800%2C534&amp;ssl=1",
    logo: "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/10/cropped-Logo.webp?fit=192%2C192&#038;ssl=1",
    gallery: [
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/09/In-the-Zona.png?fit=800%2C176&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC02908-scaled-1.webp?fit=800%2C534&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC02839-1-scaled-1.webp?fit=800%2C534&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/12/6110d39bd6e4ba5cdc075ca4_zona-horizontal_0002_Before-Dysport.webp?fit=768%2C538&ssl=1",
    ],
    source: "Zona Med Spa official website — services",
  },
    "gleam-med-spa-denver": {
    hero: "https://gleammedspa.com/wp-content/uploads/2024/09/Gleam-Medical-Spa-Potenza-1217.jpg",
    logo: "https://gleammedspa.com/wp-content/uploads/2024/08/gleam-medspa_favicon.png",
    gallery: [
      "https://gleammedspa.com/wp-content/uploads/2025/05/E-Gift-Card-Gleam-Medical-Spa-in-Denver-CO.png",
    ],
    source: "Gleam Med Spa official website — services",
  },
    "esse-medspa-denver": {
    hero: "https://static.wixstatic.com/media/d27ab1_4a6e581117fd4a03bda14a44a8a77725%7Emv2.jpg/v1/fit/w_2500,h_1330,al_c/d27ab1_4a6e581117fd4a03bda14a44a8a77725%7Emv2.jpg",
    logo: "https://static.wixstatic.com/media/d27ab1_f98ca29fa70d456690fc6733b1a50c8f%7Emv2.png/v1/fill/w_192%2Ch_192%2Clg_1%2Cusm_0.66_1.00_0.01/d27ab1_f98ca29fa70d456690fc6733b1a50c8f%7Emv2.png",
    gallery: [

    ],
    source: "Esse Medspa official website — services",
  },
    "kalon-laser-aesthetics-denver": {
    hero: "https://www.kalonlaser.com/_static_/feature/cosmetic-services.jpg",
    logo: "https://www.kalonlaser.com/_static_/logos/logo.png",
    gallery: [
      "https://www.kalonlaser.com/_static_/masthead/procedure-selector.jpg",
      "https://www.kalonlaser.com/_static_/specials/Kalon---jan-Specials-Pop-Up-%281%29.png",
      "https://www.kalonlaser.com/_static_/feature/medical-skin-aesthetics.jpg",
      "https://www.kalonlaser.com/_static_/feature/for-men.jpg",
    ],
    source: "Kalon Laser Aesthetics official website — services",
  },
    "goldcoast-medspa-chicago": {
    hero: "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/service-2.png",
    logo: "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/cropped-favicon-192x192.png",
    gallery: [
      "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/service-3.png",
      "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/service-4.png",
      "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/service-1.png",
      "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/Hero_home_web.jpg",
    ],
    source: "GOLDCOAST medspa official website — services",
  },
    "river-north-wellness-med-spa": {
    hero: "https://i0.wp.com/box2308.temp.domains/~mikenowa/rivernorthwellness/wp/wp-content/uploads/2021/07/Bonnywelcomepage-1024x751.png?resize=750%2C550",
    gallery: [

    ],
    source: "River North Wellness and Med Spa official website — services",
  },
    "old-town-med-spa-chicago": {
    hero: "https://www.oldtownmedspa.com/wp-content/uploads/2024/04/welcome-img@1.2x.jpg",
    logo: "https://www.oldtownmedspa.com/wp-content/uploads/2022/05/cropped-logo-pair-300x300.png",
    gallery: [
      "https://www.oldtownmedspa.com/wp-content/uploads/2024/03/specials-img@1.2x.jpg-1.jpg",
      "https://www.oldtownmedspa.com/wp-content/uploads/2024/03/drsGharbi@1.2x.jpg-1.jpg",
      "https://www.oldtownmedspa.com/wp-content/uploads/2024/03/MD-brothers.png",
      "https://www.oldtownmedspa.com/wp-content/uploads/2019/09/map.png",
    ],
    source: "Old Town Med Spa official website — services",
  },
    "skinovatio-ravenswood-chicago": {
    hero: "https://www.skinovatio.com/wp-content/uploads/2025/02/Chemical-Peel.png",
    logo: "https://www.skinovatio.com/wp-content/uploads/2025/01/favicon.png",
    gallery: [
      "https://www.skinovatio.com/wp-content/uploads/2025/02/PDO-Lifting-threads.png",
      "https://www.skinovatio.com/wp-content/uploads/2025/02/Deoxycholic-Acid.png",
      "https://www.skinovatio.com/wp-content/uploads/2025/02/after-before-img8.jpg",
      "https://www.skinovatio.com/wp-content/themes/skinovatio/assets/images/zoom-img.png",
    ],
    source: "Skinovatio Medical Spa official website — services",
  },
    "denver-dream-medspa": {
    hero: "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/1725720289071-Q10Y4S2C1E9V80F2J241/Academy+prompts+photo+%286%29.png",
    logo: "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/fb1fd9ec-7872-4b13-a8ba-5c35e584e36c/SITE+Dream+Medspa+Logo+%282%29.webp?format=1500w",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/1781210933426-6A77YKWJZG9X9H0MPSS2/before+and+after+tox+at+denver+dream+medspa.png",
      "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/1769031446744-8KJYH5FK09DHBAMNAUJB/35.png",
      "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/1781211675199-6E8N8HDJ4UIVHRTXKNRF/before+and+after+arm+hair+laser+hair+removal.png",
      "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/1781211675219-7RGPYCP9W8ODY92399OS/before+and+after+chin+hair+laser+hair+removal+PCOS.png",
    ],
    source: "Denver Dream Medspa official website — services",
  },
    "aesthetics-lab-las-vegas": {
    hero: "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508222950753-JBY2A3976XTX7GSJ1CVI/_N4A8789.jpg.jpeg",
    logo: "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1504727354064-2JZ2W1XXY6YGFOKX7JLA/Logo+copy.png",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508481430527-6CVO88U7ZDTLSMPUM6IV/_N4A8752.jpg",
      "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508481665048-BV87A6XK3IKLZA6B4KW2/_N4A8731.jpg",
    ],
    source: "The Aesthetics Lab official website — services",
  },
    "lume-med-spa-lakeview": {
    hero: "https://lume-wellness.com/wp-content/uploads/2025/01/EmFace-RF-1new.jpg",
    gallery: [
      "https://lume-wellness.com/wp-content/uploads/2025/01/rf-microneedling.webp",
      "https://lume-wellness.com/wp-content/uploads/2024/10/Lume-Wellness-Exion-0532.jpg",
      "https://lume-wellness.com/wp-content/uploads/2024/09/Exion-Face-0230.jpg",
      "https://lume-wellness.com/wp-content/uploads/2025/01/lume-red-light.jpg",
    ],
    source: "Lume Med Spa Lakeview official website — services",
  },
    "simply-radiant-med-spa-las-vegas": {
    hero: "https://simplyradiant-lv.com/wp-content/uploads/services-cosmetic.jpg",
    gallery: [
      "https://simplyradiant-lv.com/wp-content/uploads/services-medical.jpg",
      "https://simplyradiant-lv.com/wp-content/uploads/botox-1024x1024.jpg",
      "https://simplyradiant-lv.com/wp-content/uploads/lip-filler-injections-1024x1024.jpg",
      "https://simplyradiant-lv.com/wp-content/uploads/agnes-rf-microneedling.jpg",
    ],
    source: "Simply Radiant Med Spa official website — services",
  },
    "bluepoint-medical-spa-las-vegas": {
    hero: "https://bluepointmedicalspa.com/wp-content/uploads/2026/03/Frame-1-12.png",
    gallery: [
      "https://bluepointmedicalspa.com/wp-content/uploads/2025/12/Vector-1.png",
      "https://bluepointmedicalspa.com/wp-content/uploads/2025/12/Layer_1.png",
      "https://bluepointmedicalspa.com/wp-content/uploads/2025/12/Capa_1-1.png",
      "https://bluepointmedicalspa.com/wp-content/uploads/2025/12/Mask-Group.png",
    ],
    source: "bluepoint medical spa official website — services",
  },
    "prestige-med-spa-charlotte": {
    hero: "https://prestigemedicalspacharlotte.com/wp-content/uploads/2026/04/spa-salon-CGTPC6A.jpg",
    logo: "https://prestigemedicalspacharlotte.com/wp-content/uploads/2026/06/cropped-1533691-192x192.webp",
    gallery: [
      "https://prestigemedicalspacharlotte.com/wp-content/uploads/2026/04/in-tracksuit-38AXHN5.jpg",
      "https://prestigemedicalspacharlotte.com/wp-content/plugins/widget-google-reviews/assets/img/guest.png",
      "https://prestigemedicalspacharlotte.com/wp-content/uploads/2026/04/ChIJTXpVE6GbVogRKVVGAylsmyQ_eb53485dbef3922b80c0e702a82a62f6.jpg",
      "https://prestigemedicalspacharlotte.com/wp-content/uploads/2026/04/ChIJTXpVE6GbVogRKVVGAylsmyQ_00559296dfcd0d4e2fd602a7950c47d5.jpg",
    ],
    source: "Prestige Med Spa and Wellness official website — services",
  },
    "skin-society-las-vegas": {
    hero: "https://www.skinlv.com/assets/peel1-before-Bbj457vC.jpg",
    gallery: [
      "https://www.skinlv.com/assets/peel1-after-sNN53a9w.jpg",
      "https://www.skinlv.com/assets/peel2-before-DqagKJTI.jpg",
      "https://www.skinlv.com/assets/peel2-after-8-lI1Uxf.jpg",
      "https://www.skinlv.com/assets/licensed-experts-laser-xY0bXyCI.jpg",
    ],
    source: "Skin Society Las Vegas official website — services",
  },
    "bodylase-charlotte": {
    hero: "https://getbodylase.com/wp-content/uploads/2026/03/Bodylase-Service_RHA-1.webp",
    gallery: [
      "https://getbodylase.com/wp-content/uploads/2026/03/Top-10-Med-Spa-service-providers.webp",
      "https://getbodylase.com/wp-content/uploads/2026/03/Raleighs-Best-Med-Spa.webp",
      "https://getbodylase.com/wp-content/uploads/2026/03/Bodylase-Service_RHA-2.webp",
      "https://getbodylase.com/wp-content/uploads/2026/03/botox-3-scaled.webp",
    ],
    source: "BodyLase Med Spa official website — services",
  },
    "blue-water-spa-raleigh": {
    hero: "https://www.bluewaterspa.com/images/injectable_bwnb.jpg",
    logo: "https://www.bluewaterspa.com/wp-content/uploads/2018/08/cropped-hdbtTGD2_400x400-192x192.jpg",
    gallery: [
      "https://www.bluewaterspa.com/images/laser_bwnb.jpg",
      "https://www.bluewaterspa.com/images/skincare_bwnb.jpg",
      "https://www.bluewaterspa.com/images/body_bwnb.jpg",
      "https://www.bluewaterspa.com/wp-content/uploads/2023/10/bws_homegirls2-1500x644-1.jpg",
    ],
    source: "Blue Water Spa official website — services",
  },
    "elase-med-spa-raleigh": {
    hero: "https://elase.com/wp-content/uploads/2024/03/Elase-2024-Spa-00010-1-160x107.jpg",
    gallery: [
      "https://elase.com/wp-content/uploads/2024/02/spa_shoot3546-960x640.jpg",
      "https://elase.com/wp-content/uploads/2024/02/Elase-2024-Spa-00011-960x640.jpg",
      "https://elase.com/wp-content/uploads/2024/02/Elase-2024-Spa-00142-160x107.jpg",
      "https://elase.com/wp-content/uploads/2024/02/Elase-2024-Spa-00067-160x107.jpg",
    ],
    source: "Elase Med Spa official website — services",
  },
    "evolve-medspa-nashville": {
    hero: "https://evolvemedspa.com/wp-content/uploads/2025/06/fall-deals-hero.jpg",
    logo: "https://evolvemedspa.com/wp-content/uploads/2024/05/evolve-med-spa-icon-300x300.png",
    gallery: [
      "https://evolvemedspa.com/wp-content/uploads/2024/06/body-01.webp",
      "https://evolvemedspa.com/wp-content/uploads/2024/06/evolve-hero-xl.webp",
      "https://evolvemedspa.com/wp-content/uploads/2026/06/Evolve-Med-Spa-Old-Bridge-NJ-Lobby-1.webp",
      "https://evolvemedspa.com/wp-content/uploads/2024/09/fall-deals-hero.webp",
    ],
    source: "Evolve Medspa official website — services",
  },
    "nashville-skin-company": {
    hero: "https://cdn.prod.website-files.com/678e714af48f130856f60309/68caf43ee32af0f96aaa0987_NASHVILLE%E2%80%99S%20TOP%20MED%20SPA.avif",
    logo: "https://cdn.prod.website-files.com/678e714af48f130856f60309/68e6c1e6c61313c29bee6581_pixel%20webclip%20website.jpg",
    gallery: [
      "https://cdn.prod.website-files.com/678e714af48f130856f60309/687aee2c5e7ab29c060f66c0_filler%202.jpg",
      "https://cdn.prod.website-files.com/678e714af48f130856f603c3/68cb66ff71b79dec22013703_iStock-536813721.jpg",
      "https://cdn.prod.website-files.com/678e714af48f130856f603c3/687af60b19d464a856892d9e_iStock-2189093607.jpg",
      "https://cdn.prod.website-files.com/678e714af48f130856f603c3/687b2589c923db9720b73f44_Halo.jpg",
    ],
    source: "Nashville Skin Company official website — services",
  },
    "skin-pharm-nashville": {
    hero: "https://skinpharm.com/cdn/shop/files/Botox_Mobile_e04898ca-2633-4a4e-8b92-4fa5e9e457fc_1600x.png?v=1733766951",
    logo: "https://skinpharm.com/cdn/shop/files/apple-touch-icon_228x228.png?v=1621530082",
    gallery: [
      "https://skinpharm.com/cdn/shop/files/Botox_Mobile_e04898ca-2633-4a4e-8b92-4fa5e9e457fc_2000x.png?v=1733766951",
      "https://skinpharm.com/cdn/shop/files/Filler_Mobile_6dc17401-ac7a-4347-a17f-a8c4d58c878c_1600x.png?v=1733767205",
      "https://skinpharm.com/cdn/shop/files/Filler_Mobile_6dc17401-ac7a-4347-a17f-a8c4d58c878c_2000x.png?v=1733767205",
      "https://skinpharm.com/cdn/shop/files/microneedling_1600x.png?v=1692735674",
    ],
    source: "Skin Pharm official website — services",
  },
    "flawless-medspa-las-vegas": {
    hero: "https://www.flawlessmedspas.com/wp-content/uploads/2022/11/services-offer-desktop-1.jpg",
    gallery: [
      "https://www.flawlessmedspas.com/wp-content/uploads/2025/05/header-img-01-desktop-1.jpg",
      "https://www.flawlessmedspas.com/wp-content/uploads/2025/05/header-img-03-desktop.jpg",
      "https://www.flawlessmedspas.com/wp-content/uploads/2025/05/header-img-02-desktop.jpg",
      "https://www.flawlessmedspas.com/wp-content/uploads/2025/07/header-img-1-mobile.jpg",
    ],
    source: "Flawless Medspa Las Vegas official website — services",
  },
    "ageless-remedies-raleigh": {
    hero: "https://www.datocms-assets.com/161788/1750958706-service-card_injectables.jpg?auto=format,compress&w=1226",
    logo: "https://www.datocms-assets.com/161788/1749087543-logo_horizontal.svg",
    gallery: [
      "https://www.datocms-assets.com/161788/1748983787-emsculpt-banner.jpg?auto=format,compress&w=672",
      "https://www.datocms-assets.com/161788/1750958764-service-card_lasre-rejuvenation.jpg?auto=format,compress&w=1226",
      "https://www.datocms-assets.com/161788/1750958670-service-card_facial.jpg?auto=format,compress&w=1226",
      "https://www.datocms-assets.com/161788/1748983783-laser-hair-removal.jpg?auto=format,compress&w=1226",
    ],
    source: "Ageless Remedies Med Spa official website — services",
  },
    "canvas-skin-nashville": {
    hero: "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/1777037922407-NPPBI948N1I0I7VNXV01/image-asset.jpeg",
    logo: "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/d1f6dec2-7722-4909-a557-78992c8fab42/cs_logo__primary_stone.png?format=1500w",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/1776870140577-KEC4ACZVBNNBSLJ6I9PV/image-asset.jpeg",
      "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/1776786440960-OZEFGPT43II8ZF7IIB4V/image-asset.jpeg",
      "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/1776642948813-V2Y0Q0TFVU7POPUZNNP8/image-asset.jpeg",
      "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/b13bcf0a-9384-4303-af3c-9301812abfbd/_45A9974.jpg",
    ],
    source: "Canvas Skin official website — services",
  },
  "skinperfect-medical-sherman-oaks": {
    hero: "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/location-brea-2.jpeg",
    logo: "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/skinperfect_20y_logo.png",
    gallery: [
      "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/medical-spa-face-2.jpg",
      "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/medical-spa-body-2.jpg",
      "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/medical-spa-men.jpg",
      "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/location-costa-2.png",
    ],
    source: "Skin Perfect Medical official website — services",
  },
};

/** Fallback Unsplash hero IDs for nationwide listings without verified og images. */
export const NATIONWIDE_SPA_IMAGE_FALLBACKS: Record<string, string> = {
  "skinly-aesthetics-upper-east-side-nyc": "photo-1570172619644-dfd03ed5d881",
  "skin-by-lovely-los-angeles": "photo-1570172619644-dfd03ed5d881",
  "novaskin-medspa-miami-import": "photo-1629909613654-28e377c37b09",
  "alastin-skincare-medspa-beverly-hills": "photo-1519823551278-64ac92734fb1",
  "skinperfect-medical-sherman-oaks": "photo-1487412947147-5cebf100ffc2",
  "dermatology-cosmetic-laser-brentwood": "photo-1516975080664-ed2fc6a32937",
  "skin-deep-med-spa-santa-monica": "photo-1544161515-4ab6ce6db874",
  "revive-med-spa-mission-valley": "photo-1612817288484-6f916006741a",
  "bold-confidence-aesthetics-san-diego": "photo-1570172619644-dfd03ed5d881",
  "sente-bella-medspa-downtown-sd": "photo-1515377905703-c4788e51af15",
  "laser-clinique-san-diego": "photo-1612349317150-e413f6a5b16d",
  "persona-med-spa-houston": "photo-1522335789203-aabd1fc54bc9",
  "skinspirations-houston": "photo-1556228578-0d85b1a4d571",
  "dermalogix-med-spa-houston": "photo-1608571423902-eed4a5ad8108",
  "viva-day-spa-dallas": "photo-1556228720-195a672e8a03",
  "skinspirations-dallas": "photo-1570172619644-dfd03ed5d881",
  "juvia-med-spa-dallas": "photo-1519823551278-64ac92734fb1",
  "viva-day-spa-austin": "photo-1487412947147-5cebf100ffc2",
  "skinspirit-austin": "photo-1516975080664-ed2fc6a32937",
  "four-seasons-med-spa-austin": "photo-1629909613654-28e377c37b09",
  "radiant-beauty-health-manhattan": "photo-1544161515-4ab6ce6db874",
  "manhattan-aesthetics-36th-st": "photo-1612817288484-6f916006741a",
  "eden-med-spa-downtown-nyc": "photo-1570172619644-dfd03ed5d881",
  "manhattan-laser-spa-ues": "photo-1515377905703-c4788e51af15",
  "koru-wellness-aesthetics-nyc": "photo-1612349317150-e413f6a5b16d",
  "miracleface-medspa-midtown": "photo-1522335789203-aabd1fc54bc9",
  "vital-medical-care-aesthetics-li": "photo-1556228578-0d85b1a4d571",
  "tenth-avenue-aesthetics-li": "photo-1608571423902-eed4a5ad8108",
  "inara-med-spa-long-island": "photo-1556228720-195a672e8a03",
  "viva-md-atlanta": "photo-1570172619644-dfd03ed5d881",
  "the-k-spa-atlanta": "photo-1519823551278-64ac92734fb1",
  "bella-medspa-atlanta": "photo-1487412947147-5cebf100ffc2",
  "radiance-med-spa-atlanta": "photo-1516975080664-ed2fc6a32937",
  "skinceuticals-skinlab-atlanta": "photo-1629909613654-28e377c37b09",
  "scottsdale-med-spa": "photo-1612817288484-6f916006741a",
  "north-scottsdale-med-spa": "photo-1570172619644-dfd03ed5d881",
  "alchemy-med-bar-scottsdale": "photo-1515377905703-c4788e51af15",
  "zona-med-spa-scottsdale": "photo-1612349317150-e413f6a5b16d",
  "denver-dream-medspa": "photo-1522335789203-aabd1fc54bc9",
  "gleam-med-spa-denver": "photo-1556228578-0d85b1a4d571",
  "kalon-laser-aesthetics-denver": "photo-1608571423902-eed4a5ad8108",
  "esse-medspa-denver": "photo-1556228720-195a672e8a03",
  "goldcoast-medspa-chicago": "photo-1570172619644-dfd03ed5d881",
  "old-town-med-spa-chicago": "photo-1519823551278-64ac92734fb1",
  "essence-medspa-chicago": "photo-1487412947147-5cebf100ffc2",
  "river-north-wellness-med-spa": "photo-1516975080664-ed2fc6a32937",
  "skinovatio-ravenswood-chicago": "photo-1629909613654-28e377c37b09",
  "lume-med-spa-lakeview": "photo-1544161515-4ab6ce6db874",
  "simply-radiant-med-spa-las-vegas": "photo-1612817288484-6f916006741a",
  "flawless-medspa-las-vegas": "photo-1570172619644-dfd03ed5d881",
  "bluepoint-medical-spa-las-vegas": "photo-1515377905703-c4788e51af15",
  "aesthetics-lab-las-vegas": "photo-1612349317150-e413f6a5b16d",
  "skin-society-las-vegas": "photo-1522335789203-aabd1fc54bc9",
  "prestige-med-spa-charlotte": "photo-1556228578-0d85b1a4d571",
  "bodylase-charlotte": "photo-1608571423902-eed4a5ad8108",
  "blue-water-spa-raleigh": "photo-1556228720-195a672e8a03",
  "glo-de-vie-med-spa-raleigh": "photo-1570172619644-dfd03ed5d881",
  "elase-med-spa-raleigh": "photo-1519823551278-64ac92734fb1",
  "ageless-remedies-raleigh": "photo-1487412947147-5cebf100ffc2",
  "nsi-wellness-aesthetics-nashville": "photo-1516975080664-ed2fc6a32937",
  "evolve-medspa-nashville": "photo-1629909613654-28e377c37b09",
  "nashville-skin-company": "photo-1544161515-4ab6ce6db874",
  "skin-pharm-nashville": "photo-1612817288484-6f916006741a",
  "canvas-skin-nashville": "photo-1570172619644-dfd03ed5d881",
};
