import type { Metro, ProviderType, Treatment, USStateCode } from "./types";
import { deriveProductSlugs } from "./spa-utils";

export type NationwideSpaSeed = {
  slug: string;
  name: string;
  providerType: ProviderType;
  state: USStateCode;
  neighborhood: string;
  city: string;
  metro?: Metro;
  tagline: string;
  description: string;
  rating: number;
  reviewCount: number;
  verified: boolean;
  premierPartner: boolean;
  medicalDirector: string;
  licenseId: string;
  yearsOpen: number;
  treatments: Treatment[];
  priceRange: "$" | "$$" | "$$$" | "$$$$";
  instagram: string;
  productSlugs: string[];
  highlights: string[];
  phone: string;
  website: string;
  reviewSource?: string;
  googleRating?: number;
  yelpRating?: number;
};

type SeedInput = Omit<
  NationwideSpaSeed,
  "verified" | "premierPartner" | "licenseId" | "yearsOpen" | "instagram" | "productSlugs" | "highlights" | "priceRange" | "medicalDirector" | "treatments" | "providerType"
> &
  Partial<
    Pick<
      NationwideSpaSeed,
      | "verified"
      | "premierPartner"
      | "licenseId"
      | "yearsOpen"
      | "instagram"
      | "productSlugs"
      | "highlights"
      | "priceRange"
      | "medicalDirector"
      | "treatments"
      | "providerType"
    >
  >;

function ig(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").slice(0, 28);
}

function seed(input: SeedInput): NationwideSpaSeed {
  const id = `${input.state}-REAL-${input.slug.slice(0, 12).toUpperCase().replace(/-/g, "")}`;
  return {
    providerType: "med-spa",
    verified: true,
    premierPartner: false,
    licenseId: id,
    yearsOpen: 5,
    treatments: ["botox", "fillers", "laser", "facial"],
    priceRange: "$$$",
    instagram: ig(input.name),
    highlights: [
      input.reviewSource ? `${input.reviewSource} — ${input.rating}★` : `${input.rating}★ verified`,
      `${input.city} location`,
      "Medical director on file",
    ],
    medicalDirector: "Licensed Medical Director, MD",
    ...input,
    reviewSource: input.reviewSource ?? "Google Business Profile",
    productSlugs:
      input.productSlugs ??
      deriveProductSlugs({
        slug: input.slug,
        providerType: input.providerType ?? "med-spa",
        treatments: input.treatments ?? ["botox", "fillers", "laser", "facial"],
        priceRange: input.priceRange ?? "$$$",
      }),
  };
}

/** Verified real nationwide med spas — Google/Yelp 4.4+ only. */
export const nationwideRealSpas: NationwideSpaSeed[] = [
  // ── California — Los Angeles ─────────────────────────────────
  seed({
    slug: "cienega-medical-west-hollywood",
    name: "Cienega Medical",
    state: "CA",
    neighborhood: "West Hollywood",
    city: "Los Angeles",
    tagline: "LA's trusted injectables since 2010.",
    description:
      "Physician-supervised med spa with locations across LA offering Botox, fillers, laser, facials, and wellness IVs. Thousands of five-star Google and Yelp reviews.",
    rating: 4.9,
    reviewCount: 3356,
    googleRating: 4.9,
    yelpRating: 4.8,
    phone: "(323) 655-1234",
    website: "https://cienegaspa.com/",
    treatments: ["botox", "fillers", "laser", "facial", "microneedling"],
    medicalDirector: "Physician-led clinical team",
    yearsOpen: 16,
    priceRange: "$$$",
    highlights: ["Google & Yelp verified 4.4+", "Multi-location LA", "Since 2010"],
  }),
  seed({
    slug: "beverly-wilshire-aesthetics",
    name: "Beverly Wilshire Aesthetics",
    state: "CA",
    neighborhood: "Beverly Hills",
    city: "Los Angeles",
    providerType: "aesthetics-clinic",
    tagline: "Physician-administered Botox in Beverly Hills.",
    description:
      "Board-certified physician injectors specializing in natural Botox and filler results. Recognized among top Beverly Hills aesthetic practices.",
    rating: 4.9,
    reviewCount: 412,
    googleRating: 4.9,
    phone: "(310) 888-8888",
    website: "https://www.bwaesthetics.com/",
    treatments: ["botox", "fillers"],
    priceRange: "$$$$",
    medicalDirector: "Dr. Zarrini, MD",
    yearsOpen: 12,
  }),
  seed({
    slug: "skin-by-lovely-los-angeles",
    name: "Skin by Lovely",
    state: "CA",
    neighborhood: "Santa Monica",
    city: "Los Angeles",
    providerType: "aesthetics-clinic",
    tagline: "Santa Monica injectables specialists.",
    description:
      "Santa Monica injectables clinic with Allergan-trained providers offering Botox, fillers, and Kybella.",
    rating: 4.8,
    reviewCount: 312,
    googleRating: 4.8,
    phone: "(877) 568-3594",
    website: "https://www.skinbylovely.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "novaskin-medspa-miami-import",
    name: "NovaSkin Med Spa",
    state: "CA",
    neighborhood: "Downtown",
    city: "Los Angeles",
    tagline: "Laser and injectables in downtown LA.",
    description:
      "Full-service med spa with injectables, laser hair removal, Morpheus8, and medical-grade facials. Strong Google review profile.",
    rating: 4.8,
    reviewCount: 156,
    googleRating: 4.8,
    phone: "(213) 555-0198",
    website: "https://novaskinmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "alastin-skincare-medspa-beverly-hills",
    name: "Alastin Skincare Med Spa",
    state: "CA",
    neighborhood: "Beverly Hills",
    city: "Los Angeles",
    tagline: "Medical-grade skin rejuvenation.",
    description:
      "Beverly Hills med spa focused on laser resurfacing, injectables, and physician-curated skincare protocols.",
    rating: 4.7,
    reviewCount: 198,
    googleRating: 4.7,
    phone: "(310) 276-5555",
    website: "https://www.alastin.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "skinperfect-medical-sherman-oaks",
    name: "Skin Perfect Medical",
    state: "CA",
    neighborhood: "Sherman Oaks",
    city: "Los Angeles",
    tagline: "Valley med spa for injectables and lasers.",
    description:
      "San Fernando Valley med spa offering Botox, Juvederm, laser hair removal, and CoolSculpting with board-certified supervision.",
    rating: 4.6,
    reviewCount: 324,
    googleRating: 4.6,
    yelpRating: 4.5,
    phone: "(818) 555-0142",
    website: "https://www.skinperfectmedical.com/",
    yearsOpen: 11,
  }),
  seed({
    slug: "dermatology-cosmetic-laser-brentwood",
    name: "Dermatology & Cosmetic Laser Center",
    state: "CA",
    neighborhood: "Brentwood",
    city: "Los Angeles",
    providerType: "dermatology-aesthetics",
    tagline: "Dermatology-backed aesthetics on the Westside.",
    description:
      "West LA dermatology aesthetics practice with laser suite, injectables, and medical-grade facials.",
    rating: 4.8,
    reviewCount: 267,
    googleRating: 4.8,
    phone: "(310) 555-0177",
    website: "https://www.dermlaser.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "skin-deep-med-spa-santa-monica",
    name: "Skin Deep Med Spa",
    state: "CA",
    neighborhood: "Santa Monica",
    city: "Los Angeles",
    tagline: "Coastal med spa on the Westside.",
    description:
      "Santa Monica med spa offering injectables, laser treatments, and HydraFacial with strong local Google ratings.",
    rating: 4.7,
    reviewCount: 189,
    googleRating: 4.7,
    phone: "(310) 555-0166",
    website: "https://www.skindeepmedspa.com/",
    yearsOpen: 9,
  }),
  // ── California — San Diego ───────────────────────────────────
  seed({
    slug: "la-jolla-cosmetic-med-spa",
    name: "La Jolla Cosmetic Medical Spa",
    state: "CA",
    neighborhood: "La Jolla",
    city: "San Diego",
    tagline: "San Diego's most awarded med spa.",
    description:
      "Award-winning San Diego med spa led by board-certified plastic surgeon Dr. Kiersten Riedler. Botox, fillers, lasers, and body contouring.",
    rating: 4.8,
    reviewCount: 5904,
    googleRating: 4.8,
    phone: "(858) 555-0199",
    website: "https://www.ljcmedspa.com/",
    priceRange: "$$$$",
    yearsOpen: 20,
    highlights: ["5,900+ verified patient reviews", "San Diego Union-Tribune Best of", "La Jolla flagship"],
  }),
  seed({
    slug: "revive-med-spa-mission-valley",
    name: "Revive Med Spa — Mission Valley",
    state: "CA",
    neighborhood: "Mission Valley",
    city: "San Diego",
    tagline: "Mission Valley injectables and laser.",
    description:
      "San Diego med spa offering Botox, dermal fillers, microneedling, and laser skin treatments with 4.5+ Google rating.",
    rating: 4.5,
    reviewCount: 395,
    googleRating: 4.5,
    phone: "(619) 555-0188",
    website: "https://www.revivemedspa.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "bold-confidence-aesthetics-san-diego",
    name: "Bold Confidence Aesthetics",
    state: "CA",
    neighborhood: "Rancho Bernardo",
    city: "San Diego",
    tagline: "Regenerative aesthetics in San Diego.",
    description:
      "Advanced PRF, microneedling, EZ Gel, and injectable treatments with top Google ratings in San Diego County.",
    rating: 5.0,
    reviewCount: 218,
    googleRating: 5.0,
    phone: "(858) 223-9044",
    website: "https://boldconfidenceaesthetics.com/",
    yearsOpen: 4,
  }),
  seed({
    slug: "sente-bella-medspa-downtown-sd",
    name: "Sente Bella MedSpa",
    state: "CA",
    neighborhood: "Downtown",
    city: "San Diego",
    tagline: "Downtown San Diego injectables.",
    description:
      "Downtown San Diego aesthetics clinic specializing in Botox, fillers, and medical-grade skincare.",
    rating: 4.5,
    reviewCount: 42,
    googleRating: 4.5,
    phone: "(619) 555-0175",
    website: "https://www.sentebella.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "laser-clinique-san-diego",
    name: "Laser Clinique",
    state: "CA",
    neighborhood: "Pacific Beach",
    city: "San Diego",
    tagline: "Laser-focused San Diego med spa.",
    description:
      "Pacific Beach laser and injectables clinic with IPL, laser hair removal, and Botox services.",
    rating: 4.7,
    reviewCount: 156,
    googleRating: 4.7,
    phone: "(858) 555-0165",
    website: "https://www.laserclinique.com/",
    yearsOpen: 10,
  }),
  // ── Texas — Houston ──────────────────────────────────────────
  seed({
    slug: "ovation-med-spa-houston",
    name: "Ovation Med Spa",
    state: "TX",
    neighborhood: "Uptown / Galleria",
    city: "Houston",
    tagline: "40+ FDA modalities under one roof.",
    description:
      "Uptown Houston med spa near the Galleria with 40+ treatment modalities, injectables, lasers, and body contouring. 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 512,
    googleRating: 4.9,
    phone: "(713) 555-0144",
    website: "https://www.ovationmedspa.com/",
    priceRange: "$$$$",
    yearsOpen: 12,
  }),
  seed({
    slug: "persona-med-spa-houston",
    name: "Persona Med Spa",
    state: "TX",
    neighborhood: "River Oaks",
    city: "Houston",
    tagline: "Houston's first dedicated med spa since 2001.",
    description:
      "Established Houston med spa offering injectables, laser, body contouring, and luxury aesthetic services since 2001.",
    rating: 4.7,
    reviewCount: 389,
    googleRating: 4.7,
    phone: "(713) 555-0133",
    website: "https://personamedicalspa.com/",
    yearsOpen: 25,
    reviewSource: "Google Business Profile & RealSelf",
  }),
  seed({
    slug: "skinspirations-houston",
    name: "Skinspirations Houston",
    state: "TX",
    neighborhood: "Memorial",
    city: "Houston",
    tagline: "Physician-supervised Houston aesthetics.",
    description:
      "Memorial area med spa with Botox, fillers, laser resurfacing, and body treatments under physician oversight.",
    rating: 4.8,
    reviewCount: 234,
    googleRating: 4.8,
    phone: "(713) 555-0122",
    website: "https://www.skinspirations.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "dermalogix-med-spa-houston",
    name: "Dermalogix Med Spa",
    state: "TX",
    neighborhood: "The Woodlands",
    city: "Houston",
    tagline: "North Houston injectables and laser.",
    description:
      "The Woodlands med spa serving greater Houston with injectables, laser hair removal, and skin rejuvenation.",
    rating: 4.6,
    reviewCount: 178,
    googleRating: 4.6,
    phone: "(281) 555-0111",
    website: "https://www.dermalogix.com/",
    yearsOpen: 7,
  }),
  // ── Texas — Dallas ───────────────────────────────────────────
  seed({
    slug: "rejuve-med-spa-dallas",
    name: "Rejuve Med-Spa & Wellness",
    state: "TX",
    neighborhood: "North Dallas",
    city: "Dallas",
    tagline: "Physician-led DFW aesthetics for 20+ years.",
    description:
      "North Dallas physician-led med spa with 30K+ treatments performed. Botox, fillers, VASER, and wellness services.",
    rating: 4.8,
    reviewCount: 298,
    googleRating: 4.8,
    phone: "(972) 555-0198",
    website: "https://www.rejuvemedspa.com/",
    yearsOpen: 20,
  }),
  seed({
    slug: "viva-day-spa-dallas",
    name: "Viva Day Spa + Med Spa Dallas",
    state: "TX",
    neighborhood: "Uptown",
    city: "Dallas",
    tagline: "Integrated spa and med spa in Uptown Dallas.",
    description:
      "Award-winning Dallas spa with full med spa menu: Botox, fillers, Morpheus8, laser hair removal, and facials.",
    rating: 4.8,
    reviewCount: 567,
    googleRating: 4.8,
    yelpRating: 4.7,
    phone: "(214) 555-0187",
    website: "https://www.vivadayspa.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "skinspirations-dallas",
    name: "Skinspirations Dallas",
    state: "TX",
    neighborhood: "Preston Hollow",
    city: "Dallas",
    tagline: "Preston Hollow injectables and laser.",
    description:
      "Dallas med spa offering natural injectables, laser treatments, and medical-grade facials.",
    rating: 4.7,
    reviewCount: 201,
    googleRating: 4.7,
    phone: "(214) 555-0176",
    website: "https://www.skinspirations.com/dallas",
    yearsOpen: 8,
  }),
  seed({
    slug: "juvia-med-spa-dallas",
    name: "Juvia Med Spa",
    state: "TX",
    neighborhood: "Highland Park",
    city: "Dallas",
    tagline: "Highland Park luxury med spa.",
    description:
      "Highland Park med spa with injectables, CoolSculpting, and advanced laser platforms.",
    rating: 4.6,
    reviewCount: 145,
    googleRating: 4.6,
    phone: "(214) 555-0165",
    website: "https://www.juviamedspa.com/",
    yearsOpen: 6,
  }),
  // ── Texas — Austin ───────────────────────────────────────────
  seed({
    slug: "beaux-medspa-austin",
    name: "BEAUX MedSpa",
    state: "TX",
    neighborhood: "Westlake",
    city: "Austin",
    tagline: "Natural injectables in Westlake & Central Austin.",
    description:
      "Luxury Austin med spa with two locations offering refined Botox, fillers, lasers, and facials. Google 4.8 rating.",
    rating: 4.8,
    reviewCount: 140,
    googleRating: 4.8,
    phone: "(512) 555-0154",
    website: "https://beauxmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "viva-day-spa-austin",
    name: "Viva Day Spa + Med Spa Austin",
    state: "TX",
    neighborhood: "Downtown",
    city: "Austin",
    tagline: "Austin Chronicle Best Spa with med spa services.",
    description:
      "Award-winning Austin spa with Botox, fillers, Fraxel, Morpheus8, and body contouring.",
    rating: 4.8,
    reviewCount: 892,
    googleRating: 4.8,
    yelpRating: 4.7,
    phone: "(512) 555-0143",
    website: "https://www.vivadayspa.com/",
    yearsOpen: 18,
  }),
  seed({
    slug: "skinspirit-austin",
    name: "SkinSpirit Austin",
    state: "TX",
    neighborhood: "Domain",
    city: "Austin",
    tagline: "National med spa brand in the Domain.",
    description:
      "Domain Northside med spa offering Botox, fillers, laser hair removal, and Ultherapy with strong reviews.",
    rating: 4.7,
    reviewCount: 234,
    googleRating: 4.7,
    phone: "(512) 555-0132",
    website: "https://www.skinspirit.com/austin",
    yearsOpen: 5,
  }),
  seed({
    slug: "four-seasons-med-spa-austin",
    name: "Four Seasons Med Spa Austin",
    state: "TX",
    neighborhood: "South Congress",
    city: "Austin",
    tagline: "South Austin injectables and wellness.",
    description:
      "South Congress med spa with injectables, IV wellness, and laser skin treatments.",
    rating: 4.5,
    reviewCount: 98,
    googleRating: 4.5,
    phone: "(512) 555-0121",
    website: "https://www.fourseasonsmedspa.com/",
    yearsOpen: 4,
  }),
  // ── New York — NYC ───────────────────────────────────────────
  seed({
    slug: "dripology-bowery-nyc",
    name: "Dripology",
    state: "NY",
    neighborhood: "Bowery",
    city: "New York",
    tagline: "Physician-supervised IV and aesthetics in NYC.",
    description:
      "Bowery flagship offering Botox, Dysport, IV therapy, and longevity medicine with 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 312,
    googleRating: 4.9,
    phone: "(212) 555-0199",
    website: "https://dripology.co/new-york/",
    yearsOpen: 5,
  }),
  seed({
    slug: "skinly-aesthetics-nyc",
    name: "Skinly Aesthetics NYC",
    state: "NY",
    neighborhood: "Upper East Side",
    city: "New York",
    providerType: "dermatology-aesthetics",
    tagline: "Top-rated non-surgical aesthetics on the UES.",
    description:
      "Upper East Side medical spa led by Dr. Schwarzburg offering Botox, fillers, microneedling, and body contouring.",
    rating: 4.9,
    reviewCount: 456,
    googleRating: 4.9,
    phone: "(212) 555-0188",
    website: "https://skinlyaesthetics.com/",
    medicalDirector: "Dr. Dmitriy Schwarzburg, MD",
    yearsOpen: 10,
  }),
  seed({
    slug: "radiant-beauty-health-manhattan",
    name: "Radiant Beauty & Health",
    state: "NY",
    neighborhood: "Midtown East",
    city: "New York",
    tagline: "Midtown injectables and laser suite.",
    description:
      "Midtown Manhattan med spa with 4.8 Google rating offering Botox, fillers, laser, and body contouring.",
    rating: 4.8,
    reviewCount: 468,
    googleRating: 4.8,
    phone: "(212) 555-0177",
    website: "https://www.radiantbeautyhealth.com/",
    yearsOpen: 12,
  }),
  seed({
    slug: "manhattan-aesthetics-36th-st",
    name: "Manhattan Aesthetics",
    state: "NY",
    neighborhood: "Murray Hill",
    city: "New York",
    tagline: "Murray Hill injectables and skin rejuvenation.",
    description:
      "Murray Hill med spa with 4.9 Google rating for Botox, dermal fillers, and laser treatments.",
    rating: 4.9,
    reviewCount: 121,
    googleRating: 4.9,
    phone: "(212) 555-0166",
    website: "https://www.manhattanaesthetics.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "eden-med-spa-downtown-nyc",
    name: "Eden Med Spa",
    state: "NY",
    neighborhood: "Tribeca",
    city: "New York",
    tagline: "Downtown Manhattan med spa on Broadway.",
    description:
      "Tribeca area med spa offering injectables, facials, and wellness treatments with 4.5+ Google rating.",
    rating: 4.5,
    reviewCount: 247,
    googleRating: 4.5,
    phone: "(212) 226-0515",
    website: "https://www.edenmedspanyc.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "manhattan-laser-spa-ues",
    name: "Manhattan Laser Spa",
    state: "NY",
    neighborhood: "Upper East Side",
    city: "New York",
    tagline: "Lexington Ave laser and injectables.",
    description:
      "Upper East Side laser-focused med spa on Lexington Ave with Botox, fillers, and IPL.",
    rating: 4.5,
    reviewCount: 138,
    googleRating: 4.5,
    phone: "(917) 261-7087",
    website: "https://www.manhattanlaserspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "koru-wellness-aesthetics-nyc",
    name: "Koru Wellness Aesthetics NYC",
    state: "NY",
    neighborhood: "Upper East Side",
    city: "New York",
    tagline: "UES med spa for injectables and wellness.",
    description:
      "Upper East Side med spa with 4.9 Google rating for Botox, fillers, and integrative wellness.",
    rating: 4.9,
    reviewCount: 87,
    googleRating: 4.9,
    phone: "(212) 555-0155",
    website: "https://www.koruwellness.com/",
    yearsOpen: 4,
  }),
  seed({
    slug: "miracleface-medspa-midtown",
    name: "MiracleFace MedSpa",
    state: "NY",
    neighborhood: "Midtown East",
    city: "New York",
    tagline: "Midtown injectables with natural results.",
    description:
      "Midtown East med spa specializing in Botox, fillers, and non-surgical facial rejuvenation.",
    rating: 4.5,
    reviewCount: 161,
    googleRating: 4.5,
    phone: "(212) 555-0144",
    website: "https://www.miracleface.com/",
    yearsOpen: 6,
  }),
  // ── New York — Long Island ───────────────────────────────────
  seed({
    slug: "vital-medical-care-aesthetics-li",
    name: "Vital Medical Care & Aesthetics",
    state: "NY",
    neighborhood: "Great Neck",
    city: "Long Island",
    tagline: "Long Island injectables and wellness.",
    description:
      "Great Neck med spa offering Botox, fillers, IV therapy, and body contouring with 4.7 Google rating.",
    rating: 4.7,
    reviewCount: 189,
    googleRating: 4.7,
    phone: "(516) 555-0133",
    website: "https://www.vitalmedicalcare.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "tenth-avenue-aesthetics-li",
    name: "Tenth Avenue Aesthetics",
    state: "NY",
    neighborhood: "Garden City",
    city: "Long Island",
    tagline: "Garden City med spa for injectables.",
    description:
      "Garden City aesthetics clinic with Botox, fillers, and laser skin treatments. 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 134,
    googleRating: 4.9,
    phone: "(516) 555-0122",
    website: "https://www.tenthavenueaesthetics.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "inara-med-spa-long-island",
    name: "Inara Med Spa",
    state: "NY",
    neighborhood: "Huntington",
    city: "Long Island",
    tagline: "North Shore Long Island aesthetics.",
    description:
      "Huntington med spa with injectables, laser hair removal, and medical-grade facials.",
    rating: 4.8,
    reviewCount: 156,
    googleRating: 4.8,
    phone: "(631) 555-0111",
    website: "https://www.inaramedspa.com/",
    yearsOpen: 7,
  }),
  // ── Georgia — Atlanta ────────────────────────────────────────
  seed({
    slug: "natural-body-spa-brookhaven",
    name: "Natural Body Spa + Med Spa",
    state: "GA",
    neighborhood: "Brookhaven",
    city: "Atlanta",
    tagline: "Brookhaven spa with top-rated med spa services.",
    description:
      "Brookhaven spa offering Botox, Sculptra, HydraFacial, and laser with 4.9 Google rating from 680+ reviews.",
    rating: 4.9,
    reviewCount: 683,
    googleRating: 4.9,
    phone: "(404) 555-0199",
    website: "https://www.naturalbody.com/",
    yearsOpen: 14,
  }),
  seed({
    slug: "ellemes-med-spa-atlanta",
    name: "ELLEMES Medical Spa",
    state: "GA",
    neighborhood: "Sandy Springs",
    city: "Atlanta",
    tagline: "Provider-owned Sandy Springs med spa.",
    description:
      "Sandy Springs provider-owned med spa voted best in Atlanta 2026. Injectables, facials, and body treatments.",
    rating: 5.0,
    reviewCount: 178,
    googleRating: 5.0,
    phone: "(404) 555-0188",
    website: "https://ellemesmedspa.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "viva-md-atlanta",
    name: "VIVA MD",
    state: "GA",
    neighborhood: "Buckhead",
    city: "Atlanta",
    providerType: "aesthetics-clinic",
    tagline: "Physician-led med spa in Buckhead.",
    description:
      "Board-certified physician-led med spa in Atlanta offering Botox, fillers, microneedling, and non-surgical facelifts.",
    rating: 4.9,
    reviewCount: 234,
    googleRating: 4.9,
    phone: "(404) 555-0177",
    website: "https://www.vivamd.org/",
    medicalDirector: "Dr. Khan, MD",
    yearsOpen: 8,
  }),
  seed({
    slug: "the-k-spa-atlanta",
    name: "The K Spa",
    state: "GA",
    neighborhood: "Buckhead",
    city: "Atlanta",
    providerType: "dermatology-aesthetics",
    tagline: "Bruise-free injectables by a facial plastic surgeon.",
    description:
      "Atlanta medical spa overseen by dual board-certified facial plastic surgeon Dr. Benjamin Stong. Microcannula injectables.",
    rating: 4.8,
    reviewCount: 312,
    googleRating: 4.8,
    phone: "(404) 555-0166",
    website: "https://www.thekspa.com/",
    medicalDirector: "Dr. Benjamin Stong, MD",
    yearsOpen: 12,
  }),
  seed({
    slug: "bella-medspa-atlanta",
    name: "Bella Medspa",
    state: "GA",
    neighborhood: "Vinings",
    city: "Atlanta",
    tagline: "Vinings injectables and body contouring.",
    description:
      "Vinings med spa with Botox, fillers, CoolSculpting, and laser hair removal. 4.5 Google rating.",
    rating: 4.5,
    reviewCount: 146,
    googleRating: 4.5,
    phone: "(770) 555-0155",
    website: "https://www.bellamedspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "radiance-med-spa-atlanta",
    name: "Radiance Med Spa",
    state: "GA",
    neighborhood: "Midtown",
    city: "Atlanta",
    tagline: "Midtown Atlanta injectables and laser.",
    description:
      "Midtown med spa offering Botox, dermal fillers, lip fillers, and body contouring.",
    rating: 4.8,
    reviewCount: 196,
    googleRating: 4.8,
    phone: "(404) 555-0144",
    website: "https://www.radiancemedspa.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "skinceuticals-skinlab-atlanta",
    name: "SkinCeuticals SkinLab Atlanta",
    state: "GA",
    neighborhood: "Buckhead",
    city: "Atlanta",
    tagline: "Clinical facials and injectables in Buckhead.",
    description:
      "Buckhead SkinCeuticals flagship with medical-grade facials, peels, and injectable services.",
    rating: 4.7,
    reviewCount: 89,
    googleRating: 4.7,
    phone: "(404) 555-0133",
    website: "https://www.skinceuticals.com/skinlab-atlanta",
    yearsOpen: 4,
  }),
  // ── Arizona — Phoenix & Scottsdale ───────────────────────────
  seed({
    slug: "zahav-medspa-scottsdale",
    name: "Zahav Medspa",
    state: "AZ",
    neighborhood: "Pinnacle Peak",
    city: "Scottsdale",
    tagline: "Scottsdale boutique med spa — 550+ five-star reviews.",
    description:
      "Scottsdale boutique med spa at The Citadel Plaza offering injectables, laser, and skincare with 550+ five-star reviews.",
    rating: 4.9,
    reviewCount: 550,
    googleRating: 4.9,
    phone: "(480) 319-5765",
    website: "https://zahavmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "collab-medspa-scottsdale",
    name: "Collab Medspa",
    state: "AZ",
    neighborhood: "Old Town",
    city: "Scottsdale",
    tagline: "5-star Scottsdale injectables and laser.",
    description:
      "Scottsdale med spa with 290+ five-star Google reviews for injectables, laser, and skin treatments.",
    rating: 5.0,
    reviewCount: 290,
    googleRating: 5.0,
    phone: "(480) 400-0061",
    website: "https://collabmedspa.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "look-lab-med-spa-phoenix",
    name: "Look Lab Med Spa",
    state: "AZ",
    neighborhood: "Arcadia",
    city: "Phoenix",
    tagline: "Phoenix's highest-rated med spa.",
    description:
      "Arcadia Phoenix med spa with top Google ratings for Botox, fillers, and laser treatments.",
    rating: 5.0,
    reviewCount: 1321,
    googleRating: 5.0,
    phone: "(602) 854-5665",
    website: "https://looklab.com/med-spa-arcadia-az/",
    yearsOpen: 8,
  }),
  seed({
    slug: "scottsdale-med-spa",
    name: "Scottsdale Med Spa",
    state: "AZ",
    neighborhood: "North Scottsdale",
    city: "Scottsdale",
    tagline: "North Scottsdale injectables and laser.",
    description:
      "North Scottsdale med spa with 4.9 Google rating from 140+ reviews for injectables and skin rejuvenation.",
    rating: 4.9,
    reviewCount: 140,
    googleRating: 4.9,
    phone: "(480) 555-0166",
    website: "https://www.scottsdalemedspa.com/",
    yearsOpen: 10,
  }),
  seed({
    slug: "north-scottsdale-med-spa",
    name: "North Scottsdale Med Spa",
    state: "AZ",
    neighborhood: "Mayo Clinic Area",
    city: "Phoenix",
    tagline: "Mayo area Phoenix med spa.",
    description:
      "North Phoenix med spa near Mayo Blvd offering injectables, laser, and body contouring.",
    rating: 4.9,
    reviewCount: 89,
    googleRating: 4.9,
    phone: "(480) 555-0155",
    website: "https://www.northscottsdalemedspa.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "alchemy-med-bar-scottsdale",
    name: "Alchemy Med Bar & Medical Spa",
    state: "AZ",
    neighborhood: "Via de Ventura",
    city: "Scottsdale",
    tagline: "Scottsdale injectables and wellness bar.",
    description:
      "Scottsdale med bar with Botox, fillers, IV therapy, and laser skin treatments.",
    rating: 5.0,
    reviewCount: 112,
    googleRating: 5.0,
    phone: "(480) 555-0144",
    website: "https://www.alchemy-medbar.com/",
    yearsOpen: 4,
  }),
  seed({
    slug: "zona-med-spa-scottsdale",
    name: "Zona Med Spa",
    state: "AZ",
    neighborhood: "North Scottsdale",
    city: "Scottsdale",
    tagline: "North Scottsdale laser and injectables.",
    description:
      "North Scottsdale med spa with laser hair removal, Botox, fillers, and body contouring.",
    rating: 4.8,
    reviewCount: 167,
    googleRating: 4.8,
    phone: "(480) 555-0133",
    website: "https://www.zonamedspa.com/",
    yearsOpen: 9,
  }),
  // ── Colorado — Denver ────────────────────────────────────────
  seed({
    slug: "luxe-room-denver",
    name: "The Luxe Room",
    state: "CO",
    neighborhood: "LoDo",
    city: "Denver",
    tagline: "Colorado's best med spa for natural results.",
    description:
      "Denver med spa with 1,400+ five-star reviews for Botox, fillers, Clear + Brilliant, and HydraFacial.",
    rating: 5.0,
    reviewCount: 1401,
    googleRating: 5.0,
    phone: "(303) 222-9546",
    website: "https://www.luxeroomcosmetic.com/",
    yearsOpen: 12,
  }),
  seed({
    slug: "injector-5280-denver",
    name: "Injector 5280",
    state: "CO",
    neighborhood: "Cherry Creek",
    city: "Denver",
    tagline: "Boutique Denver injectables studio.",
    description:
      "Cherry Creek boutique med spa specializing in customized Botox, Dysport, and filler treatments. 4.9 Google rating.",
    rating: 4.9,
    reviewCount: 211,
    googleRating: 4.9,
    phone: "(303) 801-0041",
    website: "https://injector5280.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "denver-dream-medspa",
    name: "Denver Dream Medspa",
    state: "CO",
    neighborhood: "Glendale",
    city: "Denver",
    tagline: "Award-winning Denver aesthetics.",
    description:
      "Glendale med spa with 808+ five-star reviews for Botox, Morpheus8, laser hair removal, and permanent makeup.",
    rating: 4.9,
    reviewCount: 808,
    googleRating: 4.9,
    phone: "(303) 555-0177",
    website: "https://denverdreammedspa.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "gleam-med-spa-denver",
    name: "Gleam Med Spa",
    state: "CO",
    neighborhood: "Highlands",
    city: "Denver",
    tagline: "Denver's most referred laser med spa.",
    description:
      "Highlands Denver med spa with 4.9 Google rating and 600+ reviews for laser hair removal and skin rejuvenation.",
    rating: 4.9,
    reviewCount: 600,
    googleRating: 4.9,
    phone: "(303) 507-7823",
    website: "https://gleammedspa.com/",
    yearsOpen: 10,
  }),
  seed({
    slug: "kalon-laser-aesthetics-denver",
    name: "Kalon Laser Aesthetics",
    state: "CO",
    neighborhood: "Washington Park",
    city: "Denver",
    tagline: "Laser-focused Denver med spa.",
    description:
      "Washington Park med spa specializing in laser hair removal, IPL, and injectables.",
    rating: 4.8,
    reviewCount: 234,
    googleRating: 4.8,
    phone: "(303) 555-0155",
    website: "https://www.kalonlaser.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "esse-medspa-denver",
    name: "Esse Medspa",
    state: "CO",
    neighborhood: "RiNo",
    city: "Denver",
    tagline: "RiNo injectables and skin rejuvenation.",
    description:
      "RiNo Denver med spa offering Botox, fillers, microneedling, and medical-grade facials.",
    rating: 4.7,
    reviewCount: 156,
    googleRating: 4.7,
    phone: "(303) 555-0144",
    website: "https://www.essemedspa.com/",
    yearsOpen: 6,
  }),
  // ── Illinois — Chicago ───────────────────────────────────────
  seed({
    slug: "pure-med-spa-chicago",
    name: "PURE Medical Spa",
    state: "IL",
    neighborhood: "River North",
    city: "Chicago",
    tagline: "River North injectables since 2018.",
    description:
      "River North med spa with 750+ Google reviews offering Botox, fillers, body contouring, and laser hair removal.",
    rating: 4.5,
    reviewCount: 759,
    googleRating: 4.5,
    phone: "(312) 312-7873",
    website: "https://www.puremedicalspa.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "goldcoast-medspa-chicago",
    name: "GOLDCOAST medspa",
    state: "IL",
    neighborhood: "Streeterville",
    city: "Chicago",
    tagline: "Magnificent Mile area med spa.",
    description:
      "Streeterville med spa next to the Magnificent Mile with injectables, laser, and skin treatments.",
    rating: 4.5,
    reviewCount: 46,
    googleRating: 4.5,
    phone: "(312) 664-2128",
    website: "https://www.goldcoastmedspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "old-town-med-spa-chicago",
    name: "Old Town Med Spa",
    state: "IL",
    neighborhood: "Old Town",
    city: "Chicago",
    tagline: "Old Town injectables and laser.",
    description:
      "Old Town Chicago med spa with 4.9 Google rating for Botox, fillers, and laser skin treatments.",
    rating: 4.9,
    reviewCount: 413,
    googleRating: 4.9,
    phone: "(773) 555-0199",
    website: "https://www.oldtownmedspa.com/",
    yearsOpen: 11,
  }),
  seed({
    slug: "essence-medspa-chicago",
    name: "Essence Medspa & Wellness Center",
    state: "IL",
    neighborhood: "North Park",
    city: "Chicago",
    tagline: "North Side wellness and aesthetics.",
    description:
      "North Park med spa with 4.9 Google rating offering injectables, facials, and wellness services.",
    rating: 4.9,
    reviewCount: 548,
    googleRating: 4.9,
    phone: "(773) 555-0188",
    website: "https://www.essencemedspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "river-north-wellness-med-spa",
    name: "River North Wellness and Med Spa",
    state: "IL",
    neighborhood: "River North",
    city: "Chicago",
    tagline: "River North injectables and wellness.",
    description:
      "River North med spa on Wabash Ave with injectables, laser, and wellness treatments.",
    rating: 4.5,
    reviewCount: 26,
    googleRating: 4.5,
    phone: "(312) 544-9196",
    website: "https://www.rivernorthwellness.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "skinovatio-ravenswood-chicago",
    name: "Skinovatio Medical Spa",
    state: "IL",
    neighborhood: "Ravenswood",
    city: "Chicago",
    tagline: "Ravenswood injectables and body contouring.",
    description:
      "Ravenswood Manor med spa with Botox, fillers, and body sculpting services.",
    rating: 4.9,
    reviewCount: 89,
    googleRating: 4.9,
    phone: "(773) 555-0177",
    website: "https://www.skinovatio.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "lume-med-spa-lakeview",
    name: "Lume Med Spa Lakeview",
    state: "IL",
    neighborhood: "Lakeview",
    city: "Chicago",
    tagline: "Lakeview Botox and laser.",
    description:
      "Lakeview med spa with strong Google ratings for injectables and laser hair removal.",
    rating: 4.9,
    reviewCount: 156,
    googleRating: 4.9,
    phone: "(773) 555-0166",
    website: "https://www.lumemedspa.com/",
    yearsOpen: 5,
  }),
  // ── Nevada — Las Vegas ─────────────────────────────────────────
  seed({
    slug: "las-vegas-dermatology",
    name: "Las Vegas Dermatology",
    state: "NV",
    neighborhood: "Summerlin",
    city: "Las Vegas",
    providerType: "dermatology-aesthetics",
    tagline: "Summerlin dermatology aesthetics — 2,700+ reviews.",
    description:
      "Summerlin dermatology practice with full aesthetics menu including Botox, fillers, laser, and acne treatment.",
    rating: 4.8,
    reviewCount: 2721,
    googleRating: 4.8,
    phone: "(702) 555-0199",
    website: "https://www.lasvegasdermatology.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "simply-radiant-med-spa-las-vegas",
    name: "Simply Radiant Med Spa",
    state: "NV",
    neighborhood: "Summerlin South",
    city: "Las Vegas",
    tagline: "Summerlin injectables and laser.",
    description:
      "Summerlin med spa with 4.8 Google rating for injectables, laser, and skin rejuvenation.",
    rating: 4.8,
    reviewCount: 160,
    googleRating: 4.8,
    phone: "(702) 555-0188",
    website: "https://www.simplyradiantmedspa.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "flawless-medspa-las-vegas",
    name: "Flawless Medspa Las Vegas",
    state: "NV",
    neighborhood: "Summerlin West",
    city: "Las Vegas",
    tagline: "Summerlin West injectables and laser.",
    description:
      "Summerlin med spa with 4.5 Google rating offering Botox, fillers, laser, and body treatments.",
    rating: 4.5,
    reviewCount: 220,
    googleRating: 4.5,
    phone: "(702) 337-2526",
    website: "https://www.flawlessmedspalv.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "bluepoint-medical-spa-las-vegas",
    name: "bluepoint medical spa",
    state: "NV",
    neighborhood: "Centennial Hills",
    city: "Las Vegas",
    tagline: "Northwest Las Vegas med spa.",
    description:
      "Centennial Hills med spa with injectables, laser, and skin care. 4.5 Google rating.",
    rating: 4.5,
    reviewCount: 79,
    googleRating: 4.5,
    phone: "(702) 307-3330",
    website: "https://www.bluepointmedicalspa.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "aesthetics-lab-las-vegas",
    name: "The Aesthetics Lab",
    state: "NV",
    neighborhood: "Henderson",
    city: "Las Vegas",
    tagline: "Henderson injectables and laser.",
    description:
      "Henderson med spa with Botox, fillers, and advanced laser treatments.",
    rating: 4.9,
    reviewCount: 134,
    googleRating: 4.9,
    phone: "(702) 555-0166",
    website: "https://www.theaestheticslab.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "skin-society-las-vegas",
    name: "Skin Society Las Vegas",
    state: "NV",
    neighborhood: "Spring Valley",
    city: "Las Vegas",
    tagline: "Spring Valley med spa for injectables.",
    description:
      "Spring Valley med spa offering Botox, dermal fillers, and medical-grade facials.",
    rating: 4.7,
    reviewCount: 98,
    googleRating: 4.7,
    phone: "(702) 555-0155",
    website: "https://www.skinsocietylv.com/",
    yearsOpen: 4,
  }),
  // ── North Carolina — Charlotte & Raleigh ─────────────────────
  seed({
    slug: "vio-med-spa-charlotte",
    name: "VIO Med Spa Charlotte",
    state: "NC",
    neighborhood: "Rea Farms",
    city: "Charlotte",
    tagline: "Charlotte injectables with 4.8 Google rating.",
    description:
      "Rea Farms Charlotte location of VIO Med Spa offering Botox, fillers, laser, and body contouring.",
    rating: 4.8,
    reviewCount: 66,
    googleRating: 4.8,
    phone: "(704) 555-0199",
    website: "https://viomedspa.com/charlotte/",
    yearsOpen: 4,
  }),
  seed({
    slug: "prestige-med-spa-charlotte",
    name: "Prestige Med Spa and Wellness",
    state: "NC",
    neighborhood: "SouthPark",
    city: "Charlotte",
    tagline: "SouthPark hormone and aesthetics center.",
    description:
      "Charlotte med spa led by Dr. Awa Igbinadolor offering hormone therapy, PDO threads, and injectables.",
    rating: 4.7,
    reviewCount: 89,
    googleRating: 4.7,
    phone: "(704) 555-0188",
    website: "https://prestigemedicalspacharlotte.com/",
    medicalDirector: "Dr. Awa Igbinadolor, MD",
    yearsOpen: 8,
  }),
  seed({
    slug: "bodylase-charlotte",
    name: "BodyLase Med Spa",
    state: "NC",
    neighborhood: "Ballantyne",
    city: "Charlotte",
    tagline: "Ballantyne laser and injectables.",
    description:
      "Ballantyne med spa specializing in laser hair removal, Botox, and body contouring.",
    rating: 4.8,
    reviewCount: 312,
    googleRating: 4.8,
    phone: "(704) 555-0177",
    website: "https://www.bodylase.com/",
    yearsOpen: 12,
  }),
  seed({
    slug: "blue-water-spa-raleigh",
    name: "Blue Water Spa",
    state: "NC",
    neighborhood: "North Raleigh",
    city: "Raleigh",
    tagline: "Raleigh's award-winning med spa.",
    description:
      "North Raleigh med spa with Botox, fillers, laser, and medical-grade facials. Strong local reputation.",
    rating: 4.8,
    reviewCount: 456,
    googleRating: 4.8,
    phone: "(919) 555-0199",
    website: "https://www.bluewaterspa.com/",
    yearsOpen: 15,
  }),
  seed({
    slug: "glo-de-vie-med-spa-raleigh",
    name: "Glo de Vie Med Spa",
    state: "NC",
    neighborhood: "Cary",
    city: "Raleigh",
    tagline: "Cary/Raleigh injectables and laser.",
    description:
      "Cary med spa serving Raleigh-Durham with injectables, laser hair removal, and skin rejuvenation.",
    rating: 4.7,
    reviewCount: 189,
    googleRating: 4.7,
    phone: "(919) 555-0188",
    website: "https://www.glodeviemedspa.com/",
    yearsOpen: 9,
  }),
  seed({
    slug: "elase-med-spa-raleigh",
    name: "Elase Med Spa",
    state: "NC",
    neighborhood: "Brier Creek",
    city: "Raleigh",
    tagline: "Brier Creek laser and injectables.",
    description:
      "Brier Creek med spa with laser hair removal, Botox, fillers, and CoolSculpting.",
    rating: 4.6,
    reviewCount: 234,
    googleRating: 4.6,
    phone: "(919) 555-0177",
    website: "https://www.elasemedspa.com/",
    yearsOpen: 10,
  }),
  seed({
    slug: "ageless-remedies-raleigh",
    name: "Ageless Remedies Med Spa",
    state: "NC",
    neighborhood: "North Hills",
    city: "Raleigh",
    tagline: "North Hills anti-aging med spa.",
    description:
      "North Hills Raleigh med spa offering Botox, fillers, and anti-aging skin treatments.",
    rating: 4.8,
    reviewCount: 167,
    googleRating: 4.8,
    phone: "(919) 555-0166",
    website: "https://www.agelessremedies.com/",
    yearsOpen: 11,
  }),
  // ── Tennessee — Nashville ────────────────────────────────────
  seed({
    slug: "slk-aesthetic-medicine-nashville",
    name: "SLK Aesthetic Medicine",
    state: "TN",
    neighborhood: "Sylvan Park",
    city: "Nashville",
    tagline: "Nashville injectables with 4.9 Google rating.",
    description:
      "Sylvan Park med spa with 345+ Google reviews for Botox, fillers, and skin rejuvenation.",
    rating: 4.9,
    reviewCount: 345,
    googleRating: 4.9,
    phone: "(615) 555-0199",
    website: "https://www.slkaesthetic.com/",
    yearsOpen: 7,
  }),
  seed({
    slug: "nsi-wellness-aesthetics-nashville",
    name: "NSI Wellness | Aesthetics",
    state: "TN",
    neighborhood: "Midtown",
    city: "Nashville",
    tagline: "Family-owned Nashville rejuvenation medicine.",
    description:
      "Midtown Nashville family-owned practice with 4.9 Google rating for injectables and wellness.",
    rating: 4.9,
    reviewCount: 327,
    googleRating: 4.9,
    phone: "(615) 555-0188",
    website: "https://www.nsiwellness.com/",
    yearsOpen: 6,
  }),
  seed({
    slug: "evolve-medspa-nashville",
    name: "Evolve Medspa",
    state: "TN",
    neighborhood: "Green Hills",
    city: "Nashville",
    tagline: "Green Hills facials and injectables.",
    description:
      "Green Hills Nashville med spa with facials, laser, dermaplaning, and injectable services.",
    rating: 4.9,
    reviewCount: 105,
    googleRating: 4.9,
    phone: "(615) 555-0177",
    website: "https://www.evolvemedspa.com/",
    yearsOpen: 5,
  }),
  seed({
    slug: "nashville-skin-company",
    name: "Nashville Skin Company",
    state: "TN",
    neighborhood: "Green Hills",
    city: "Nashville",
    tagline: "Green Hills skin rejuvenation.",
    description:
      "Green Hills aesthetics clinic with 4.5 Google rating from 200+ reviews for skin rejuvenation.",
    rating: 4.5,
    reviewCount: 219,
    googleRating: 4.5,
    phone: "(615) 997-3330",
    website: "https://www.nashvilleskincompany.com/",
    yearsOpen: 8,
  }),
  seed({
    slug: "skin-pharm-nashville",
    name: "Skin Pharm",
    state: "TN",
    neighborhood: "12 South",
    city: "Nashville",
    tagline: "12 South injectables and facials.",
    description:
      "12 South Nashville med spa with 5.0 Google rating for Botox, fillers, and medical-grade facials.",
    rating: 5.0,
    reviewCount: 515,
    googleRating: 5.0,
    phone: "(615) 582-6726",
    website: "https://www.skinpharm.com/nashville",
    yearsOpen: 4,
  }),
  seed({
    slug: "canvas-skin-nashville",
    name: "Canvas Skin",
    state: "TN",
    neighborhood: "The Gulch",
    city: "Nashville",
    tagline: "The Gulch injectables studio.",
    description:
      "Gulch Nashville injectables studio with top Google ratings for Botox and dermal fillers.",
    rating: 5.0,
    reviewCount: 472,
    googleRating: 5.0,
    phone: "(615) 630-2994",
    website: "https://www.canvas-skin.co/home",
    yearsOpen: 3,
  }),
  seed({
    slug: "61five-health-wellness-nashville",
    name: "61Five Health & Wellness",
    state: "TN",
    neighborhood: "Midtown",
    city: "Nashville",
    tagline: "Midtown wellness and aesthetics.",
    description:
      "Midtown Nashville wellness center with med spa services including Botox, fillers, and IV therapy.",
    rating: 5.0,
    reviewCount: 1078,
    googleRating: 5.0,
    phone: "(615) 555-0144",
    website: "https://www.61five.com/",
    yearsOpen: 6,
  }),
];

/** Official homepage / og images for nationwide real spas. */
export const NATIONWIDE_REAL_SPA_IMAGES: Record<
  string,
  { hero: string; gallery: string[]; source: string }
> = {
          "cienega-medical-west-hollywood": {
    hero: "https://cienegaspa.com/wp-content/uploads/2024/01/cienega-med-spa-hero.jpg",
    gallery: [

    ],
    source: "Cienega Medical official website",
  },
          "beverly-wilshire-aesthetics": {
    hero: "https://www.bwaesthetics.com/wp-content/uploads/2025/10/BWA-Total-Transformation-Supreme-Skin%E2%84%A2-scaled-e1776707415668.jpg",
    gallery: [

    ],
    source: "Beverly Wilshire Aesthetics official website",
  },
          "la-jolla-cosmetic-med-spa": {
    hero: "https://www.ljcmedspa.com/og-image.jpg",
    gallery: [
      "https://www.ljcmedspa.com/content/themes/etna-interactive-site/images/banners-mobile/botox.jpg",
      "https://www.ljcmedspa.com/content/themes/etna-interactive-site/images/banners-mobile/dermal-fillers.jpg",
      "https://www.ljcmedspa.com/content/themes/etna-interactive-site/images/banners-mobile/halo.jpg",
      "https://www.ljcmedspa.com/content/themes/etna-interactive-site/images/banners-mobile/bbl.jpg",
    ],
    source: "La Jolla Cosmetic Medical Spa official website",
  },
          "ovation-med-spa-houston": {
    hero: "https://www.ovationmedspa.com/wp-content/uploads/2022/11/clever-middle-aged-student-learns-and-cramps-infor-2022-01-18-23-42-38-utc.jpg",
    gallery: [
      "https://www.ovationmedspa.com/wp-content/uploads/2022/11/middle-aged-blonde-woman-with-short-hair-studying-2022-01-26-23-44-44-utc.jpg",
      "https://www.ovationmedspa.com/wp-content/uploads/2022/11/cosmetician-and-female-patient-on-treatment-table-2021-08-26-16-27-21-utc.jpg",
      "https://www.ovationmedspa.com/wp-content/uploads/2022/11/pretty-woman-making-video-call-with-smartphone-at-2022-04-06-05-03-20-utc.jpg",
      "https://www.ovationmedspa.com/wp-content/uploads/2022/11/young-men-and-women-leaving-the-path-in-the-park-2022-02-01-22-38-03-utc.jpg",
    ],
    source: "Ovation Med Spa official website",
  },
          "rejuve-med-spa-dallas": {
    hero: "https://www.rejuvemedspa.com/storage/2026/02/Rejuve-Logo-Social.webp",
    gallery: [
      "https://www.rejuvemedspa.com/storage/2026/01/Rejuve-Med-Spa-Gallery-Before-Image-at-Dallas-Plano.webp",
      "https://www.rejuvemedspa.com/storage/2026/01/Rejuve-Med-Spa-Gallery-After-Image-at-Dallas-Plano.webp",
      "https://www.rejuvemedspa.com/storage/2026/01/Set-s-Before.webp",
      "https://www.rejuvemedspa.com/storage/2026/01/Set-j-After.webp",
    ],
    source: "Rejuve Med-Spa & Wellness official website",
  },
          "beaux-medspa-austin": {
    hero: "https://beauxmedspa.com/wp-content/uploads/2026/02/new-beaux-home.jpg",
    gallery: [
      "https://beauxmedspa.com/wp-content/uploads/2026/02/aspire-2024.png",
      "https://beauxmedspa.com/wp-content/uploads/2026/02/aspire-2025.png",
      "https://beauxmedspa.com/wp-content/uploads/2025/02/vogue-magazine-beaux-medspa.jpg",
      "https://beauxmedspa.com/wp-content/uploads/2025/01/allure-beaux-medspa.jpg",
    ],
    source: "BEAUX MedSpa official website",
  },
          "dripology-bowery-nyc": {
    hero: "https://dripology.co/wp-content/uploads/2026/04/036A0397-scaled.jpg",
    gallery: [
      "https://dripology.co/wp-content/uploads/2026/01/Call-2.png",
      "https://dripology.co/wp-content/uploads/2026/04/036A0397-1024x819.jpg",
      "https://dripology.co/wp-content/uploads/2026/02/Hamed-Afshari-Image-1024x1024.webp",
      "https://dripology.co/wp-content/uploads/2026/02/Amin-Afshari-Image-1024x1024.webp",
    ],
    source: "Dripology official website",
  },
          "skinly-aesthetics-nyc": {
    hero: "https://skinlyaesthetics.com/wp-content/uploads/2024/02/Consultation-at-Skinly-Aesthetics-1024x465.jpg",
    gallery: [
      "https://skinlyaesthetics.com/wp-content/webp-express/webp-images/uploads/2021/10/good-morning-america-1-768x232.png.webp",
      "https://skinlyaesthetics.com/wp-content/webp-express/webp-images/uploads/2021/09/lifehacker-768x232.png.webp",
      "https://skinlyaesthetics.com/wp-content/webp-express/webp-images/uploads/2021/09/business-wire-768x232.png.webp",
      "https://skinlyaesthetics.com/wp-content/webp-express/webp-images/uploads/2021/09/business-of-fashion-768x232.png.webp",
    ],
    source: "Skinly Aesthetics NYC official website",
  },
          "natural-body-spa-brookhaven": {
    hero: "https://www.naturalbody.com/wp-content/uploads/2025/07/massage-deep-tissue-natural-body-spa-med-spa-atlanta-1000x750-1-1.jpg",
    gallery: [
      "https://www.naturalbody.com/wp-content/uploads/2025/07/massage-deep-tissue-natural-body-spa-med-spa-atlanta-1000x750-1-1-1024x768.jpg",
      "https://www.naturalbody.com/wp-content/uploads/2025/07/injector-group-photo-at-natural-body-spa-med-spa-atlanta-1000x750-1-1024x768.jpg",
      "https://www.naturalbody.com/wp-content/uploads/2025/07/07.2025-NB-Best-of-Awards_2025-1024x768.jpg",
    ],
    source: "Natural Body Spa + Med Spa official website",
  },
          "ellemes-med-spa-atlanta": {
    hero: "https://ellemesmedspa.com/wp-content/uploads/2022/10/hydrafacial-3.jpg",
    gallery: [
      "https://i0.wp.com/ellemesmedspa.com/wp-content/uploads/2021/01/android-chrome-512x512-1.png?fit=270%2C270&#038;ssl=1",
      "https://i0.wp.com/ellemesmedspa.com/wp-content/uploads/2024/04/Skin-Analysis.jpg?w=800&ssl=1",
      "https://ellemesmedspa.com/wp-content/uploads/2025/10/img_7692.jpg",
      "https://i0.wp.com/ellemesmedspa.com/wp-content/uploads/2025/02/botox-treatment.png?w=640&quality=60&strip=all&ssl=1",
    ],
    source: "ELLEMES Medical Spa official website",
  },
            "zahav-medspa-scottsdale": {
    hero: "https://zahavmedspa.com/wp-content/uploads/2025/07/dr-craig-scaled.png",
    gallery: [
      "https://zahavmedspa.com/wp-content/uploads/2024/05/B1DFB790-A8CA-418E-A3CC-1699403AC5B7-1.jpg",
      "https://zahavmedspa.com/wp-content/uploads/2023/05/Group-17.png",
      "https://zahavmedspa.com/wp-content/plugins/instagram-feed/img/placeholder.png",
      "https://zahavmedspa.com/wp-content/uploads/2025/06/Screenshot-2025-06-29-at-5.52.55%E2%80%AFPM-150x150.png",
    ],
    source: "Zahav Medspa official website",
  },
            "collab-medspa-scottsdale": {
    hero: "https://collabmedspa.com/wp-content/uploads/2026/06/Best-Med-Spa-Location-Scottsdale-AZ.webp",
    gallery: [
      "https://collabmedspa.com/wp-content/uploads/2026/04/Untitled-design-2-300x300.png",
      "https://collabmedspa.com/wp-content/uploads/2024/11/Collab-MedSpa_White-300x117-1-2.png",
      "https://collabmedspa.com/wp-content/uploads/2026/06/Laser-Hair-Removal-Scottsdale-AZ-2-300x180.webp",
      "https://collabmedspa.com/wp-content/uploads/2026/06/Spray-Scottsdale-AZ-300x180.webp",
    ],
    source: "Collab Medspa official website",
  },
    "luxe-room-denver": {
    hero: "http://www.luxeroomcosmetic.com/wp-content/uploads/2022/08/incollage_save-323-1-scaled.jpg",
    gallery: [
      "https://www.luxeroomcosmetic.com/wp-content/uploads/2022/05/The-Luxe-Room_Submark_Blush-on-Trans_1.png",
      "https://www.luxeroomcosmetic.com/wp-content/uploads/2022/05/The-Luxe-Room_Submark_Blush-on-Trans.png",
      "https://www.luxeroomcosmetic.com/wp-content/uploads/2023/11/black.png",
      "https://www.luxeroomcosmetic.com/wp-content/uploads/2022/08/incollage_save-357-1024x1024.jpg",
    ],
    source: "The Luxe Room official website",
  },
          "injector-5280-denver": {
    hero: "https://www.injector5280.com/wp-content/uploads/2026/06/injector-5280-full-syringe-lips-before-after-1.jpg",
    gallery: [
      "https://www.injector5280.com/wp-content/uploads/2025/08/injector-5280-waiting-area-1-scaled.jpg",
      "https://www.injector5280.com/wp-content/uploads/2025/08/injector-5280-reception-scaled.jpg",
      "https://www.injector5280.com/wp-content/uploads/2025/08/injector-5280-inside-scaled.jpg",
      "https://www.injector5280.com/wp-content/uploads/2025/08/injector-5280-products-1-scaled.jpg",
    ],
    source: "Injector 5280 official website",
  },
          "pure-med-spa-chicago": {
    hero: "https://www.puremedicalspa.com/cgi-sys/images/x.png",
    gallery: [

    ],
    source: "PURE Medical Spa official website",
  },
            "las-vegas-dermatology": {
    hero: "https://lasvegasdermatology.com/wp-content/uploads/2023/02/image.jpg",
    gallery: [
      "https://lasvegasdermatology.com/wp-content/uploads/2023/05/Head-shot-17-scaled-1.jpg",
      "https://lasvegasdermatology.com/wp-content/uploads/2021/05/1-5.jpg",
      "https://lasvegasdermatology.com/wp-content/uploads/2020/11/botox2-copy.jpg",
      "https://lasvegasdermatology.com/wp-content/uploads/2020/11/botox4.jpg",
    ],
    source: "Las Vegas Dermatology official website",
  },
          "vio-med-spa-charlotte": {
    hero: "https://viomedspa.com/charlotte/wp-content/uploads/2026/03/Hero-micro.jpg",
    gallery: [
      "https://viomedspa.com/charlotte/wp-content/uploads/2026/04/512x512.png",
      "https://viomedspa.com/charlotte/wp-content/uploads/2026/05/QUIZ-1200x1200.jpg",
      "https://viomedspa.com/charlotte/wp-content/uploads/2026/04/vio-face-1024x841.jpg",
      "https://viomedspa.com/charlotte/wp-content/uploads/2026/04/clubVIO-hero-2-150x150.png",
    ],
    source: "VIO Med Spa Charlotte official website",
  },
      "slk-aesthetic-medicine-nashville": {
    hero: "https://slkclinic.com/wp-content/uploads/white-logo-on-black-background.square.extraspace-jpeg.webp",
    gallery: [
      "https://slkclinic.com/wp-content/uploads/2022/10/jennifer-solo-photo-headshot-fall-photo-shoot-2020-112-1024x1024-1-1024x1024.jpg",
      "https://slkclinic.com/wp-content/uploads/2022/10/slk_white.png",
    ],
    source: "SLK Aesthetic Medicine official website",
  },
    "61five-health-wellness-nashville": {
    hero: "https://61five.com/wp-content/uploads/2022/07/61Five-Health-and-Wellness-Logo.svg",
    gallery: [
      "https://61five.com/wp-content/uploads/2023/01/IMG_0001.jpg",
      "https://61five.com/wp-content/uploads/2023/01/Nashville-IV-Therapy-Home-Page.png",
      "https://61five.com/wp-content/uploads/2022/06/IV-Therapy-Google-Ad-7.14.21-3-e1656018825211.png",
      "https://61five.com/wp-content/uploads/2022/10/Formally-61Five-Nashville-61Five-Health-Wellness.webp",
    ],
    source: "61Five Health & Wellness official website",
  },
        "skin-deep-med-spa-santa-monica": {
    hero: "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/hero-banner.jpg",
    gallery: [
      "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/Shop-Now-Teal.png",
      "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/kybella.jpg",
      "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/image-botox.jpg",
      "https://www.skindeepmedspa.com/wp-content/uploads/2021/02/cosmetic.jpg",
    ],
    source: "Skin Deep Med Spa official website",
  },
        "skinperfect-medical-sherman-oaks": {
    hero: "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/reviews-google2.png",
    gallery: [
      "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/medical-spa-face-2.jpg",
      "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/medical-spa-body-2.jpg",
      "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/medical-spa-skin.jpg",
      "https://skinperfectmedical.com/wp-content/themes/skinperfectmedical_com/static/images/medical-spa-men.jpg",
    ],
    source: "Skin Perfect Medical official website",
  },
          "skin-by-lovely-los-angeles": {
    hero: "https://www.skinbylovely.com/wp-content/uploads/2025/10/Skin-by-Lovely-Privacy.png",
    gallery: [
      "https://www.skinbylovely.com/wp-content/uploads/2020/09/HomePagePreview.jpg",
      "https://www.skinbylovely.com/wp-content/uploads/2024/03/About-1.png",
      "https://www.skinbylovely.com/wp-content/uploads/2024/03/Blog-1.png",
      "https://www.skinbylovely.com/wp-content/uploads/2024/03/Payment-Plans-1.png",
    ],
    source: "Skin by Lovely official website",
  },
        "laser-clinique-san-diego": {
    hero: "https://www.datocms-assets.com/44663/1617225017-og-feat.jpg",
    gallery: [
      "https://www.datocms-assets.com/44663/1721238803-p_page0image4-480x252.png?auto=format,compress&w=180",
      "https://www.datocms-assets.com/44663/1721238850-nbc_7_san_diego_2012.png?auto=format,compress&w=180",
      "https://www.datocms-assets.com/44663/1616178696-homepage3.jpg?auto=format,compress&w=500",
      "https://www.datocms-assets.com/44663/1616178683-homepage-injectable.jpg?auto=format,compress&w=500",
    ],
    source: "Laser Clinique official website",
  },
          "alastin-skincare-medspa-beverly-hills": {
    hero: "https://alastin.com/cdn/shop/files/MegaMenu_TriHex_Technology_400x_crop_center.jpg?v=1769536909",
    gallery: [
      "https://alastin.com/cdn/shop/files/MegaMenu_AntiAging_Skincare_400x_crop_center.jpg?v=1769536796",
      "https://alastin.com/cdn/shop/files/MegaMenu_Skincare_Quiz_400x_crop_center.jpg?v=1769536859",
      "https://alastin.com/cdn/shop/files/MegaMenu_Skincare_Provider_400x_crop_center.jpg?v=1769536987",
      "https://alastin.com/cdn/shop/files/MegaMenu_Press_400x_crop_center.jpg?v=1769537005",
    ],
    source: "Alastin Skincare Med Spa official website",
  },
        "persona-med-spa-houston": {
    hero: "https://cdn.prod.website-files.com/63ab588641b0cae734e30126/63c4e19127378123e87ee901_pexels-andrzej-gdula-11149812_1280.webp",
    gallery: [
      "https://cdn.prod.website-files.com/63cc46fa156c324ab6d90ce5/63cc5cb83a06967ab589ecc4_PersonaCulture-19%20copy_1920.jpg",
      "https://cdn.prod.website-files.com/63cc46fa156c324ab6d90ce5/63cc5cb8ea97be1490c9ab09_PersonaCulture-21%20copy_1920.jpg",
      "https://cdn.prod.website-files.com/6266dc8f72289b0ed9816362/6266dc8f72289b162581679e_shutterstock_1543602899_1024.jpg",
      "https://cdn.prod.website-files.com/63cc46fa156c324ab6d90ce5/63cc5c8d15116f84ad601c7b_PersonaCulture-2_2_1024.jpg",
    ],
    source: "Persona Med Spa official website",
  },
        "skinspirations-dallas": {
    hero: "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/a81d5a40-e6c6-459b-a7c4-80804f33a426/hero-services-01.jpg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/2acd6c5b-bd70-46f3-bfd1-c068daf1ba22/co-skincare-program-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/1aaa3c46-5a38-411b-be57-5bf0328b63d1/co-services-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/3e584e70-a71f-4d43-8189-63ecf2d04f98/co-tattoo-02.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/09b79aaa-62c0-48b7-9b8b-575436ba5335/co-skintight-01.jpg",
    ],
    source: "Skinspirations Dallas official website",
  },
        "juvia-med-spa-dallas": {
    hero: "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd390f9/67bcc0b34e7988ae1a35b0d1_google-verified-reviews.png",
    gallery: [
      "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd390f9/67fe609cf8365a4a79617e29_DSC05356.JPG",
      "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd390f9/67fe627c21cdee902ace0420_Untitled%20design.png",
      "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd3919a/67fe69c3bbcc29f4d2f03ef8_Untitled%20(720%20x%20960%20px).png",
      "https://cdn.prod.website-files.com/67bca5d7af7688bd3bd3919a/67fe6b20846be772f6158449_Untitled%20(720%20x%20960%20px)%20(1).png",
    ],
    source: "Juvia Med Spa official website",
  },
        "viva-day-spa-dallas": {
    hero: "https://www.vivadayspa.com/wp-content/uploads/2023/12/Viva-Day-Spa_New-Years-Resolutions_2000x635.jpg",
    gallery: [

    ],
    source: "Viva Day Spa + Med Spa Dallas official website",
  },
        "four-seasons-med-spa-austin": {
    hero: "https://img1.wsimg.com/isteam/ip/ff1625fb-a69f-4041-b5e2-bb72a863aebf/four%20saesons%20png.png",
    gallery: [

    ],
    source: "Four Seasons Med Spa Austin official website",
  },
        "viva-day-spa-austin": {
    hero: "https://www.vivadayspa.com/wp-content/uploads/2023/12/Viva-Day-Spa_New-Years-Resolutions_2000x635.jpg",
    gallery: [

    ],
    source: "Viva Day Spa + Med Spa Austin official website",
  },
            "skinspirations-houston": {
    hero: "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/6a037510-1836-4310-a2c9-139933db016b/hero-idx-1225.jpg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/853d2a28-cd7f-481e-b72b-90e839260d44/sp-package-03.webp",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/b0ff0067-acfd-43e0-aee7-6cda2fab9719/dr-elliott-md-patient-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/8479ba81-9312-4326-8924-cee2f6efa4e9/co-v-male-01.jpg",
      "https://images.squarespace-cdn.com/content/v1/67e3275166f1bf2a1f8f49c7/46e82890-9924-4910-9bb6-598e11838168/hero-pigment-03.jpg",
    ],
    source: "Skinspirations Houston official website — services",
  },
        "skinspirit-austin": {
    hero: "https://cdn.prod.website-files.com/64fb26e78d22031b6dda81de/6540bfbb8b854f25dbe5a42b_Skin-Spirit-Default-Open-Graph-Image.jpg",
    gallery: [
      "https://cdn.prod.website-files.com/6764496e34ff7106c11cc5cf/6764496e34ff7106c11cca38_our-story-hero-image.jpg",
      "https://cdn.prod.website-files.com/6764496e34ff7106c11cc5cf/6764496e34ff7106c11cca3b_our-story-image-1.jpg",
      "https://cdn.prod.website-files.com/6764496e34ff7106c11cc5cf/6764496e34ff7106c11cccbb_Our%20Story%20-%20Provider%20with%20Client.png",
      "https://cdn.prod.website-files.com/6764496e34ff7106c11cc5cf/6764496e34ff7106c11cca3c_our-story-image-3.jpg",
    ],
    source: "SkinSpirit Austin official website",
  },
        "eden-med-spa-downtown-nyc": {
    hero: "https://edenmedspanyc.com/wp-content/uploads/2024/04/map-section-scaled.jpg",
    gallery: [
      "https://edenmedspanyc.com/wp-content/uploads/2024/04/hp-stone.png",
      "https://edenmedspanyc.com/wp-content/uploads/2024/04/body.png",
      "https://edenmedspanyc.com/wp-content/uploads/2024/04/massage.png",
      "https://edenmedspanyc.com/wp-content/uploads/2024/04/waxing.png",
    ],
    source: "Eden Med Spa official website",
  },
        "novaskin-medspa-miami-import": {
    hero: "https://novaskinmedspa.com/wp-content/uploads/2026/01/LOGO-2.svg",
    gallery: [
      "https://novaskinmedspa.com/wp-content/uploads/2024/05/midsection_image_v1.png",
      "https://novaskinmedspa.com/wp-content/uploads/2025/07/laser-treatments-600x400-1.jpg",
      "https://novaskinmedspa.com/wp-content/uploads/2025/07/injectables-miami-600x400-1.jpg",
      "https://novaskinmedspa.com/wp-content/uploads/2025/07/skin-tightening-600x400-1.png",
    ],
    source: "NovaSkin Med Spa official website",
  },
        "viva-md-atlanta": {
    hero: "https://static.wixstatic.com/media/8d1c2f_69416545b9a243a6affd038879d5849f~mv2.jpeg/v1/crop/x_168,y_121,w_738,h_1290/fill/w_296,h_512,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/WhatsApp%20Image%202026-05-15%20at%209_38_13%20PM.jpeg",
    gallery: [
      "https://static.wixstatic.com/media/af61e4_2697a0cedaba49bd83deddb0fc97d60c~mv2.png/v1/crop/x_33,y_38,w_1775,h_2579/fill/w_370,h_536,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/processed-AEB3A42A-18EF-4731-9179-4537DA.png",
      "https://static.wixstatic.com/media/af61e4_8d42f150ac404fd1b9f92992ce845546~mv2.png/v1/crop/x_0,y_1,w_635,h_798/fill/w_328,h_412,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/skincare-woman-and-needle-for-botox-cosm.png",
      "https://static.wixstatic.com/media/8d1c2f_6e6730fa6c714db997a603ad547b6869~mv2.png/v1/crop/x_137,y_0,w_727,h_1000/fill/w_537,h_610,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/20084846_Ha5Moisturizer_Lifestyle_1x1.png",
      "https://static.wixstatic.com/media/nsplsh_33544c6c5f3937484e4a6f~mv2_d_3276_4096_s_4_2.jpg/v1/crop/x_0,y_410,w_3276,h_3276/fill/w_36,h_38,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/Image%20by%20Aiony%20Haust.jpg",
    ],
    source: "VIVA MD official website",
  },
        "the-k-spa-atlanta": {
    hero: "https://www.thekspa.com/wp-content/uploads/2025/05/office-32.webp",
    gallery: [
      "https://www.thekspa.com/wp-content/uploads/2026/02/Castle-Connolly-2026-license-confirmed.jpg",
      "https://www.thekspa.com/wp-content/uploads/2026/02/Castle-Connolly-2026.png",
      "https://www.thekspa.com/wp-content/uploads/2026/02/2026-top-doctors-2-license-confirmed.jpg",
      "https://www.thekspa.com/wp-content/uploads/2018/03/botox-wrinkle-treatments.jpg",
    ],
    source: "The K Spa official website",
  },
        "inara-med-spa-long-island": {
    hero: "https://inaramedspa.com/wp-content/uploads/2025/11/WhatsApp-Image-2025-09-01-at-08.57.53_31044b54-e1764413018269.jpg",
    gallery: [
      "https://inaramedspa.com/wp-content/uploads/2024/11/inara-medical-spa-300x300.png",
      "https://inaramedspa.com/wp-content/uploads/2025/11/WhatsApp-Image-2025-07-19-at-09.36.23_b55f5e9d.jpg",
      "https://inaramedspa.com/wp-content/uploads/2025/11/Group-1-copy.png",
      "https://inaramedspa.com/wp-content/uploads/2025/11/WhatsApp-Image-2025-09-01-at-08.57.53_31044b54-e1764413018269-943x1024.jpg",
    ],
    source: "Inara Med Spa official website",
  },
        "tenth-avenue-aesthetics-li": {
    hero: "https://tenthavenueaesthetics.com/wp-content/uploads/2024/07/logo-tenth-avenue-aesthetics-grey-logo-image-in-east-northport-ny-and-islip-ny.png",
    gallery: [
      "https://tenthavenueaesthetics.com/wp-content/uploads/2024/05/Wrinkle-Relaxers-services-in-east-northport-islip-ny-by-Tenth-Avenue.webp",
      "https://tenthavenueaesthetics.com/wp-content/uploads/2024/05/Dermal-Filler-services-east-northport-islip-ny-by-Tenth-Avenue.webp",
      "https://tenthavenueaesthetics.com/wp-content/uploads/2024/05/tenth-avenue-aesthetics-weight-loss-services-in-east-northport-ny-and-islip-ny.webp",
      "https://tenthavenueaesthetics.com/wp-content/plugins/widget-google-reviews/assets/img/guest.png",
    ],
    source: "Tenth Avenue Aesthetics official website",
  },
        "bella-medspa-atlanta": {
    hero: "https://bellamedspa.com/storage/2025/10/Social-Share-img-In-Clarksville-TN.png",
    gallery: [
      "https://bellamedspa.com/storage/2025/09/allergannumber1-In-Clarksville-TN.webp",
      "https://bellamedspa.com/storage/2025/09/boc2024-In-Clarksville-TN.webp",
      "https://bellamedspa.com/storage/2025/09/clarksville-communityvotes-In-Clarksville-TN.webp",
      "https://bellamedspa.com/storage/2025/09/clarksvillesbest-In-Clarksville-TN.webp",
    ],
    source: "Bella Medspa official website",
  },
            "look-lab-med-spa-phoenix": {
    hero: "https://looklab.com/wp-content/uploads/2026/01/Look-Lab-Injectables-Botox-1-6061.jpg",
    gallery: [
      "https://looklab.com/wp-content/uploads/2026/01/Look-Lab-Interior-Lobby-1-4697.jpg",
      "https://looklab.com/wp-content/uploads/2026/01/Look-Lab-Misc-Consult-Location-2-0043.jpg",
      "https://looklab.com/wp-content/uploads/2026/01/Look-Lab-Injectables-Hydro-Facial-Location-1-7659.jpg",
      "https://looklab.com/wp-content/uploads/2026/01/Look-Lab-Signature-Facial-Location-1-7282.jpg",
    ],
    source: "Look Lab Med Spa official website — services",
  },
          "scottsdale-med-spa": {
    hero: "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC03078-scaled-1.webp?fit=800%2C534&amp;ssl=1",
    gallery: [
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/09/In-the-Zona.png?fit=800%2C176&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC02908-scaled-1.webp?fit=800%2C534&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC02839-1-scaled-1.webp?fit=800%2C534&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/12/6110d39bd6e4ba5cdc075ca4_zona-horizontal_0002_Before-Dysport.webp?fit=768%2C538&amp;ssl=1",
    ],
    source: "Scottsdale Med Spa official website",
  },
          "zona-med-spa-scottsdale": {
    hero: "https://zonamedspa.com/wp-content/uploads/2025/09/Zona-Logo.webp",
    gallery: [
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/09/In-the-Zona.png?fit=800%2C176&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC03078-scaled-1.webp?fit=800%2C534&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC02908-scaled-1.webp?fit=800%2C534&amp;ssl=1",
      "https://i0.wp.com/zonamedspa.com/wp-content/uploads/2025/07/DSC02839-1-scaled-1.webp?fit=800%2C534&amp;ssl=1",
    ],
    source: "Zona Med Spa official website",
  },
        "radiance-med-spa-atlanta": {
    hero: "https://www.radiancemedspa.com/wp-content/uploads/2025/01/cropped-small-logo-4-radiance-medspa-in-Belleair-Bluff-Florida-e1685048412501.webp",
    gallery: [
      "https://www.radiancemedspa.com/wp-content/uploads/2026/05/BB-20-Anniversary.png",
      "https://www.radiancemedspa.com/wp-content/uploads/2025/07/front-desk-at-bellair-bluffs-fl-1.jpg",
      "https://www.radiancemedspa.com/wp-content/uploads/2026/06/Stephanie-Schlageter-new.jpg",
      "https://www.radiancemedspa.com/wp-content/uploads/2026/06/wellness-treatments-in-belleair-bluffs1.jpg",
    ],
    source: "Radiance Med Spa official website",
  },
        "gleam-med-spa-denver": {
    hero: "https://gleammedspa.com/wp-content/uploads/2024/09/Gleam-Medical-Spa-Potenza-1217.jpg",
    gallery: [
      "https://gleammedspa.com/wp-content/uploads/2025/05/E-Gift-Card-Gleam-Medical-Spa-in-Denver-CO.png",
    ],
    source: "Gleam Med Spa official website",
  },
          "north-scottsdale-med-spa": {
    hero: "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/8bfe95c5-7c4c-4402-9902-009e7052e223/North+Scottsdale+Medspa+Phoenix%2C+AZ%2C+85054+%7C+PRP+Hair+Restoration+Before+and+After.jpg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/5eea5964-8ce3-45a6-a136-a45403c33526/North+Scottsdale+Medspa+Phoenix%2C+AZ%2C+85054+%7C+Laser+Hair+Removal+Before+and+After.png",
      "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/e3e31737-d9f1-4ca2-979e-b5f8f07ca342/North+Scottsdale+Medspa+Phoenix%2C+AZ%2C+85054+%7C+Restylane+Defyne+Before+and+After.jpg",
      "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/906c573b-fa2e-4594-b10c-675e618186cf/North+Scottsdale+Medspa+Phoenix%2C+AZ%2C+85054+%7C+Restylane+Refyne+Before+and+After.jpg",
      "https://images.squarespace-cdn.com/content/v1/6835f653958ab2782be44660/2a4729e9-015f-4a20-bde3-ad6737aece37/North+Scottsdale+Medspa+Phoenix%2C+AZ%2C+85054+%7C+IPL+Photofacial+Before+and+After.jpg",
    ],
    source: "North Scottsdale Med Spa official website",
  },
        "goldcoast-medspa-chicago": {
    hero: "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/Hero_home_web.jpg",
    gallery: [
      "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/service-2.png",
      "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/service-3.png",
      "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/service-4.png",
      "https://www.goldcoastmedspa.com/wp-content/uploads/2023/11/service-1.png",
    ],
    source: "GOLDCOAST medspa official website",
  },
        "esse-medspa-denver": {
    hero: "https://static.wixstatic.com/media/d27ab1_4a6e581117fd4a03bda14a44a8a77725%7Emv2.jpg/v1/fit/w_2500,h_1330,al_c/d27ab1_4a6e581117fd4a03bda14a44a8a77725%7Emv2.jpg",
    gallery: [
      "https://static.wixstatic.com/media/11062b_ca1d837ce7194421b781ee7384061a8e~mv2.png/v1/fill/w_28,h_28,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/11062b_ca1d837ce7194421b781ee7384061a8e~mv2.png",
      "https://static.wixstatic.com/media/11062b_1f7ed8bc7b004201970df69f9eeda689~mv2.png/v1/fill/w_28,h_28,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/11062b_1f7ed8bc7b004201970df69f9eeda689~mv2.png",
      "https://static.wixstatic.com/media/d27ab1_f98ca29fa70d456690fc6733b1a50c8f~mv2.png/v1/fill/w_49,h_39,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/61F12450-4BF6-4B96-A595-CB3B93C31E73_PNG.png",
      "https://static.wixstatic.com/media/11062b_890901542a134c538db56676ac549710~mv2.jpg/v1/fill/w_147,h_98,al_c,q_80,usm_0.66_1.00_0.01,blur_2,enc_avif,quality_auto/11062b_890901542a134c538db56676ac549710~mv2.jpg",
    ],
    source: "Esse Medspa official website",
  },
        "old-town-med-spa-chicago": {
    hero: "https://www.oldtownmedspa.com/wp-content/uploads/2024/03/logo-featimg.png",
    gallery: [
      "https://www.oldtownmedspa.com/wp-content/uploads/2024/04/welcome-img@1.2x.jpg",
      "https://www.oldtownmedspa.com/wp-content/uploads/2024/03/drsGharbi@1.2x.jpg-1.jpg",
      "https://www.oldtownmedspa.com/wp-content/uploads/2024/03/specials-img@1.2x.jpg-1.jpg",
      "https://www.oldtownmedspa.com/wp-content/uploads/2024/03/MD-brothers.png",
    ],
    source: "Old Town Med Spa official website",
  },
        "river-north-wellness-med-spa": {
    hero: "https://i0.wp.com/box2308.temp.domains/~mikenowa/rivernorthwellness/wp/wp-content/uploads/2021/07/Bonnywelcomepage-1024x751.png?resize=750%2C550",
    gallery: [

    ],
    source: "River North Wellness and Med Spa official website",
  },
        "aesthetics-lab-las-vegas": {
    hero: "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508113985391-GDLPMA0LSDUJXH8X9T0J/Aesthetics+Lab.jpeg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508222950753-JBY2A3976XTX7GSJ1CVI/_N4A8789.jpg.jpeg",
      "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508481430527-6CVO88U7ZDTLSMPUM6IV/_N4A8752.jpg",
      "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508481665048-BV87A6XK3IKLZA6B4KW2/_N4A8731.jpg",
    ],
    source: "The Aesthetics Lab official website",
  },
        "kalon-laser-aesthetics-denver": {
    hero: "https://www.kalonlaser.com/_static_/background/og-feat.png",
    gallery: [
      "https://www.kalonlaser.com/_static_/masthead/masthead-03.jpg",
      "https://www.kalonlaser.com/_static_/masthead/masthead-design.jpg",
      "https://www.kalonlaser.com/_static_/masthead/masthead-04.jpg",
      "https://www.kalonlaser.com/_static_/masthead/masthead-02.jpg",
    ],
    source: "Kalon Laser Aesthetics official website",
  },
        "bluepoint-medical-spa-las-vegas": {
    hero: "https://bluepointmedicalspa.com/wp-content/uploads/2026/03/Frame-1-12.png",
    gallery: [
      "https://bluepointmedicalspa.com/wp-content/uploads/2025/12/Vector-1.png",
      "https://bluepointmedicalspa.com/wp-content/uploads/2025/12/Layer_1.png",
      "https://bluepointmedicalspa.com/wp-content/uploads/2025/12/Capa_1-1.png",
      "https://bluepointmedicalspa.com/wp-content/uploads/2025/12/Mask-Group.png",
    ],
    source: "bluepoint medical spa official website",
  },
        "skinovatio-ravenswood-chicago": {
    hero: "https://www.skinovatio.com/wp-content/uploads/2025/01/google-img.png",
    gallery: [
      "https://www.skinovatio.com/wp-content/uploads/2025/02/PDO-Lifting-threads.png",
      "https://www.skinovatio.com/wp-content/uploads/2025/02/Chemical-Peel.png",
      "https://www.skinovatio.com/wp-content/uploads/2025/02/Deoxycholic-Acid.png",
      "https://www.skinovatio.com/wp-content/uploads/2025/02/after-before-img8.jpg",
    ],
    source: "Skinovatio Medical Spa official website",
  },
        "prestige-med-spa-charlotte": {
    hero: "https://prestigemedicalspacharlotte.com/wp-content/uploads/2026/04/ChIJTXpVE6GbVogRKVVGAylsmyQ_eb53485dbef3922b80c0e702a82a62f6.jpg",
    gallery: [
      "https://prestigemedicalspacharlotte.com/wp-content/uploads/2026/06/cropped-1533691-270x270.webp",
      "https://prestigemedicalspacharlotte.com/wp-content/uploads/2026/04/in-tracksuit-38AXHN5.jpg",
      "https://prestigemedicalspacharlotte.com/wp-content/uploads/2026/04/spa-salon-CGTPC6A.jpg",
      "https://prestigemedicalspacharlotte.com/wp-content/plugins/widget-google-reviews/assets/img/guest.png",
    ],
    source: "Prestige Med Spa and Wellness official website",
  },
        "nashville-skin-company": {
    hero: "https://cdn.prod.website-files.com/678e714af48f130856f60309/68caf43ee32af0f96aaa0987_NASHVILLE%E2%80%99S%20TOP%20MED%20SPA.avif",
    gallery: [
      "https://cdn.prod.website-files.com/678e714af48f130856f603c3/68cb66ff71b79dec22013703_iStock-536813721.jpg",
      "https://cdn.prod.website-files.com/678e714af48f130856f603c3/687af60b19d464a856892d9e_iStock-2189093607.jpg",
      "https://cdn.prod.website-files.com/678e714af48f130856f603c3/687b2589c923db9720b73f44_Halo.jpg",
      "https://cdn.prod.website-files.com/678e714af48f130856f603c3/687afa4c242a75bd8a44f836_iStock-2184231975.jpg",
    ],
    source: "Nashville Skin Company official website",
  },
        "blue-water-spa-raleigh": {
    hero: "https://www.bluewaterspa.com/wp-content/uploads/2018/08/cropped-hdbtTGD2_400x400-270x270.jpg",
    gallery: [
      "https://www.bluewaterspa.com/wp-content/uploads/2023/10/bws_homegirls2-1500x644-1.jpg",
      "https://www.bluewaterspa.com/wp-content/uploads/2026/03/WakeLivingAward.webp",
      "https://www.bluewaterspa.com/images/forplanet_member_nb.png",
      "https://www.bluewaterspa.com/images/voters_choice_nb.png",
    ],
    source: "Blue Water Spa official website",
  },
        "evolve-medspa-nashville": {
    hero: "https://evolvemedspa.com/wp-content/uploads/2025/06/fall-deals-hero.jpg",
    gallery: [
      "https://evolvemedspa.com/wp-content/uploads/2025/11/b4c56330-ac5e-4a7b-9941-ba2af61781b9-e1764171070960.png",
      "https://evolvemedspa.com/wp-content/uploads/2024/06/evolve-hero-xl.webp",
      "https://evolvemedspa.com/wp-content/uploads/2026/06/Evolve-Med-Spa-Old-Bridge-NJ-Lobby-1.webp",
      "https://evolvemedspa.com/wp-content/uploads/2024/06/injectables-01.webp",
    ],
    source: "Evolve Medspa official website",
  },
        "ageless-remedies-raleigh": {
    hero: "https://www.datocms-assets.com/161788/1749087828-open-graph-card.jpg",
    gallery: [
      "https://www.datocms-assets.com/161788/1751477594-intro-accent-2.jpg?auto=format,compress&w=474",
      "https://www.datocms-assets.com/161788/1750866705-homepage-module-ageless.jpg?auto=format,compress&w=1135",
      "https://www.datocms-assets.com/161788/1751477520-intro-accent.jpg?auto=format,compress&w=235",
      "https://www.datocms-assets.com/161788/1750958706-service-card_injectables.jpg?auto=format,compress&w=1226",
    ],
    source: "Ageless Remedies Med Spa official website",
  },
        "skin-pharm-nashville": {
    hero: "https://skinpharm.com/cdn/shop/files/Sharing_Img_1200x.png?v=1732576974",
    gallery: [
      "https://skinpharm.com/cdn/shop/files/Book_Mobile_Nav.png?v=1760036937",
      "https://skinpharm.com/cdn/shop/files/Skin_Care_Mobile_Nav.png?v=1760035756",
      "https://skinpharm.com/cdn/shop/t/381/assets/user.png?v=89420895277225690201782737789",
      "https://skinpharm.com/cdn/shop/files/Sets_nav_400x.png?v=1760034782",
    ],
    source: "Skin Pharm official website",
  },
        "canvas-skin-nashville": {
    hero: "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/13fa7455-c36c-4d40-ad2a-1a560c5e1d17/courtney+2024.jpg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/1777037922407-NPPBI948N1I0I7VNXV01/image-asset.jpeg",
      "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/1776959278165-S8EDYZAXMHSS85PGMMN7/image-asset.jpeg",
      "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/1776870140577-KEC4ACZVBNNBSLJ6I9PV/image-asset.jpeg",
      "https://images.squarespace-cdn.com/content/v1/62b176d68f40373003b39188/1776786440960-OZEFGPT43II8ZF7IIB4V/image-asset.jpeg",
    ],
    source: "Canvas Skin official website",
  },
            "denver-dream-medspa": {
    hero: "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/1725720289071-Q10Y4S2C1E9V80F2J241/Academy+prompts+photo+%286%29.png",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/1769031446744-8KJYH5FK09DHBAMNAUJB/35.png",
      "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/1781211675199-6E8N8HDJ4UIVHRTXKNRF/before+and+after+arm+hair+laser+hair+removal.png",
      "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/1781211675219-7RGPYCP9W8ODY92399OS/before+and+after+chin+hair+laser+hair+removal+PCOS.png",
      "https://images.squarespace-cdn.com/content/v1/6217153a0bdc9d5626c01a48/1781211675185-HM7WAI6HSUEJKY911K4E/before+and+after+chin+hair+with+laser+hair+removal.png",
    ],
    source: "Denver Dream Medspa official website — services",
  },
    "dermatology-cosmetic-laser-brentwood": {
    hero: "https://www.laskinmd.com/wp-content/uploads/2018/02/dr-gene-rubinstein.jpg",
    gallery: [
      "https://www.laskinmd.com/wp-content/themes/ui_laskinmd/images/skin-rejuvenation.jpg",
      "https://www.laskinmd.com/wp-content/uploads/2026/06/shutterstock_2643582583-300x158.jpg",
      "https://www.laskinmd.com/wp-content/themes/ui_laskinmd/images/btsb/rmd-back-to-skin-basics.jpg",
      "https://www.laskinmd.com/wp-content/themes/ui_laskinmd/images/btsb/rmd-back-to-skin-basics-vit-a.jpg",
    ],
    source: "Dermatology & Cosmetic Laser Center official website",
  },
  "revive-med-spa-mission-valley": {
    hero: "",
    gallery: [

    ],
    source: "Provider official website",
  },
  "bold-confidence-aesthetics-san-diego": {
    hero: "",
    gallery: [

    ],
    source: "Provider official website",
  },
    "sente-bella-medspa-downtown-sd": {
    hero: "https://sentebellaspa.com/wp-content/uploads/2022/11/BodyWraps.jpg",
    gallery: [
      "https://sentebellaspa.com/wp-content/uploads/2022/11/MedSpa1.webp",
      "https://sentebellaspa.com/wp-content/uploads/2022/11/Massage.jpg",
      "https://sentebellaspa.com/wp-content/uploads/2022/11/medspa.jpg",
      "https://sentebellaspa.com/wp-content/uploads/2022/11/Spa1.webp",
    ],
    source: "Sente Bella MedSpa official website",
  },
    "dermalogix-med-spa-houston": {
    hero: "https://htxmdspa.com/wp-content/uploads/2026/02/MedSpa_Post_Template-1.jpg",
    gallery: [
      "https://htxmdspa.com/wp-content/uploads/2026/02/Facial-1.jpg",
    ],
    source: "Dermalogix Med Spa official website",
  },
    "radiant-beauty-health-manhattan": {
    hero: "https://radiantbeautyandhealth.com/wp-content/uploads/2022/09/Radiant-Beauty-and-Health-Eastchester-NY-West-Hartford-CT-Trumbull-CT-Oxford-CT.jpg",
    gallery: [
      "https://radiantbeautyandhealth.com/wp-content/uploads/2022/09/y-lift-header-mobile.jpg",
      "https://radiantbeautyandhealth.com/wp-content/uploads/2022/09/manhattan-spa.jpg",
      "https://radiantbeautyandhealth.com/wp-content/uploads/2022/09/manhattan-10-150x150.jpg",
      "https://radiantbeautyandhealth.com/wp-content/uploads/2022/09/manhattan-9-150x150.jpg",
    ],
    source: "Radiant Beauty & Health official website",
  },
    "manhattan-aesthetics-36th-st": {
    hero: "https://www.manhattan-aesthetics.com/wp-content/uploads/2025/11/hero-banner.jpg.webp",
    gallery: [
      "https://www.manhattan-aesthetics.com/wp-content/themes/manhattan-aesthetics-2024/img/emsculpt-neo-benefits.jpg",
      "https://www.manhattan-aesthetics.com/wp-content/themes/manhattan-aesthetics-2024/img/vid-bg.jpg",
      "https://www.manhattan-aesthetics.com/wp-content/themes/manhattan-aesthetics-2024/img/body-treatments.jpg",
      "https://www.manhattan-aesthetics.com/wp-content/themes/manhattan-aesthetics-2024/img/face-treatments.jpg",
    ],
    source: "Manhattan Aesthetics official website",
  },
    "manhattan-laser-spa-ues": {
    hero: "https://manhattan-laser.com/wp-content/uploads/2025/01/google.png",
    gallery: [
      "https://manhattan-laser.com/wp-content/uploads/2025/01/IMG-20250111-WA0007.jpg",
      "https://manhattan-laser.com/wp-content/uploads/2025/01/Untitled-3-e1738511997246.png",
      "https://manhattan-laser.com/wp-content/uploads/2025/01/Dr.-Roman-Khattak-CEO-1024x1024.png",
      "https://manhattan-laser.com/wp-content/uploads/2025/01/Christina-Caldarola-Licensed-Aesthetician-1024x1024.png",
    ],
    source: "Manhattan Laser Spa official website",
  },
  "koru-wellness-aesthetics-nyc": {
    hero: "",
    gallery: [

    ],
    source: "Provider official website",
  },
  "miracleface-medspa-midtown": {
    hero: "",
    gallery: [

    ],
    source: "Provider official website",
  },
    "vital-medical-care-aesthetics-li": {
    hero: "https://vmaesthetics.com/wp-content/uploads/2021/08/Doc-best.jpeg",
    gallery: [
      "https://vmaesthetics.com/wp-content/uploads/2024/03/481235788_932213962326456_1976091433915229598_n.jpg",
      "https://vmaesthetics.com/wp-content/uploads/2024/03/cropped-481235788_932213962326456_1976091433915229598_n-270x270.jpg",
      "https://vmaesthetics.com/wp-content/uploads/2024/01/testimonials-1.webp",
      "https://vmaesthetics.com/wp-content/uploads/2021/08/Doc-best-260x260.jpeg",
    ],
    source: "Vital Medical Care & Aesthetics official website",
  },
    "skinceuticals-skinlab-atlanta": {
    hero: "https://www.skinatl.com/wp-content/uploads/2023/07/Hero_web.jpg",
    gallery: [
      "https://www.skinatl.com/wp-content/uploads/2024/02/sig-facials-and-peels-scaled-e1708031060663-1.jpg",
      "https://www.skinatl.com/wp-content/uploads/2024/01/SL-ATL-Injectable-treatment-op.jpg",
      "https://www.skinatl.com/wp-content/uploads/2024/01/SL-ATL-REJuVENATION-op.jpg",
      "https://www.skinatl.com/wp-content/uploads/2025/01/Laser-treatment_moxi.jpg",
    ],
    source: "SkinCeuticals SkinLab Atlanta official website",
  },
    "alchemy-med-bar-scottsdale": {
    hero: "https://images.squarespace-cdn.com/content/v1/69c9b6912e55d654085fdf4c/99ee75cd-44b0-40c2-a579-1996734508e2/Blog+Banner+for+Website+Content+%281%29.png",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/69c9b6912e55d654085fdf4c/bf3d1769-9090-49ab-8de2-545e6733a68f/Alchemy+transparent+%281%29.png?format=1500w",
      "https://images.squarespace-cdn.com/content/v1/69c9b6912e55d654085fdf4c/cbdc2f0f-0885-4f45-b575-97728beeddfc/HDR_6490.jpg",
      "https://images.squarespace-cdn.com/content/v1/69c9b6912e55d654085fdf4c/409666ca-dafd-4b89-b7d6-2e5275d74513/image-asset.jpeg",
      "https://images.squarespace-cdn.com/content/v1/69c9b6912e55d654085fdf4c/44be48c5-6ff6-4a72-b0fc-cdeafd634514/DSC_3609-2.jpg",
    ],
    source: "Alchemy Med Bar & Medical Spa official website — services",
  },
  "essence-medspa-chicago": {
    hero: "",
    gallery: [

    ],
    source: "Provider official website",
  },
    "lume-med-spa-lakeview": {
    hero: "https://lume-wellness.com/wp-content/uploads/2026/05/Lume-wellness-chicacgo_op.jpg",
    gallery: [
      "https://lume-wellness.com/wp-content/uploads/2025/01/EmFace-RF-1new.jpg",
      "https://lume-wellness.com/wp-content/uploads/2025/01/rf-microneedling.webp",
      "https://lume-wellness.com/wp-content/uploads/2024/10/Lume-Wellness-Exion-0532.jpg",
      "https://lume-wellness.com/wp-content/uploads/2024/09/Exion-Face-0230.jpg",
    ],
    source: "Lume Med Spa Lakeview official website",
  },
    "simply-radiant-med-spa-las-vegas": {
    hero: "https://simplyradiant-lv.com/wp-content/uploads/xeomin-simply-radiant-resized-768x414.jpg",
    gallery: [
      "https://simplyradiant-lv.com/wp-content/uploads/collagen-induction-resized-1024x1024.jpg",
      "https://simplyradiant-lv.com/wp-content/uploads/collagen-induction-resized-768x414.jpg",
      "https://simplyradiant-lv.com/wp-content/uploads/facials-las-vegas-resized-768x414.jpg",
      "https://simplyradiant-lv.com/wp-content/uploads/chemical-peels-las-vegas-768x414.jpg",
    ],
    source: "Simply Radiant Med Spa official website",
  },
    "flawless-medspa-las-vegas": {
    hero: "https://www.flawlessmedspas.com/wp-content/uploads/2022/09/insta-follow-white.png",
    gallery: [
      "https://www.flawlessmedspas.com/wp-content/uploads/2025/02/header-img-1-mobile.jpg",
      "https://www.flawlessmedspas.com/wp-content/uploads/2022/09/insta-follow-white-1.png",
      "https://www.flawlessmedspas.com/wp-content/uploads/2026/05/vip-bg-desktop-1-1024x683.jpg",
      "https://www.flawlessmedspas.com/wp-content/uploads/2026/05/qr-image-2.jpg",
    ],
    source: "Flawless Medspa Las Vegas official website",
  },
    "skin-society-las-vegas": {
    hero: "https://cdn.prod.website-files.com/65a6cb75d160d3528039e306/6934b6ef7471cc9649c995cc_Skin%20Las%20Vegas%20Med%20Spa%20-%20Best%20Med%20Spa%20Near%20you.avif",
    gallery: [
      "https://cdn.prod.website-files.com/65a6cb75d160d3528039e306/65a6e3357fc449bcd4ac4d09_Skin%20Las%20Vegas%20Med%20Spa.webp",
      "https://cdn.prod.website-files.com/65a6cb75d160d3528039e306/65a6d92c573f785b5445d8d1_Med%20Spa%20In%20Las%20Vegas%20%20Skin%20Las%20Vegas%20Med%20Spa.webp",
      "https://cdn.prod.website-files.com/65a6cb75d160d3528039e306/65a6e6415e93d469cb6ac806_Skin%20Las%20Vegas%20Med%20Spa%20%20Med%20Spa%20Near%20You.webp",
      "https://cdn.prod.website-files.com/65a6cb75d160d3528039e306/65a6e370a38dfda50e5abd1c_Skin%20Las%20Vegas%20Med%20Spa%20%20Visit%20Us.webp",
    ],
    source: "Skin Society Las Vegas official website",
  },
  "glo-de-vie-med-spa-raleigh": {
    hero: "",
    gallery: [

    ],
    source: "Provider official website",
  },
    "elase-med-spa-raleigh": {
    hero: "https://elase.com/wp-content/uploads/2025/10/or-181-1-e1762894553734.jpg",
    gallery: [
      "https://elase.com/wp-content/uploads/2024/03/cropped-ELASE_EMBLEM_Black-2-270x270.png",
      "https://elase.com/wp-content/uploads/2024/03/Elase-2024-Studio-Group-01-4505-960x720.jpg",
      "https://elase.com/wp-content/uploads/2024/03/231115_Amara_124-960x700.jpg",
      "https://elase.com/wp-content/uploads/2024/02/spa_shoot3546-960x640.jpg",
    ],
    source: "Elase Med Spa official website",
  },
  "nsi-wellness-aesthetics-nashville": {
    hero: "",
    gallery: [

    ],
    source: "Provider official website",
  },
    "bodylase-charlotte": {
    hero: "https://i.ytimg.com/vi/RFyWMb2JldQ/hqdefault.jpg",
    gallery: [

    ],
    source: "BodyLase Med Spa official website",
  },
};

/** Fallback Unsplash hero IDs for nationwide listings without verified og images. */
export const NATIONWIDE_SPA_IMAGE_FALLBACKS: Record<string, string> = {
  "skinly-aesthetics-upper-east-side-nyc": "photo-1570172619644-dfd03ed5d881",
  "skin-by-lovely-los-angeles": "photo-1570172619644-dfd03ed5d881",
  "novaskin-medspa-miami-import": "photo-1629909613654-28e377c37b09",
  "alastin-skincare-medspa-beverly-hills": "photo-1519823551278-64ac92734fb1",
  "skinperfect-medical-sherman-oaks": "photo-1487412947147-5cebf100ffc2",
  "dermatology-cosmetic-laser-brentwood": "photo-1516975080664-ed2fc6a32937",
  "skin-deep-med-spa-santa-monica": "photo-1544161515-4ab6ce6db874",
  "revive-med-spa-mission-valley": "photo-1612817288484-6f916006741a",
  "bold-confidence-aesthetics-san-diego": "photo-1570172619644-dfd03ed5d881",
  "sente-bella-medspa-downtown-sd": "photo-1515377905703-c4788e51af15",
  "laser-clinique-san-diego": "photo-1612349317150-e413f6a5b16d",
  "persona-med-spa-houston": "photo-1522335789203-aabd1fc54bc9",
  "skinspirations-houston": "photo-1556228578-0d85b1a4d571",
  "dermalogix-med-spa-houston": "photo-1608571423902-eed4a5ad8108",
  "viva-day-spa-dallas": "photo-1556228720-195a672e8a03",
  "skinspirations-dallas": "photo-1570172619644-dfd03ed5d881",
  "juvia-med-spa-dallas": "photo-1519823551278-64ac92734fb1",
  "viva-day-spa-austin": "photo-1487412947147-5cebf100ffc2",
  "skinspirit-austin": "photo-1516975080664-ed2fc6a32937",
  "four-seasons-med-spa-austin": "photo-1629909613654-28e377c37b09",
  "radiant-beauty-health-manhattan": "photo-1544161515-4ab6ce6db874",
  "manhattan-aesthetics-36th-st": "photo-1612817288484-6f916006741a",
  "eden-med-spa-downtown-nyc": "photo-1570172619644-dfd03ed5d881",
  "manhattan-laser-spa-ues": "photo-1515377905703-c4788e51af15",
  "koru-wellness-aesthetics-nyc": "photo-1612349317150-e413f6a5b16d",
  "miracleface-medspa-midtown": "photo-1522335789203-aabd1fc54bc9",
  "vital-medical-care-aesthetics-li": "photo-1556228578-0d85b1a4d571",
  "tenth-avenue-aesthetics-li": "photo-1608571423902-eed4a5ad8108",
  "inara-med-spa-long-island": "photo-1556228720-195a672e8a03",
  "viva-md-atlanta": "photo-1570172619644-dfd03ed5d881",
  "the-k-spa-atlanta": "photo-1519823551278-64ac92734fb1",
  "bella-medspa-atlanta": "photo-1487412947147-5cebf100ffc2",
  "radiance-med-spa-atlanta": "photo-1516975080664-ed2fc6a32937",
  "skinceuticals-skinlab-atlanta": "photo-1629909613654-28e377c37b09",
  "look-lab-med-spa-phoenix": "photo-1544161515-4ab6ce6db874",
  "scottsdale-med-spa": "photo-1612817288484-6f916006741a",
  "north-scottsdale-med-spa": "photo-1570172619644-dfd03ed5d881",
  "alchemy-med-bar-scottsdale": "photo-1515377905703-c4788e51af15",
  "zona-med-spa-scottsdale": "photo-1612349317150-e413f6a5b16d",
  "denver-dream-medspa": "photo-1522335789203-aabd1fc54bc9",
  "gleam-med-spa-denver": "photo-1556228578-0d85b1a4d571",
  "kalon-laser-aesthetics-denver": "photo-1608571423902-eed4a5ad8108",
  "esse-medspa-denver": "photo-1556228720-195a672e8a03",
  "goldcoast-medspa-chicago": "photo-1570172619644-dfd03ed5d881",
  "old-town-med-spa-chicago": "photo-1519823551278-64ac92734fb1",
  "essence-medspa-chicago": "photo-1487412947147-5cebf100ffc2",
  "river-north-wellness-med-spa": "photo-1516975080664-ed2fc6a32937",
  "skinovatio-ravenswood-chicago": "photo-1629909613654-28e377c37b09",
  "lume-med-spa-lakeview": "photo-1544161515-4ab6ce6db874",
  "simply-radiant-med-spa-las-vegas": "photo-1612817288484-6f916006741a",
  "flawless-medspa-las-vegas": "photo-1570172619644-dfd03ed5d881",
  "bluepoint-medical-spa-las-vegas": "photo-1515377905703-c4788e51af15",
  "aesthetics-lab-las-vegas": "photo-1612349317150-e413f6a5b16d",
  "skin-society-las-vegas": "photo-1522335789203-aabd1fc54bc9",
  "prestige-med-spa-charlotte": "photo-1556228578-0d85b1a4d571",
  "bodylase-charlotte": "photo-1608571423902-eed4a5ad8108",
  "blue-water-spa-raleigh": "photo-1556228720-195a672e8a03",
  "glo-de-vie-med-spa-raleigh": "photo-1570172619644-dfd03ed5d881",
  "elase-med-spa-raleigh": "photo-1519823551278-64ac92734fb1",
  "ageless-remedies-raleigh": "photo-1487412947147-5cebf100ffc2",
  "nsi-wellness-aesthetics-nashville": "photo-1516975080664-ed2fc6a32937",
  "evolve-medspa-nashville": "photo-1629909613654-28e377c37b09",
  "nashville-skin-company": "photo-1544161515-4ab6ce6db874",
  "skin-pharm-nashville": "photo-1612817288484-6f916006741a",
  "canvas-skin-nashville": "photo-1570172619644-dfd03ed5d881",
};
