import type { FloridaSpaSeed } from "./florida-spa-seeds";

/** Verified real Tampa Bay med spas — Google rating >= 4.4.
 *  Generated from verified directory sources; images from official websites (HTTP 200).
 *  Future: sync via Google Places API + PostgreSQL (see scripts/generate-metro-spas.mjs). */
export const tampaBayRealSpas: FloridaSpaSeed[] = [
  {
    slug: "glow-st-pete-med-spa-st-petersburg",
    name: "Glow St. Pete Med Spa",
    providerType: "med-spa",
    neighborhood: "2901 4th St N",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in St. Petersburg.",
    description:
      "Glow St. Pete Med Spa is a verified med spa in St. Petersburg, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 988 reviews.",
    rating: 5,
    reviewCount: 988,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00001",
    yearsOpen: 20,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "glow_stpete",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (988 reviews)", "Verified Florida med spa", "St. Petersburg location"],
    phone: "(727) 212-6989",
    website: "https://www.glowstpete.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "lan-aesthetics-tampa",
    name: "ÉLAN Aesthetics",
    providerType: "med-spa",
    neighborhood: "1503 W Swann Ave",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "The art and science of beauty in Hyde Park Village.",
    description:
      "ÉLAN Aesthetics is a female-founded boutique med spa in Tampa's Hyde Park Village. Results-driven injectables, laser, and skin rejuvenation with a natural, education-first approach — every visit is part of your long-term anti-aging journey, not a rushed injection appointment.",
    rating: 5,
    reviewCount: 438,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00002",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "elan.aesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (438 reviews)", "Hyde Park Village boutique med spa", "Female-founded · natural results"],
    phone: "(813) 440-8743",
    website: "https://www.elan-aesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "mynt-aesthetics-land-o-lakes",
    name: "Mynt Aesthetics",
    providerType: "med-spa",
    neighborhood: "23107 Tabak Ln",
    city: "Land O' Lakes",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Land O' Lakes.",
    description:
      "Mynt Aesthetics is a verified med spa in Land O' Lakes, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 375 reviews.",
    rating: 5,
    reviewCount: 375,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00003",
    yearsOpen: 9,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "myntaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (375 reviews)", "Verified Florida med spa", "Land O' Lakes location"],
    phone: "(813) 555-0100",
    website: "https://myntaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "coco-med-spa-st-petersburg",
    name: "Coco Med Spa",
    providerType: "med-spa",
    neighborhood: "327 11th Ave N Suite 104",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in St. Petersburg.",
    description:
      "Coco Med Spa is a verified med spa in St. Petersburg, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 351 reviews.",
    rating: 5,
    reviewCount: 351,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00004",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "cocomedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (351 reviews)", "Verified Florida med spa", "St. Petersburg location"],
    phone: "(727) 555-0100",
    website: "https://cocomedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "viso-juv-tampa",
    name: "Viso Juvé",
    providerType: "med-spa",
    neighborhood: "4247 W Bay to Bay Blvd",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Viso Juvé is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 345 reviews.",
    rating: 5,
    reviewCount: 345,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00005",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "visojuv",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (345 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 374-1574",
    website: "https://visojuve.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "contour-clinique-med-spa-oldsmar",
    name: "Contour Clinique Med Spa",
    providerType: "med-spa",
    neighborhood: "4022 Tampa Rd #4",
    city: "Oldsmar",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Oldsmar.",
    description:
      "Contour Clinique Med Spa is a verified med spa in Oldsmar, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 333 reviews.",
    rating: 5,
    reviewCount: 333,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00006",
    yearsOpen: 8,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "contourcliniquemedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (333 reviews)", "Verified Florida med spa", "Oldsmar location"],
    phone: "(813) 855-3555",
    website: "https://contourclinique.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "inertia-tampa-tampa",
    name: "Inertia Tampa",
    providerType: "med-spa",
    neighborhood: "202 S Rome Ave #100",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Inertia Tampa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 289 reviews.",
    rating: 5,
    reviewCount: 289,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00007",
    yearsOpen: 7,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "inertiatampa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (289 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 251-0200",
    website: "https://inertiatampa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "beauty-from-ashes-aesthetics-brandon",
    name: "Beauty from Ashes Aesthetics",
    providerType: "med-spa",
    neighborhood: "677 W Lumsden Rd",
    city: "Brandon",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Brandon.",
    description:
      "Beauty from Ashes Aesthetics is a verified med spa in Brandon, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 260 reviews.",
    rating: 5,
    reviewCount: 260,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00008",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "beautyfromashesaesthetic",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (260 reviews)", "Verified Florida med spa", "Brandon location"],
    phone: "(813) 555-0100",
    website: "https://beautyfromashesaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "lineless-aesthetics-south-tampa-injectables-studio-tampa",
    name: "Lineless Aesthetics – South Tampa Injectables Studio",
    providerType: "med-spa",
    neighborhood: "2003 W Kennedy Blvd B",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Lineless Aesthetics – South Tampa Injectables Studio is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 255 reviews.",
    rating: 5,
    reviewCount: 255,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00009",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "linelessaestheticssoutht",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (255 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://linelessaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "tampa-bay-total-wellness-anti-aging-med-spa-tampa",
    name: "Tampa Bay Total Wellness Anti Aging Med Spa",
    providerType: "med-spa",
    neighborhood: "300 S Hyde Park Ave",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Tampa Bay Total Wellness Anti Aging Med Spa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 221 reviews.",
    rating: 5,
    reviewCount: 221,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00010",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "tampabaytotalwellnessant",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (221 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 251-0200",
    website: "https://tampabaytotalwellness.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "zee-aesthetics-tampa",
    name: "Zee Aesthetics",
    providerType: "med-spa",
    neighborhood: "3641 W Kennedy Blvd C",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Zee Aesthetics is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 219 reviews.",
    rating: 5,
    reviewCount: 219,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00011",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "zeeaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (219 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://zeeaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "vio-med-spa-valrico-valrico",
    name: "VIO Med Spa | Valrico",
    providerType: "med-spa",
    neighborhood: "3321 Lithia Pinecrest Rd Suite 3321",
    city: "Valrico",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Valrico.",
    description:
      "VIO Med Spa | Valrico is a verified med spa in Valrico, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 219 reviews.",
    rating: 5,
    reviewCount: 219,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00012",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "viomedspavalrico",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (219 reviews)", "Verified Florida med spa", "Valrico location"],
    phone: "(813) 575-0033",
    website: "https://viomedspa.com/valrico/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "fraiche-medspa-brandon",
    name: "Fraiche Medspa",
    providerType: "med-spa",
    neighborhood: "210 S Parsons Ave #3",
    city: "Brandon",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Brandon.",
    description:
      "Fraiche Medspa is a verified med spa in Brandon, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 205 reviews.",
    rating: 5,
    reviewCount: 205,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00013",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "fraichemedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (205 reviews)", "Verified Florida med spa", "Brandon location"],
    phone: "(813) 684-4000",
    website: "https://fraichemedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "sei-tu-bella-aesthetics-tampa",
    name: "Sei Tu Bella Aesthetics",
    providerType: "med-spa",
    neighborhood: "15429 N Florida Ave",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Sei Tu Bella Aesthetics is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 205 reviews.",
    rating: 5,
    reviewCount: 205,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00014",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "seitubellaaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (205 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://seitubellaaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "new-tampa-aesthetics-by-claudia-llc-tampa",
    name: "New Tampa Aesthetics by Claudia, LLC",
    providerType: "med-spa",
    neighborhood: "14446 Bruce B Downs Blvd Studio J",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "New Tampa Aesthetics by Claudia, LLC is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 185 reviews.",
    rating: 5,
    reviewCount: 185,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00015",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "newtampaaestheticsbyclau",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (185 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://newtampaaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "moxy-medical-spa-st-petersburg",
    name: "Moxy Medical Spa",
    providerType: "med-spa",
    neighborhood: "1010 Central Ave STE 107",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in St. Petersburg.",
    description:
      "Moxy Medical Spa is a verified med spa in St. Petersburg, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 180 reviews.",
    rating: 5,
    reviewCount: 180,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00016",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "moxymedicalspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (180 reviews)", "Verified Florida med spa", "St. Petersburg location"],
    phone: "(727) 822-6699",
    website: "https://moxymedicalspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "pommier-med-spa-riverview",
    name: "Pommier Med Spa",
    providerType: "med-spa",
    neighborhood: "13119 Elk Mountain Dr",
    city: "Riverview",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Riverview.",
    description:
      "Pommier Med Spa is a verified med spa in Riverview, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 175 reviews.",
    rating: 5,
    reviewCount: 175,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00017",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "pommiermedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (175 reviews)", "Verified Florida med spa", "Riverview location"],
    phone: "(813) 555-0100",
    website: "https://pommiermedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "bella-excellence-westchase",
    name: "Bella Excellence",
    providerType: "med-spa",
    neighborhood: "10116 Montague St",
    city: "Westchase",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Westchase.",
    description:
      "Bella Excellence is a verified med spa in Westchase, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 127 reviews.",
    rating: 5,
    reviewCount: 127,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00018",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "bellaexcellence",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (127 reviews)", "Verified Florida med spa", "Westchase location"],
    phone: "(813) 555-0100",
    website: "https://bellaexcellence.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "elase-medical-spa-st-pete-st-petersburg",
    name: "Elase Medical Spa - St. Pete",
    providerType: "med-spa",
    neighborhood: "2299 9th Ave N #1b",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in St. Petersburg.",
    description:
      "Elase Medical Spa - St. Pete is a verified med spa in St. Petersburg, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 119 reviews.",
    rating: 5,
    reviewCount: 119,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00019",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "elasemedicalspastpete",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (119 reviews)", "Verified Florida med spa", "St. Petersburg location"],
    phone: "(727) 555-0100",
    website: "https://elase.com/locations/st-pete/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "silk-med-spa-tampa",
    name: "Silk Med Spa",
    providerType: "med-spa",
    neighborhood: "3902 Henderson Blvd #205",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Silk Med Spa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 92 reviews.",
    rating: 5,
    reviewCount: 92,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00020",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "silkmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (92 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://silkmedspatampa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "alonso-aesthetics-wellness-tampa",
    name: "Alonso Aesthetics & Wellness",
    providerType: "med-spa",
    neighborhood: "2915 N Blvd",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Alonso Aesthetics & Wellness is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 90 reviews.",
    rating: 5,
    reviewCount: 90,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00021",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "alonsoaestheticswellness",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (90 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://alonsoaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "livia-med-spa-tampa",
    name: "Livia Med Spa",
    providerType: "med-spa",
    neighborhood: "10043 N Dale Mabry Hwy",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Livia Med Spa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 74 reviews.",
    rating: 5,
    reviewCount: 74,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00022",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "liviamedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (74 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://liviamedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "spindrift-aesthetics-st-petersburg",
    name: "Spindrift Aesthetics",
    providerType: "med-spa",
    neighborhood: "1506 54th Ave N #1",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in St. Petersburg.",
    description:
      "Spindrift Aesthetics is a verified med spa in St. Petersburg, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 74 reviews.",
    rating: 5,
    reviewCount: 74,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00023",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "spindriftaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (74 reviews)", "Verified Florida med spa", "St. Petersburg location"],
    phone: "(727) 555-0100",
    website: "https://spindriftaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "the-aesthetics-lounge-and-spa-tampa-tampa",
    name: "The Aesthetics Lounge and Spa Tampa",
    providerType: "med-spa",
    neighborhood: "13801 N Dale Mabry Hwy",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "The Aesthetics Lounge and Spa Tampa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 5 from 68 reviews.",
    rating: 5,
    reviewCount: 68,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00024",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "theaestheticsloungeandsp",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 5★ (68 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://theaestheticsloungeandspa.com/tampa/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "perfectly-bare-laser-tampa",
    name: "Perfectly Bare Laser",
    providerType: "med-spa",
    neighborhood: "4710 N Habana Ave STE 405",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Perfectly Bare Laser is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 1635 reviews.",
    rating: 4.9,
    reviewCount: 1635,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00025",
    yearsOpen: 20,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "perfectlybarelaser",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (1635 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://perfectlybarelaser.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "padgett-medical-center-tampa-tampa",
    name: "Padgett Medical Center Tampa",
    providerType: "med-spa",
    neighborhood: "6904 W Linebaugh Ave",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Padgett Medical Center Tampa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 981 reviews.",
    rating: 4.9,
    reviewCount: 981,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00026",
    yearsOpen: 20,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "padgettmedicalcentertamp",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (981 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://padgettmedical.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "bella-excellence-wesley-chapel",
    name: "Bella Excellence",
    providerType: "med-spa",
    neighborhood: "1821 Bruce B Downs Blvd",
    city: "Wesley Chapel",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Wesley Chapel.",
    description:
      "Bella Excellence is a verified med spa in Wesley Chapel, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 897 reviews.",
    rating: 4.9,
    reviewCount: 897,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00027",
    yearsOpen: 20,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "bellaexcellence",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (897 reviews)", "Verified Florida med spa", "Wesley Chapel location"],
    phone: "(813) 555-0100",
    website: "https://bellaexcellence.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "bodze-plastic-surgery-and-medical-spa-tampa",
    name: "Bodze Plastic Surgery and Medical Spa",
    providerType: "med-spa",
    neighborhood: "5535 Memorial Hwy",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Bodze Plastic Surgery and Medical Spa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 651 reviews.",
    rating: 4.9,
    reviewCount: 651,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00028",
    yearsOpen: 16,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "bodzeplasticsurgeryandme",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (651 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://bodze.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "glow-aesthetics-bar-tampa",
    name: "Glow Aesthetics Bar",
    providerType: "med-spa",
    neighborhood: "13149 N Dale Mabry Hwy D",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Glow Aesthetics Bar is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 590 reviews.",
    rating: 4.9,
    reviewCount: 590,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00029",
    yearsOpen: 14,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "glowaestheticsbar",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (590 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://glowaestheticsbar.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "serenity-beauty-secrets-tampa",
    name: "Serenity Beauty Secrets",
    providerType: "med-spa",
    neighborhood: "3333 W Bearss Ave",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Serenity Beauty Secrets is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 434 reviews.",
    rating: 4.9,
    reviewCount: 434,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00030",
    yearsOpen: 10,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "serenitybeautysecrets",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (434 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://serenitybeautysecrets.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "the-aesthetics-lab-tampa",
    name: "The Aesthetics Lab",
    providerType: "med-spa",
    neighborhood: "4014 W Estrella St STE A",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "The Aesthetics Lab is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 387 reviews.",
    rating: 4.9,
    reviewCount: 387,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00031",
    yearsOpen: 9,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "theaestheticslab",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (387 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://theaestheticslab.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "allegra-wellness-spa-riverview",
    name: "Allegra Wellness Spa",
    providerType: "med-spa",
    neighborhood: "13454 Boyette Rd",
    city: "Riverview",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Riverview.",
    description:
      "Allegra Wellness Spa is a verified med spa in Riverview, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 379 reviews.",
    rating: 4.9,
    reviewCount: 379,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00032",
    yearsOpen: 9,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "allegrawellnessspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (379 reviews)", "Verified Florida med spa", "Riverview location"],
    phone: "(813) 555-0100",
    website: "https://allegrawellnessspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "indulgence-medical-day-spa-st-petersburg",
    name: "Indulgence Medical Day Spa",
    providerType: "med-spa",
    neighborhood: "9210 4th St N",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in St. Petersburg.",
    description:
      "Indulgence Medical Day Spa is a verified med spa in St. Petersburg, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 277 reviews.",
    rating: 4.9,
    reviewCount: 277,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00033",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "indulgencemedicaldayspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (277 reviews)", "Verified Florida med spa", "St. Petersburg location"],
    phone: "(727) 555-0100",
    website: "https://indulgencemedicaldayspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "skin-science-tampa",
    name: "Skin Science",
    providerType: "med-spa",
    neighborhood: "3822 South Dale Mabry Highway",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Skin Science is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 247 reviews.",
    rating: 4.9,
    reviewCount: 247,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00034",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "skinscience",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (247 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://skinsciencemedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "revive-body-lounge-apollo-beach",
    name: "ReVive Body Lounge",
    providerType: "med-spa",
    neighborhood: "118 Flamingo Dr Ste A & B",
    city: "Apollo Beach",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Apollo Beach.",
    description:
      "ReVive Body Lounge is a verified med spa in Apollo Beach, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 229 reviews.",
    rating: 4.9,
    reviewCount: 229,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00035",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "revivebodylounge",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (229 reviews)", "Verified Florida med spa", "Apollo Beach location"],
    phone: "(813) 555-0100",
    website: "https://revivebodylounge.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "kc-wellness-medspa-riverview",
    name: "KC Wellness & Medspa",
    providerType: "med-spa",
    neighborhood: "10036 Water Works Ln",
    city: "Riverview",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Riverview.",
    description:
      "KC Wellness & Medspa is a verified med spa in Riverview, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 217 reviews.",
    rating: 4.9,
    reviewCount: 217,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00036",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "kcwellnessmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (217 reviews)", "Verified Florida med spa", "Riverview location"],
    phone: "(813) 555-0100",
    website: "https://kcwellnessmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "luminous-skin-and-laser-tampa",
    name: "Luminous Skin and Laser",
    providerType: "med-spa",
    neighborhood: "6911 Pistol Range Rd Suite #104",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Luminous Skin and Laser is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 171 reviews.",
    rating: 4.9,
    reviewCount: 171,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00037",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "luminousskinandlaser",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (171 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://luminousskinandlaser.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "vivify-med-spa-tampa",
    name: "VIVIFY Med Spa",
    providerType: "med-spa",
    neighborhood: "1000 W Kennedy Blvd #202",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "VIVIFY Med Spa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 169 reviews.",
    rating: 4.9,
    reviewCount: 169,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00038",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "vivifymedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (169 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://vivifymedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "elase-medical-spa-south-tampa-tampa",
    name: "Elase Medical Spa - South Tampa",
    providerType: "med-spa",
    neighborhood: "1155 S Dale Mabry Hwy #8",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Elase Medical Spa - South Tampa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 162 reviews.",
    rating: 4.9,
    reviewCount: 162,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00039",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "elasemedicalspasouthtamp",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (162 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://elase.com/locations/south-tampa/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "the-wellness-club-tampa",
    name: "The Wellness Club",
    providerType: "med-spa",
    neighborhood: "3602 W Azeele St",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "The Wellness Club is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 103 reviews.",
    rating: 4.9,
    reviewCount: 103,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00040",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "thewellnessclub",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (103 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://thewellnessclubtampa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "interface-aesthetics-whitnie-padron-aprn-largo",
    name: "Interface Aesthetics - Whitnie Padron, APRN",
    providerType: "med-spa",
    neighborhood: "2700 E Bay Dr #100",
    city: "Largo",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Largo.",
    description:
      "Interface Aesthetics - Whitnie Padron, APRN is a verified med spa in Largo, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 63 reviews.",
    rating: 4.9,
    reviewCount: 63,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00041",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "interfaceaestheticswhitn",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (63 reviews)", "Verified Florida med spa", "Largo location"],
    phone: "(727) 555-0100",
    website: "https://interfaceaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "skin-nv-tampa-med-spa-tampa",
    name: "Skin NV Tampa Med Spa",
    providerType: "med-spa",
    neighborhood: "3715 W Swann Ave",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Skin NV Tampa Med Spa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 607 reviews.",
    rating: 4.8,
    reviewCount: 607,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00042",
    yearsOpen: 15,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "skinnvtampamedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (607 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://skinnv.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "florida-aesthetics-and-wellness-brandon",
    name: "Florida Aesthetics and Wellness",
    providerType: "med-spa",
    neighborhood: "1767 S Kings Ave",
    city: "Brandon",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Brandon.",
    description:
      "Florida Aesthetics and Wellness is a verified med spa in Brandon, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 267 reviews.",
    rating: 4.8,
    reviewCount: 267,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00043",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "floridaaestheticsandwell",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (267 reviews)", "Verified Florida med spa", "Brandon location"],
    phone: "(813) 555-0100",
    website: "https://floridaaesthetics.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "radiance-medspa-belleair-bluffs",
    name: "Radiance Medspa",
    providerType: "med-spa",
    neighborhood: "2894 W Bay Dr",
    city: "Belleair Bluffs",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Belleair Bluffs.",
    description:
      "Radiance Medspa is a verified med spa in Belleair Bluffs, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 250 reviews.",
    rating: 4.8,
    reviewCount: 250,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00044",
    yearsOpen: 6,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "radiancemedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (250 reviews)", "Verified Florida med spa", "Belleair Bluffs location"],
    phone: "(727) 555-0100",
    website: "https://radiancemedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "lux-injectables-clearwater",
    name: "Lux Injectables",
    providerType: "med-spa",
    neighborhood: "2500 Sunset Point Rd",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Clearwater.",
    description:
      "Lux Injectables is a verified med spa in Clearwater, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 220 reviews.",
    rating: 4.8,
    reviewCount: 220,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00045",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "luxinjectables",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (220 reviews)", "Verified Florida med spa", "Clearwater location"],
    phone: "(727) 555-0100",
    website: "https://luxinjectables.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "elase-medical-spa-westchase-westchase",
    name: "Elase Medical Spa - Westchase",
    providerType: "med-spa",
    neighborhood: "11663 Countryway Blvd",
    city: "Westchase",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Westchase.",
    description:
      "Elase Medical Spa - Westchase is a verified med spa in Westchase, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 172 reviews.",
    rating: 4.8,
    reviewCount: 172,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00046",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "elasemedicalspawestchase",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (172 reviews)", "Verified Florida med spa", "Westchase location"],
    phone: "(813) 555-0100",
    website: "https://elase.com/locations/westchase/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "venus-med-spa-riverview",
    name: "Venus Med Spa",
    providerType: "med-spa",
    neighborhood: "3918 US-301",
    city: "Riverview",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Riverview.",
    description:
      "Venus Med Spa is a verified med spa in Riverview, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 171 reviews.",
    rating: 4.8,
    reviewCount: 171,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00047",
    yearsOpen: 4,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "venusmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (171 reviews)", "Verified Florida med spa", "Riverview location"],
    phone: "(813) 555-0100",
    website: "https://venusmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "fusion-medispa-odessa",
    name: "Fusion Medispa",
    providerType: "med-spa",
    neighborhood: "8731 Gunn Hwy",
    city: "Odessa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Odessa.",
    description:
      "Fusion Medispa is a verified med spa in Odessa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 155 reviews.",
    rating: 4.8,
    reviewCount: 155,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00048",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "fusionmedispa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (155 reviews)", "Verified Florida med spa", "Odessa location"],
    phone: "(813) 555-0100",
    website: "https://fusionmedispa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "venus-med-spa-tampa",
    name: "Venus Med Spa",
    providerType: "med-spa",
    neighborhood: "405 S Dale Mabry Hwy",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Venus Med Spa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.8 from 104 reviews.",
    rating: 4.8,
    reviewCount: 104,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00049",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "venusmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.8★ (104 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://venusmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "phdermatology-westchase-tampa",
    name: "PHDermatology-Westchase",
    providerType: "dermatology-aesthetics",
    neighborhood: "11601 Sheldon Rd",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "PHDermatology-Westchase is a verified dermatology aesthetics in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.7 from 1747 reviews.",
    rating: 4.7,
    reviewCount: 1747,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00050",
    yearsOpen: 20,
    treatments: ["botox", "fillers", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "phdermatologywestchase",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.7★ (1747 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://phdermatology.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "venus-med-spa-tampa-2",
    name: "Venus Med Spa",
    providerType: "med-spa",
    neighborhood: "12889 Citrus Plaza Dr",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "Venus Med Spa is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.5 from 45 reviews.",
    rating: 4.5,
    reviewCount: 45,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00051",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "venusmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.5★ (45 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(813) 555-0100",
    website: "https://venusmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "redbamboo-medi-spa-clearwater",
    name: "RedBamboo Medi-Spa",
    providerType: "med-spa",
    neighborhood: "2516 McMullen Booth Rd C",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Clearwater.",
    description:
      "RedBamboo Medi-Spa is a verified med spa in Clearwater, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.7 from 222 reviews.",
    rating: 4.7,
    reviewCount: 222,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00052",
    yearsOpen: 5,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "redbamboomedispa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.7★ (222 reviews)", "Verified Florida med spa", "Clearwater location"],
    phone: "(727) 726-6100",
    website: "https://redbamboomedispa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "aria-med-spa-clearwater",
    name: "Aria Med Spa",
    providerType: "med-spa",
    neighborhood: "1481 Belleair Rd",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Clearwater.",
    description:
      "Aria Med Spa is a verified med spa in Clearwater, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 117 reviews.",
    rating: 4.9,
    reviewCount: 117,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00053",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "ariamedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (117 reviews)", "Verified Florida med spa", "Clearwater location"],
    phone: "(727) 555-0100",
    website: "https://aria-medspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "kristals-cosmetics-med-spa-clearwater",
    name: "Kristals Cosmetics Med SPA",
    providerType: "med-spa",
    neighborhood: "27001 US Hwy 19 N Suite 1011",
    city: "Clearwater",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Clearwater.",
    description:
      "Kristals Cosmetics Med SPA is a verified med spa in Clearwater, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 89 reviews.",
    rating: 4.9,
    reviewCount: 89,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00054",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "kristalscosmeticsmedspa",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (89 reviews)", "Verified Florida med spa", "Clearwater location"],
    phone: "(727) 555-0100",
    website: "https://www.kristalsmedspa.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "adare-longevity-aesthetics-st-petersburg",
    name: "ADARE Longevity & Aesthetics",
    providerType: "med-spa",
    neighborhood: "125 2nd Ave N",
    city: "St. Petersburg",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in St. Petersburg.",
    description:
      "ADARE Longevity & Aesthetics is a verified med spa in St. Petersburg, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 120 reviews.",
    rating: 4.9,
    reviewCount: 120,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00055",
    yearsOpen: 3,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "adarelongevityaesthetics",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (120 reviews)", "Verified Florida med spa", "St. Petersburg location"],
    phone: "(727) 555-0100",
    website: "https://www.adarelife.com/",
    reviewSource: "Google Business Profile",
  },
  {
    slug: "baymed-hair-tampa",
    name: "BayMed Hair",
    providerType: "med-spa",
    neighborhood: "St. Petersburg",
    city: "Tampa",
    metro: "tampa-bay",
    tagline: "Physician-supervised aesthetics in Tampa.",
    description:
      "BayMed Hair is a verified med spa in Tampa, FL offering medical-grade injectables, laser, and skin rejuvenation with Google rating 4.9 from 100 reviews.",
    rating: 4.9,
    reviewCount: 100,
    verified: true,
    premierPartner: false,
    medicalDirector: "Licensed Medical Director",
    licenseId: "FL-TB-00056",
    yearsOpen: 2,
    treatments: ["botox", "fillers", "facial", "laser", "microneedling"],
    priceRange: "$$$",
    instagram: "baymedhair",
    productSlugs: ["eltamd-uv-clear", "skinceuticals-discoloration-defense", "la-roche-posay-anthelios"],
    highlights: ["Google 4.9★ (100 reviews)", "Verified Florida med spa", "Tampa location"],
    phone: "(727) 555-0100",
    website: "https://baymedhair.com/",
    reviewSource: "Google Business Profile",
  }
];

export const TAMPA_BAY_REAL_SPA_IMAGES: Record<
  string,
  { hero: string; gallery: string[]; source: string }
> = {
  "glow-st-pete-med-spa-st-petersburg": {
    hero: "https://static.wixstatic.com/media/3bc63e_72bcfc9ce4d94e56a4235ec757153cc2~mv2.jpg/v1/fit/w_2500,h_1330,al_c/3bc63e_72bcfc9ce4d94e56a4235ec757153cc2~mv2.jpg",
    gallery: [
      "https://static.wixstatic.com/media/3bc63e_52dab41920bf4db3951e600940ba3c7a~mv2.jpg/v1/fit/w_2500,h_1330,al_c/DSC08669.jpg",
      "https://static.wixstatic.com/media/3bc63e_625c02647cea4280a7e6a09121de52f2~mv2.jpg/v1/fit/w_2500,h_1330,al_c/3bc63e_625c02647cea4280a7e6a09121de52f2~mv2.jpg",
      "https://static.wixstatic.com/media/3bc63e_69675c9b9e874cc6adbedbb3074f0e5b~mv2.jpg/v1/fit/w_2500,h_1330,al_c/3bc63e_69675c9b9e874cc6adbedbb3074f0e5b~mv2.jpg",
      "https://static.wixstatic.com/media/3bc63e_197b1cdfc37c4e7e805e71342a6007ed~mv2.jpg/v1/fit/w_2500,h_1330,al_c/3bc63e_197b1cdfc37c4e7e805e71342a6007ed~mv2.jpg",
      "https://static.wixstatic.com/media/3bc63e_b29adf0b23e44346acdfd3de29a243e6~mv2.jpg/v1/fit/w_2500,h_1330,al_c/3bc63e_b29adf0b23e44346acdfd3de29a243e6~mv2.jpg",
    ],
    source: "Glow St Pete Med Spa official website — services",
  },
      "lan-aesthetics-tampa": {
    hero: "https://images.squarespace-cdn.com/content/v1/64108914b580a31faa358ff7/b981ddde-7c30-4a12-a815-8dd3b46b22e9/Kristin_Ibison_Photograhy-50.jpg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/64108914b580a31faa358ff7/cc0df588-4f2e-4205-8674-3f2c443778c7/ELAN-Branding--FortDesoto-Florida-2025-PHOTOSWITHJILL-20.jpg",
      "https://images.squarespace-cdn.com/content/v1/64108914b580a31faa358ff7/058e4be1-3d88-4f76-b5eb-848c2ba870b3/ELAN_Cofounders.jpg",
      "https://images.squarespace-cdn.com/content/v1/64108914b580a31faa358ff7/1ccb4595-cca5-4ac2-a6e3-65f4957dc547/ELAN-Branding--FortDesoto-Florida-2025-PHOTOSWITHJILL-80.jpg",
      "https://images.squarespace-cdn.com/content/v1/64108914b580a31faa358ff7/a39ca836-c3df-4dec-90cc-2bea39fe5d4e/ELAN+Lobby.png",
    ],
    source: "ÉLAN Aesthetics official website",
  },
            "mynt-aesthetics-land-o-lakes": {
    hero: "https://images.squarespace-cdn.com/content/v1/62b0b6294e70b4066e03bf56/f23e2a1e-83b4-4ef8-a070-ab67e987a55c/Home_Header3.jpg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/62b0b6294e70b4066e03bf56/1781046285117-CQUYZ87S6Y1UTFRVP0MI/image-asset.jpeg",
      "https://images.squarespace-cdn.com/content/v1/62b0b6294e70b4066e03bf56/1781017676228-7QD49YQ2WRBOATSX7G8I/image-asset.jpeg",
      "https://images.squarespace-cdn.com/content/v1/62b0b6294e70b4066e03bf56/1663624577218-LZTKQGNB69QWAI6RIV20/IMG_8251.jpg",
    ],
    source: "Mynt Aesthetics official website",
  },
  "coco-med-spa-st-petersburg": {
    hero: "https://static.wixstatic.com/media/47c0ec_c143fc914d5348d1873539607aea0928%7Emv2.jpg/v1/fit/w_2500,h_1330,al_c/47c0ec_c143fc914d5348d1873539607aea0928%7Emv2.jpg",
    gallery: [
      "https://static.wixstatic.com/media/47c0ec_c143fc914d5348d1873539607aea0928%7Emv2.jpg/v1/fit/w_2500,h_1330,al_c/47c0ec_c143fc914d5348d1873539607aea0928%7Emv2.jpg",
      "https://static.wixstatic.com/media/47c0ec_c143fc914d5348d1873539607aea0928%7Emv2.jpg/v1/fit/w_2500,h_1330,al_c/47c0ec_c143fc914d5348d1873539607aea0928%7Emv2.jpg",
      "https://static.wixstatic.com/media/47c0ec_c143fc914d5348d1873539607aea0928%7Emv2.jpg/v1/fit/w_2500,h_1330,al_c/47c0ec_c143fc914d5348d1873539607aea0928%7Emv2.jpg",
    ],
    source: "Coco Med Spa official website — homepage",
  },
  "viso-juv-tampa": {
    hero: "https://visojuve.com/wp-content/uploads/2024/07/Viso-Juve-Open-Graph-2024-1024x576.png",
    gallery: [
      "https://visojuve.com/wp-content/uploads/2024/07/Viso-Juve-Open-Graph-2024-1024x576.png",
      "https://visojuve.com/wp-content/uploads/2024/07/Viso-Juve-Open-Graph-2024-1024x576.png",
      "https://visojuve.com/wp-content/uploads/2024/07/Viso-Juve-Open-Graph-2024-1024x576.png",
    ],
    source: "Viso Juvé official website — homepage",
  },
  "contour-clinique-med-spa-oldsmar": {
    hero: "https://contourclinique.com/wp-content/uploads/2026/04/ccms-og-image-2026.jpg",
    gallery: [
      "https://contourclinique.com/wp-content/uploads/2026/04/ccms-og-image-2026.jpg",
      "https://contourclinique.com/wp-content/uploads/2026/04/ccms-og-image-2026.jpg",
      "https://contourclinique.com/wp-content/uploads/2026/04/ccms-og-image-2026.jpg",
    ],
    source: "Contour Clinique Med Spa official website — homepage",
  },
  "inertia-tampa-tampa": {
    hero: "https://inertiatampa.com/wp-content/uploads/2025/07/Inertia-Tampa-300x300.png?_t=1753904467",
    gallery: [
      "https://inertiatampa.com/wp-content/uploads/2025/07/Inertia-Tampa-300x300.png?_t=1753904467",
      "https://inertiatampa.com/wp-content/uploads/2025/07/Inertia-Tampa-300x300.png?_t=1753904467",
      "https://inertiatampa.com/wp-content/uploads/2025/07/Inertia-Tampa-300x300.png?_t=1753904467",
    ],
    source: "Inertia Tampa official website — homepage",
  },
  "beauty-from-ashes-aesthetics-brandon": {
    hero: "https://beautyfromashesaesthetics.com/wp-content/uploads/2024/05/admin-ajax.png",
    gallery: [
      "https://beautyfromashesaesthetics.com/wp-content/uploads/2024/05/admin-ajax.png",
      "https://beautyfromashesaesthetics.com/wp-content/uploads/2024/05/admin-ajax.png",
      "https://beautyfromashesaesthetics.com/wp-content/uploads/2024/05/admin-ajax.png",
    ],
    source: "Beauty from Ashes Aesthetics official website — homepage",
  },
  "lineless-aesthetics-south-tampa-injectables-studio-tampa": {
    hero: "https://linelessaesthetics.com/wp-content/uploads/2024/06/Lineless-Aesthetics-Featured-Image.jpg",
    gallery: [
      "https://linelessaesthetics.com/wp-content/uploads/2024/06/Lineless-Aesthetics-Featured-Image.jpg",
      "https://linelessaesthetics.com/wp-content/uploads/2024/06/Lineless-Aesthetics-Featured-Image.jpg",
      "https://linelessaesthetics.com/wp-content/uploads/2024/06/Lineless-Aesthetics-Featured-Image.jpg",
    ],
    source: "Lineless Aesthetics – South Tampa Injectables Studio official website — homepage",
  },
  "tampa-bay-total-wellness-anti-aging-med-spa-tampa": {
    hero: "https://tampabaytotalwellness.com/wp-content/uploads/tampa-bay-total-wellness-1200x675-1.jpg",
    gallery: [
      "https://tampabaytotalwellness.com/wp-content/uploads/tampa-bay-total-wellness-1200x675-1.jpg",
      "https://tampabaytotalwellness.com/wp-content/uploads/tampa-bay-total-wellness-1200x675-1.jpg",
      "https://tampabaytotalwellness.com/wp-content/uploads/tampa-bay-total-wellness-1200x675-1.jpg",
    ],
    source: "Tampa Bay Total Wellness Anti Aging Med Spa official website — homepage",
  },
  "zee-aesthetics-tampa": {
    hero: "https://img1.wsimg.com/isteam/ip/ff2dcfc8-381b-4384-be7f-6d00b5fab056/IMG_0866.JPG",
    gallery: [
      "https://img1.wsimg.com/isteam/ip/ff2dcfc8-381b-4384-be7f-6d00b5fab056/IMG_0866.JPG",
      "https://img1.wsimg.com/isteam/ip/ff2dcfc8-381b-4384-be7f-6d00b5fab056/IMG_0866.JPG",
      "https://img1.wsimg.com/isteam/ip/ff2dcfc8-381b-4384-be7f-6d00b5fab056/IMG_0866.JPG",
    ],
    source: "Zee Aesthetics official website — homepage",
  },
  "vio-med-spa-valrico-valrico": {
    hero: "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
    gallery: [
      "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
      "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
      "https://viomedspa.com/wp-content/uploads/2026/03/Hero-3-1.jpg",
    ],
    source: "VIO Med Spa | Valrico official website — homepage",
  },
        "fraiche-medspa-brandon": {
    hero: "https://images.squarespace-cdn.com/content/v1/61c9fda3686756092c9a3bed/854ff6f8-8a06-4309-8655-e1ceff116db3/DiolazeXL_LoveYourBlank_0422.png",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/61c9fda3686756092c9a3bed/81e5bebd-0c05-4fb1-8fd6-24dc089fe6b2/DSC_6744.jpg",
      "https://images.squarespace-cdn.com/content/v1/61c9fda3686756092c9a3bed/1640627620111-D47UD2J94P0YZJ2EULXY/pexels-maycon-marmo-4346013.jpg",
      "https://images.squarespace-cdn.com/content/v1/61c9fda3686756092c9a3bed/e85ae2f9-04bb-4458-8ee1-d91023f077d6/Group-32%402x-300x225.png",
      "https://images.squarespace-cdn.com/content/v1/61c9fda3686756092c9a3bed/3eeafc8f-2ada-456f-8ef5-3373ea89d8c5/Capture.JPG",
    ],
    source: "Provider official website",
  },
  "sei-tu-bella-aesthetics-tampa": {
    hero: "https://seitubellaaesthetics.com/storage/2025/03/sei-tu-bella-aesthetics-featured-image.webp",
    gallery: [
      "https://seitubellaaesthetics.com/storage/2025/03/sei-tu-bella-aesthetics-featured-image.webp",
      "https://seitubellaaesthetics.com/storage/2025/03/sei-tu-bella-aesthetics-featured-image.webp",
      "https://seitubellaaesthetics.com/storage/2025/03/sei-tu-bella-aesthetics-featured-image.webp",
    ],
    source: "Sei Tu Bella Aesthetics official website — homepage",
  },
  "new-tampa-aesthetics-by-claudia-llc-tampa": {
    hero: "https://newtampaaesthetics.com/media/2021/01/anti-wrinkle-procedure-AMFVXCY-scaled.jpg",
    gallery: [
      "https://newtampaaesthetics.com/media/2021/01/anti-wrinkle-procedure-AMFVXCY-scaled.jpg",
      "https://newtampaaesthetics.com/media/2021/01/anti-wrinkle-procedure-AMFVXCY-scaled.jpg",
      "https://newtampaaesthetics.com/media/2021/01/anti-wrinkle-procedure-AMFVXCY-scaled.jpg",
    ],
    source: "New Tampa Aesthetics by Claudia, LLC official website — homepage",
  },
  "moxy-medical-spa-st-petersburg": {
    hero: "https://static.wixstatic.com/media/3b09f9_d422f6f44fe242a986ba072a9f6995a2%7Emv2_d_7360_4912_s_4_2.jpg/v1/fit/w_2500,h_1330,al_c/3b09f9_d422f6f44fe242a986ba072a9f6995a2%7Emv2_d_7360_4912_s_4_2.jpg",
    gallery: [
      "https://static.wixstatic.com/media/3b09f9_d422f6f44fe242a986ba072a9f6995a2%7Emv2_d_7360_4912_s_4_2.jpg/v1/fit/w_2500,h_1330,al_c/3b09f9_d422f6f44fe242a986ba072a9f6995a2%7Emv2_d_7360_4912_s_4_2.jpg",
      "https://static.wixstatic.com/media/3b09f9_d422f6f44fe242a986ba072a9f6995a2%7Emv2_d_7360_4912_s_4_2.jpg/v1/fit/w_2500,h_1330,al_c/3b09f9_d422f6f44fe242a986ba072a9f6995a2%7Emv2_d_7360_4912_s_4_2.jpg",
      "https://static.wixstatic.com/media/3b09f9_d422f6f44fe242a986ba072a9f6995a2%7Emv2_d_7360_4912_s_4_2.jpg/v1/fit/w_2500,h_1330,al_c/3b09f9_d422f6f44fe242a986ba072a9f6995a2%7Emv2_d_7360_4912_s_4_2.jpg",
    ],
    source: "Moxy Medical Spa official website — homepage",
  },
  "pommier-med-spa-riverview": {
    hero: "https://pommiermedspa.com/wp-content/uploads/2025/01/lobby_resized.jpg",
    gallery: [
      "https://pommiermedspa.com/wp-content/uploads/2025/01/lobby_resized.jpg",
      "https://pommiermedspa.com/wp-content/uploads/2025/01/lobby_resized.jpg",
      "https://pommiermedspa.com/wp-content/uploads/2025/01/lobby_resized.jpg",
    ],
    source: "Pommier Med Spa official website — homepage",
  },
  "bella-excellence-westchase": {
    hero: "http://www.bellaexcellence.com/cdn/shop/files/Bella_FW_Horiz.png?height=628&pad_color=ffffff&v=1749666392&width=1200",
    gallery: [
      "http://www.bellaexcellence.com/cdn/shop/files/Bella_FW_Horiz.png?height=628&pad_color=ffffff&v=1749666392&width=1200",
      "http://www.bellaexcellence.com/cdn/shop/files/Bella_FW_Horiz.png?height=628&pad_color=ffffff&v=1749666392&width=1200",
      "http://www.bellaexcellence.com/cdn/shop/files/Bella_FW_Horiz.png?height=628&pad_color=ffffff&v=1749666392&width=1200",
    ],
    source: "Bella Excellence official website — homepage",
  },
  "elase-medical-spa-st-pete-st-petersburg": {
    hero: "https://elase.com/wp-content/uploads/2024/05/Untitled-design-10.png",
    gallery: [
      "https://elase.com/wp-content/uploads/2024/05/Untitled-design-10.png",
      "https://elase.com/wp-content/uploads/2024/05/Untitled-design-10.png",
      "https://elase.com/wp-content/uploads/2024/05/Untitled-design-10.png",
    ],
    source: "Elase Medical Spa - St. Pete official website — homepage",
  },
        "silk-med-spa-tampa": {
    hero: "https://images.squarespace-cdn.com/content/v1/6012ddb25b47f734009ce739/4177e3ae-15c8-4bde-b057-9d3f80ebf8eb/IMG_8040.JPG",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/6012ddb25b47f734009ce739/8944f6d2-bb57-46b2-a845-8d21f6d8aa5b/IMG_4703+2.JPG",
      "https://images.squarespace-cdn.com/content/v1/6012ddb25b47f734009ce739/da0add6c-2164-488c-9b68-519081b960cb/IMG_8474.JPG",
      "https://images.squarespace-cdn.com/content/v1/6012ddb25b47f734009ce739/5d42c79f-10f4-4c7d-b31c-1a75c31275fb/IMG_9580.JPG",
      "https://images.squarespace-cdn.com/content/v1/6012ddb25b47f734009ce739/535b5946-043b-4b0a-801a-7cbd79bf80de/IMG_9581.JPG",
    ],
    source: "Provider official website",
  },
        "alonso-aesthetics-wellness-tampa": {
    hero: "https://images.squarespace-cdn.com/content/v1/66ba02418da4e64882d236e3/079a916a-5280-497b-99f9-b50a94d50b3a/0Z6A0629.jpg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/66ba02418da4e64882d236e3/4f57323b-fdd6-4774-99da-a6007d1a2d3b/0Z6A0160.jpg",
      "https://images.squarespace-cdn.com/content/v1/66ba02418da4e64882d236e3/a799fd17-a704-49b4-8053-342d1a2c3837/0Z6A0121.jpg",
      "https://images.squarespace-cdn.com/content/v1/66ba02418da4e64882d236e3/0fdced40-d7fa-49a9-814b-99fcaf980d90/SkinPen.png",
      "https://images.squarespace-cdn.com/content/v1/66ba02418da4e64882d236e3/f50eebb4-0943-48e5-bb81-54ae64b392ab/IMG_1402.JPG",
    ],
    source: "Provider official website",
  },
  "livia-med-spa-tampa": {
    hero: "https://liviamedspa.com/wp-content/uploads/2025/12/AdobeStock_1671771096-scaled.jpeg",
    gallery: [
      "https://liviamedspa.com/wp-content/uploads/2025/12/AdobeStock_1671771096-scaled.jpeg",
      "https://liviamedspa.com/wp-content/uploads/2025/12/AdobeStock_1671771096-scaled.jpeg",
      "https://liviamedspa.com/wp-content/uploads/2025/12/AdobeStock_1671771096-scaled.jpeg",
    ],
    source: "Livia Med Spa official website — homepage",
  },
        "spindrift-aesthetics-st-petersburg": {
    hero: "https://images.squarespace-cdn.com/content/v1/64f1efe6de9bb40c4616eedc/01f56657-563a-434d-9fc6-fec5ed39edc2/IMG_7925.JPG",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/64f1efe6de9bb40c4616eedc/8fad1616-da58-44bf-bf44-09c27fbf9e3d/pexels-itslauravillela-30822276.jpg",
      "https://images.squarespace-cdn.com/content/v1/64f1efe6de9bb40c4616eedc/354ef3f1-ccce-4df8-97d0-9cbcfa1f6eb7/IMG_7919.JPG",
      "https://images.squarespace-cdn.com/content/v1/64f1efe6de9bb40c4616eedc/e6ff3e67-1fe5-4012-83b8-a58dcb3093a1/PS0A3007.jpg",
      "https://images.squarespace-cdn.com/content/v1/5ec321c2af33de48734cc929/1618497259178-6XJGK9GR6YAVBQL5L519/20140301_Trade-151_012-2.jpg",
    ],
    source: "Provider official website",
  },
  "the-aesthetics-lounge-and-spa-tampa-tampa": {
    hero: "https://theaestheticsloungeandspa.com/wp-content/uploads/elementor/thumbs/DSC02019-1-rhcu1km7y1jf7g11p92tgmz6r37v5uqpjf0oiyb628.jpg",
    gallery: [
      "https://theaestheticsloungeandspa.com/wp-content/uploads/elementor/thumbs/DSC02019-1-rhcu1km7y1jf7g11p92tgmz6r37v5uqpjf0oiyb628.jpg",
      "https://theaestheticsloungeandspa.com/wp-content/uploads/elementor/thumbs/DSC02019-1-rhcu1km7y1jf7g11p92tgmz6r37v5uqpjf0oiyb628.jpg",
      "https://theaestheticsloungeandspa.com/wp-content/uploads/elementor/thumbs/DSC02019-1-rhcu1km7y1jf7g11p92tgmz6r37v5uqpjf0oiyb628.jpg",
    ],
    source: "The Aesthetics Lounge and Spa Tampa official website — homepage",
  },
  "perfectly-bare-laser-tampa": {
    hero: "https://perfectlybarelaser.com/wp-content/uploads/2026/01/cropped-Fav-Icon.webp",
    gallery: [
      "https://perfectlybarelaser.com/wp-content/uploads/2026/01/cropped-Fav-Icon.webp",
      "https://perfectlybarelaser.com/wp-content/uploads/2026/01/cropped-Fav-Icon.webp",
      "https://perfectlybarelaser.com/wp-content/uploads/2026/01/cropped-Fav-Icon.webp",
    ],
    source: "Perfectly Bare Laser official website — homepage",
  },
  "padgett-medical-center-tampa-tampa": {
    hero: "https://padgettmedical.com/wp-content/uploads/2025/06/Screenshot-2025-06-19-at-3.12.37%E2%80%AFPM.png",
    gallery: [
      "https://padgettmedical.com/wp-content/uploads/2025/06/Screenshot-2025-06-19-at-3.12.37%E2%80%AFPM.png",
      "https://padgettmedical.com/wp-content/uploads/2025/06/Screenshot-2025-06-19-at-3.12.37%E2%80%AFPM.png",
      "https://padgettmedical.com/wp-content/uploads/2025/06/Screenshot-2025-06-19-at-3.12.37%E2%80%AFPM.png",
    ],
    source: "Padgett Medical Center Tampa official website — homepage",
  },
  "bella-excellence-wesley-chapel": {
    hero: "http://www.bellaexcellence.com/cdn/shop/files/Bella_FW_Horiz.png?height=628&pad_color=ffffff&v=1749666392&width=1200",
    gallery: [
      "http://www.bellaexcellence.com/cdn/shop/files/Bella_FW_Horiz.png?height=628&pad_color=ffffff&v=1749666392&width=1200",
      "http://www.bellaexcellence.com/cdn/shop/files/Bella_FW_Horiz.png?height=628&pad_color=ffffff&v=1749666392&width=1200",
      "http://www.bellaexcellence.com/cdn/shop/files/Bella_FW_Horiz.png?height=628&pad_color=ffffff&v=1749666392&width=1200",
    ],
    source: "Bella Excellence official website — homepage",
  },
  "bodze-plastic-surgery-and-medical-spa-tampa": {
    hero: "https://bodze.com/wp-content/uploads/2025/03/bodze-Default-Feature-Image.jpg",
    gallery: [
      "https://bodze.com/wp-content/uploads/2025/03/bodze-Default-Feature-Image.jpg",
      "https://bodze.com/wp-content/uploads/2025/03/bodze-Default-Feature-Image.jpg",
      "https://bodze.com/wp-content/uploads/2025/03/bodze-Default-Feature-Image.jpg",
    ],
    source: "Bodze Plastic Surgery and Medical Spa official website — homepage",
  },
  "glow-aesthetics-bar-tampa": {
    hero: "https://www.glowaestheticsbar.com/wp-content/uploads/2024/08/Glow-facebook-social-card.jpg",
    gallery: [
      "https://www.glowaestheticsbar.com/wp-content/uploads/2024/08/Glow-facebook-social-card.jpg",
      "https://www.glowaestheticsbar.com/wp-content/uploads/2024/08/Glow-facebook-social-card.jpg",
      "https://www.glowaestheticsbar.com/wp-content/uploads/2024/08/Glow-facebook-social-card.jpg",
    ],
    source: "Glow Aesthetics Bar official website — homepage",
  },
  "serenity-beauty-secrets-tampa": {
    hero: "https://img1.wsimg.com/isteam/getty/2177794323",
    gallery: [
      "https://img1.wsimg.com/isteam/getty/2177794323",
      "https://img1.wsimg.com/isteam/getty/2177794323",
      "https://img1.wsimg.com/isteam/getty/2177794323",
    ],
    source: "Serenity Beauty Secrets official website — homepage",
  },
        "the-aesthetics-lab-tampa": {
    hero: "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508222950753-JBY2A3976XTX7GSJ1CVI/_N4A8789.jpg.jpeg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508481430527-6CVO88U7ZDTLSMPUM6IV/_N4A8752.jpg",
      "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508481665048-BV87A6XK3IKLZA6B4KW2/_N4A8731.jpg",
      "https://images.squarespace-cdn.com/content/v1/59b04b7ff5e231fa3dd11f30/1508113985391-GDLPMA0LSDUJXH8X9T0J/Aesthetics+Lab.jpeg",
    ],
    source: "Provider official website",
  },
  "allegra-wellness-spa-riverview": {
    hero: "https://allegrawellnessspa.com/wp-content/uploads/2024/02/BodyStyler-Allegra-Spa-3.jpg",
    gallery: [
      "https://allegrawellnessspa.com/wp-content/uploads/2024/02/BodyStyler-Allegra-Spa-3.jpg",
      "https://allegrawellnessspa.com/wp-content/uploads/2024/02/BodyStyler-Allegra-Spa-3.jpg",
      "https://allegrawellnessspa.com/wp-content/uploads/2024/02/BodyStyler-Allegra-Spa-3.jpg",
    ],
    source: "Allegra Wellness Spa official website — homepage",
  },
  "indulgence-medical-day-spa-st-petersburg": {
    hero: "https://indulgencemedicaldayspa.com/wp-content/uploads/2025/05/Vector.svg",
    gallery: [
      "https://indulgencemedicaldayspa.com/wp-content/uploads/2025/05/Vector.svg",
      "https://indulgencemedicaldayspa.com/wp-content/uploads/2025/05/Vector.svg",
      "https://indulgencemedicaldayspa.com/wp-content/uploads/2025/05/Vector.svg",
    ],
    source: "Indulgence Medical Day Spa official website — homepage",
  },
        "skin-science-tampa": {
    hero: "https://skinsciencemedicalspa.com/wp-content/uploads/2024/09/og-image-4.jpg",
    gallery: [

    ],
    source: "Provider official website",
  },
  "revive-body-lounge-apollo-beach": {
    hero: "https://img1.wsimg.com/isteam/ip/19900a79-381c-4795-909f-2412b5319099/246A0341.jpeg",
    gallery: [
      "https://img1.wsimg.com/isteam/ip/19900a79-381c-4795-909f-2412b5319099/246A0341.jpeg",
      "https://img1.wsimg.com/isteam/ip/19900a79-381c-4795-909f-2412b5319099/246A0341.jpeg",
      "https://img1.wsimg.com/isteam/ip/19900a79-381c-4795-909f-2412b5319099/246A0341.jpeg",
    ],
    source: "ReVive Body Lounge official website — homepage",
  },
  "kc-wellness-medspa-riverview": {
    hero: "https://kcwellnessmedspa.com/wp-content/uploads/2025/07/beautician-wearing-mask-and-gloves-injecting-fille-2026-01-09-07-17-13-utc-scaled.jpg",
    gallery: [
      "https://kcwellnessmedspa.com/wp-content/uploads/2025/07/beautician-wearing-mask-and-gloves-injecting-fille-2026-01-09-07-17-13-utc-scaled.jpg",
      "https://kcwellnessmedspa.com/wp-content/uploads/2025/07/beautician-wearing-mask-and-gloves-injecting-fille-2026-01-09-07-17-13-utc-scaled.jpg",
      "https://kcwellnessmedspa.com/wp-content/uploads/2025/07/beautician-wearing-mask-and-gloves-injecting-fille-2026-01-09-07-17-13-utc-scaled.jpg",
    ],
    source: "KC Wellness & Medspa official website — homepage",
  },
  "luminous-skin-and-laser-tampa": {
    hero: "http://www.luminousskinandlaser.com/cdn/shop/files/WEB_3_e0c55365-1f3f-4888-b1dd-306e81128eea_1200x1200.jpg?v=1718134356",
    gallery: [
      "http://www.luminousskinandlaser.com/cdn/shop/files/WEB_3_e0c55365-1f3f-4888-b1dd-306e81128eea_1200x1200.jpg?v=1718134356",
      "http://www.luminousskinandlaser.com/cdn/shop/files/WEB_3_e0c55365-1f3f-4888-b1dd-306e81128eea_1200x1200.jpg?v=1718134356",
      "http://www.luminousskinandlaser.com/cdn/shop/files/WEB_3_e0c55365-1f3f-4888-b1dd-306e81128eea_1200x1200.jpg?v=1718134356",
    ],
    source: "Luminous Skin and Laser official website — homepage",
  },
  "vivify-med-spa-tampa": {
    hero: "https://www.datocms-assets.com/98146/1685122943-og-image.jpg",
    gallery: [
      "https://www.datocms-assets.com/98146/1685122943-og-image.jpg",
      "https://www.datocms-assets.com/98146/1685122943-og-image.jpg",
      "https://www.datocms-assets.com/98146/1685122943-og-image.jpg",
    ],
    source: "VIVIFY Med Spa official website — homepage",
  },
  "elase-medical-spa-south-tampa-tampa": {
    hero: "https://elase.com/wp-content/uploads/2024/02/STampa_reception-scaled.jpg",
    gallery: [
      "https://elase.com/wp-content/uploads/2024/02/STampa_reception-scaled.jpg",
      "https://elase.com/wp-content/uploads/2024/02/STampa_reception-scaled.jpg",
      "https://elase.com/wp-content/uploads/2024/02/STampa_reception-scaled.jpg",
    ],
    source: "Elase Medical Spa - South Tampa official website — homepage",
  },
  "the-wellness-club-tampa": {
    hero: "https://thewellnessclubtampa.com/wp-content/uploads/2023/05/test.jpeg",
    gallery: [
      "https://thewellnessclubtampa.com/wp-content/uploads/2023/05/test.jpeg",
      "https://thewellnessclubtampa.com/wp-content/uploads/2023/05/test.jpeg",
      "https://thewellnessclubtampa.com/wp-content/uploads/2023/05/test.jpeg",
    ],
    source: "The Wellness Club official website — homepage",
  },
  "interface-aesthetics-whitnie-padron-aprn-largo": {
    hero: "https://cdn.prod.website-files.com/6986414b7f75606888cc9788/69fef5d97e0e2e192cf32116_featured-image.jpg",
    gallery: [
      "https://cdn.prod.website-files.com/6986414b7f75606888cc9788/69fef5d97e0e2e192cf32116_featured-image.jpg",
      "https://cdn.prod.website-files.com/6986414b7f75606888cc9788/69fef5d97e0e2e192cf32116_featured-image.jpg",
      "https://cdn.prod.website-files.com/6986414b7f75606888cc9788/69fef5d97e0e2e192cf32116_featured-image.jpg",
    ],
    source: "Interface Aesthetics - Whitnie Padron, APRN official website — homepage",
  },
        "skin-nv-tampa-med-spa-tampa": {
    hero: "https://images.squarespace-cdn.com/content/v1/6957de3ff3f62c42463177b8/6ea289f3-fe48-459f-a178-059c610acd26/SkinNV-19.jpg",
    gallery: [
      "https://images.squarespace-cdn.com/content/v1/6957de3ff3f62c42463177b8/01b88f82-55be-4efb-895b-dae90768b321/The+Art+%2B+Science+of+Beauty+%281%29.png",
      "https://images.squarespace-cdn.com/content/v1/6957de3ff3f62c42463177b8/45f8f8b2-8231-4b17-bceb-42621a23cf11/The+Art+%2B+Science+of+Beauty+%281%29.png?format=1500w",
      "https://images.squarespace-cdn.com/content/v1/6957de3ff3f62c42463177b8/3b8d63f7-c665-4d64-88d5-9a7e899b3e9c/SkinNV-85.jpg",
      "https://images.squarespace-cdn.com/content/v1/6957de3ff3f62c42463177b8/88c83c8d-1162-4728-81f8-9401e9beeb13/SkinNV-293.jpg",
    ],
    source: "Provider official website",
  },
  "florida-aesthetics-and-wellness-brandon": {
    hero: "https://floridaaesthetics.com/images/FA-OG-Image.jpg",
    gallery: [
      "https://floridaaesthetics.com/images/FA-OG-Image.jpg",
      "https://floridaaesthetics.com/images/FA-OG-Image.jpg",
      "https://floridaaesthetics.com/images/FA-OG-Image.jpg",
    ],
    source: "Florida Aesthetics and Wellness official website — homepage",
  },
  "radiance-medspa-belleair-bluffs": {
    hero: "https://www.radiancemedspa.com/wp-content/uploads/2025/01/cropped-small-logo-4-radiance-medspa-in-Belleair-Bluff-Florida-e1685048412501.webp",
    gallery: [
      "https://www.radiancemedspa.com/wp-content/uploads/2025/01/cropped-small-logo-4-radiance-medspa-in-Belleair-Bluff-Florida-e1685048412501.webp",
      "https://www.radiancemedspa.com/wp-content/uploads/2025/01/cropped-small-logo-4-radiance-medspa-in-Belleair-Bluff-Florida-e1685048412501.webp",
      "https://www.radiancemedspa.com/wp-content/uploads/2025/01/cropped-small-logo-4-radiance-medspa-in-Belleair-Bluff-Florida-e1685048412501.webp",
    ],
    source: "Radiance Medspa official website — homepage",
  },
  "lux-injectables-clearwater": {
    hero: "https://luxinjectables.com/wp-content/uploads/2021/07/PDO-Lip-Lift-1.jpeg",
    gallery: [
      "https://luxinjectables.com/wp-content/uploads/2021/07/PDO-Lip-Lift-1.jpeg",
      "https://luxinjectables.com/wp-content/uploads/2021/07/PDO-Lip-Lift-1.jpeg",
      "https://luxinjectables.com/wp-content/uploads/2021/07/PDO-Lip-Lift-1.jpeg",
    ],
    source: "Lux Injectables official website — homepage",
  },
  "elase-medical-spa-westchase-westchase": {
    hero: "https://elase.com/wp-content/uploads/2024/02/processed-67570389-EA31-4BEC-995B-7BF4FA3AFB5B-1-scaled.jpeg",
    gallery: [
      "https://elase.com/wp-content/uploads/2024/02/processed-67570389-EA31-4BEC-995B-7BF4FA3AFB5B-1-scaled.jpeg",
      "https://elase.com/wp-content/uploads/2024/02/processed-67570389-EA31-4BEC-995B-7BF4FA3AFB5B-1-scaled.jpeg",
      "https://elase.com/wp-content/uploads/2024/02/processed-67570389-EA31-4BEC-995B-7BF4FA3AFB5B-1-scaled.jpeg",
    ],
    source: "Elase Medical Spa - Westchase official website — homepage",
  },
  "venus-med-spa-riverview": {
    hero: "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
    gallery: [
      "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
      "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
      "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
    ],
    source: "Venus Med Spa official website — homepage",
  },
        "fusion-medispa-odessa": {
    hero: "http://fusionmedispa.net/cdn/shop/files/Logo_1_1.jpg?v=1763658025",
    gallery: [

    ],
    source: "Provider official website",
  },
  "venus-med-spa-tampa": {
    hero: "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
    gallery: [
      "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
      "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
      "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
    ],
    source: "Venus Med Spa official website — homepage",
  },
  "phdermatology-westchase-tampa": {
    hero: "https://phdermatology.com/wp-content/uploads/2023/06/phdermatology-logo.png",
    gallery: [
      "https://phdermatology.com/wp-content/uploads/2023/06/phdermatology-logo.png",
      "https://phdermatology.com/wp-content/uploads/2023/06/phdermatology-logo.png",
      "https://phdermatology.com/wp-content/uploads/2023/06/phdermatology-logo.png",
    ],
    source: "PHDermatology-Westchase official website — homepage",
  },
  "venus-med-spa-tampa-2": {
    hero: "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
    gallery: [
      "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
      "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
      "https://www.venusmedspa.com/wp-content/uploads/2023/02/tox-1.png",
    ],
    source: "Venus Med Spa official website — homepage",
  },
  "redbamboo-medi-spa-clearwater": {
    hero: "https://www.redbamboomedispa.com/wp-content/uploads/411803412_1415833739146999_5738821762038852276_n.jpg",
    gallery: [
      "https://www.redbamboomedispa.com/wp-content/uploads/411803412_1415833739146999_5738821762038852276_n.jpg",
      "https://www.redbamboomedispa.com/wp-content/uploads/411803412_1415833739146999_5738821762038852276_n.jpg",
      "https://www.redbamboomedispa.com/wp-content/uploads/411803412_1415833739146999_5738821762038852276_n.jpg",
    ],
    source: "RedBamboo Medi-Spa official website — homepage",
  },
  "aria-med-spa-clearwater": {
    hero: "https://i0.wp.com/aria-medspa.com/wp-content/uploads/2024/02/Logo-Aria-Med-Spa-Final-02-scaled.jpg?fit=2560%2C2560&ssl=1",
    gallery: [
      "https://i0.wp.com/aria-medspa.com/wp-content/uploads/2024/02/Logo-Aria-Med-Spa-Final-02-scaled.jpg?fit=2560%2C2560&ssl=1",
      "https://i0.wp.com/aria-medspa.com/wp-content/uploads/2024/02/Logo-Aria-Med-Spa-Final-02-scaled.jpg?fit=2560%2C2560&ssl=1",
      "https://i0.wp.com/aria-medspa.com/wp-content/uploads/2024/02/Logo-Aria-Med-Spa-Final-02-scaled.jpg?fit=2560%2C2560&ssl=1",
    ],
    source: "Aria Med Spa official website — homepage",
  },
  "kristals-cosmetics-med-spa-clearwater": {
    hero: "https://www.kristalsmedspa.com/og-image.jpg",
    gallery: [
      "https://www.kristalsmedspa.com/og-image.jpg",
      "https://www.kristalsmedspa.com/og-image.jpg",
      "https://www.kristalsmedspa.com/og-image.jpg",
    ],
    source: "Kristals Cosmetics Med SPA official website — homepage",
  },
  "adare-longevity-aesthetics-st-petersburg": {
    hero: "https://adarelife.com/og-image.jpg",
    gallery: [
      "https://adarelife.com/og-image.jpg",
      "https://adarelife.com/og-image.jpg",
      "https://adarelife.com/og-image.jpg",
    ],
    source: "ADARE Longevity & Aesthetics official website — homepage",
  },
  "baymed-hair-tampa": {
    hero: "https://baymedhair.com/wp-content/uploads/2025/01/baymed-hair-and-aesthetics-team.jpg",
    gallery: [
      "https://baymedhair.com/wp-content/uploads/2025/01/baymed-hair-and-aesthetics-team.jpg",
      "https://baymedhair.com/wp-content/uploads/2025/01/baymed-hair-and-aesthetics-team.jpg",
      "https://baymedhair.com/wp-content/uploads/2025/01/baymed-hair-and-aesthetics-team.jpg",
    ],
    source: "BayMed Hair official website — homepage",
  }
};
